removed hardcoded docroot from files

diff --git a/bin/archive-transfer b/bin/archive-transfer
--- a/bin/archive-transfer
+++ b/bin/archive-transfer
@@ -89,7 +89,11 @@ elif [ "$transfer_type" == "recv_active" -a -e "$file_to_use" ]; then
   error "file '$file_to_use' already exists"
 fi
 
-token_file="$tokens_dir/${USER#w_}.$transfer_type.$token"
+if ! vhost=$(get_vhost_from_linuxuser); then
+  error "unable to get vhost from user $USER"
+fi
+
+token_file="$tokens_dir/$vhost.$transfer_type.$token"
 if [ ! -e "$token_file" ]; then
   error "token file '$token_file' doesn't exist"
 elif [ ! -f "$token_file" ]; then
diff --git a/bin/restore-vhost-subsystem b/bin/restore-vhost-subsystem
--- a/bin/restore-vhost-subsystem
+++ b/bin/restore-vhost-subsystem
@@ -485,8 +485,12 @@ done
 
 # set main system variables
 user_web="$USER"
-vhost="${user_web#w_}"
-user_db="b_$vhost"
+
+if ! vhost=$(get_vhost_from_linuxuser); then
+  error "unable to get vhost name"
+fi
+
+user_db="b_${user_web#w_}"
 config_dir="$we_base_dir/config/vhosts/$vhost"
 home="`eval \"echo ~$user_web\"`"
 vhost_config_dir=.webenabled/private
diff --git a/bin/vhost-ssh-wrapper b/bin/vhost-ssh-wrapper
--- a/bin/vhost-ssh-wrapper
+++ b/bin/vhost-ssh-wrapper
@@ -20,12 +20,23 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+lib_f="$sys_dir/lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
 command=${SSH_ORIGINAL_COMMAND%% *}
 cmd_args=${SSH_ORIGINAL_COMMANDS#* }
 
 case "$command" in
   site_sync_recv_files)
-    vhost_dir="$HOME/public_html/${USER#w_}"
+    vhost_dir=$(get_docroot_from_user)
+    if [ $? -ne 0 ]; then
+      error "unable to get docroot for user"
+    elif [ ! -d "$vhost_dir" ]; then
+      error "directory '$vhost_dir' does not exist."
+    fi
 
     rsync --server -vvlogDtpr . "$vhost_dir"
     st=$?
diff --git a/lib/init-shell b/lib/init-shell
--- a/lib/init-shell
+++ b/lib/init-shell
@@ -1,6 +1,16 @@
 #!/bin/bash
 
-public_html_dir="$HOME/public_html/${USER#w_}"
+self_bin=$(readlink -e "$0")
+self_dir=${self_bin%/*}
+sys_dir=${self_dir%/*}
+
+lib_f="$sys_dir/lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
+public_html_dir=$(get_docroot_from_user)
 if [ -d "$public_html_dir" ]; then
   cd "$public_html_dir"
 fi
