bin/gen-temp-sshkey: fix problem w/ -p and other opts
-p didn't work well with other options like -a and -c. Fixed.

diff --git a/bin/gen-temp-sshkey b/bin/gen-temp-sshkey
--- a/bin/gen-temp-sshkey
+++ b/bin/gen-temp-sshkey
@@ -13,14 +13,15 @@ usage() {
     -a            output the line with the syntax ready to be piped to
                   public-key-vhost stdin
 
+    -C comment    a comment string to append to the key
     -h            displays the usage msg
 "
   exit 1
 }
 
 # main
-getopt_flags='ahpc:'
-unset target_file print_existing format_add_stdin forced_command
+getopt_flags='ahpc:C:'
+unset target_file print_existing format_add_stdin forced_command comment_str
 while getopts $getopt_flags OPTF; do
   case $OPTF in
     h)
@@ -34,6 +35,9 @@ while getopts $getopt_flags OPTF; do
       ;;
     a)
       format_add_stdin=1
+      ;;
+    C)
+      comment_str="$OPTARG"
       ;;
     *)
       usage
@@ -49,25 +53,30 @@ if [ -e "$target_file" -a -z "$print_existing" ]; then
   echo "Error: file '$target_file' already exists" 1>&2
   exit 1
 elif [ -e "$target_file" -a -n "$print_existing" ]; then
-  ssh-keygen -f "$target_file" -y
-  if [ $? -eq 0 ]; then
-    exit 0
-  else
+  key_str=`ssh-keygen -f "$target_file" -y`
+  if [ $? -ne 0 ]; then
     echo "Error: unable to extract public key from file '$target_file'" 1>&2
     exit 1
   fi
-fi
+else # key doesn't exist, try to generate it
+  target_dir=`dirname "$target_file"`
+  if [ ! -e "$target_dir" ] && ! mkdir -m 700 "$target_dir"; then
+    echo "Error: could not create target dir '$target_dir'" 1>&2
+    exit 1
+  fi
 
-target_dir=`dirname "$target_file"`
-if [ ! -e "$target_dir" ] && ! mkdir -m 700 "$target_dir"; then
-  echo "Error: could not create target dir '$target_dir'" 1>&2
-  exit 1
-fi
+  ssh-keygen -b 4096 -f "$target_file" -P '' -C "$comment_str" &>/dev/null
+  if [ $? -ne 0 ]; then
+    echo "Error: unable to generate key file" 1>&2
+    exit 1
+  fi
 
-ssh-keygen -b 4096 -f "$target_file" -P '' &>/dev/null
-if [ $? -ne 0 ]; then
-  echo "Error: unable to generate key file" 1>&2
-  exit 1
+  key_str=`cat "$target_file.pub"`
+  if [ $? -ne 0 -o -z "$key_str" ]; then
+    echo #
+    echo "Error: unable to retrieve key contents" 1>&2
+    exit 1
+  fi
 fi
 
 if [ -n "$format_add_stdin" ]; then
@@ -80,9 +89,4 @@ if [ -n "$forced_command" ]; then
   echo -n "$cmd_line"' '
 fi
 
-cat "$target_file.pub"
-if [ $? -ne 0 ]; then
-  echo #
-  echo "Error: unable to display key contents" 1>&2
-  exit 1
-fi
+echo "$key_str"
