bin/git-init-repo: added cmdline options -c and -r

diff --git a/bin/git-init-repo b/bin/git-init-repo
--- a/bin/git-init-repo
+++ b/bin/git-init-repo
@@ -4,8 +4,15 @@ usage() {
   echo "Usage: `basename "$0"` [ options ] <name>
   
   Options
-    -d <target_dir>           the target directory where to clone
-    -I                        initialize repository with a commit
+    -d <target_dir>              the target directory where to clone
+    -I                           initialize repository with a commit
+    -r remote_name=remote_addr   sets the remote name and address
+                                 (this flag can be used multiple times)
+    -c key=value                 options to be saved by git config.
+                                 This option can be used multiple times
+
+
+  <name> is just a friendly short name when the -d option is not used
 "
   exit 1
 }
@@ -20,8 +27,10 @@ if [ $EUID -eq 0 ]; then
   exit 1
 fi
 
-getopt_flags='d:I'
+getopt_flags='d:r:c:I'
 unset initialize target_dir
+declare -a remotes_ar=()
+declare -a configs_ar=()
 while getopts $getopt_flags OPTNAME; do
   case "$OPTNAME" in
     d)
@@ -30,11 +39,28 @@ while getopts $getopt_flags OPTNAME; do
     I)
       initialize=1
       ;;
+    r)
+      if echo "$OPTARG" | egrep -q '^[A-Za-z0-9._-]+=.+'; then
+        remotes_ar+=( "$OPTARG" )
+      else
+        echo "Error: parameter passed to -r has an invalid format." 1>&2
+        exit 1
+      fi
+      ;;
+    c)
+      if echo "$OPTARG" | egrep -q '^[A-Za-z0-9._-]+=.+'; then
+        configs_ar+=( "$OPTARG" )
+      else
+        echo "Error: parameter passed to -c has an invalid format." 1>&2
+        exit 1
+      fi
+      ;;
     *)
       exit 1
       ;;
   esac
 done
+[ $OPTIND -gt 1 ] && shift $(( $OPTIND - 1 ))
 
 name="$1"
 [ -z "$name" ] && usage
@@ -51,6 +77,7 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+GIT_DIR="$target_dir"
 if [ -n "$initialize" ]; then
   work_dir=`mktemp -d`
   if [ $? -ne 0 ]; then
@@ -72,7 +99,7 @@ if [ -n "$initialize" ]; then
     author_email="support@devpanel.com"
   fi
 
-  GIT_DIR="$work_dir/.git" git -c "user.name=$author_name" \
+  GIT_DIR="$GIT_DIR" git -c "user.name=$author_name" \
     -c "user.email=$author_email" commit --allow-empty \
     -m "Repository initiliazed using DevPanel"
 
@@ -81,11 +108,36 @@ if [ -n "$initialize" ]; then
     exit 1
   fi
 
-  GIT_DIR="$work_dir/.git" git push origin master
+  GIT_DIR="$GIT_DIR" git push origin master
   if [ $? -ne 0 ]; then
     echo "Error: unable to push the initial commit back to the repository" 1>&2
     exit 1
   fi
 fi
+
+for remote_str in ${remotes_ar[@]}; do
+  # split the name=value string
+  remote_name=${remote_str%%=*}
+  remote_addr=${remote_str#*=}
+
+  # if it was initialized earlier, and there's a new origin, then remove the
+  # previous origin before attempting to add the new one
+  if [ -n "$initialize" -a "$remote_name" == "origin" ]; then
+    origin_path="$GIT_DIR/refs/remotes/origin/"
+    if [ -e "$origin_path" ]; then
+      GIT_DIR="$GIT_DIR" git remote remove origin
+    fi
+  fi
+
+  GIT_DIR="$GIT_DIR" git remote add "$remote_name" "$remote_addr"
+done
+
+for config_str in ${configs_ar[@]}; do
+  # split the name=value string
+  config_key=${config_str%%=*}
+  config_vle=${config_str#*=}
+
+  GIT_DIR="$GIT_DIR" git config "$config_key" "$config_vle"
+done
 
 exit 0
