changes to speed up git repo creation
moved the ssh key handling from controller to host. This speed ups the
creation of git repositories and websites.

diff --git a/bin/git-init-repo b/bin/git-init-repo
--- a/bin/git-init-repo
+++ b/bin/git-init-repo
@@ -31,6 +31,15 @@ if [ $EUID -eq 0 ]; then
   exit 1
 fi
 
+self_bin=`readlink -e "$0"`
+if [ $? -ne 0 ]; then
+  echo "Error: unable to get self path" 1>&2
+  exit 1
+fi
+
+self_dir="${self_bin%/*}"
+sys_dir="${self_dir%/*}"
+
 getopt_flags='d:r:c:IPn'
 is_bare=1
 unset GIT_DIR initial_commit target_dir
@@ -152,6 +161,19 @@ fi
 if ! cd "$target_dir"; then
   echo "Error: unable to chdir to $target_dir" 1>&2
   exit 1
+fi
+
+if [ -n "$name" ]; then
+  repo_ssh_key="$HOME/.ssh/id_rsa_dp_repo_$name"
+  if "$sys_dir/bin/gen-temp-sshkey" "$repo_ssh_key" >/dev/null; then
+    "$sys_dir/bin/update-dot-ssh-config" "$HOME/.ssh/config" \
+      add_section "git-repo-$name.*" "IdentityFile=$repo_ssh_key"
+    if [ $? -ne 0 ]; then
+      echo "Warning: failed to update .ssh/config with the repo key" 1>&2
+    fi
+  else
+    echo "Warning: failed to generate repo ssh key $repo_ssh_key" 1>&2
+  fi
 fi
  
 for remote_str in ${remotes_ar[@]}; do
