Issue : https://help.webstandard.com/issues/7254
	modified:   bin/git-import
	    Add source lib/functions

diff --git a/bin/git-import b/bin/git-import
--- a/bin/git-import
+++ b/bin/git-import
@@ -25,6 +25,16 @@ fi
 
 [ $# -eq 0 ] && usage
 
+self_bin=$(readlink -e "$0")
+self_dir=$(dirname "$self_bin")
+sys_dir=$(readlink -e "$self_dir/..")
+lib_file="$sys_dir/lib/functions"
+
+if ! source "$lib_file"; then
+  echo "Error: unable to load auxiliary functions from $lib_file" 1>&2
+  exit 1
+fi
+
 getopt_flags='u:r:d:m:s:P:' 
 
 unset OPTIND remote_name repo_user repo_name source_dir dont_rename_dot_git
