first rough version of clone-tokens (will be removed in the next commit). Put here just for the sake of historic of the original idea/implementation (as said, it's very rough, next one if much better in terms of problem prediction)

diff --git a/files/opt/webenabled/backend-scripts/libexec/clone-tokens b/files/opt/webenabled/backend-scripts/libexec/clone-tokens
--- a/files/opt/webenabled/backend-scripts/libexec/clone-tokens
+++ b/files/opt/webenabled/backend-scripts/libexec/clone-tokens
@@ -11,8 +11,10 @@ Usage: $prog [ OPTIONS ] <vhost>
 
   Options:
     -n number         number of characters of the token
-    -t type           Type of the clone. Accepted types: push or pull
-
+    -t type           Type of the clone. Accepted types: recv or send
+    -T token          use the specified token (instead of generating a
+                      random one)
+    -r                remove the token specified in option -T
 "
   exit 1
 }
@@ -33,7 +35,9 @@ elif [ ! -d "$token_dir" ]; then
   error "path '$token_dir' is not a directory"
 fi
 
-getopt_flags='n:t:'
+delete_token=0
+unset token_str
+getopt_flags='rn:t:T:'
 while getopts $getopt_flags OPTN; do
   case $OPTN in
     n)
@@ -46,11 +50,21 @@ while getopts $getopt_flags OPTN; do
       fi
       ;;
     t)
-      if [ "$OPTARG" != "pull" -a "$OPTARG" != "push" ]; then
-        error "invalid type. Accepted values: pull or push"
+      if [ "$OPTARG" != "recv" -a "$OPTARG" != "send" ]; then
+        error "invalid type. Accepted values: recv or send"
       else
         clone_type="$OPTARG"
       fi
+      ;;
+    T)
+      if [ ${#OPTARG} -eq $token_length ]; then
+        token_str="$OPTARG"
+      else
+        error "the specified token doesn't match the required token length ($token_length)"
+      fi
+      ;;
+    r)
+      delete_token=1
       ;;
     *)
       usage
@@ -62,27 +76,57 @@ done
 # missing vhost name
 [ $# -lt 1 -o ${#1} -lt 1 ] && usage
 
+if [ -z "$clone_type" ]; then
+  error "please specify clone type (-t)"
+fi
+
 vhost="$1"
+if [ $delete_token -eq 1 -a -z "$token_str" ]; then
+  error "requested token deletion (-r), but token string is missing (-T)"
+elif [ $delete_token -eq 1 ]; then
+  token_file="$token_dir/$vhost.$clone_type.$token_str"
+  if [ ! -e "$token_file" ]; then
+    wedp_warn "token file doesn't exist"
+    exit 0 # exit 0, not important here
+  fi
+
+  rm -f "$token_file"
+  if [ $? -eq 0 ]; then
+    exit 0
+  else
+    error "unable to delete token file '$token_file'"
+  fi
+fi
+
 if ! getent passwd "w_$vhost" ; then
   wedp_warn "vhost 'w_$vhost' doesn't exist yet (this is just a warning)"
 fi
 
-for n in {1..5}; do
-  if token_str=$( wedp_gen_random_str $token_length ); then
-    token_file="$token_dir/$vhost.$clone_type.$token_str"
-    if [ -e "$token_file" ]; then
-      wedp_warn "token_file '$token_file' already exists. Trying again"
+if [ -z "$token_str" ]; then
+  for n in {1..5}; do
+    if token_str=$( wedp_gen_random_str $token_length ); then
+      token_file="$token_dir/$vhost.$clone_type.$token_str"
+      if [ -e "$token_file" ]; then
+        wedp_warn "token_file '$token_file' already exists. Trying again"
+      else
+        break
+      fi
     else
-      break
+      continue
     fi
-  else
-    continue
-  fi
-  token_file=""
-done
+    token_file=""
+  done
+else
+  token_file="$token_dir/$vhost.$clone_type.$token_str"
+fi
 
 if [ -z "$token_file" ]; then
   error "unable to generate token file. Exceeded max number of attempts"
+fi
+
+if [ -e "$token_file" ]; then
+  wedp_warn "token already exists (this is just a warning)"
+  exit 0
 fi
 
 touch "$token_file"
