fix misc bugs for long vhost names

diff --git a/lib/cli/bin/clear-app-cache b/lib/cli/bin/clear-app-cache
--- a/lib/cli/bin/clear-app-cache
+++ b/lib/cli/bin/clear-app-cache
@@ -10,11 +10,11 @@ set_usage_msg \
 "
 
 devpanel_cmd__clear_app_cache() {
-  [ $# -eq 0 -o -z "$1" ] && usage
+  [ $EUID -eq 0 ] && [ $# -eq 0 -o -z "$1" ] && usage
 
-  local name vhost
+  local name vhost user
 
-  local -a cmd_args=()
+  local -a cmd_args_ar=()
   local -a opts_ar=( )
 
   while [ -n "$1" ]; do
@@ -28,17 +28,40 @@ devpanel_cmd__clear_app_cache() {
       --help)
         usage
         ;;
+      --)
+        shift
+        break
+        ;;
       *)
         usage
         ;;
     esac
   done
 
-  [ -z "$vhost" ] && error_missing_param vhost
+  if [ $EUID -eq 0 ]; then
+    [ -z "$vhost" ] && error_missing_param vhost
 
-  user="w_${vhost}"
+    if ! vhost_exists "$vhost"; then
+      error "vhost doesn't exist."
+    fi
+
+    get_linux_username_from_vhost "$vhost" && \
+    user="$_dp_value" || error "unable to get linux user from vhost"
+  else
+    if vhost=$(get_vhost_from_linuxuser); then
+      user="$USER"
+    else
+      error "unable to determine vhost for current user"
+    fi
+  fi
 
   local exec_bin="$sys_dir/bin/restore-vhost-subsystem"
 
-  su -l -c "$exec_bin -C" "$user"
+  cmd_args_ar=( "$exec_bin" -C )
+
+  if [ $EUID -eq 0 ]; then
+    su -l -c "${cmd_args_ar[*]}" "$user"
+  else
+    "${cmd_args_ar[@]}"
+  fi
 }
diff --git a/lib/cli/bin/config-app b/lib/cli/bin/config-app
--- a/lib/cli/bin/config-app
+++ b/lib/cli/bin/config-app
@@ -11,7 +11,7 @@ set_usage_msg \
 "
 
 devpanel_cmd__config_app() {
-  [ $# -eq 0 -o -z "$1" ] && usage
+  [ $EUID -eq 0 ] && [ $# -eq 0 -o -z "$1" ] && usage
 
   local name vhost admin_pw
 
@@ -44,6 +44,10 @@ devpanel_cmd__config_app() {
       --help)
         usage
         ;;
+      --)
+        shift
+        break
+        ;;
       --[A-Za-z0-9_-]*)
         error "unknown option $name"
         ;;
@@ -54,21 +58,42 @@ devpanel_cmd__config_app() {
     esac
   done
 
-  [ -z "$vhost" ] && error_missing_param vhost
-
   if [ ${#opts_ar[*]} -eq 0 -a -z "$admin_pw" ]; then
     usage
   fi
 
-  user="w_${vhost}"
+  if [ $EUID -eq 0 ]; then
+    [ -z "$vhost" ] && error_missing_param vhost
+
+    if ! vhost_exists "$vhost"; then
+      error "vhost doesn't exist."
+    fi
+
+    get_linux_username_from_vhost "$vhost" && \
+    user="$_dp_value" || error "unable to get linux user for vhost '$vhost'"
+  else
+    if vhost=$(get_vhost_from_linuxuser); then
+      user="$USER"
+    else
+      error "unable to determine vhost for current user"
+    fi
+  fi
 
   local exec_bin="$sys_dir/bin/restore-vhost-subsystem"
 
   if [ -n "$admin_pw" ]; then
-    echo "$admin_pw" | su -l -c "$exec_bin -i -p" "$user"
+    if [ $EUID -eq 0 ]; then
+      echo "$admin_pw" | su -l -c "$exec_bin -i -p" "$user"
+    else
+      "$exec_bin" -i -p
+    fi
   fi
 
   if [ ${#opts_ar[*]} -gt 0 ]; then
-    su -l -c "$exec_bin"\ "${cmd_args[*]}"\ "${opts_ar[*]}" "$user"
+    if [ $EUID -eq 0 ]; then
+      su -l -c "$exec_bin"\ "${cmd_args[*]}"\ "${opts_ar[*]}" "$user"
+    else
+      "$exec_bin" "${cmd_args[@]}" "${opts_ar[@]}"
+    fi
   fi
 }
diff --git a/lib/cli/bin/manage-htpasswd b/lib/cli/bin/manage-htpasswd
--- a/lib/cli/bin/manage-htpasswd
+++ b/lib/cli/bin/manage-htpasswd
@@ -16,10 +16,10 @@ set_usage_msg \
 "
 
 devpanel_cmd__manage_htpasswd() {
-  [ $# -eq 0 -o -z "$1" ] && usage
+  [ $EUID -eq 0 ] && [ $# -eq 0 -o -z "$1" ] && usage
 
   local name vhost file password
-  local op op_str
+  local op op_str user htpasswd_file
   local -a cmd_args=()
 
   local -i exclusive_ops=0
@@ -53,7 +53,19 @@ devpanel_cmd__manage_htpasswd() {
     esac
   done
 
-  [ -z "$vhost" ] && error_missing_param vhost
+  if [ $EUID -eq 0 ]; then
+    [ -z "$vhost" ] && error_missing_param vhost
+
+    if ! vhost_exists "$vhost"; then
+      error "vhost doesn't exist."
+    fi
+  else
+    if vhost=$(get_vhost_from_linuxuser); then
+      user="$USER"
+    else
+      error "unable to determine vhost for current user"
+    fi
+  fi
 
   if [ $exclusive_ops -gt 1 ]; then
     error "only one of --add-user, --del-user, --chpasswd can be used a time"
@@ -70,7 +82,7 @@ devpanel_cmd__manage_htpasswd() {
 
   local has_tty
 
-  if tty -s; then
+  if [ -t 0 ]; then
     has_tty=1
   fi
 
@@ -98,7 +110,15 @@ devpanel_cmd__manage_htpasswd() {
 
   local exec_bin="$sys_dir/bin/htpasswd-bulk"
 
-  local user="w_$vhost"
+  htpasswd_file=$(eval echo -n ~$user/.htpasswd)
+  cmd_args=( "$exec_bin" -c "$htpasswd_file" )
+  if [ $EUID -eq 0 ]; then
+    get_linux_username_from_vhost "$vhost" && \
+    user="$_dp_value" || error "unable to get linux user for vhost '$vhost'"
 
-  echo "$op_str" | su -l -c "$exec_bin -c ~/.htpasswd" "$user"
+    echo "$op_str" | su -l -c "${cmd_args[*]}" "$user"
+  else
+    echo "$op_str" | "${cmd_args[@]}"
+  fi
+
 }
