CLI list backups: auto detect vhost for unpriv users

diff --git a/lib/cli/bin/list-backups b/lib/cli/bin/list-backups
--- a/lib/cli/bin/list-backups
+++ b/lib/cli/bin/list-backups
@@ -11,8 +11,6 @@ set_usage_msg \
 "
 
 devpanel_cmd__list_backups() {
-  [ $# -eq 0 -o -z "$1" ] && usage
-
   local name vhost file full_path
 
   while [ -n "$1" ]; do
@@ -27,6 +25,9 @@ devpanel_cmd__list_backups() {
         full_path=1
         shift
         ;;
+      --help)
+        usage
+        ;;
       --)
         shift
         break
@@ -36,6 +37,13 @@ devpanel_cmd__list_backups() {
         ;;
     esac
   done
+
+  if [ $EUID -ne 0 ]; then
+    if ! vhost=$(get_vhost_from_linuxuser); then
+      error "unable to get vhost for current user" -
+      return $?
+    fi
+  fi
 
   local param
   for param in vhost; do
@@ -88,5 +96,4 @@ devpanel_cmd__list_backups() {
       "$last_mod_friendly" "$display_name" "$size_txt"
 
   done
-
 }
