cli/manage-htpasswd: added a few missing lines from previous commit

diff --git a/lib/cli/bin/manage-htpasswd b/lib/cli/bin/manage-htpasswd
--- a/lib/cli/bin/manage-htpasswd
+++ b/lib/cli/bin/manage-htpasswd
@@ -59,6 +59,9 @@ devpanel_cmd__manage_htpasswd() {
     if ! vhost_exists "$vhost"; then
       error "vhost doesn't exist."
     fi
+
+    get_linux_username_from_vhost "$vhost" && \
+    user="$_dp_value" || error "unable to get linux user for vhost '$vhost'"
   else
     if vhost=$(get_vhost_from_linuxuser); then
       user="$USER"
@@ -113,9 +116,6 @@ devpanel_cmd__manage_htpasswd() {
   htpasswd_file=$(eval echo -n ~$user/.htpasswd)
   cmd_args=( "$exec_bin" -c "$htpasswd_file" )
   if [ $EUID -eq 0 ]; then
-    get_linux_username_from_vhost "$vhost" && \
-    user="$_dp_value" || error "unable to get linux user for vhost '$vhost'"
-
     echo "$op_str" | su -l -c "${cmd_args[*]}" "$user"
   else
     echo "$op_str" | "${cmd_args[@]}"
