improve file extraction to avoid duplicating big files
Improve the file extraction to avoid creating big temporary files when not
necessary. This fixes failed clones when the server doesn't have much free
space, though has enough to handle the clone successfully.

diff --git a/lib/cli/bin/restore-backup b/lib/cli/bin/restore-backup
--- a/lib/cli/bin/restore-backup
+++ b/lib/cli/bin/restore-backup
@@ -8,6 +8,8 @@ set_usage_msg \
 
     --filename <filename>       name of the archive file to extract
 
+    --from-dir <source_dir>     import from an already extracted source dir
+
     --dont-remove-files         don't remove all existing files/dirs before
                                 restoring. By default all files are removed
                                 before restoring the backup file.
@@ -25,7 +27,7 @@ set_usage_msg \
 devpanel_cmd__restore_backup() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
-  local name vhost filename skip_files skip_dbs public_files
+  local name vhost source_type filename source_dir skip_files skip_dbs public_files
   local temp_dir quiet
   local vhost_home_dir web_user doc_root st
   local disable_vhost=yes remove_files=yes
@@ -43,8 +45,16 @@ devpanel_cmd__restore_backup() {
 
       --filename)
         [ -z "$2" ] && error_missing_value "$name"
+        source_type=file
         filename="$2"
         extract_args_ar+=( "$name" "$2" )
+        shift 2
+        ;;
+
+      --from-dir)
+        [ -z "$2" ] && error_missing_value "$name"
+        source_type=dir
+        source_dir="$2"
         shift 2
         ;;
 
@@ -78,10 +88,15 @@ devpanel_cmd__restore_backup() {
     esac
   done
 
-  local param
-  for param in filename; do
-    [ -z "${!param}" ] && error_missing_param $param
-  done
+  if [ -z "$source_type" ]; then
+    usage
+    return $?
+  fi
+
+  if [ -n "$filename" -a -n "$source_dir" ]; then
+    error "can't use --filename and --source-dir at the same time. Specify only one." -
+    return $?
+  fi
 
   if [ $EUID -eq 0 ]; then
     [ -z "$vhost" ] && error_missing_param vhost
@@ -116,14 +131,16 @@ devpanel_cmd__restore_backup() {
 
   doc_root="$v__vhost__document_root"
 
-  temp_dir=$(mktemp -d ${conf__paths__temp_dir:+-t -p "$conf__paths__temp_dir"})
-  if [ $? -ne 0 ]; then
-    error "unable to create temporary directory" -
-    return $?
+  if [ "$source_type" == "file" ]; then
+    temp_dir=$(mktemp -d ${conf__paths__temp_dir:+-t -p "$conf__paths__temp_dir"})
+    if [ $? -ne 0 ]; then
+      error "unable to create temporary directory" -
+      return $?
+    fi
+    temp_dirs_ar+=( "$temp_dir" )
+    source_dir="$temp_dir"
+    extract_args_ar+=( --target-dir "$temp_dir" --extract-raw --quiet )
   fi
-  temp_dirs_ar+=( "$temp_dir" )
-
-  extract_args_ar+=( --target-dir "$temp_dir" --extract-raw --quiet )
 
   if [ $EUID -eq 0 -a -n "$disable_vhost" ]; then
     # temporarily disable the vhost on apache for the app not to be modified
@@ -131,10 +148,12 @@ devpanel_cmd__restore_backup() {
     "$sys_dir/libexec/rewrite-vhost-config" -D $vhost || return $?
   fi
 
-  # TODO(enhance): check if there's enough disk space to extract the files
-  #       (it's actually better to do on 'extract backup' command)
+  if [ "$source_type" == "file" ]; then
+    # TODO(enhance): check if there's enough disk space to extract the files
+    #       (it's actually better to do on 'extract backup' command)
 
-  devpanel_run extract backup "${extract_args_ar[@]}" || return $?
+    devpanel_run extract backup "${extract_args_ar[@]}" || return $?
+  fi
 
   # if the user running this script is root
   # 
@@ -143,9 +162,9 @@ devpanel_cmd__restore_backup() {
 
   if [ $EUID -eq 0 ]; then
     chown -R -c "$web_user" "$vhost_home_dir"
-    chgrp -R "$web_user" "$temp_dir"
-    chmod 770 $temp_dir $temp_dir/db $temp_dir/web
-    chmod 640 $temp_dir/db/* $temp_dir/web/*
+    chgrp -R "$web_user" "$source_dir"
+    chmod 770 $source_dir $source_dir/db $source_dir/web
+    chmod 640 $source_dir/db/* $source_dir/web/*
   else
     #TODO(enhance): test status of find and abort if there are files not
     # writable by the user (to avoid restoring a partial state)
@@ -153,14 +172,14 @@ devpanel_cmd__restore_backup() {
     find "$vhost_home_dir" -type d -perm -0500 -exec chmod u+wx {} \;
   fi
 
-  if [ -d "$temp_dir/db" -a -n "$v__mysql__instance" ]; then
+  if [ -d "$source_dir/db" -a -n "$v__mysql__instance" ]; then
     local import_dbs_bin="$sys_dir/bin/import-databases-from-dir"
     local -a import_dbs_cmd_ar=( "$import_dbs_bin" --safer-overwrite \
                                   --my-cnf "$v__mysql__client_file" )
     if [ -n "$v__mysql__database_prefix" ]; then
       import_dbs_cmd_ar+=( --db-name-prefix "$v__mysql__database_prefix" )
     fi
-    import_dbs_cmd_ar+=( "$temp_dir/db" )
+    import_dbs_cmd_ar+=( "$source_dir/db" )
 
     if [ $EUID -eq 0 ]; then
       run_as_user --login "$web_user" "${import_dbs_cmd_ar[@]}"
@@ -182,11 +201,11 @@ devpanel_cmd__restore_backup() {
 
     if [ $EUID -eq 0 ]; then
       run_as_user "$web_user" "${remove_dirs_cmd_ar[@]}" \
-                    >$temp_dir/rm-output.txt 2>&1
+                    >$source_dir/rm-output.txt 2>&1
     else
       # have to duplicate command here instead of using $remove_dirs_cmd_ar
       # because the ';' is expanded as a quoted string
-      rm -rf "$vhost_home_dir" >$temp_dir/rm-output.txt 2>&1
+      rm -rf "$vhost_home_dir" >$source_dir/rm-output.txt 2>&1
       mkdir -m 751 -p "$doc_root"
     fi
 
@@ -194,9 +213,9 @@ devpanel_cmd__restore_backup() {
     # permissions to the $vhost_home_dir/../ )
     # 
     # if there's only one warning, then it's ok. Otherwise show the warnings.
-    local rm_n_err=`wc -l < $temp_dir/rm-output.txt`
+    local rm_n_err=`wc -l < $source_dir/rm-output.txt`
     if [ $? -eq 0 -a $rm_n_err -gt 1 ]; then
-      cat $temp_dir/rm-output.txt 1>&2
+      cat $source_dir/rm-output.txt 1>&2
     fi
 
   fi
@@ -219,7 +238,7 @@ devpanel_cmd__restore_backup() {
   local extract_bin="$sys_dir/bin/extract-vhost-files-from-dir"
   local -a extract_cmd_ar=()
 
-  extract_cmd_ar=( "$extract_bin" "$temp_dir/web" "$vhost" \
+  extract_cmd_ar=( "$extract_bin" "$source_dir/web" "$vhost" \
                        "$vhost_home_dir" "$doc_root" )
 
   [ -z "$quiet" ] && echo "Extracting files..."
diff --git a/lib/cli/sbin/create-vhost b/lib/cli/sbin/create-vhost
--- a/lib/cli/sbin/create-vhost
+++ b/lib/cli/sbin/create-vhost
@@ -53,8 +53,9 @@ devpanel_cmd__create_vhost() {
   local branch app_password read_pw_stdin php_version subsystem
   local source_type publisher uri_part app_url mysql_instance db_name
   local dedicated_mysql with_mysql=yes
+  local st_archive_extracted st_extracted_dir
   local print_summary=yes do_config_app=yes
-  local -a cmd_args=() lamp_cmd_args=() app_cmd_ar=()
+  local -a cmd_args=() lamp_cmd_args=() app_cmd_ar=() restore_cmd_args=()
 
   while [ -n "$1" ]; do
     name="$1"
@@ -213,6 +214,13 @@ devpanel_cmd__create_vhost() {
     return $?
   fi
 
+  if st_extracted_dir=$(mktemp -d "$conf__paths__temp_dir/vhost_extract.XXXXXX"); then
+    temp_dirs_ar+=( "$st_extracted_dir" )
+  else
+    echo "$FUNCNAME(): failed to create temporary dir" 1>&2
+    return 1
+  fi
+
   # detect the source type
   # e.g. devpanel://wordpress-v4, webenabled://drupal-v7
   #      http://...
@@ -271,33 +279,29 @@ devpanel_cmd__create_vhost() {
         ;;
 
       stdin)
-        if src_archive=$(mktemp ${conf__paths__temp_dir:+-t -p "$conf__paths__temp_dir"}); then
-          temp_files_ar+=( "$src_archive" )
-        else
-          error "unable to create temp file" -
-          return $?
-        fi
-
         if [ -t 0 ]; then
           echo "Reading archive file from STDIN..." 1>&2
         fi
 
-        if ! cat >$src_archive; then
-          error "failed to save archive file '$src_archive'" -
-          return $?
+        if tar --no-same-owner -zxpSf - -C "$st_extracted_dir"; then
+          st_archive_extracted=yes
+        else
+          echo "$FUNCNAME(): failed to extract archive from STDIN..." 1>&2
+          return 1
         fi
 
         ;;
 
       url)
-        if src_archive=$(mktemp ${conf__paths__temp_dir:+-t -p "$conf__paths__temp_dir"}); then
-          temp_files_ar+=( "$src_archive" )
-        else
-          error "unable to create temp file" -
-          return $?
-        fi
+        download_file "$app_url" - | \
+          tar --no-same-owner -zxpSf - -C "$st_extracted_dir"
 
-        download_url_n_cache "$app_url" "$src_archive" || return $?
+        if [ $? -eq 0 ]; then
+          st_archive_extracted=yes
+        else
+          echo "$FUNCNAME(): failed to extract tar ball from url" 1>&2
+          return 1
+        fi
         ;;
 
         *)
@@ -307,9 +311,17 @@ devpanel_cmd__create_vhost() {
       esac
   fi # // if [ -n $from ]
 
-  echo "Extracting metadata from file '$src_archive'..."
-  read_devpanel_ini_from_app_archive --missing-ok "$src_archive" || \
-    return $?
+  if is_yes "$st_archive_extracted"; then
+    local _tmp_app_ini="$st_extracted_dir/.devpanel/app.ini"
+    if [ -f "$_tmp_app_ini" ] && ! read_ini_file_into_namespace "$_tmp_app_ini" src; then
+      echo "$FUNCNAME(): failed to read from '$_tmp_app_ini'" 1>&2
+      return 1
+    fi
+  else
+    echo "Extracting metadata from file '$src_archive'..."
+    read_devpanel_ini_from_app_archive --missing-ok "$src_archive" || \
+      return $?
+  fi
 
   if [ -n "$subsystem" ]; then
     src__app__subsystem="$subsystem"
@@ -317,8 +329,18 @@ devpanel_cmd__create_vhost() {
     if [ -n "$src__app__subsystem" ]; then
       subsystem="$src__app__subsystem"
     else
-      # guess app type from tar ball when --subsystem not specified
-      if ! subsystem=$(guess_subsystem_from_app_archive "$src_archive" ); then
+      # guess app type when --subsystem not specified
+      if is_yes "$st_archive_extracted"; then
+        if guess_subsystem_from_database_filelist "$st_extracted_dir/db/databases"; then
+          subsystem="$_dp_value"
+        fi
+      else
+        if guess_subsystem_from_app_archive "$src_archive"; then
+          subsystem="$_dp_value"
+        fi
+      fi
+
+      if [ -z "$subsystem" ]; then
         error "couldn't detect the subsystem of the app. Please specify it on command line." -
         return $?
       fi
@@ -363,8 +385,14 @@ devpanel_cmd__create_vhost() {
     return $?
   fi
 
+  if [ "$source_type" == "file" ]; then
+    restore_cmd_args+=( --filename "$src_archive" )
+  else
+    restore_cmd_args+=( --from-dir "$st_extracted_dir" )
+  fi
+
   if ! devpanel_run restore backup --vhost "$vhost" --dont-remove-files \
-       --filename "$src_archive" --dont-disable-vhost --quiet; then
+       "${restore_cmd_args[@]}" --dont-disable-vhost --quiet; then
     error "failed to extract the contents of tar ball" -
     return $?
   fi
diff --git a/libexec/old-we-v1/clone-vhost-proxy b/libexec/old-we-v1/clone-vhost-proxy
--- a/libexec/old-we-v1/clone-vhost-proxy
+++ b/libexec/old-we-v1/clone-vhost-proxy
@@ -84,7 +84,7 @@ usage()
 
 if [ $opt_i = 1 ]
 then
-  read -r password || error "Cannot read password"
+  read -p "Reading password from STDIN: " -r password || error "Cannot read password"
   [ -n "$password" ] || error "Empty password"
 fi
 
@@ -92,30 +92,34 @@ fi
 
 set -o pipefail
 echo "Cloning stage 1 & 2: archive $source | restore $target"
-tmp_dir="/opt/webenabled-data/tmp"
-tmp_archive="$tmp_dir/_${source}-$(date +%b-%d-%Y--%H-%M)-$RANDOM.tgz"
 
 # don't overwrite existing files
 set -o noclobber
 
+restore_args_ar+=( --vhost "$target" --from - )
+
 WEBENABLED_SERVER="$source_server" $sys_dir/sbin/archive-vhost $options \
-  "$source" - >$tmp_archive
-if [ $? -ne 0 ]; then
-  error "failed to archive vhost '$source' on server '$source_server'"
-fi
-trap 'rm -f $tmp_archive' EXIT
+  "$source" - | {
 
-restore_args_ar+=( --vhost "$target" --from "$tmp_archive" )
+  # NOTE: doing this as a pipe to avoid creating a big temporary file and
+  # extracting from it. Previously it was implemented like that, but it
+  # required at least 3 times as much free disk space as the size of the 
+  # temporary file (due to how the internal structure of the archive file 
+  # is designed, what is a problem for small VPSs with sites that use
+  # lots of disk space).
 
-if [ -n "$password" ]; then
-  restore_args_ar+=( --password-stdin )
-  echo "$password" | devpanel create vhost "${restore_args_ar[@]}"
+  if [ -n "$password" ]; then
+    restore_args_ar+=( --password-stdin )
+    { echo "$password"; cat; } | devpanel create vhost "${restore_args_ar[@]}"
+  else
+    devpanel create vhost "${restore_args_ar[@]}"
+  fi
+}
+st=$?
+
+if [ $st -eq 0 ]; then
+  echo
+  echo Done
 else
-  devpanel create vhost "${restore_args_ar[@]}"
+  error "failed to create vhost '$target'"
 fi
-if [ $? -ne 0 ]; then
-  error "failed to create vhost '$target_vhost'"
-fi
-
-echo
-echo Done
