Major improvements to MySQL management
This is a huge commit of MySQL management improvements, mostly to
support shared MySQL instances (instead of a single dedicated instance
per vhost).

The previous default of having one MySQL instance per vhost limited
severely the number of vhosts that a server could host, due to memory
allocation limitations. The new default now is to create a shared mysql
instance on the server first install, and use that instance for all
vhosts created.

The old default of one MySQL instance per vhost is still supported,
but for new servers it needs to be passed explicitly to the `create vhost`
command. Servers that were already installed before this commit
still keep the old default, unless changed manually (i.e. created a new
shared MySQL instance manually and set it as default).

This commit also brings several small bug fixes and enhancements to the
mysql scripts and functions.

It also introduces the possibility of the creation of vhosts without a
MySQL instance, both through the command line options, but also through
the app.ini file of a seed app (option: `mysql.skip = yes`).

Also added command `remove mysql instance` to remove instances on
existing servers for apps that don't need MySQL (e.g. Grav and
Dokuwiki).

diff --git a/lib/cli/bin/restore-backup b/lib/cli/bin/restore-backup
--- a/lib/cli/bin/restore-backup
+++ b/lib/cli/bin/restore-backup
@@ -153,19 +153,26 @@ devpanel_cmd__restore_backup() {
     find "$vhost_home_dir" -type d -perm -0500 -exec chmod u+wx {} \;
   fi
 
-  local import_dbs_bin="$sys_dir/bin/import-databases-from-dir"
-  local -a import_dbs_cmd_ar=( "$import_dbs_bin" --safer-overwrite \
-                                --my-cnf "$v__mysql__client_file" "$temp_dir/db" )
-  if [ $EUID -eq 0 ]; then
-    run_as_user --login "$web_user" "${import_dbs_cmd_ar[@]}"
-  else
-    "${import_dbs_cmd_ar[@]}"
-  fi
-  st=$?
+  if [ -d "$temp_dir/db" -a -n "$v__mysql__instance" ]; then
+    local import_dbs_bin="$sys_dir/bin/import-databases-from-dir"
+    local -a import_dbs_cmd_ar=( "$import_dbs_bin" --safer-overwrite \
+                                  --my-cnf "$v__mysql__client_file" )
+    if [ -n "$v__mysql__database_prefix" ]; then
+      import_dbs_cmd_ar+=( --db-name-prefix "$v__mysql__database_prefix" )
+    fi
+    import_dbs_cmd_ar+=( "$temp_dir/db" )
 
-  if [ $st -ne 0 ]; then
-    error "failed to import databases" -
-    return $st
+    if [ $EUID -eq 0 ]; then
+      run_as_user --login "$web_user" "${import_dbs_cmd_ar[@]}"
+    else
+      "${import_dbs_cmd_ar[@]}"
+    fi
+    st=$?
+
+    if [ $st -ne 0 ]; then
+      error "failed to import databases" -
+      return $st
+    fi
   fi
 
   if [ -n "$remove_files" ]; then
@@ -196,14 +203,17 @@ devpanel_cmd__restore_backup() {
 
   # TODO(enhance): regenerate prod specific files (e.g. ~/logs ~/.my.cnf )
   if [ $EUID -eq 0 ]; then
-    run_as_user "$web_user" \
-      "rm -f $vhost_home_dir/{.my.cnf,logs} ; \
-       ln -s $v__vhost__logs_dir $vhost_home_dir/logs ; \
-       ln -s $v__mysql__client_file $vhost_home_dir/.my.cnf"
+    run_as_user "$web_user"               \
+      rm -f \~/{.my.cnf,logs}        \;   \
+      ln -s $v__vhost__logs_dir \~/logs \;
+
+    if [ -n "$v__mysql__instance" ]; then
+      run_as_user "$web_user" ln -s $v__mysql__client_file \~/.my.cnf
+    fi
   else
     rm -f $vhost_home_dir/{.my.cnf,logs}
     ln -s $v__vhost__logs_dir $vhost_home_dir/logs
-    ln -s $v__mysql__client_file $vhost_home_dir/.my.cnf
+    [ -n "$v__mysql__instance" ] && ln -s $v__mysql__client_file $vhost_home_dir/.my.cnf
   fi
 
   local extract_bin="$sys_dir/bin/extract-vhost-files-from-dir"
diff --git a/lib/cli/sbin/create-lamp-vhost b/lib/cli/sbin/create-lamp-vhost
--- a/lib/cli/sbin/create-lamp-vhost
+++ b/lib/cli/sbin/create-lamp-vhost
@@ -11,7 +11,11 @@ set_usage_msg \
     --subsystem name          name of the app subsystem (e.g. drupal,
                               wordpress, etc)
 
-    --mysql-instance name     the mysql instance to use
+    --dedicated-mysql         create a new dedicated MySQL instance
+
+    --skip-mysql              don't do any MySQL configuration for this vhost
+
+    --mysql-instance name     the name of the mysql instance to use
     --mysql-dbs               name of the mysql databases to create
     --db-name name            the name of the main database of the app
 
@@ -33,7 +37,10 @@ devpanel_cmd__create_lamp_vhost() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
   local activate_now=yes
-  local name vhost subsystem php_version description db_name
+  local name vhost subsystem php_version description
+  local dedicated_mysql with_mysql=yes
+  local mysql_instance mysql_pw mysql_db_name create_mysql_instance
+  local db_name db_prefix db_suffix
   local -a domains_ar apache_args_ar opts_ar
 
   while [ -n "$1" ]; do
@@ -59,6 +66,29 @@ devpanel_cmd__create_lamp_vhost() {
         [ -z "$2" ] && { error_missing_value "$name" ; return $?; }
         vhost="$2"
         shift 2
+        ;;
+
+      --dedicated-mysql)
+        dedicated_mysql=yes
+        if ! is_var_set_to_yes with_mysql; then
+          error "conflicting mysql options on command line" -
+          return $?
+        fi
+
+        shift
+        ;;
+
+      --skip-mysql)
+        if [ -n "$dedicated_mysql" ]; then
+          error "can't use $name with --dedicated-mysql at the same time" -
+          return $?
+        elif [ -n "$mysql_instance" ]; then
+          error "can't use $name with --mysql-instance at the same time" -
+          return $?
+        fi
+
+        unset with_mysql
+        shift
         ;;
 
       --subsystem)
@@ -96,6 +126,17 @@ devpanel_cmd__create_lamp_vhost() {
         shift 2
         ;;
 
+      --mysql-instance)
+        [ -z "$2" ] && { error_missing_value "$name" ; return $?; }
+        if ! is_var_set_to_yes with_mysql; then
+          error "conflicting mysql options on command line" -
+          return $?
+        fi
+
+        mysql_instance="$2"
+        shift 2
+        ;;
+
       *)
         error "unknown option '$name'"
         ;;
@@ -109,26 +150,137 @@ devpanel_cmd__create_lamp_vhost() {
     return $?
   fi
 
+  if mysql_instance_exists "$vhost"; then
+    # NOTE: technically it'd be possible to have an instance and a vhost
+    #       with the same name. But to avoid any confusion we don't
+    #       allow it.
+    error "there's already a mysql instance with name '$vhost'" -
+    return $?
+  fi
+
+  if [ -n "$mysql_instance" ]; then
+    mysql_is_valid_instance_name "$mysql_instance" || return $?
+  fi
+
+  if is_var_set_to_yes with_mysql; then
+    if [ -n "$mysql_instance" -a -z "$dedicated_mysql" ]; then
+      if ! mysql_instance_exists "$mysql_instance"; then
+        error "there's no MySQL instance named '$mysql_instance'" -
+        return $?
+      fi
+
+      load_mysql_instance_config "$mysql_instance" || return $?
+
+      if ! is_var_set_to_yes mysql__params__shared; then
+        error "the specified mysql instance is not set as shared. So can't use it." -
+        return $?
+      fi
+    elif [ -n "$mysql_instance" -a -n "$dedicated_mysql" ]; then
+      if mysql_instance_exists "$mysql_instance"; then
+        load_mysql_instance_config "$mysql_instance" || return $?
+
+        if is_var_set_to_yes mysql__params__shared; then
+          # mysql instance is shared
+          error "can't use this mysql instance because it's shared" -
+          return $?
+        else
+          if [ -n "$mysql__params__vhosts" ]; then
+            # mysql instance is not shared, but there's already a vhost
+            error "this mysql instance is already being used by another vhost." -
+            return $?
+          fi
+        fi
+      else
+        # mysql instance doesn't exist, and a name was specified for it
+        create_mysql_instance=yes
+      fi
+    elif [ -z "$mysql_instance" -a -n "$dedicated_mysql" ]; then
+      create_mysql_instance=yes
+      mysql_instance="$vhost"
+    elif [ -z "$mysql_instance" -a -z "$dedicated_mysql" ]; then
+      if [ -n "$lamp__mysql__default_instance" ]; then
+        # no mysql was specified, but there's a system default:
+        #   use the default mysql instance
+        mysql_instance="$lamp__mysql__default_instance"
+      else
+        # backwards compatible behavior: create a new mysql instance when
+        # there isn't a default mysql instance in the configuration
+        #
+        # Each mysql instance generally requires hundreds of MB of memory
+        # allocation, what significantly limits the number of vhosts on a
+        # server. This is why we reverted this default.
+        create_mysql_instance=yes
+        mysql_instance="$vhost"
+      fi
+    else
+      error "unknown condition for determining mysql instance." -
+      return $?
+    fi
+  fi # // with_mysql sanity checks
+
+  # NOTE: the apache vhost needs to be created before the dedicated mysql
+  #       instance because it needs to check/create the vhost user and the
+  #       linux user of the mysql database is based on username of the
+  #       apache vhost
+  #
   if ! apache_vhost_create "${apache_args_ar[@]}" "$vhost"; then
     error "unable to create apache vhost" -
     return $?
   fi
 
-  mysql_instance="$vhost"
-  if mysql_create_instance_for_vhost "$vhost"; then
-    opts_ar+=( "mysql.instance = $mysql_instance" )
-  else
-    error "unable to create mysql instance" -
-    return $?
-  fi
+  if is_var_set_to_yes with_mysql; then
+    if is_var_set_to_yes create_mysql_instance; then
+      # create a new dedicated mysql instance
+      if ! mysql_create_instance_for_vhost "$vhost"; then
+        error "unable to create mysql instance" -
+        return $?
+      fi
+    else
+      # use an existing mysql instance, just setup the credentials
+      mysql_pw=$(gen_random_str_az09_lower 12)
+      db_prefix="${vhost//-/_}__"
+      if [ -n "$db_name" ]; then
+        mysql_db_name="${db_prefix}${db_name}"
+      elif [ -n "$subsystem" ]; then
+        mysql_db_name="${db_prefix}${subsystem}"
+      fi
+      
+      mysql_create_unpriv_user_for_vhost --user "$v__vhost__linux_user" \
+        --instance "$mysql_instance" --password "$mysql_pw"             \
+        --vhost "$vhost" --write-my-cnf --db-prefix "$db_prefix"
 
-  if [ -n "$subsystem" ]; then
-    if [ -z "$db_name" ]; then
-      db_name="$subsystem"
+      opts_ar+=( "mysql.external = yes" )
+      opts_ar+=( "mysql.database_prefix = $db_prefix" )
+
+      save_opts_in_mysql_instance "$mysql_instance" \
+        "params.vhosts +=w $vhost"
     fi
 
-    opts_ar+=( "app.subsystem       = $subsystem"  )
-    opts_ar+=( "app.database_name   = $db_name"    )
+    opts_ar+=( "mysql.instance      = $mysql_instance" )
+
+    if [ -n "$db_name" ]; then
+      if [ -n "$db_prefix" ]; then
+        mysql_db_name="${db_prefix}${db_name}"
+      else
+        mysql_db_name="$db_name"
+      fi
+    else
+      if [ -n "$subsystem" ]; then
+        if [ -n "$db_prefix" ]; then
+          mysql_db_name="${db_prefix}${subsystem}"
+        else
+          mysql_db_name="${subsystem}"
+        fi
+      fi
+    fi
+
+    if [ -n "$mysql_db_name" ]; then
+      opts_ar+=( "app.database_name   = $mysql_db_name"  )
+    fi
+  fi # // with_mysql
+
+  if [ -n "$subsystem" ]; then
+    opts_ar+=( "app.subsystem       = $subsystem"     )
   fi
 
   if [ -n "$description" ]; then
diff --git a/lib/cli/sbin/create-vhost b/lib/cli/sbin/create-vhost
--- a/lib/cli/sbin/create-vhost
+++ b/lib/cli/sbin/create-vhost
@@ -9,6 +9,13 @@ set_usage_msg \
     --from  <source>          source from where to create the app
                               (can be a filename or url for the tar ball)
 
+    --dedicated-mysql         create a new dedicated MySQL instance
+
+    --skip-mysql              don't do any MySQL configuration for this vhost
+
+    --mysql-instance name     use an existing MySQL instance as the MySQL
+                              server
+
     --title <site_title>      sets the website title for the apps that
                               support it
 
@@ -44,8 +51,9 @@ devpanel_cmd__create_vhost() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
   local name vhost from source_type title desc
-  local branch app_password read_pw_stdin php_version subsystem db_name
-  local source_type publisher uri_part app_url
+  local branch app_password read_pw_stdin php_version subsystem
+  local source_type publisher uri_part app_url mysql_instance db_name
+  local dedicated_mysql with_mysql=yes
   local print_summary=yes do_config_app=yes
   local -a cmd_args=() lamp_cmd_args=() app_cmd_ar=()
 
@@ -74,6 +82,43 @@ devpanel_cmd__create_vhost() {
         [ -z "$2" ] && error_missing_value "$name"
         php_version="$2"
         shift 2
+        ;;
+
+      --dedicated-mysql)
+        dedicated_mysql=yes
+        if ! is_var_set_to_yes with_mysql; then
+          error "conflicting mysql options on command line" -
+          return $?
+        fi
+
+        lamp_cmd_args+=( $name )
+        shift
+        ;;
+
+      --mysql-instance)
+        [ -z "$2" ] && error_missing_value "$name"
+
+        if ! is_var_set_to_yes with_mysql; then
+          error "conflicting mysql options on command line" -
+          return $?
+        fi
+
+        mysql_instance="$2"
+        lamp_cmd_args+=( "$name" "$mysql_instance" )
+        shift 2
+        ;;
+
+      --skip-mysql)
+        if [ -n "$dedicated_mysql" ]; then
+          error "can't use $name with --dedicated-mysql at the same time" -
+          return $?
+        elif [ -n "$mysql_instance" ]; then
+          error "can't use $name with --mysql-instance at the same time" -
+          return $?
+        fi
+
+        unset with_mysql
+        shift
         ;;
 
       --help)
@@ -287,6 +332,10 @@ devpanel_cmd__create_vhost() {
     return $?
   fi
 
+  if is_var_set_to_yes src__mysql__skip; then
+    unset with_mysql
+  fi
+
   if [ -n "$php_version" ]; then
     src__php__version="$php_version"
     lamp_cmd_args+=( --php-version "$php_version" )
@@ -295,12 +344,16 @@ devpanel_cmd__create_vhost() {
     lamp_cmd_args+=( --php-version "$php_version" )
   fi
 
-  if [ -n "$db_name" ]; then
-    lamp_cmd_args+=( --db-name "$db_name" )
-    src__app__database_name="$db_name"
-  elif [ -n "$src__app__database_name" ]; then
-    db_name="$src__app__database_name"
-    lamp_cmd_args+=( --db-name "$db_name" )
+  if is_var_set_to_yes with_mysql; then
+    if [ -n "$db_name" ]; then
+      lamp_cmd_args+=( --db-name "$db_name" )
+      src__app__database_name="$db_name"
+    elif [ -n "$src__app__database_name" ]; then
+      db_name="$src__app__database_name"
+      lamp_cmd_args+=( --db-name "$db_name" )
+    fi
+  else
+    lamp_cmd_args+=( --skip-mysql )
   fi
 
   if ! devpanel_run create lamp vhost "${lamp_cmd_args[@]}" --vhost "$vhost" \
diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -569,8 +569,8 @@ get_shell_from_user() {
 }
 
 run_as_user() {
-  local -a exec_args_ar=()
-  local opt_name
+  local -a exec_args_ar=() cmd_ar=()
+  local opt_name arg
   local shell_bin
   while [ -n "$1" -a "${1:0:1}" == - ]; do
     opt_name="$1"
@@ -606,7 +606,14 @@ run_as_user() {
   local user="$1"
   shift
 
-  local -a cmd_ar=( "$@" )
+  for arg in "$@"; do
+    if [[ "$arg" == *\ * ]]; then
+      # escape the arg if it contains a space
+      cmd_ar+=( $(printf '%q' "$arg") )
+    else
+      cmd_ar+=( "$arg" )
+    fi
+  done
 
   if hash runuser &>/dev/null; then
     runuser "${exec_args_ar[@]}" -c "${cmd_ar[*]}" "$user"
@@ -2200,7 +2207,7 @@ is_valid_mysql_db_or_table_name() {
 
   [ -z "$str" ] && return 1
 
-  if [[ "$str" =~ ^[A-Za-z0-9_]+$ ]]; then
+  if [[ "$str" =~ ^[A-Za-z0-9_-]+$ ]]; then
     return 0
   else
     return 1
@@ -2444,6 +2451,30 @@ get_list_of_enabled_vhosts() {
   fi
 
   return 0
+}
+
+get_list_of_mysql_instances() {
+  local config_dir="$lamp__paths__mysql_instances_config_dir"
+  local instance instance_dir
+  local -a instances_ar=()
+
+  if [ ! -d "$config_dir" ]; then
+    echo "$FUNCNAME(): missing config dir $config_dir" 1>&2
+    return 1
+  fi
+
+  for instance_dir in "$config_dir/"*; do
+    [ ! -d "$instance_dir" ] && continue
+    [ ! -f "$instance_dir/config.ini" ] && continue
+    instance=${instance_dir##*/}
+    instances_ar+=( "$instance" )
+  done
+
+  if [ ${#instances_ar[*]} -le 0 ]; then
+    return 0
+  else
+    echo "${instances_ar[@]}"
+  fi
 }
 
 get_vhost_with_hostname() {
@@ -3513,22 +3544,31 @@ App: @app_type@
 PHP Version: @php_version@
 SFTP User: @ssh_user@
 SFTP Host: @ssh_host@
-MySQL Host/Port: @db_host_port@
-MySQL Database:  @db_name@
 FastCGI: @fastcgi_status@
 Htpasswd: @htpasswd_status@
 Snapshots: @snapshots_txt@
 "
-
-  if should_skip_nginx_vhost "$vhost"; then
-    summ_txt+="Skipping nginx vhost: Yes"$'\n'
-  fi
 
   local domains_txt="" out_txt="" status_str=""
   local main_url ssh_host ssh_user db_name db_host_port db_name app_type
   local fastcgi_status htpasswd_status
   local snapshots_txt
   local ssl_txt php_ver
+
+  if [ -n "$v__mysql__instance" ]; then
+    summ_txt+="\
+MySQL Instance: @mysql_instance@
+MySQL Host/Port: @db_host_port@
+MySQL Database:  @db_name@
+"
+
+    db_host_port="$v__mysql__client__host:$v__mysql__client__port"
+    db_name="$v__app__database_name"
+  fi
+
+  if should_skip_nginx_vhost "$vhost"; then
+    summ_txt+="Skipping nginx vhost: Yes"$'\n'
+  fi
 
   if is_vhost_enabled "$vhost"; then
     status_str=enabled
@@ -3538,8 +3578,6 @@ Snapshots: @snapshots_txt@
 
   main_url=$(get_main_url_of_vhost "$vhost")
   app_type=$v__app__subsystem
-  db_host_port="$v__mysql__client__host:$v__mysql__client__port"
-  db_name="$v__app__database_name"
 
   if is_fastcgi_enabled_on_vhost "$vhost"; then
     fastcgi_status=enabled
@@ -3646,13 +3684,17 @@ Snapshots: @snapshots_txt@
   out_txt=${out_txt//@ssl_txt@/$ssl_txt}
   out_txt=${out_txt//@app_type@/$app_type}
   out_txt=${out_txt//@php_version@/$php_ver}
-  out_txt=${out_txt//@db_host_port@/$db_host_port}
-  out_txt=${out_txt//@db_name@/$db_name}
   out_txt=${out_txt//@ssh_user@/$ssh_user}
   out_txt=${out_txt//@ssh_host@/$ssh_host}
   out_txt=${out_txt//@fastcgi_status@/$fastcgi_status}
   out_txt=${out_txt//@htpasswd_status@/$htpasswd_status}
   out_txt=${out_txt//@snapshots_txt@/$snapshots_txt}
+
+  if [ -n "$v__mysql__instance" ]; then
+    out_txt=${out_txt//@mysql_instance@/$v__mysql__instance}
+    out_txt=${out_txt//@db_host_port@/$db_host_port}
+    out_txt=${out_txt//@db_name@/$db_name}
+  fi
 
   echo "$out_txt"
 }
@@ -3791,7 +3833,7 @@ print_vhost_metadata_json() {
   local tmp_bkp_files_json_ar="$tmp_dir_1/bkp_files_ar.json"
 
   local vhost_st fastcgi_st htpasswd_st st
-  local -a ssl_opts_ar
+  local -a ssl_opts_ar mysql_opts_ar app_opts_ar
   local app_type db_name doc_root user_inc_st https_redir_st
   local mysql_host mysql_user mysql_port mysql_password
   local linux_user
@@ -3812,10 +3854,12 @@ print_vhost_metadata_json() {
   fi
 
   app_type=$v__app__subsystem
-  db_name=$v__app__database_name
-  mysql_host=$v__mysql__client__host
-  mysql_port=$v__mysql__client__port
-  mysql_user=$v__mysql__client__user
+  if [ -n "$v__mysql__instance" ]; then
+    db_name=$v__app__database_name
+    mysql_host=$v__mysql__client__host
+    mysql_port=$v__mysql__client__port
+    mysql_user=$v__mysql__client__user
+  fi
 
   linux_user=$v__vhost__linux_user
 
@@ -3867,14 +3911,24 @@ print_vhost_metadata_json() {
     user_inc_st=0
   fi
 
+  if [ -n "$v__mysql__instance" ]; then
+    mysql_opts_ar+=( lamp.mysql.instance=$v__mysql__instance \
+                     lamp.mysql.host=$mysql_host             \
+                     lamp.mysql.port=$mysql_port             \
+                     lamp.mysql.user=$mysql_user
+    )
+  fi
+
+  if [ -n "$db_name" ]; then
+    app_opts_ar+=( app.database_name=$db_name )
+  fi
+
   jo ${pretty:+-p} -d . name=$vhost enabled@$vhost_st stack=$stack \
     domains:=$tmp_domains_json_af document_root="$doc_root" \
     backup_files:=$tmp_bkp_files_json_ar user_includes@$user_inc_st \
     fastcgi.enabled@$fastcgi_st htpasswd.enabled@$htpasswd_st \
-    app.linux_user="$linux_user" app.type=$app_type app.database_name=$db_name \
-    app.mysql_host=$mysql_host app.mysql_port=$mysql_port \
-    app.mysql_user=$mysql_user \
-    "${ssl_opts_ar[@]}"
+    app.linux_user="$linux_user" app.type=$app_type \
+    "${ssl_opts_ar[@]}" "${mysql_opts_ar[@]}" "${app_opts_ar[@]}"
   st=$?
 
   rm -rf "$tmp_dir_1"
