variable name fixes on cmd line parsing

diff --git a/lib/cli/bin/show-vhost-info b/lib/cli/bin/show-vhost-info
--- a/lib/cli/bin/show-vhost-info
+++ b/lib/cli/bin/show-vhost-info
@@ -24,17 +24,23 @@ devpanel_cmd__show_vhost_info() {
           vhost="$2"
           shift 2
         else
-          error "invalid format for vhost name"
+          error "invalid format for vhost name" -
+          return $?
         fi
         ;;
+
       --help)
         usage
         ;;
-      --[A-Za-z0-9_-]*)
-        error "unknown option $name"
+
+      --)
+        shift
+        break
         ;;
+
       *)
-        usage
+        error "unknown option $arg" -
+        return $?
         ;;
     esac
   done
