LAMP: major internal changes
* simpler management of mysql instances
* moved MySQL config to /etc/devpanel/mysql/instances/
* broke down LAMP stack creation in smaller steps
* tens of other small bug fixes

diff --git a/compat/dbmgr/0.0.7/bin/createdb b/compat/dbmgr/0.0.7/bin/createdb
--- a/compat/dbmgr/0.0.7/bin/createdb
+++ b/compat/dbmgr/0.0.7/bin/createdb
@@ -74,6 +74,13 @@ if [ x"$USER" == x$(id -nu "$USER" 2>/dev/null) ]; then
 	exit 3
 fi
 
+if ! . "$sys_dir/lib/functions"; then
+  echo "Error: failed to load '$sys_dir/lib/functions'" 1>&2
+  exit 1
+fi
+
+load_devpanel_config || exit $?
+
 DATA_DIR="${DB_HOME_BASE%%/}/$USER/$TYPE"
 
 "$DBMGR_BINDIR"daemon-add -t "$TYPE" -u "$USER" -d "$DATA_DIR" $ADDON #&> /dev/null
@@ -118,7 +125,7 @@ if [ "$?" -ne 0 ]; then
 	exit 5
 fi
 
-client_config_dir="$DBMGR_HOME/config/mysql/$USER"
+client_config_dir="$lamp__paths__mysql_instances_config_dir/$USER"
 # this is a hack
 w_USER=${USER/b_/w_}
 web_password=$($DBMGR_BINDIR/passgen)
diff --git a/compat/dbmgr/0.0.7/bin/daemon-action b/compat/dbmgr/0.0.7/bin/daemon-action
--- a/compat/dbmgr/0.0.7/bin/daemon-action
+++ b/compat/dbmgr/0.0.7/bin/daemon-action
@@ -49,7 +49,7 @@ instance_exists() {
     return 1
   fi
 
-  local config_dir="$dbmgr_dir/config/mysql/$instance"
+  local config_dir="$lamp__paths__mysql_instances_config_dir/$instance"
 
   if [ -d "$config_dir" ]; then
     return 0
@@ -142,7 +142,7 @@ has_conditional_lock() {
 
 ping_mysql_instance() {
   local instance="$1"
-  local config_file="$dbmgr_dir/config/mysql/$instance/root.client.cnf"
+  local config_file="$lamp__paths__mysql_instances_config_dir/$instance/root.client.cnf"
 
   mysqladmin --defaults-file="$config_file" ping
 }
@@ -156,7 +156,7 @@ start_mysql_instance() {
 stop_mysql_instance() {
   local instance="$1"
 
-  local config_file="$dbmgr_dir/config/mysql/$instance/root.client.cnf"
+  local config_file="$lamp__paths__mysql_instances_config_dir/$instance/root.client.cnf"
 
   mysqladmin --defaults-file="$config_file" --verbose shutdown
 }
@@ -209,9 +209,16 @@ sys_dir="${dbmgr_dir%/*/*}"
 action="$1"
 instance="$2"
 
+if ! . "$sys_dir/lib/functions"; then
+  error "failed to load '$sys_dir/lib/functions'"
+fi
+
+load_devpanel_config || exit $?
+
 if ! instance_exists "$instance"; then
   error "mysql instance doesn't exist."
 fi
+
 
 case "$action" in
   status)
diff --git a/lib/cli/bin/config-app b/lib/cli/bin/config-app
--- a/lib/cli/bin/config-app
+++ b/lib/cli/bin/config-app
@@ -5,7 +5,23 @@ set_usage_msg \
 
   Options:
     --vhost <vhost>             the vhost
+
     --name-value <name=value>   sets the specified name and value
+
+    --refresh-config-file       update the config file(s) with mysql
+                                credentials, etc
+
+    --config-function name      name of the config function to run to setup
+                                the app
+
+    --install-profile name      name of the install profile for apps that
+                                support different profiles on install
+
+    --site-title title          title of the website created by the app (for
+                                apps that support it)
+
+    --first-setup               update config with settings usually done
+                                on the first setup (setup URL, etc)
 
   Sets specific name and value pairs to the specified application.
 "
@@ -13,7 +29,7 @@ set_usage_msg \
 devpanel_cmd__config_app() {
   [ $EUID -eq 0 ] && [ $# -eq 0 -o -z "$1" ] && usage
 
-  local name vhost admin_pw user
+  local name vhost admin_pw user config_function
 
   local -a cmd_args=()
   local -a opts_ar=( )
@@ -26,11 +42,23 @@ devpanel_cmd__config_app() {
         vhost="$2"
         shift 2
         ;;
+
       --admin-password)
         [ -z "$2" ] && error_missing_value admin-password
         admin_pw="$2"
         shift 2
         ;;
+
+      --refresh-config-file)
+        opts_ar+=( -n )
+        shift
+        ;;
+
+      --first-setup)
+        opts_ar+=( -n -F )
+        shift
+        ;;
+
       --name-value)
         [ -z "$2" ] && error_missing_value name-value
         if [[ "$2" == *=* ]]; then
@@ -41,19 +69,46 @@ devpanel_cmd__config_app() {
 
         shift 2
         ;;
+
+      --site-title)
+        [ -z "$2" ] && error_missing_value "$name"
+        opts_ar+=( -O site_title="$2" )
+        shift 2
+        ;;
+
+      --config-function)
+        [ -z "$2" ] && error_missing_value "$name"
+        if [[ "$2" =~ ^[A-Za-z0-9_-]+$ ]]; then
+          opts_ar+=( -O config_function=$2 )
+        else
+          error "invalid format for parameter $name" -
+          return $?
+        fi
+        shift 2
+        ;;
+
+      --install-profile)
+        [ -z "$2" ] && error_missing_value "$name"
+        if [[ "$2" =~ ^[A-Za-z0-9_-]+$ ]]; then
+          opts_ar+=( -O install_profile=$2 )
+        else
+          error "invalid format for parameter $name" -
+          return $?
+        fi
+        shift 2
+        ;;
+
       --help)
         usage
         ;;
+
       --)
         shift
         break
         ;;
-      --[A-Za-z0-9_-]*)
-        error "unknown option $name"
-        ;;
+
       *)
-        cmd_args+=( "$name" )
-        shift
+        error "unknown option $name"
         ;;
     esac
   done
diff --git a/lib/cli/bin/restore-backup b/lib/cli/bin/restore-backup
--- a/lib/cli/bin/restore-backup
+++ b/lib/cli/bin/restore-backup
@@ -8,34 +8,27 @@ set_usage_msg \
 
     --filename <filename>       name of the archive file to extract
 
+    --dont-remove-files         don't remove all existing files/dirs before
+                                restoring. By default all files are removed
+                                before restoring the backup file.
+
+    --quiet                     don't show progress/success msgs
+
+    --dont-disable-vhost        don't disable the Apache vhost meanwhile
+                                restoring
+
   Restore the contents of a backup of the vhost.
 
   NOTE: it overwrites the current data.
 "
 
-devpanel_cmd__restore_backup_on_exit() {
-  local vhost="$1"
-
-  # re-enable the vhost in case the user running it is root
-  if [ $EUID -eq 0 ]; then
-    devpanel_run rewrite vhost config --vhost $vhost
-  fi
-
-  if [ $exit_code -eq 0 ]; then
-    echo
-    echo "Successfully restored vhost $vhost."
-  else
-    echo
-    error "failed to restore vhost $vhost." -
-  fi
-}
-
 devpanel_cmd__restore_backup() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
   local name vhost filename skip_files skip_dbs public_files
-  local temp_dir
+  local temp_dir quiet
   local vhost_home_dir web_user doc_root st
+  local disable_vhost=yes remove_files=yes
   local -a extract_args_ar=()
 
   while [ -n "$1" ]; do
@@ -55,6 +48,11 @@ devpanel_cmd__restore_backup() {
         shift 2
         ;;
 
+      --quiet)
+        quiet=1
+        shift
+        ;;
+
       --help)
         usage
         ;;
@@ -63,6 +61,17 @@ devpanel_cmd__restore_backup() {
         shift
         break
         ;;
+
+      --dont-disable-vhost)
+        unset disable_vhost
+        shift
+        ;;
+
+      --dont-remove-files)
+        unset remove_files
+        shift
+        ;;
+
       *)
         error "unknown option $name"
         ;;
@@ -116,12 +125,11 @@ devpanel_cmd__restore_backup() {
 
   extract_args_ar+=( --target-dir "$temp_dir" --extract-raw --quiet )
 
-  if [ $EUID -eq 0 ]; then
+  if [ $EUID -eq 0 -a -n "$disable_vhost" ]; then
     # temporarily disable the vhost on apache for the app not to be modified
     # during the restore
     "$sys_dir/libexec/rewrite-vhost-config" -D $vhost || return $?
   fi
-  devpanel_trap_exit_cmds_ar+=( "devpanel_cmd__restore_backup_on_exit $vhost" )
 
   # TODO(enhance): check if there's enough disk space to extract the files
   #       (it's actually better to do on 'extract backup' command)
@@ -146,7 +154,8 @@ devpanel_cmd__restore_backup() {
   fi
 
   local import_dbs_bin="$sys_dir/bin/import-databases-from-dir"
-  local -a import_dbs_cmd_ar=( "$import_dbs_bin" --safer-overwrite "$temp_dir/db" )
+  local -a import_dbs_cmd_ar=( "$import_dbs_bin" --safer-overwrite \
+                                --my-cnf "$v__mysql__client_file" "$temp_dir/db" )
   if [ $EUID -eq 0 ]; then
     run_as_user --login "$web_user" "${import_dbs_cmd_ar[@]}"
   else
@@ -159,27 +168,30 @@ devpanel_cmd__restore_backup() {
     return $st
   fi
 
-  local -a remove_dirs_cmd_ar=(
-    rm -rf "$vhost_home_dir" \; mkdir -m 751 -p "$doc_root"
-  )
+  if [ -n "$remove_files" ]; then
+    local -a remove_dirs_cmd_ar=(
+      rm -rf "$vhost_home_dir" \; mkdir -m 751 -p "$doc_root"
+    )
 
-  if [ $EUID -eq 0 ]; then
-    run_as_user "$web_user" "${remove_dirs_cmd_ar[@]}" \
-                  >$temp_dir/rm-output.txt 2>&1
-  else
-    # have to duplicate command here instead of using $remove_dirs_cmd_ar
-    # because the ';' is expanded as a quoted string
-    rm -rf "$vhost_home_dir" >$temp_dir/rm-output.txt 2>&1
-    mkdir -m 751 -p "$doc_root"
-  fi
+    if [ $EUID -eq 0 ]; then
+      run_as_user "$web_user" "${remove_dirs_cmd_ar[@]}" \
+                    >$temp_dir/rm-output.txt 2>&1
+    else
+      # have to duplicate command here instead of using $remove_dirs_cmd_ar
+      # because the ';' is expanded as a quoted string
+      rm -rf "$vhost_home_dir" >$temp_dir/rm-output.txt 2>&1
+      mkdir -m 751 -p "$doc_root"
+    fi
 
-  # it'll warn about removing the user dir (the user doesn't have write
-  # permissions to the $vhost_home_dir/../ )
-  # 
-  # if there's only one warning, then it's ok. Otherwise show the warnings.
-  local rm_n_err=`wc -l < $temp_dir/rm-output.txt`
-  if [ $? -eq 0 -a $rm_n_err -gt 1 ]; then
-    cat $temp_dir/rm-output.txt 1>&2
+    # it'll warn about removing the user dir (the user doesn't have write
+    # permissions to the $vhost_home_dir/../ )
+    # 
+    # if there's only one warning, then it's ok. Otherwise show the warnings.
+    local rm_n_err=`wc -l < $temp_dir/rm-output.txt`
+    if [ $? -eq 0 -a $rm_n_err -gt 1 ]; then
+      cat $temp_dir/rm-output.txt 1>&2
+    fi
+
   fi
 
   # TODO(enhance): regenerate prod specific files (e.g. ~/logs ~/.my.cnf )
@@ -200,7 +212,7 @@ devpanel_cmd__restore_backup() {
   extract_cmd_ar=( "$extract_bin" "$temp_dir/web" "$vhost" \
                        "$vhost_home_dir" "$doc_root" )
 
-  echo "Extracting files..."
+  [ -z "$quiet" ] && echo "Extracting files..."
   if [ $EUID -eq 0 ]; then
     run_as_user --login "$web_user" "${extract_cmd_ar[@]}"
   else
@@ -208,10 +220,24 @@ devpanel_cmd__restore_backup() {
   fi
   st=$?
 
-  # NOTE: status msg is sent by the function that traps the exit of the
-  # shell to properly display order of status msgs (because sometimes Apache
-  # needs to be reloaded on exit, and we don't want Apache msgs to be the
-  # last ones).
+  if [ -n "$remove_files" -a -n "$v__php__version" ]; then
+    # when all files are removed it also removes the PHP links that set the
+    # PHP version of the vhost. So we need to reset it.
+    devpanel_run set php version --vhost "$vhost" \
+      --version "$v__php__version"
+  fi
+
+  # re-enable the vhost in case the user running it is root
+  if [ $EUID -eq 0 -a -n "$disable_vhost" ]; then
+    devpanel_run rewrite vhost config --vhost $vhost
+  fi
+
+  if [ $st -eq 0 ]; then
+    [ -z "$quiet" ] && { echo; echo "Successfully restored vhost $vhost."; }
+  else
+    echo
+    error "failed to restore vhost $vhost." -
+  fi
 
   return $st
 }
diff --git a/lib/cli/sbin/clone-vhost b/lib/cli/sbin/clone-vhost
--- a/lib/cli/sbin/clone-vhost
+++ b/lib/cli/sbin/clone-vhost
@@ -9,13 +9,18 @@ set_usage_msg \
 
     --target-vhost  <vhost>         the new vhost to be created
 
+    --password-stdin                read the password of the admin user of
+                                    the app from stdin
+
   Clones a vhost to a new virtual host (copies the files and databases to a
   new virtual host).
 "
 
 devpanel_cmd__clone_vhost() {
   local name source_vhost target_vhost
+  local source_vuser tmp_archive tmp_archive_fp
   local st php_ver
+  local -a restore_args_ar=()
   
   [ $# -eq 0 -o -z "$1" ] && usage
 
@@ -28,21 +33,31 @@ devpanel_cmd__clone_vhost() {
         source_vhost="$2"
         shift 2
         ;;
+
       --target-vhost)
         [ -z "$2" ] && error_missing_value "$name"
         target_vhost="$2"
         shift 2
         ;;
+
+      --password-stdin)
+        restore_args_ar+=( --password-stdin )
+        shift
+        ;;
+
       --help)
         usage
         shift
         ;;
+
       --)
         shift
         break
         ;;
+
       *)
-        error "unknown parameter: $name"
+        error "unknown parameter: $name" -
+        return $?
         ;;
     esac
   done
@@ -57,11 +72,25 @@ devpanel_cmd__clone_vhost() {
     error "target vhost already exists. Can't clone to an existing vhost."
   fi
 
-  "$sys_dir/libexec/clone-vhost-local" "$source_vhost" "$target_vhost"
-  st=$?
+  load_vhost_config "$source_vhost" || return $?
+  source_vuser="$v__vhost__linux_user"
 
-  if [ $st -ne 0 ]; then
-    return $st
+  tmp_archive="tmp_archive_$source_vhost-$(date +%b-%d-%Y--%H-%M).tgz"
+  tmp_archive_fp="$v__vhost__archives_dir/$tmp_archive"
+
+  echo "Cloning stage 1: archive $src_vhost to $tmp_archive"
+  if ! devpanel_run backup vhost --vhost "$source_vhost" \
+         --file "$tmp_archive"; then
+    return 1
+  fi
+  devpanel_trap_exit_cmds_ar+=( "rm -f $tmp_archive_fp" )
+
+  echo "Cloning stage 2: restore $target_vhost from $tmp_archive"
+  restore_args_ar+=( --vhost "$target_vhost" --from "$tmp_archive_fp" )
+  restore_args_ar+=( --no-summary )
+  if ! devpanel_run create vhost "${restore_args_ar[@]}"; then
+    error "failed to create vhost '$target_vhost' from '$tmp_archive'" -
+    return $?
   fi
 
   if is_htpasswd_enabled_on_vhost "$source_vhost"; then
@@ -76,5 +105,4 @@ devpanel_cmd__clone_vhost() {
 
   echo "Successfully cloned vhost '$source_vhost' to '$target_vhost'"
   return 0
-
 }
diff --git a/lib/cli/sbin/create-vhost b/lib/cli/sbin/create-vhost
--- a/lib/cli/sbin/create-vhost
+++ b/lib/cli/sbin/create-vhost
@@ -5,14 +5,12 @@ set_usage_msg \
 
   Options:
     --vhost <vhost>           name of the vhost
+
     --from  <source>          source from where to create the app
-                              (can be a filename or a public git url)
+                              (can be a filename or url for the tar ball)
 
     --title <site_title>      sets the website title for the apps that
                               support it
-
-    --branch <branch>         when the source type is git, clone the
-                              specified branch
 
     --desc <description>      a short description of the vhost's purpose
 
@@ -24,6 +22,15 @@ set_usage_msg \
     --no-summary              don't print the summary information after
                               creating the vhost
 
+    --subsystem <name>        name of the app subsystem (e.g. drupal,
+                              wordpress, etc)
+
+    --config-function name    name of the config function to run to setup
+                              the app
+
+    --install-profile name    name of the install profile for apps that
+                              support different profiles on install
+
   Creates a new vhost from the specified source.
 "
 
@@ -32,12 +39,10 @@ devpanel_cmd__create_vhost() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
   local name vhost from source_type title desc
-  local branch app_password read_pw_stdin php_version
+  local branch app_password read_pw_stdin php_version subsystem
+  local source_type publisher uri_part app_url
   local print_summary=yes
-  local -a cmd_args=()
-
-  # by default let's assume the source is a file
-  local def_source_type=file
+  local -a cmd_args=() lamp_cmd_args=() app_cmd_ar=()
 
   while [ -n "$1" ]; do
     name="$1"
@@ -52,33 +57,32 @@ devpanel_cmd__create_vhost() {
         from="$2"
         shift 2
         ;;
-      --branch)
-        [ -z "$2" ] && error_missing_value branch
-        branch="$2"
-        cmd_args+=( -b "$branch" )
-        shift 2
-        ;;
+
       --title)
         [ -z "$2" ] && error_missing_value title
         title="$2"
-        cmd_args+=( -O "site_title=$title" )
+        app_cmd_ar+=( --site-title "$title" )
         shift 2
         ;;
 
       --php-version)
         [ -z "$2" ] && error_missing_value "$name"
         php_version="$2"
+        lamp_cmd_args+=( "$name" "$php_version" )
         shift 2
         ;;
 
       --help)
         usage
         ;;
+
       --desc)
         [ -z "$2" ] && error_missing_value "$name"
         desc="$2"
+        lamp_cmd_args+=( --description "$desc" )
         shift 2
         ;;
+
       --password-stdin)
         read_pw_stdin=1
         shift
@@ -87,6 +91,29 @@ devpanel_cmd__create_vhost() {
       --no-summary)
         unset print_summary
         shift
+        ;;
+
+      --subsystem)
+        [ -z "$2" ] && error_missing_value "$name"
+        if is_known_seedapp_subsystem "$2"; then
+          subsystem="$2"
+        else
+          error "unknown subsystem" -
+          return 1
+        fi
+
+        shift 2
+        ;;
+
+      --config-function|--install-profile)
+        [ -z "$2" ] && error_missing_value "$name"
+        if [[ "$2" =~ ^[A-Za-z0-9_-]+$ ]]; then
+          app_cmd_ar+=( "$name" "$2" )
+        else
+          error "invalid format for parameter $name" -
+          return $?
+        fi
+        shift 2
         ;;
 
       --[A-Za-z0-9_-]*)
@@ -117,12 +144,46 @@ devpanel_cmd__create_vhost() {
   [ -z "$vhost" ]  && error_missing_param vhost
   [ -z "$from" ]   && error_missing_param from
 
+  if ! is_valid_vhost_string "$vhost"; then
+    error "invalid string format for vhost name" -
+    return $?
+  fi
+
+  if vhost_exists "$vhost"; then
+    error "there's already a vhost with this name." -
+    return $?
+  fi
+
   # detect the source type
-  # e.g. github://drupal/serverlink , we://drupal-v7
+  # e.g. devpanel://wordpress-v4, webenabled://drupal-v7
+  #      http://...
   if [[ "$from" =~ ^([a-z0-9]+)://.+$ ]]; then
-    source_type=${BASH_REMATCH[1]}
+    source_type=url
+
+    # check if it's a short hand publisher://name url
+    # and then translate it
+    if [[ "$from" =~ ^([a-z0-9]+)://[A-Za-z0-9-]+$ ]] && \
+       ! in_array "$source_type" file ftp http https; then
+
+      publisher=${from%%://*}
+      uri_part=${from#*://}
+      if is_known_seedapp_publisher "$publisher"; then
+        if ! app_url=$(get_tarball_url_for_app "$uri_part" "$publisher"); then
+          return 1
+        fi
+      else
+        error "unknown publisher '$publisher'" -
+        return 1
+      fi
+    else
+      # otherwise, treat it as a url to be passed directly to curl
+      app_url="$from"
+    fi
+  elif [ "$from" == - ]; then
+    source_type=stdin
   else
-    source_type="$def_source_type"
+    # by default let's assume the source is a file
+    source_type=file
   fi
 
   if [ -n "$read_pw_stdin" ]; then
@@ -139,43 +200,93 @@ devpanel_cmd__create_vhost() {
     cmd_args+=( -T "$php_version" )
   fi
 
-  if [ "$source_type" == "github" -o "$source_type" == "git" ]; then
+  if [ -n "$from" ]; then
+    case $source_type in
+      file)
+        if [ -f "$from" ]; then
+          src_archive="$from"
+        else
+          error "file not found" -
+          return 1
+        fi
+        ;;
 
-    # replace github://name/repo with https://github.com/name/repo.git
-    if [ "$source_type" == "github" ]; then
-      from=${from//$source_type:\/\//https:\/\/github.com\/}
-      if ! [[ "$from" == *.git ]]; then
-        from+=.git
-      fi
-    fi
+      stdin)
+        if src_archive=$(mktemp); then
+          temp_files_ar+=( "$src_archive" )
+        else
+          error "unable to create temp file" -
+          return $?
+        fi
 
-    "$sys_dir/libexec/import-site-from-git" "${cmd_args[@]}" "$vhost" "$from"
-    st=$?
-  else
-    "$sys_dir/libexec/restore-vhost" "${cmd_args[@]}" $vhost "$from"
-    st=$?
+        if [ -t 0 ]; then
+          echo "Reading archive file from STDIN..." 1>&2
+        fi
+
+        if ! cat >$src_archive; then
+          error "failed to save archive file '$src_archive'" -
+          return $?
+        fi
+
+        ;;
+
+      url)
+        if src_archive=$(mktemp); then
+          temp_files_ar+=( "$src_archive" )
+        else
+          error "unable to create temp file" -
+          return $?
+        fi
+
+        download_url_n_cache "$app_url" "$src_archive" || return $?
+        ;;
+
+        *)
+        error "don't know how to handle --from value '$from' (not an existing file nor a url)" -
+        return $?
+        ;;
+      esac
+  fi # // if [ -n $from ]
+
+  if [ -z "$subsystem" ]; then
+    # guess app type from tar ball when --subsystem not specified
+    subsystem=$(guess_subsystem_from_app_archive "$src_archive" ) || \
+      return $?
   fi
 
-  if [ $st -eq 0 ]; then
-    if ! load_vhost_config "$vhost"; then
-      echo "Warning: unable to load config for the newly created vhost" 1>&2
-    fi
+  if ! devpanel_run create lamp vhost "${lamp_cmd_args[@]}" --vhost "$vhost" \
+         --subsystem "$subsystem" --dont-activate-now; then
 
-    if [ -n "$app_password" ]; then
-      echo "$app_password" | devpanel_run reset app password --vhost "$vhost"
-      if [ $? -ne 0 ]; then
-        echo "Warning: failed setting the password for app..." 1>&2
-      fi
-    fi
-
-    if [ -n "$desc" ]; then
-      devpanel_run set vhost description --vhost "$vhost" --quiet --desc "$desc"
-    fi
-
-    [ -n "$print_summary" ] && print_vhost_summary "$vhost"
-
-    echo "Successfully created vhost $vhost"
+    error "failed to create lamp vhost" -
+    return $?
   fi
 
-  return $st
+  if ! devpanel_run restore backup --vhost "$vhost" --dont-remove-files \
+       --filename "$src_archive" --dont-disable-vhost --quiet; then
+    error "failed to extract the contents of tar ball" -
+    return $?
+  fi
+
+  app_cmd_ar+=( --first-setup )
+  devpanel_run config app "${app_cmd_ar[@]}" --vhost "$vhost" || return $?
+
+  if ! load_vhost_config "$vhost"; then
+    echo "Warning: unable to load config for the newly created vhost" 1>&2
+  fi
+
+  if [ -n "$app_password" ]; then
+    echo "$app_password" | devpanel_run reset app password --vhost "$vhost"
+    if [ $? -ne 0 ]; then
+      echo "Warning: failed setting the password for app..." 1>&2
+    fi
+  fi
+
+  if ! devpanel_run rewrite vhost config --vhost "$vhost"; then
+    echo "Warning: vhost created, but failed to write Apache config" 1>&2
+    [ -t 0 ] && sleep 2
+  fi
+
+  [ -n "$print_summary" ] && print_vhost_summary "$vhost"
+
+  echo "Successfully created vhost $vhost"
 }
diff --git a/lib/cli/sbin/restart-mysql b/lib/cli/sbin/restart-mysql
--- a/lib/cli/sbin/restart-mysql
+++ b/lib/cli/sbin/restart-mysql
@@ -5,16 +5,26 @@ set_usage_msg \
 
   Options:
     --vhost  <vhost>          the vhost
+
     --domain <domain>         find the vhost associated with the
                               specified domain
+
     --conditional             only try to restart if the vhost is enabled
+
+    --quick                  just start MySQL but don't verify where it
+                             keeps running (e.g. didn't stop due to an
+                             internal error)
+
 
   Restarts mysqld associated with the specified domain or vhost.
 "
 
 devpanel_cmd__restart_mysql() {
   local param vhost domain vhost_user db_user  
-  local conditional
+  local instance conditional quick
+  local -a cmd_args_ar=()
+  local -i st
+
   [ $# -eq 0 -o -z "$1" ] && usage
 
   while [ -n "$1" ]; do
@@ -26,22 +36,34 @@ devpanel_cmd__restart_mysql() {
         vhost="$2"
         shift 2
         ;;
+
       --domain)
         [ -z "$2" ] && error_missing_value domain
         domain="$2"
         shift 2
         ;;
+
+      --quick)
+        quick=yes
+        cmd_args_ar+=( $param )
+        shift
+        ;;
+
       --help)
         usage
         ;;
+
       --)
         shift
         break
         ;;
+
       --conditional)
         conditional=1
+        cmd_args_ar+=( $param )
         shift
         ;;
+
       *)
         error "unknown parameter: $param"
         ;;
@@ -66,24 +88,25 @@ devpanel_cmd__restart_mysql() {
   load_vhost_config "$vhost" || return $?
   vhost_user="$v__vhost__linux_user"
 
+  if [ -z "$v__mysql__instance" ]; then
+    error "this vhost is not associated to a MySQL instance" -
+    return $?
+  fi
+
   if [ -n "$conditional" ]; then
     if ! is_vhost_enabled "$vhost"; then
       return 0
     fi
   fi
 
-  db_user="b_${vhost_user#w_}"
-
-  local actions_bin="$sys_dir/compat/dbmgr/current/bin/daemon-action"
-
-  "$actions_bin" stop-politely-or-force "$db_user"
-
-  echo "Starting mysql for vhost $vhost..."
-  echo -n "  "
-  "$actions_bin" start "$db_user"
-  if [ $? -eq 0 ]; then
-    return 0
-  else
-    error "unable to start mysql for vhost $vhost"
+  mysql_instance_is_running "$instance"
+  st=$?
+  if [ $st -eq 0 ]; then
+    devpanel_run stop mysql --vhost "$vhost" --forceful
+  elif [ $st -eq 50 ]; then
+    error "unable to get status of mysql instance" -
+    return $?
   fi
+
+  devpanel_run start mysql --vhost "$vhost" "${cmd_args_ar[@]}"
 }
diff --git a/lib/cli/sbin/start-mysql b/lib/cli/sbin/start-mysql
--- a/lib/cli/sbin/start-mysql
+++ b/lib/cli/sbin/start-mysql
@@ -5,17 +5,24 @@ set_usage_msg \
 
   Options:
     --vhost  <vhost>         the vhost
+
     --domain <domain>        find the vhost associated with the
                              specified domain
+
     --conditional            only start if the vhost is not disabled and
                              if mysql was not intentionally stopped
+
+    --quick                  just start MySQL but don't verify where it
+                             keeps running (e.g. didn't stop due to an
+                             internal error)
 
   Starts mysqld associated with the specified domain or vhost.
 "
 
 devpanel_cmd__start_mysql() {
-  local param vhost vhost_user db_user domain
-  local conditional
+  local param vhost vhost_user domain instance
+  local conditional quick
+  local st
   
   [ $# -eq 0 -o -z "$1" ] && usage
 
@@ -28,15 +35,23 @@ devpanel_cmd__start_mysql() {
         vhost="$2"
         shift 2
         ;;
+
       --domain)
         [ -z "$2" ] && error_missing_value domain
         domain="$2"
         shift 2
         ;;
+
       --conditional)
         conditional=1
         shift
         ;;
+
+      --quick)
+        quick=yes
+        shift
+        ;;
+
       --help)
         usage
         ;;
@@ -64,27 +79,57 @@ devpanel_cmd__start_mysql() {
   load_vhost_config "$vhost" || return $?
   vhost_user="$v__vhost__linux_user"
 
-  if [ -z "$v__mysql__instance" ]; then
-    if [ -t 0 ]; then
-      echo "Warning: this vhost doesn't have any mysql instance" 1>&2
-    fi
+  if [ -n "$v__mysql__instance" ]; then
+    instance="$v__mysql__instance"
 
-    return 0
+    if [ -n "$v__mysql__external" -a "$v__mysql__external" == yes ]; then
+      if [ -t 0 ]; then
+        echo -n "Warning: the mysql instance of this vhost is external"
+        echo " (will not restart it)"
+      fi
+
+      return 0
+    fi
+  else
+    error "this vhost doesn't have a mysql instance" -
+    return $?
   fi
 
-  db_user="b_${vhost_user#w_}"
-     
-  local action
   if [ -n "$conditional" ]; then
     if ! is_vhost_enabled "$vhost"; then
       # vhost is disabled, don't start it
       return 0
     fi
 
-    action="cond-start"
-  else
-    action=start
+    if mysql_is_instanced_autostart_locked "$instance"; then
+      # don't start if the instance is locked (e.g. manually stopped)
+      return 0
+    fi
+
+    if mysql_instance_is_running "$instance"; then
+      return 0
+    fi
   fi
 
-  "$sys_dir/compat/dbmgr/current/bin/daemon-action" "$action" "$db_user"
+  mysql_instance_is_running "$instance"
+  st=$?
+  if [ $st -eq 0 ]; then
+    error "mysql instance is already running" -
+    return $?
+  elif [ $st -eq 50 ]; then
+    # 50 == internal error, unable to determine mysql state
+    error "unable to determine mysql status" -
+    return $st
+  fi
+
+  mysql_unlock_instance_autostart "$instance"
+
+  if [ -n "$quick" ]; then
+    mysql_start_instance "$instance"
+  else
+    mysql_start_n_check_instance "$instance"
+    if [ $? -eq 0 ]; then
+      echo "Successfully started MySQL instance '$instance'"
+    fi
+  fi
 }
diff --git a/lib/cli/sbin/stop-mysql b/lib/cli/sbin/stop-mysql
--- a/lib/cli/sbin/stop-mysql
+++ b/lib/cli/sbin/stop-mysql
@@ -7,12 +7,14 @@ set_usage_msg \
     --vhost  <vhost>         the vhost
     --domain <domain>        find the vhost associated with the
                              specified domain
+    --forceful               do a forceful stop (kill -9)
 
   Stops mysqld associated with the specified domain or vhost.
 "
 
 devpanel_cmd__stop_mysql() {
-  local param vhost vhost_user db_user domain
+  local param vhost vhost_user db_user domain instance forceful
+  local st
   
   [ $# -eq 0 -o -z "$1" ] && usage
 
@@ -29,6 +31,10 @@ devpanel_cmd__stop_mysql() {
         [ -z "$2" ] && error_missing_value domain
         domain="$2"
         shift 2
+        ;;
+      --forceful)
+        forceful=yes
+        shift
         ;;
       --help)
         usage
@@ -55,14 +61,46 @@ devpanel_cmd__stop_mysql() {
   fi
 
   load_vhost_config "$vhost" || return $?
-  vhost_user="$v__vhost__linux_user"
+  if [ -n "$v__mysql__instance" ]; then
+    instance="$v__mysql__instance"
 
-  db_user="b_${vhost_user#w_}"
-     
-  "$sys_dir/compat/dbmgr/current/bin/daemon-action" stop "$db_user"
-  if [ $? -eq 0 ]; then
-    echo "Successfully stopped mysql instance for vhost $vhost"
+    if [ -n "$v__mysql__external" -a "$v__mysql__external" == yes ]; then
+      error "the mysql of this vhost is external. Can't be restarted" 1>&2 -
+      return $?
+    fi
   else
-    error "unable to stop mysql instance for vhost $vhost"
+    error "this vhost doesn't have any mysql instance" -
+    return $?
+  fi
+
+  mysql_instance_is_running "$instance"
+  st=$?
+  if [ $st -ne 0 ]; then
+    if [ $st -eq 50 ]; then
+      # 50 == internal error
+      error "can't get status of mysql instance" -
+      return $?
+    else
+      error "mysql instance is not running" -
+      return $?
+    fi
+  fi
+
+  mysql_lock_instance_autostart "$instance"
+
+  if mysql_stop_instance "$instance"; then
+    echo "Succesfully stopped mysql instance '$instance'"
+    return 0
+  else
+    if [ -z "$forceful" ]; then
+      echo "Failed to stop mysql instance '$instance'" 1>&2
+      return 1
+    fi
+  fi
+
+  if [ -n "$forceful" ]; then
+    mysql_force_instance_stop "$instance"
+  else
+    return 0
   fi
 }
diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -377,11 +377,43 @@ wedp_gen_random_str() {
   fi
 }
 
+gen_12char_random_uuid() {
+  local raw hex
+
+  raw=$(head -c 16384 /dev/urandom | md5sum )
+  if [ $? -ne 0 ]; then
+    echo "$FUNCNAME(): failed to generate uuid" 1>&2
+    return 1
+  fi
+
+  hex=${raw%% *}
+  if [ -z "$hex" ]; then
+    echo "$FUNCNAME(): got an empty hex string" 1>&2
+    return 1
+  elif [ ${#hex} -ne 32 ]; then
+    echo "$FUNCNAME(): got a hex string of ${#hex} characters (not 32)" 1>&2
+    return 1
+  elif [ ${#hex} -eq 32 ]; then
+    echo "${hex:0:8}-${hex:8:4}-${hex:12:4}-${hex:16:4}-${hex:20:12}"
+    return 0
+  else
+    echo "$FUNCNAME(): got an invalid hex string" 1>&2
+    return 1
+  fi
+}
+
 gen_random_str_az_lower() {
   local length=${1:-6}
   local str
 
   wedp_gen_random_str $length a-z
+}
+
+gen_random_str_az09_lower() {
+  local length=${1:-6}
+  local str
+
+  wedp_gen_random_str $length a-z0-9
 }
 
 is_valid_domain_string() {
@@ -744,6 +776,28 @@ download_url_n_cache() {
   fi
 
   return 0
+}
+
+translate_url_from_publisher_uri() {
+  local uri="$1"
+  local publisher url base_url tmp_rel_url
+
+  publisher="${uri%%://*}"
+
+  if [[ ! "$publisher" =~ ^[a-z0-9]+$ ]]; then
+    echo "$FUNCNAME(): error, invalid publisher name" 1>&2
+    return 1
+  fi
+
+  base_url=$(get_base_url_for_publisher "$publisher" ) || return $?
+
+  tmp_rel_url=${uri#*://}
+  url="${base_url%/}/$tmp_rel_url"
+  if ! [[ "$url" == *.tgz ]]; then
+    url+=".tgz"
+  fi
+
+  echo "$url"
 }
 
 ini_section_get_key_value() {
@@ -1387,6 +1441,37 @@ get_metadata_value() {
   else
     echo "$FUNCNAME(): found, but couldn't read link value on '$link_path'" 1>&2
     return 1
+  fi
+}
+
+looks_like_an_app_url() {
+  local url="$1"
+
+  if [  ${#url} -gt 10 -a "${url:0:7}"   == "http://"           \
+     -o ${#url} -gt 10 -a "${url:0:8}"   == "https://"          \
+     -o ${#url} -gt 10 -a "${url:0:6}"   == "ftp://"            \
+     -o ${#url} -gt  5 -a "${url:0:5}"   == "we://"             \
+     -o ${#url} -gt 13 -a "${url:0:13}"  == "webenabled://"     \
+     -o ${#url} -gt 11 -a "${url:0:11}"  == "devpanel://"       \
+     ]; then
+
+    return 0
+  else
+    return 1
+  fi
+}
+
+looks_like_a_publisher_url() {
+  local url="$1"
+
+  if ! looks_like_an_app_url "$url"; then
+    return 1
+  fi
+
+  if [[ "$url" =~ ^(https?|ftp):// ]]; then
+    return 1
+  elif [[ "$url" =~ ^[a-z0-9]://.+$ ]]; then
+    return 0
   fi
 }
 
@@ -2047,25 +2132,6 @@ date_placeholders() {
   printf '%s' "$date_str"
 }
 
-get_mysql_version() {
-  if ! hash mysql &>/dev/null; then
-    echo "$FUNCNAME(): missing mysql command" 1>&2
-    return 1
-  fi
-
-  local tmp_str
-  tmp_str=$(mysql -V 2>/dev/null | egrep -o 'Distrib [0-9]\.[0-9]+(\.[0-9]+)?')
-  if [ $? -ne 0 -o -z "$tmp_str" ]; then
-    echo "$FUNCNAME(): unable to get mysql version from mysql command" 1>&2
-    return 1
-  fi
-
-  local junk version_str
-  IFS=" " read junk version_str <<< "$tmp_str"
-
-  echo -n "$version_str"
-}
-
 get_php_version() {
   if hash php-config &>/dev/null; then
     php-config --version
@@ -2622,6 +2688,60 @@ detect_app_type_on_dir() {
 
   if [ -n "$app_type" ]; then
     echo -n "$app_type"
+    return 0
+  else
+    return 1
+  fi
+}
+
+guess_subsystem_from_app_archive() {
+  local archive="$1"
+  local tmp_dir subsystem _sub_dir _tmp_subsystem
+  local db_dir db_dir_tst db_ext db_dir_1 db_dir_2
+
+  if ! tmp_dir=$(mktemp -d); then
+    echo "$FUNCNAME(): unable to create temp dir" 1>&2
+    return 1
+  fi
+
+  db_dir_1="db"
+  db_dir_2="./db"
+  for db_dir_tst in "$db_dir_1" "$db_dir_2"; do
+    if tar -ztf "$archive" --no-recursion "$db_dir_tst" &>/dev/null; then
+      db_dir="$db_dir_tst"
+      db_ext="$db_dir/databases"
+      if tar -zxf "$archive" -C "$tmp_dir" "$db_ext"; then
+        break
+      else
+        echo "$FUNCNAME(): failed to extract '$db_ext' from '$archive'" 1>&2
+        return 1
+      fi
+    fi
+  done
+
+  if [ -z "$db_dir" ]; then
+    echo "$FUNCNAME(): didn't find database dir on archive '$archive'" 1>&2
+    return 1
+  fi
+
+  for _sub_dir in "$DEVPANEL_HOME/bin/seeds/"*; do
+    if [ ! -d "$_sub_dir" ]; then
+      continue
+    fi
+
+    _tmp_subsystem=${_sub_dir##*/}
+    if is_known_seedapp_subsystem "$_tmp_subsystem"; then
+      if fgrep -qx "$_tmp_subsystem" "$tmp_dir/db/databases"; then
+        subsystem="$_tmp_subsystem"
+        break
+      fi
+    fi
+  done
+
+  rm -rf "$tmp_dir"
+
+  if [ -n "$subsystem" ]; then
+    echo "$subsystem"
     return 0
   else
     return 1
@@ -3386,8 +3506,9 @@ Snapshots: @snapshots_txt@
     ssl_txt+="  HTTP to HTTPS redirect: "
     if is_https_redirect_enabled_for_vhost "$vhost"; then
       ssl_txt+="yes"
-      if [ -n "$v__vhost__https_redirect_target_domain" ]; then
+      if [ -n "$v__ssl__https_redirect_target_domain" ]; then
         ssl_txt+=", targeted redirect to https://"
+        ssl_txt+="$v__ssl__https_redirect_target_domain/"
       fi
       ssl_txt+=$'\n'
     else
@@ -3665,7 +3786,7 @@ is_https_redirect_enabled_by_default() {
 
 is_https_redirect_enabled_for_vhost() {
   local vhost="$1"
-  local var="v__vhost__https_redirect_enabled"
+  local var="v__ssl__https_redirect_enabled"
 
   if [ -n "${!var}" -a "${!var}" == yes ]; then
     return 0
@@ -3798,6 +3919,12 @@ get_default_app_publisher() {
   else
     return 1
   fi
+}
+
+is_known_seedapp_publisher() {
+  local pub="$1"
+
+  get_base_url_for_publisher "$pub" >/dev/null
 }
 
 get_base_url_for_publisher() {
@@ -4335,14 +4462,191 @@ get_system_lock_dir() {
   return 0
 }
 
-if [ -f "$DEVPANEL_HOME/lib/functions.base.sh" ]; then
-  . "$DEVPANEL_HOME/lib/functions.base.sh"
-fi
+reserve_port() {
+  local proto="$1"
+  local port="$2"
 
-if [ -f "$DEVPANEL_HOME/lib/functions.linux-kernel.sh" ]; then
-  . "$DEVPANEL_HOME/lib/functions.linux-kernel.sh"
-fi
+  local tmp_clobber rsv_file
+  local -i st
 
-if [ -f "$DEVPANEL_HOME/lib/functions.mysql" ]; then
-  . "$DEVPANEL_HOME/lib/functions.mysql"
-fi
+  if [[ "$-" != *C* ]]; then
+    # file clobber (no overwriting) is disabled, temporary enable it
+    set -C
+    tmp_clobber=yes
+  fi
+
+  rsv_file="$conf__paths__port_reservation_dir/$proto.$port"
+
+  : 2>/dev/null >"$rsv_file"
+  st=$?
+
+  if [ -n "$tmp_clobber" ]; then
+    # disable file clobbering again
+    set +C
+  fi
+
+  return $st
+}
+
+assign_available_port() {
+  local proto="${1,,}"
+  local ref_port_state="state__ports_${proto}__last_assigned"
+  local -i first_port last_port n_ports n_trials
+
+  unset _dp_value
+
+  if [ -n "$conf__ports__last_port" ]; then
+    last_port=$conf__ports__last_port
+  else
+    echo "$FUNCNAME(): error, missing variable conf__ports__last_port" 1>&2
+    return 1
+  fi
+
+  if [ -n "${!ref_port_state}" ]; then
+    # the last port used is in the state cache
+    if [ "${!ref_port_state}" -ge $conf__ports__first_port -a \
+         "${!ref_port_state}" -le $conf__ports__last_port       ]; then
+      # port saved in state cache is in the valid range
+
+      first_port=$(( ${!ref_port_state} + 1 ))
+      if [ $first_port -gt $last_port ]; then
+        first_port=$conf__ports__first_port
+      fi
+    else
+     # port saved in state is outside the conf range. So ignore it
+     first_port=$conf__ports__first_port
+    fi
+  else
+    # last port used is not cached. So use the first one in the range.
+    if [ -n "$conf__ports__first_port" ]; then
+      first_port=$conf__ports__first_port
+    else
+      echo "$FUNCNAME(): error, missing variable conf__ports__first_port" 1>&2
+      return 1
+    fi
+  fi
+
+  n_ports=$(( $conf__ports__last_port - $conf__ports__first_port + 1 ))
+
+  for((i=$first_port; i <= $last_port; i++)); do
+    n_trials+=1
+    if reserve_port "$proto" $i; then
+      _dp_value="$i"
+      save_opts_in_state "ports_${proto}.last_assigned = $i"
+      return 0
+    else
+      if [ $i == $last_port -a $n_trials -le $n_ports ]; then
+        # if it's the last port and it hasn't tried all ports yet, then
+        # reset the trial value to the config's first port
+        i=$(( $conf__ports__first_port - 1 ))
+        continue
+      fi
+
+      if [ $n_trials -ge $n_ports ]; then
+        # tried all the ports, give up the loop
+        break
+      fi
+    fi
+  done
+
+  return 1
+}
+
+release_port() {
+  local proto="${1,,}"
+  local port="$2"
+  local port_file="$conf__paths__port_reservation_dir/$proto.$port"
+
+  if [ ! -e "$port_file" ]; then
+    echo "$FUNCNAME(): warning, port not assigned" 1>&2
+    return 0
+  fi
+
+  rm -f "$port_file"
+}
+
+force_kill_proc_using_file() {
+  local file="$1"
+  local -i i
+
+  if ! fuser -s "$file" 2>/dev/null; then
+    echo "$FUNCNAME(): no process using file $file" 1>&2
+    return 1
+  fi
+
+  if ! fuser -s -k -TERM "$file" 2>/dev/null; then
+    echo "$FUNCNAME(): unable to send TERM signal to process using file $file" 1>&2
+    return 1
+  fi
+
+  for i in {1..20}; do
+    sleep 0.2
+    if ! fuser -s "$file" 2>/dev/null; then
+      # process is not running anymore
+      return 0
+    fi
+  done
+
+  # finally send a KILL signal if the process didn't exit after previous
+  # time
+  fuser -s -k -KILL "$file" 2>/dev/null
+}
+
+dmi_id_matches() {
+  local id="$1"
+  local search_string="$2"
+  local id_file="/sys/devices/virtual/dmi/id/$id"
+  local ver_string
+
+  if [ -f "$id_file" ]; then
+    IFS='' read ver_string < "$id_file"
+    if [ -n "$ver_string" ] && [[ "${ver_string,,}" == *$search_string* ]]; then
+      return 0
+    fi
+  fi
+
+  return 1
+}
+
+bios_version_matches() {
+  local search_string="$1"
+  dmi_id_matches bios_version "$search_string"
+}
+
+bios_vendor_matches() {
+  local search_string="$1"
+  dmi_id_matches bios_vendor "$search_string"
+}
+
+am_i_on_aws() {
+  if bios_version_matches amazon; then
+    return 0
+  fi
+
+  local output
+  local url='http://169.254.169.254/latest/meta-data/public-hostname'
+
+  output=$(curl -sSN --max-time 3 --connect-timeout 2 --retry 1 \
+            --retry-delay 1 "$url" )
+  if [ $? -eq 0 ] && [[ "$output" == *.amazonaws.com ]]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+am_i_on_virtualbox() {
+  bios_version_matches virtualbox
+}
+
+am_i_on_digital_ocean() {
+  bios_vendor_matches digitalocean
+}
+
+for _name in base lamp_vhost linux-kernel mysql; do
+  if [ -f "$DEVPANEL_HOME/lib/functions.$_name.sh" ]; then
+    . "$DEVPANEL_HOME/lib/functions.$_name.sh"
+  else
+    :
+  fi
+done
diff --git a/libexec/archive-vhost-db b/libexec/archive-vhost-db
--- a/libexec/archive-vhost-db
+++ b/libexec/archive-vhost-db
@@ -99,19 +99,26 @@ load_devpanel_config || exit $?
 
 load_vhost_config "$vhost" || exit $?
 
+if [ -z "$v__mysql__instance" ]; then
+  echo "Warning: this vhost is not associated to any mysql instance" 1>&2
+  exit 1
+fi
+
+instance_ini="$lamp__paths__mysql_instances_config_dir/$v__mysql__instance/config.ini"
+read_ini_file_into_namespace --no-cleanup "$instance_ini" v__mysql || exit $?
+
 user_web="$v__vhost__linux_user"
-user="b_${user_web#w_}"
+user="$v__mysql__params__linux_user"
 archive_list="$archive_dir/databases"
 archive_my_cnf="$archive_dir/b_.my.cnf"
 home="$v__vhost__linux_user_home"
 date=`date  +'%Y%m%d'`
-vhost_config_dir="$sys_dir/config/vhosts/$vhost"
 
-if ! `id -u "$user" 2>/dev/null >/dev/null`
-then
-  echo "No such user: $user" >&2
-  exit 1
-fi
+#if ! `id -u "$user" 2>/dev/null >/dev/null`
+#then
+#  echo "No such user: $user" >&2
+#  exit 1
+#fi
 
 if ! [ -d "$home" ]
 then
@@ -145,9 +152,12 @@ fi
 chmod +w "$archive_list" || exit 1
 
 echo Listing the databases...
-list=`$dir/dbmgr-show-databases "$user"` || exit 1
-list=`echo "$list" | egrep -v '^(mysql|performance_schema|information_schema|sys)$'`
-echo "$list" >"$archive_list"
+if mysql_list_databases "$v__mysql__instance" >"$archive_list"; then
+  sed -i -e '/^mysql$/d; /^performance_schema$/d; /^information_schema$/d;
+              /^sys$/d;' "$archive_list"
+else
+  error "unable to list mysql databases"
+fi
 
 echo Checking for .my.cnf...
 if run_su "[ -s .my.cnf ]"
@@ -162,18 +172,18 @@ else
   echo Not found
 fi
 
-if [ -z "$lock_cmd_arg" ] && get_metadata_value "$vhost_config_dir" config.mysql.skip_lock_tables &>/dev/null; then
-  dont_lock_tables=1
+if [ -s "$archive_list" ]; then
+  while read database; do
+    archive_file="$archive_dir/$database.sql"
+    echo "Archiving $database to $archive_file"
+    if mysql_dump_database "$v__mysql__instance" "$database" >$archive_file; then
+      if ! gzip "$archive_file"; then
+        error "failed to gzip database file '$archive_file'"
+      fi
+    else
+      error "failed to dump database '$database'"
+    fi
+  done < "$archive_list"
 fi
 
-for database in $list
-do
-  archive_file="$archive_dir/$database.sql"
-  echo "Archiving $database to $archive_file"
-  if ! run2 $dir/dbmgr-mysql-as-root "$user" mysqldump --extended-insert=false ${dont_lock_tables:+--skip-lock-tables} "$database" 2>&1 >"$archive_file" ||
-     ! run gzip "$archive_file"
-  then
-    echo "Aborting" >&2
-    exit 1
-  fi
-done
+exit 0
diff --git a/libexec/dbmgr-mysql-as-root b/libexec/dbmgr-mysql-as-root
--- a/libexec/dbmgr-mysql-as-root
+++ b/libexec/dbmgr-mysql-as-root
@@ -1,5 +1,11 @@
 #!/bin/bash
-dir=`dirname "$0"`
+self_bin=$(readlink -e "$0")
+if [ $? -ne 0 ]; then
+  echo "Error: failed to determine self path" 1>&2
+  exit 1
+fi
+dir="${self_bin%/*}"
+sys_dir="${dir%/*}"
 user="$1"
 shift
 command="$1"
@@ -10,7 +16,14 @@ then
   exit 1
 fi
 
-dbmgr_config_dir="$dir/../config/os/pathnames/opt/dbmgr/config/mysql/$user"
+if ! . "$sys_dir/lib/functions"; then
+  echo "Error: failed to load '$sys_dir/lib/functions'" 1>&2
+  exit 1
+fi
+
+load_devpanel_config || exit $?
+
+dbmgr_config_dir="$lamp__paths__mysql_instances_config_dir/$user"
 
 root_client_cnf=$(readlink -m "$dbmgr_config_dir/root.client.cnf")
 
diff --git a/libexec/old-we-v1/clone-vhost-proxy b/libexec/old-we-v1/clone-vhost-proxy
--- a/libexec/old-we-v1/clone-vhost-proxy
+++ b/libexec/old-we-v1/clone-vhost-proxy
@@ -92,17 +92,30 @@ fi
 
 set -o pipefail
 echo "Cloning stage 1 & 2: archive $source | restore $target"
-if ! (if [ $opt_i = 1 ]; then echo "$password";  fi
-         if ! WEBENABLED_SERVER="$source_server" $sys_dir/sbin/archive-vhost $options "$source" -
-         then
-           echo adding garbage to stdout to signal a broken archive
-           false
-         fi
-     ) |
-     WEBENABLED_SERVER="$target_server" $sys_dir/libexec/restore-vhost $options $target_options "$target" - "$@"
-then
-  echo ERROR >&2
-  exit 1
+tmp_dir="/opt/webenabled-data/tmp"
+tmp_archive="$tmp_dir/_${source}-$(date +%b-%d-%Y--%H-%M)-$RANDOM.tgz"
+
+# don't overwrite existing files
+set -o noclobber
+
+WEBENABLED_SERVER="$source_server" $sys_dir/sbin/archive-vhost $options \
+  "$source" - >$tmp_archive
+if [ $? -ne 0 ]; then
+  error "failed to archive vhost '$source' on server '$source_server'"
 fi
-  
+trap 'rm -f $tmp_archive' EXIT
+
+restore_args_ar+=( --vhost "$target" --from "$tmp_archive" )
+
+if [ -n "$password" ]; then
+  restore_args_ar+=( --password-stdin )
+  echo "$password" | devpanel create vhost "${restore_args_ar[@]}"
+else
+  devpanel create vhost "${restore_args_ar[@]}"
+fi
+if [ $? -ne 0 ]; then
+  error "failed to create vhost '$target_vhost'"
+fi
+
+echo
 echo Done
