CLI: create vhost: added option to read admin password from stdin

diff --git a/lib/cli/sbin/create-vhost b/lib/cli/sbin/create-vhost
--- a/lib/cli/sbin/create-vhost
+++ b/lib/cli/sbin/create-vhost
@@ -15,6 +15,8 @@ set_usage_msg \
 
     --desc <description>      a short description of the vhost's purpose
 
+    --password-stdin          read app password from STDIN
+
   Creates a new vhost from the specified source.
 "
 
@@ -23,7 +25,7 @@ devpanel_cmd__create_vhost() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
   local name vhost from source_type title desc
-  local branch
+  local branch app_password read_pw_stdin
   local -a cmd_args=()
 
   # by default let's assume the source is a file
@@ -62,6 +64,10 @@ devpanel_cmd__create_vhost() {
         desc="$2"
         shift 2
         ;;
+      --password-stdin)
+        read_pw_stdin=1
+        shift
+        ;;
       --[A-Za-z0-9_-]*)
         error "unknown argument $name"
         ;;
@@ -98,6 +104,14 @@ devpanel_cmd__create_vhost() {
     source_type="$def_source_type"
   fi
 
+  if [ -n "$read_pw_stdin" ]; then
+    read -p "Enter app password (stdin): " app_password
+    if [ -z "$app_password" ]; then
+      error "got an empty password on stdin" -
+      return 1
+    fi
+  fi
+
   local st
 
   if [ "$source_type" == "github" -o "$source_type" == "git" ]; then
@@ -118,6 +132,13 @@ devpanel_cmd__create_vhost() {
   fi
 
   if [ $st -eq 0 ]; then
+    if [ -n "$app_password" ]; then
+      echo "$app_password" | devpanel_run reset app password --vhost "$vhost"
+      if [ $? -ne 0 ]; then
+        echo "Warning: failed setting the password for app..." 1>&2
+      fi
+    fi
+
     if [ -n "$desc" ]; then
       devpanel_run set vhost description --vhost "$vhost" --quiet --desc "$desc"
     fi
diff --git a/lib/cli/sbin/install-app b/lib/cli/sbin/install-app
--- a/lib/cli/sbin/install-app
+++ b/lib/cli/sbin/install-app
@@ -8,6 +8,7 @@ set_usage_msg \
     --app <name>               the name of the application to install
     --vhost <name>             the name of the vhost where to install
     --desc <description>       a short description of the apps's purpose
+    --password-stdin           read the app admin password from stdin
 
   Installs the specified application in a new virtual host.
 "
@@ -16,6 +17,7 @@ devpanel_cmd__install_app(){
   [ -z "$1" ] && usage
 
   local name vhost arg publisher app app_url desc
+  local read_pw_stdin
   local -a cmd_args=()
 
   while [ -n "$1" ]; do
@@ -49,6 +51,10 @@ devpanel_cmd__install_app(){
         shift 2
         ;;
 
+      --password-stdin)
+        read_pw_stdin=1
+        shift
+        ;;
       --help)
         usage
         ;;
@@ -73,13 +79,31 @@ devpanel_cmd__install_app(){
 
   "$sys_dir/libexec/check-vhost-name" restore "$vhost" || return $?
 
-  local app_url
+  local app_url app_password
   app_url=$(get_tarball_url_for_app "$app" "$publisher") || return $?
 
-  devpanel_run create vhost --vhost "$vhost" --from "$app_url" \
-    ${desc:+--desc "$desc"}
+  if [ -n "$read_pw_stdin" ]; then
+    read -p "Enter app password (stdin): " app_password
+    if [ -z "$app_password" ]; then
+      error "got an empty password on stdin" -
+      return 1
+    fi
+  else
+    app_password=$(wedp_gen_random_str 12)
+    if [ $? -ne 0 ]; then
+      error "unable to generate random password" -
+      return 1
+    fi
+  fi
+
+  echo "$app_password" | devpanel_run create vhost --vhost "$vhost" --from "$app_url" \
+    ${desc:+--desc "$desc"} --password-stdin
 
   if [ $? -eq 0 ]; then
+    echo
+    echo "App credentials:"
+    echo "  username: admin"
+    echo "  password: $app_password"
     echo
     echo "Successfully installed $app."
   else
