init config: detect IPv4 from external interface
useful when wanting to use the hostname on a host that has only private IPs
on local interfaces and a public routable IP, like on AWS EC2.

diff --git a/lib/cli/sbin/init-config b/lib/cli/sbin/init-config
--- a/lib/cli/sbin/init-config
+++ b/lib/cli/sbin/init-config
@@ -9,6 +9,12 @@ set_usage_msg \
     --gen-hostname-from-ip          generate a base hostname from the IP address
                                     of the default network interface
 
+    --hostname-from-external-ip     if generating the hostname from IP,
+                                    detect the external IP of this server
+                                    (useful when wanting to use external IP
+                                     but the server has only private IPs
+                                     assigned, as on AWS EC2, for example)
+
     --virtualbox-net-workaround     try to find an IP of an interface that is
                                     not the NAT one
 
@@ -155,12 +161,62 @@ find_non_local_virtualbox_ipv4() {
   return 1
 }
 
+detect_ipv4_with_opendns() {
+  local ipv4
+
+  if ! hash dig &>/dev/null; then
+    return 1
+  fi
+
+  ipv4=$(dig +short @resolver1.opendns.com myip.opendns.com a 2>/dev/null)
+  if [ $? -eq 0 -a -n "$ipv4" ] && 
+     [[ "$ipv4" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+    echo "$ipv4"
+    return 0
+  else
+    return 1
+  fi
+}
+
+detect_ipv4_with_akamai() {
+  local ipv4
+
+  if ! hash curl &>/dev/null; then
+    return 1
+  fi
+
+  ipv4=$(curl -s --connect-timeout 5 --retry 3  --retry-delay 3  http://whatismyip.akamai.com/ )
+  if [ $? -eq 0 -a -n "$ipv4" ] && 
+     [[ "$ipv4" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+    echo "$ipv4"
+    return 0
+  else
+    return 1
+  fi
+}
+
+detect_external_ipv4() {
+  local ipv4
+
+  if ipv4=$(detect_ipv4_with_opendns); then
+    echo "$ipv4"
+    return 0
+  elif ipv4=$(detect_ipv4_with_akamai); then
+    echo "$ipv4"
+    return 0
+  else
+    echo "$FUNCNAME(): unable to detect external IPv4" 1>&2
+    return 1
+  fi
+}
+
 # // hostname functions
 
 devpanel_cmd__init_config() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
-  local arg hostname ipv4 domain vagrant_net_workaround auto_gen_hostname
+  local arg hostname ipv4 domain
+  local auto_gen_hostname ipv4_detect_type
   local show_intro st
   local do_update=1
 
@@ -172,6 +228,12 @@ devpanel_cmd__init_config() {
         shift
       ;;
 
+      --hostname-from-external-ip)
+        auto_gen_hostname=1
+        ipv4_detect_type=external_ipv4
+        shift
+        ;;
+
       --hostname)
         [ -z "$2" ] && error_missing_value hostname
         hostname="$2"
@@ -180,7 +242,7 @@ devpanel_cmd__init_config() {
 
       --virtualbox-net-workaround)
         auto_gen_hostname=1
-        virtualbox_net_workaround=1
+        ipv4_detect_type=local_ifaces_vbox_workaround
         shift
         ;;
 
@@ -206,28 +268,50 @@ devpanel_cmd__init_config() {
     esac
   done
 
-  if [ -n "$auto_gen_hostname" -a -n "$hostname" ]; then
-    error "received conflicting parameters about hostname generation." - && \
-      return 1
-  fi
-
-  if [ -n "$virtualbox_net_workaround" ]; then
-    ipv4=$(find_non_local_virtualbox_ipv4)
-    if [ $? -ne 0 ]; then
-      error "unable to find an IP to use in hostname generation" - && \
+  if [ -n "$auto_gen_hostname" ]; then
+    if [ -n "$hostname" ]; then
+      error "received conflicting parameters about hostname generation." - && \
         return 1
     fi
-  fi
 
-  if [ -n "$auto_gen_hostname" ]; then
     assign_deref_os_prop_or_exit domain "$sys_dir" auto_gen_domain
-    [ -z "$ipv4" ] && ipv4=$(get_my_default_ipv4)
-    hostname=$(gen_hostname_for_ipv4 "$ipv4" "$domain")
-    echo "Setting base hostname to '$hostname' based on IP '$ipv4'."
-  else
-    [ -z "$hostname" ] && usage
-  fi
 
+    ipv4_detect_type=${ipv4_detect_type:-default_route}
+
+    case $ipv4_detect_type in
+      external_ipv4)
+        # detect and use the external IP
+        ipv4=$(detect_external_ipv4)
+        ;;
+
+      local_ifaces_vbox_workaround)
+        # detect and use VirtualBox non-NAT IP
+        ipv4=$(find_non_local_virtualbox_ipv4)
+        ;;
+
+      default_route)
+        ipv4=$(get_my_default_ipv4)
+        ;;
+
+      *)
+        error "unknown way of detecting IP address"
+        ;;
+    esac
+
+    if [ -z "$ipv4" ]; then
+      error "failed to detect IPv4 address to use on hostname"
+    fi
+
+    hostname=$(gen_hostname_for_ipv4 "$ipv4" "$domain")
+    if [ $? -eq 0 ]; then
+      echo "Setting base hostname to '$hostname' based on IP '$ipv4'."
+    else
+      error "failed to generate hostname from IPv4 '$ipv4'"
+    fi
+  else
+    # auto detect no specified, nor hostname specified
+    [ -z "$hostname" ] && usage
+  fi # // auto_gen_hostname
 
   if [ -n "$do_update" ]; then
     devpanel_run update || return $?
@@ -235,6 +319,9 @@ devpanel_cmd__init_config() {
 
   devpanel_run set base hostname --name "$hostname"
   st=$?
+  if [ $st -ne 0 ]; then
+    return $st
+  fi
 
   if [ -n "$show_intro" ]; then
     devpanel_run help --section intro
