reimplemented S3 integration
* more intuitive commands
* asynchronous operations

diff --git a/lib/cli/sbin/set-s3-options-for-vhost b/lib/cli/sbin/set-s3-options-for-vhost
--- a/lib/cli/sbin/set-s3-options-for-vhost
+++ b/lib/cli/sbin/set-s3-options-for-vhost
@@ -1,16 +1,19 @@
 #!/bin/bash
 
 set_usage_msg \
-  "Usage: $bin_name ${cmd_ar[*]} <opts>
+  "Usage: $bin_name ${cmd_ar[*]} <--vhost name> <opts>
 
-  Options:
-    --default-server name           name of the profile of the default
-                                    S3 server to use
+  Required Options:
+    --vhost <name>                  name of the vhost
 
-    --default-bucket <name>         name of the bucket to be the default one
 
-    --enabled yes/no                upload vhost archives by default for all
-                                    vhosts (default: yes)
+  Optional Options:
+
+    --upload-enabled yes/no         enable/disable automated uploads to S3
+
+    --bucket <name>                 name of the bucket
+
+    --server <name>                 name of the server profile to use
 
     --upload-path <path>            relative path on S3 bucket where to upload
                                     the files (default: $conf__s3__upload_path)
@@ -23,40 +26,45 @@ set_usage_msg \
                                     previously saved (this option can't be used
                                     with other options in the same command line)
 
-
-  NOTE: all options above are optional (except --default-server and --bucket
-                                        when one of it was not saved in 
-                                        config previously).
-
-
-  Sets options for S3 integration.
+  Sets options for S3 integration specifically for a vhost.
 "
 
-devpanel_cmd__set_s3_options() {
+devpanel_cmd__set_s3_options_for_vhost() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
-  local default_server default_bucket upload_path
-  local delete_after_upload enabled remove_all
-  local var st
-  local -a cmd_args=() opts_ar=() s3cfg_opts_ar=()
+  local vhost server bucket upload_path
+  local delete_after_upload upload_enabled remove_all
+  local var
+  local -a cmd_args=()
 
   while [ -n "$1" ]; do
     name="$1"
     case "$name" in
-      --default-server)
+      --vhost)
         [ -z "$2" ] && error_missing_value "$name"
-        default_server="$2"
-        if ! s3_server_profile_exists "$default_server"; then
-          error "S3 server profile '$default_server' doesn't exist" -
-          return 1
-        fi
-
+        vhost="$2"
         shift 2
         ;;
 
-      --default-bucket)
+      --upload-enabled)
         [ -z "$2" ] && error_missing_value "$name"
-        default_bucket="$2"
+        if [ "${2,,}" != yes -a "${2,,}" != no ]; then
+          error "invalid value for $name option. Must be yes/no." -
+          return 1
+        fi
+        upload_enabled="${2,,}"
+        shift 2
+        ;;
+
+      --server)
+        [ -z "$2" ] && error_missing_value "$name"
+        server="$2"
+        shift 2
+        ;;
+
+      --bucket)
+        [ -z "$2" ] && error_missing_value "$name"
+        bucket="$2"
         shift 2
         ;;
 
@@ -66,20 +74,10 @@ devpanel_cmd__set_s3_options() {
         shift 2
         ;;
 
-      --enabled)
-        [ -z "$2" ] && error_missing_value "$name"
-        if [ "$2" != yes -a "$2" != no ]; then
-          error "invalid value for $name option. Must be yes/no." -
-          return 1
-        fi
-        enabled="$2"
-        shift 2
-        ;;
-
       --delete-after-upload)
         [ -z "$2" ] && error_missing_value "$name"
         if [ "$2" != yes -a "$2" != no ]; then
-          error "invalid value for $name option. Must be yes/no." -
+          error "invalid value for --delete-after-upload option. Must be yes/no." -
           return 1
         fi
         delete_after_upload="$2"
@@ -106,18 +104,13 @@ devpanel_cmd__set_s3_options() {
     esac
   done
 
-  if [ -z "$default_bucket" -a -z "$conf__s3__default_bucket" ]; then
-    error "missing bucket name. Please specify it." -
-    return $?
-  fi
+  [ -z "$vhost" ] && usage
 
-  if [ -z "$default_server" -a -z "$conf__s3__default_server" ]; then
-    error "missing default server. Please specify it." -
-    return $?
-  fi
+  load_vhost_config "$vhost" || return $?
 
-  enabled=${enabled:-yes}
-  for var in default_server default_bucket upload_path enabled delete_after_upload; do
+  local st
+  local -a opts_ar=()
+  for var in  upload_enabled server bucket upload_path delete_after_upload; do
     if [ -n "${!var}" ]; then
       opts_ar+=( "s3.$var = ${!var}" )
     fi
@@ -129,15 +122,20 @@ devpanel_cmd__set_s3_options() {
       return $?
     fi
 
-    save_opts_in_devpanel_config "- s3"
+    save_opts_in_vhost_config "$vhost" "- s3"
     return $?
+  else
+    if [ ${#opts_ar} -eq 0 ]; then
+      error "no change specified." -
+      return $?
+    fi
   fi
 
-  save_opts_in_devpanel_config "${opts_ar[@]}"
+  save_opts_in_vhost_config "$vhost" "${opts_ar[@]}"
   st=$?
 
   if [ $st -eq 0 ]; then
-    echo "Successfully saved S3 options."
+    echo "Successfully saved S3 options for vhost '$vhost'."
   else
     error "failed to save s3 options" -
     return $?
diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -30,6 +30,15 @@ error() {
   fi
 }
 
+warn_3lines() {
+  local msg="$1"
+
+	echo 1>&2
+	[ -t 0 ] && sleep 2
+	echo "Warning: $msg" 1>&2
+	echo 1>&2
+}
+
 wedp_warn() {
   local msg="$1"
 
@@ -1985,96 +1994,6 @@ get_htpasswd_vhost_template() {
   fi
 }
 
-set_s3_options() {
-  save_opts_in_devpanel_config "$@"
-}
-
-write_s3cfg() {
-  local file="$1"
-  shift
-
-  if [ "$file" == @ ]; then
-    file=/etc/devpanel/provisioners/aws/.s3cfg/default
-  fi
-
-  if [ ! -f "$file" ]; then
-    touch "$file"
-    chmod 600 "$file"
-  fi
-
-  write_ini_file "$file" "$@"
-}
-
-set_s3_bucket() {
-  local bucket="$1"
-
-  save_opts_in_devpanel_config "s3.bucket_name = $bucket" \
-    "s3.upload_files = yes"
-}
-
-disable_s3_global_uploads() {
-  save_opts_in_devpanel_config "s3.upload_files = no"
-}
-
-is_global_s3_uploads_enabled() {
-  if [ -n "$conf__s3__upload_files" -a "$conf__s3__upload_files" == "yes" ]; then
-    return 0
-  else
-    return 1
-  fi
-}
-
-get_global_s3_bucket() {
-  if [ -n "$conf__s3__bucket_name" ]; then
-    echo "$conf__s3__bucket_name"
-    return 0
-  else
-    return 1
-  fi
-}
-
-get_global_s3_base_addr_template() {
-  if [ -n "$conf__s3__baseaddr_vhost_tmpl" ]; then
-    echo "$conf__s3__baseaddr_vhost_tmpl"
-    return 0
-  else
-    return 1
-  fi
-}
-
-get_s3_upload_speed_limit() {
-  if [ -n "$conf__s3__upload_speed_limit" ]; then
-    echo "$conf__s3__upload_speed_limit"
-    return 0
-  else
-    return 1
-  fi
-}
-
-get_s3_url_base_for_vhost() {
-  local vhost="$1"
-
-  local bucket_name virtwww_domain tmpl_url
-  local url var
-
-  tmpl_url=$(get_global_s3_base_addr_template ) || return $?
-  virtwww_domain=$(get_server_base_domain )     || return $?
-  bucket_name=$(get_global_s3_bucket )          || return $?
-
-  url="$tmpl_url"
-  for var in bucket_name virtwww_domain vhost ; do
-    url=${url//@$var@/${!var}}
-    url=${url//./-}
-  done
-
-  local -i url_len=${#url}
-  if [ "${url:$(( $url_len - 1 ))}" != / ]; then
-    url+="/"
-  fi
-
-  echo "$url"
-}
-
 get_aws_cluster_region() {
   deref_os_prop "$DEVPANEL_HOME" aws_cluster_region
 }
@@ -3673,6 +3592,38 @@ MySQL Database:  @db_name@
   if has_user_includes "$vhost"; then
     summ_txt+="Custom Includes: yes"$'\n'
   fi
+
+  if is_s3_fully_configured; then
+    summ_txt+="S3 Options:"$'\n'
+    summ_txt+=" Server: $v__s3___server"
+    if [ -z "$v__s3__server" ]; then
+      summ_txt+="  (system default)"
+    fi
+    summ_txt+=$'\n'
+
+    summ_txt+=" Bucket: $v__s3___bucket"
+    if [ -z "$v__s3__bucket" ]; then
+      summ_txt+="  (system default)"
+    fi
+    summ_txt+=$'\n'
+
+    summ_txt+=" Uploads enabled: "
+    if is_s3_uploads_enabled_for_vhost ; then
+      summ_txt+="yes"
+    else
+      summ_txt+="no"
+    fi
+    if [ -z "$v__s3__upload_enabled" ]; then
+      summ_txt+=" (system default)"
+    fi
+    summ_txt+=$'\n'
+
+    if [ -n "$v__s3__upload_path" ]; then
+      summ_txt+=" Upload path: $v__s3__upload_path"$'\n'
+    fi
+
+    summ_txt+=" URL: $v__s3___url"$'\n'
+  fi
  
   ssh_host=$lamp__apache_vhosts__virtwww_domain
 
@@ -3755,11 +3706,11 @@ print_server_metadata_json() {
     server.vhosts_base_domain=$vhosts_base_domain
   )
 
-  if [ -n "$conf__s3__bucket_name" ]; then
-    jo_args_ar+=( server.s3.bucket_name=$conf__s3__bucket_name )
+  if [ -n "$conf__s3__default_bucket" ]; then
+    jo_args_ar+=( server.s3.bucket=$conf__s3__default_bucket )
 
     local key var value
-    for key in upload_by_default delete_after_upload; do
+    for key in enabled delete_after_upload; do
       var="conf__s3__$key"
       value="${!var}"
       if [ -n "$value" -a "$value" == yes ]; then
@@ -4817,14 +4768,40 @@ am_i_on_digital_ocean() {
   bios_vendor_matches digitalocean
 }
 
-is_var_set_to_yes() {
-  local var="$1"
+is_yes() {
+  local str="$1"
 
-  if [ -n "${!var}" ] && [[ "${!var}" == [Yy][Ee][Ss] ]]; then
+  if [ -n "$str" ] && [[ "$str" == [Yy][Ee][Ss] ]]; then
     return 0
   else
     return 1
   fi
+}
+
+is_var_set_to_yes() {
+  local var="$1"
+
+  if [ -n "$var" ] && is_yes "${!var}"; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+is_var_cascanding_yes() {
+  # is 'cascandingly' yes?
+  local var
+  for var in "$@"; do
+    [ -z "$var" ] && continue
+
+    if [ -n "${!var}" ] && ! is_yes "${!var}"; then
+      return 1
+    elif is_yes "${!var}"; then
+      return 0
+    fi
+  done
+
+  return 1
 }
 
 is_to_setup_lets_encrypt_on_base_domain() {
@@ -4844,10 +4821,147 @@ is_to_setup_lets_encrypt_on_base_domain() {
   is_var_set_to_yes lamp__apache_ssl__$base
 }
 
-for _name in base lamp_vhost linux-kernel mysql; do
+s3_translate_uri_template() {
+  local orig_str="$1"
+  local str="$orig_str"
+  local _key _key_name
+
+  unset _dp_value
+
+  # replace @key@ with the value of $v__{key} 
+  for _key in ${!v__*}; do
+    if [ -n "${!_key}" ]; then
+      _key_name=${_key#v__}
+      if [[ "$str" == *@$_key_name@* ]]; then
+        str=${str//@$_key_name@/${!_key}}
+      fi
+    fi
+  done
+
+  _dp_value="$str"
+}
+
+is_s3_upload_globally_enabled() {
+  is_yes "$conf__s3__enabled"
+}
+
+is_s3_fully_configured() {
+  local found_server found_bucket
+
+  if [ -n "$v__s3__server" ]; then
+    found_server=1
+  elif [ -n "$conf__s3__default_server" ]; then
+    found_server=1
+  fi
+
+  if [ -n "$v__s3__bucket" ]; then
+    found_bucket=1
+  elif [ -n "$conf__s3__default_bucket" ]; then
+    found_bucket=1
+  fi
+
+  if [ -n "$found_server" -a -n "$found_bucket" ]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+is_s3_uploads_enabled_for_vhost() {
+  if is_var_set_to_yes  v__s3___upload_enabled ; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+is_to_delete_file_after_upload() {
+  local vhost_key="v__s3__delete_after_upload"
+  local conf_key="conf__s3__delete_after_upload"
+ 
+  if [ -n "${!vhost_key}" ] && is_var_set_to_yes $vhost_key; then
+    return 0
+  fi
+
+  if [ -n "${!conf_key}" ] && is_var_set_to_yes $conf_key; then
+    return 0
+  fi
+
+  return 1
+}
+
+s3_server_profile_exists() {
+  local profile_name="$1"
+  local config_file
+
+  config_file="$conf__paths__s3__config_dir/$profile_name.cfg"
+  if [ -f "$config_file" ]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+is_valid_hour_range() {
+  local test_range="$1"
+  local n1 n2 self_name
+
+  local regex='^((1?[0-9]|2[0-3])|(1?[0-9]|2[0-3])-(1?[0-9]|2[0-3])?)$'
+
+  if [[ "$test_range" =~ $regex ]]; then
+    if [[ "$test_range" == *-* ]]; then
+      # range n1-n2
+      n1=${test_range%-*}
+      n2=${test_range#*-}
+
+      if [ $n1 -le $n2 ]; then
+        return 0
+      fi
+    else
+      # single value
+      return 0
+    fi
+  fi
+
+  self_name=${FUNCNAME[1]:-${FUNCNAME[0]}}
+
+  echo "$self_name(): invalid hour range" 1>&2
+  return 1
+}
+
+is_current_hour_within_range() {
+  local range="$1"
+  local curr_hour start_hour end_hour
+
+  is_valid_hour_range "$range" || return $?
+
+  curr_hour=$(date +%H)
+
+  if [[ "$range" =~ - ]]; then
+    start_hour=${range%-*}
+    end_hour=${range#*-}
+
+    if [ $curr_hour -ge $start_hour -a $curr_hour -le $end_hour ]; then
+      return 0
+    fi
+  else
+    if [ $curr_hour -eq $range ]; then
+      return 0
+    fi
+  fi
+
+  return 1
+}
+
+is_current_hour_within_ops_range() {
+  local range=${1:-$conf__ops__hour_range}
+
+  is_current_hour_within_range "$range"
+}
+
+for _name in base lamp_vhost linux-kernel ltsv mysql; do
   if [ -f "$DEVPANEL_HOME/lib/functions.$_name.sh" ]; then
     . "$DEVPANEL_HOME/lib/functions.$_name.sh"
-  else
-    :
   fi
 done
+unset _name
diff --git a/libexec/archive-vhost b/libexec/archive-vhost
--- a/libexec/archive-vhost
+++ b/libexec/archive-vhost
@@ -29,6 +29,8 @@ usage() {
     -C        don't do checksum calculations
     -G        skip vhost group ownership changes on directories (used when
               removing a vhost)
+    -K k:v    specify key-value based metadata to store along with the
+              backup file
 
   This command creates an archive of the current state of a vhost, saving
   Apache files and MySQL databases into a tar ball.
@@ -69,7 +71,7 @@ process_still_exists() {
 
 [ $# -eq 0 -o -z "$1" ] && usage
 
-declare -a archive_web_args_ar=()
+declare -a archive_web_args_ar=() in_metadata_ar=()
 check_archive_pathname_options=""
 debug=""
 in_user_path=""
@@ -78,7 +80,7 @@ skip_group_changes=""
 
 umask 027
 
-while getopts "PudGCe:x:" OPTOPT
+while getopts "PudGCe:x:K:" OPTOPT
 do
   case "$OPTOPT" in
     P) archive_web_args_ar+=( -$OPTOPT ) ;;
@@ -95,6 +97,13 @@ do
       ;;
     x)
       archive_web_args_ar+=( -$OPTOPT "$OPTARG" )
+      ;;
+    K)
+      if [[ "$OPTARG" =~ ^[A-Za-z0-9_]+:.+$ ]]; then
+        in_metadata_ar+=( "$OPTARG" )
+      else
+        error "invalid format for metadata string. Accepted format: ^[A-Za-z0-9_]+:.+$"
+      fi
       ;;
     *) exit 1;
   esac
@@ -348,6 +357,9 @@ else
   fi
 fi
 
+cleanup_namespace fmeta
+fmeta__start_time=$(date +%s)
+
 echo "Archiving web files..." 1>&2
 ${debug:+run} "$0-web" "${archive_web_args_ar[@]}" "$vhost" "$tmp_archive_dir/web" 1>&2
 if [ $? -ne 0 ]; then
@@ -363,6 +375,7 @@ if [ -n "$v__mysql__instance" ]; then
 else
   opts_ar+=( "mysql.skip = yes" )
 fi
+fmeta__end_time=$(date +%s)
 
 # write devpanel.ini with the app metadata
 for var in app__database_name app__subsystem php__version; do
@@ -447,7 +460,18 @@ fi
 
 # now move the tmp file to the target location
 # don't overwrite in case the target file exists
-if ! ${debug:+run} mv -n "$tmp_target_file" "$target_file"; then
+if ${debug:+run} mv -n "$tmp_target_file" "$target_file"; then
+  for raw_kv in "${in_metadata_ar[@]}"; do
+    key=${raw_kv%%:*}
+    value=${raw_kv#*:}
+    set_global_var fmeta__${key} "$value"
+  done
+
+  metadata_file="${target_file%/*}/.${target_file##*/}.metadata.ltsv"
+  if ! ltsv_save_namespace_to_file fmeta "$metadata_file"; then
+    warn_3lines "failed to save metadata to file '$metadata_file'"
+  fi
+else
   error "unable to move '$tmp_target_file' to '$target_file'"
 fi
 
diff --git a/libexec/recurring-snapshot-utils b/libexec/recurring-snapshot-utils
--- a/libexec/recurring-snapshot-utils
+++ b/libexec/recurring-snapshot-utils
@@ -202,7 +202,14 @@ if [ -n "$verbose" -a -n "$quiet" ]; then
   error "-v and -q are conflicting options. Use only one at a time."
 fi
 
-op=${0##*/}
+if [ "${0##*/}" == "${self_bin##*/}" ]; then
+  op="$1"
+  shift
+elif [ -L "$0" ]; then
+  op=${0##*/}
+else
+  error "don't know how determine what to execute."
+fi
 
 case $op in
   ${self_bin##*/})
@@ -367,18 +374,22 @@ case $op in
     fi
 
     start_time_epoch=$(date +%s)
-    # no archive for the same frequency exists, go and archive it
-    nice -n $niceness "$self_dir/archive-vhost" \
-      ${exclude_file:+-e $exclude_file} "$vhost" "$backup_str"
-    snap_st=$?
-
-    end_time_epoch=$(date +%s)
-
     if [ $n_rm_add_time -gt 0 ]; then
-      rm_after_time_epoch=$(( $end_time_epoch + $n_rm_add_time ))
+      rm_after_time_epoch=$(( $start_time_epoch + $n_rm_add_time ))
     else
       rm_after_time_epoch=0
     fi
+
+    # no archive for the same frequency exists, go and archive it
+    nice -n $niceness devpanel backup vhost --vhost "$vhost"   \
+      --file "$backup_str"                                     \
+      ${exclude_file:+--exclude-from "$exclude_file"}          \
+      --key-value run_type:scheduled                           \
+      --key-value frequency:$frequency                         \
+      --key-value remove_after:$rm_after_time_epoch
+    snap_st=$?
+
+    end_time_epoch=$(date +%s)
 
     if [ $snap_st -eq 0 ]; then
       if ln -s "$backup_basename" "$frequency_status_link"; then
@@ -550,6 +561,82 @@ case $op in
     for vhost in $(get_list_of_vhosts); do
       "$self_dir/remove-old-snapshot-files" "${aux_opts[@]}" "$vhost"
     done
+    ;;
+
+  new-s3-upload)
+    _entry_file="$1"
+    if [ ! -f "$_entry_file" ]; then
+      error "couldn't find file '$_entry_file'"
+    fi
+
+    if ! ltsv_load_line_from_file_into_namespace entry "$_entry_file"; then
+      exit 1
+    fi
+
+    declare -a s3_args_ar=()
+
+    vhost="$entry__vhost"
+    file="$entry__file"
+
+    load_devpanel_config || exit $?
+
+    if ! load_vhost_config "$vhost"; then
+      exit 1
+    fi
+
+    if [ "${file:0:1}" == / ]; then
+      file_fullpath="$file"
+    else
+      file_fullpath="$v__vhost__archives_dir/$file"
+    fi
+
+    if [ ! -f "$file_fullpath" ]; then
+      if [ -t 0 ]; then
+        error "couldn't find file '$file_fullpath'"
+      else
+        exit 1
+      fi
+    fi
+
+    load_vhost_archive_metadata "$file_fullpath" fmeta
+
+    if [ -n "$v__s3___config_file" -a -f "$v__s3___config_file" ]; then
+      s3_args_ar+=( --config="$v__s3___config_file" )
+    else
+      error "missing S3 config file"
+    fi
+
+    hdr_fields_txt=""
+    if [ "$v__vhost__server_name" != "$v__vhost__base_domain" ]; then
+      hdr_fields_txt+=" domain:$v__vhost__server_name"
+    fi
+    hdr_fields_txt+=" host:$v__vhost__base_domain"
+    hdr_fields_txt+=" vhost:$v__vhost__name"
+
+    for _key in ${!fmeta__*}; do
+      [ -z "${!_key}" ] && continue
+
+      _key_name=${_key#fmeta__}
+      ltsv_encode_string "${!_key}"
+      _key_value="$_ltsv_encoded"
+
+      hdr_fields_txt+=" ${_key_name}:${_key_value}"
+    done
+
+    hdr_name="x-amz-meta-devpanel-vhost-snapshot"
+    s3_args_ar+=( --add-header="$hdr_name:$hdr_fields_txt" )
+
+    target_s3_url="${v__s3___url%/}/${file_fullpath##*/}"
+    s3cmd "${s3_args_ar[@]}" --quiet --acl-private \
+      put "$file_fullpath" "$target_s3_url"
+    st=$?
+
+    if [ $st -eq 0 ] && is_to_delete_file_after_upload; then
+      rm_vhost_archive "$file_fullpath"
+    fi
+
+    exit $st
+
     ;;
 
   *)
