changes for AWS cluster to support multiple vhosts

diff --git a/paas-provisioner/aws/git-hook-rsync-cluster-webservers b/paas-provisioner/aws/git-hook-rsync-cluster-webservers
--- a/paas-provisioner/aws/git-hook-rsync-cluster-webservers
+++ b/paas-provisioner/aws/git-hook-rsync-cluster-webservers
@@ -1,11 +1,8 @@
 #!/bin/bash
-#set -x
 
 usage() {
   :
 }
-
-remote_docroot_dir="/var/www/html"
 
 # main
 
@@ -17,22 +14,44 @@ we_base_dir=`readlink -e "$dir/../.."`
 
 lib_file="$we_base_dir/lib/functions"
 if ! source "$lib_file"; then
-  error "unable to source lib file '$lib_file'"
+  echo "Error: unable to source lib file '$lib_file'" 1>&2
+  exit 1
 fi
 
-export GIT_DIR=`readlink -e "$GIT_DIR"`
-if [ -z "$GIT_DIR" ]; then
-  assign_deref_os_prop_or_exit repo_name "$we_base_dir" aws_cluster_repo_name
+if [ -n "$GL_REPO" ]; then
+  repo_name="$GL_REPO"
+else
+  echo "Error: missing variable GL_REPO" 1>&2
+  exit 1
+fi
+
+if [ -n "$GIT_DIR" ]; then
+  export GIT_DIR=`readlink -e "$GIT_DIR"`
+else
   export GIT_DIR="$HOME/repositories/$repo_name.git"
-  webserver_ips="$SSH_ORIGINAL_COMMAND"
 fi
 
-if [ -z "$webserver_ips" ]; then
-  webserver_ips=`"$dir/get-cluster-webserver-ips"`
-  if [ $? -ne 0 ]; then
-    echo "Error: unable to get IPs of webservers" 1>&2
-    exit 1
-  fi
+metadata_dir="$HOME/.devpanel/metadata"
+if [ ! -d "$GIT_DIR" ]; then
+  echo "Error: unable to find git dir '$GIT_DIR'" 1>&2
+  exit 1
+elif [ ! -d "$metadata_dir" ]; then
+  echo "Error: unable to find metadata dir '$metadata_dir'" 1>&2
+  exit 1
+fi
+
+vhost=`get_metadata_value "$metadata_dir" "config:param:aws_vhost:repo:$repo_name" 2>/dev/null`
+if [ -z "$vhost" ]; then
+  echo "Error: unable to get vhost from git metadata" 1>&2
+  exit 1
+fi
+
+remote_docroot_dir="/var/www/html/$vhost"
+
+webserver_ips=`"$dir/get-cluster-webserver-ips"`
+if [ $? -ne 0 ]; then
+echo "Error: unable to get IPs of webservers" 1>&2
+exit 1
 fi
 
 tmp_checkout_dir=`mktemp -d`
@@ -49,6 +68,7 @@ git -c core.bare=false checkout -f
 for ip in "$webserver_ips"; do
   rsync -a ./ "root@$ip:$remote_docroot_dir"
 
-  ssh root@"$ip" chown -R www-data:www-data "$remote_docroot_dir" \
-    \; /opt/webenabled/paas-provisioner/aws/update-drupal-settings
+  ssh root@"$ip" \
+    chown -R www-data:www-data "$remote_docroot_dir" \; \
+    /opt/webenabled/paas-provisioner/aws/update-drupal-settings "$vhost"
 done
diff --git a/paas-provisioner/aws/mysql-copy-db b/paas-provisioner/aws/mysql-copy-db
--- a/paas-provisioner/aws/mysql-copy-db
+++ b/paas-provisioner/aws/mysql-copy-db
@@ -1,7 +1,14 @@
 #!/bin/bash
 
 usage() {
-  echo "Usage: `basename "$0"` <target_db_name> <dump_file>"
+  echo "Usage: `basename "$0"` [options] <target_db_name> <dump_file>
+
+  Options:
+    -i my_cnf_file            path to an alternate cnf file
+    -s vhost_name             the vhost name (used to figured the my_cnf
+                              file automatically)
+  
+"
   exit 1
 }
 
@@ -20,12 +27,15 @@ self_bin=`readlink -e "$0"`
 curr_dir=`dirname "$self_bin"`
 we_base_dir=`readlink -e "$curr_dir/../.."`
 
-getopt_flags='i:'
+getopt_flags='i:s:'
 
 while getopts $getopt_flags OPTN; do
   case $OPTN in
     i)
       my_cnf_file="$OPTARG"
+      ;;
+    s)
+      site_name="$OPTARG"
       ;;
     *)
       usage
@@ -35,7 +45,12 @@ done
 
 [ $OPTIND -gt 1 ] && shift $(( $OPTIND - 1 ))
 
-my_cnf_file=${my_cnf_file:-"$we_base_dir/etc/aws-cluster.ini"}
+template_my_cnf="$we_base_dir/etc/aws-rds--my_cnf.ini"
+if [ -z "$my_cnf_file" -a -z "$site_name" ]; then
+  my_cnf_file=${my_cnf_file:-"$template_my_cnf"}
+elif [ -z "$my_cnf_file" -a -n "$site_name" ]; then
+  my_cnf_file=${my_cnf_file:-"$we_base_dir/etc/aws-rds--my_cnf-$site_name.ini"}
+fi
 
 if [ -z "$my_cnf_file" ]; then
   error "please specify the ini with the remote db configuration (option -i)"
@@ -56,11 +71,16 @@ elif [ ! -f "$dump_file" ]; then
   error "path '$dump_file' is not a regular file"
 fi
 
-if ! mysql --defaults-file="$my_cnf_file" -BN -D "$target_db_name" -e "SHOW TABLES;" >/dev/null; then
-  error "unable to connect to target db"
-fi
+if mysql --defaults-file="$my_cnf_file" -BN -D "$target_db_name" -e "SHOW TABLES;" >/dev/null; then
 
-mysql --defaults-file="$my_cnf_file" -e "DROP DATABASE $target_db_name; CREATE DATABASE $target_db_name;"
+  if ! mysql --defaults-file="$my_cnf_file" -e "DROP DATABASE $target_db_name; CREATE DATABASE $target_db_name;"; then
+    error "unable to DROP and CREATE database $target_db_name"
+  fi
+else
+  if ! mysql --defaults-file="$my_cnf_file" -e "CREATE DATABASE $target_db_name;" >/dev/null; then
+    error "unable to create database $target_db_name"
+  fi
+fi
 
 mysql --defaults-file="$my_cnf_file" -D "$target_db_name" < "$dump_file"
 if [ $? -ne 0 ]; then
