enhanced recurring snapshot creation and removal
much improver wrapper on recurring snapshots creation and removal of old
files. Now the creation and rotation are all based on the local server
(doesn't require connectivity to the master server anymore).

Created script libexec/recurring-snapshot-utils that holds all logic for
handling recurring snapshots and cleanup.

Modified install/utils/crontab/cron.hourly to run hourly the recurring
snapshots checks.

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -1,4 +1,12 @@
 #!/bin/bash
+if [ -z "$DEVPANEL_HOME" ]; then
+  tmp_self=$(readlink -e "${BASH_SOURCE[0]}")
+  if [ $? -eq 0 ]; then
+    tmp_self_dir="${tmp_self%/*}"
+    DEVPANEL_HOME=$(readlink -e "$tmp_self_dir/..")
+  fi
+  unset tmp_self tmp_self_dir
+fi
 
 # avoid a warning on MacOS X because md5sum doesn't exist
 if [ -n "$OSTYPE" ] && [[ "$OSTYPE" =~ ^darwin ]] && hash md5 &>/dev/null; then
@@ -1064,22 +1072,40 @@ date_placeholders() {
     return 1
   fi
 
-  local fmt_str='+%d %b %m %Y %H %M'
+  # local fmt_str='+%d %b %m %Y %H %M'
+  local fmt_str='+%d %b %m %Y %H %M %W %w %s %j %a %x %X %Z %z'
 
-  local day month monthn year hour minute
+  # local day month monthn year hour minute
+  local day month_name month_number year hour minute \
+        week_year day_week epoch day_year day_name   \
+        locale_date locale_time timezone_abrev timezone_num
 
-  IFS=" " read day month monthn year hour minute \
-    <<< $(date -d "$ref_date" "$fmt_str")
+  IFS=" " read day month_name month_number year hour minute \
+               week_year day_week epoch day_year day_name   \
+               locale_date locale_time timezone_abrev timezone_num \
+            <<< $(date -d "$ref_date" "$fmt_str")
 
   local date_str
 
   date_str="$template_str"
   date_str=${date_str//@day@/"$day"}
-  date_str=${date_str//@month@/"$month"}
-  date_str=${date_str//@monthn@/"$monthn"}
+  date_str=${date_str//@month_name@/"$month_name"}
+  date_str=${date_str//@month_number@/"$monthn"}
   date_str=${date_str//@year@/"$year"}
   date_str=${date_str//@hour@/"$hour"}
   date_str=${date_str//@minute@/"$minute"}
+  date_str=${date_str//@week_year@/"$week_year"}
+  date_str=${date_str//@day_week@/"$day_week"}
+  date_str=${date_str//@epoch@/"$epoch"}
+  date_str=${date_str//@day_year@/"$day_year"}
+  date_str=${date_str//@day_name@/"$day_name"}
+  date_str=${date_str//@locale_date@/"$locale_date"}
+  date_str=${date_str//@locale_time@/"$locale_time"}
+  date_str=${date_str//@timezone_abrev@/"$timezone_abrev"}
+  date_str=${date_str//@timezone_num@/"$timezone_num"}
+
+  # auxiliary formats for breviety
+  date_str=${date_str//@aux_date_str@/$month_name-$day-$year}
 
   printf '%s' "$date_str"
 }
@@ -1173,3 +1199,62 @@ escape_quotes() {
   printf '%s' "$new"
 }
 
+get_list_of_vhosts() {
+  local vhost_config_dir="$DEVPANEL_HOME/config/vhosts"
+  local vhost vhost_dir
+  local -a vhosts_ar=()
+
+  if [ ! -d "$vhost_config_dir" ]; then
+    echo "$FUNCNAME(): missing config dir $vhost_config_dir" 1>&2
+    return 1
+  fi
+
+  for vhost_dir in "$vhost_config_dir/"*; do
+    [ ! -d "$vhost_dir" ] && continue
+    vhost=${vhost_dir##*/}
+    vhosts_ar+=( "$vhost" )
+  done
+
+  if [ ${#vhosts_ar[*]} -le 0 ]; then
+    return 0
+  else
+    echo "${vhosts_ar[@]}"
+  fi
+}
+
+translate_archive_placeholders() {
+  local orig="$1"
+  local final
+
+  # uses globals $sys_data_dir $vhost_data_dir $vhost $period
+  #              $archive_template_str
+
+  final="$orig"
+
+  [ -n "$archive_template_str" ] && \
+    final=${final//@archive_template_str@/$archive_template_str}
+
+  [ -n "$sys_data_dir" ]   && final=${final//@system_data_dir@/$sys_data_dir}
+
+  [ -n "$vhost_archive_dir" ] && \
+    final=${final//@vhost_archive_dir@/$vhost_archive_dir}
+
+  [ -n "$vhost" ]        && final=${final//@vhost@/$vhost}
+  [ -n "$frequency" ]    && final=${final//@frequency@/$frequency}
+
+  final=$(date_placeholders "$final") || return 1
+
+  echo "$final"
+}
+
+get_recurring_backup_property() {
+  local period="$1"
+  local unit="$2"
+  local vhost="$3"
+
+  local vhost_config_dir="$DEVPANEL_HOME/config/vhosts/$vhost"
+
+  local link="$vhost_config_dir/config:backup_snapshot:$period:$unit"
+
+  deref_contents "$link"
+}
diff --git a/libexec/archive-vhost b/libexec/archive-vhost
--- a/libexec/archive-vhost
+++ b/libexec/archive-vhost
@@ -150,20 +150,27 @@ if [ ! -d "$upper_tmp_dir" ]; then
   fi
 fi
 
+# these variables need to be set in advance for
+#   translate_archive_placeholders()
+archive_dir_in_user="$home/public_html/gen/archive"
+archive_dir_in_sys="$sys_archive_dir/$vhost"
+if [ -n "$in_user_path" ]; then
+  vhost_archive_dir="$archive_dir_in_user"
+else
+  vhost_archive_dir="$archive_dir_in_sys"
+fi
+
 if [ -n "$archive_to" -a "$archive_to" == "-" ]; then
   to_stdout=1  # destination is STDOUT
 else # destination is a file
-  if [ -z "$archive_to" ]; then
+  if [ -n "$archive_to" ]; then
+    archive_to=$(translate_archive_placeholders "$archive_to")
+    if [ $? -ne 0 ]; then
+      error "unable to translate placeholders from input filename"
+    fi
+  else
     # archive name was not passed on cmdline, use the full template
     archive_to="$archive_template_str"
-  fi
-
-  archive_dir_in_user="$home/public_html/gen/archive"
-  archive_dir_in_sys="$sys_archive_dir/$vhost"
-  if [ -n "$in_user_path" ]; then
-    vhost_archive_dir="$archive_dir_in_user"
-  else
-    vhost_archive_dir="$archive_dir_in_sys"
   fi
 
   if [ "${archive_to:0:1}" == "/" ]; then
@@ -172,32 +179,26 @@ else # destination is a file
     tmp_full_path=$(readlink -m "$vhost_archive_dir/$archive_to")
   fi
 
-  if [ -n "$uninstall" -a "${tmp_full_path#$sys_archive_dir}" == "$tmp_full_path" ]; then
-    error "the file needs to created inside $sys_archive_dir."
-  elif [ -z "$uninstall" -a "${tmp_full_path#$vhost_archive_dir}" == "$tmp_full_path" ]; then
-    error "the file needs to created inside $vhost_archive_dir."
-  fi
-
   if [ -d "$tmp_full_path" ]; then
     # if the whole filename is actually a directory,
     # then append the default filename
     tmp_full_path+="/@archive_template_str@"
+    tmp_full_path=$(translate_archive_placeholders "$tmp_full_path")
+    [ $? -ne 0 ] && exit 1
   fi
-
   archive_filename=$(basename "$tmp_full_path")
-
-  # do some last transformations to the archive_filename
-  archive_filename=${archive_filename//@archive_template_str@/"$archive_template_str"}
-  archive_filename=${archive_filename//@vhost@/"$vhost"}
-  archive_filename=$(date_placeholders "$archive_filename")
-  [ $? -ne 0 ] && exit 1
-
   if [[ "$archive_filename" != *.[Tt][Gg][Zz] ]]; then
     archive_filename+=".tgz"
   fi
 
   target_dir=${tmp_full_path%/*}
   target_file="$target_dir/$archive_filename"
+
+  if [ -n "$uninstall" -a "${target_file#$sys_archive_dir}" == "$target_file" ]; then
+    error "the file needs to be created inside $sys_archive_dir."
+  elif [ -z "$uninstall" -a "${target_file#$vhost_archive_dir}" == "$target_file" ]; then
+    error "the file needs to be created inside $vhost_archive_dir."
+  fi
 
   # test whether the target file already exists
   if [ -e "$target_file" -o -L "$target_file" ]; then
