major changes to internals of archive/remove vhost
Archive vhost
  * archive on a directory outside the system installation dir
  * all archives are now owned by root and only chgrp'ed by the vhost user,
    so that the vhost user can't remove archives anymore
  * the archive filename is now optional, a default template filename is
    used when a filename is not passed. The command also understands
    relative paths as being relative to the backup directory.
  * better locking to avoid running more than one process at a time

Remove vhost:
  * before removing anything, first archive data into the external
    directory, change similar to the one above on archive-vhost
  * archive name is also optional, if not passed the same template from
    archive-vhost will be used
  * the vhost is now disabled before removing things, so that it doesn't keep
    the site up meanwhile removal is happening
  * now try to remove the database first, and later the files
  * all operations are now done on remove-vhost file, the removal operations
    are very few lines, so it doesn't need to have the external files -web and
   -db

libexec/check-vhost-name:
  * changed 'archive' operation to succeed when the virtwww file of the
    vhost is missing (in case the vhost has just been disabled by
    remove-host)

libexec/config-vhost-apache:
  * added option to disable the specified vhost by moving out the
    configuration file

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -897,3 +897,33 @@ get_metadata_value() {
     return 1
   fi
 }
+
+date_placeholders() {
+  local template_str="$1"
+  local ref_date="${2:-now}"
+
+  if [ -n "$ref_date" ] && ! [[ "$ref_date" =~ ^[A-Za-z0-9\ -]+$ ]]; then
+    echo "$FUNCNAME(): invalid ref_date" 1>&2
+    return 1
+  fi
+
+  local fmt_str='+%d %b %m %Y %H %M'
+
+  local day month monthn year hour minute
+
+  IFS=" " read day month monthn year hour minute \
+    <<< $(date -d "$ref_date" "$fmt_str")
+
+  local date_str
+
+  date_str="$template_str"
+  date_str=${date_str//@day@/"$day"}
+  date_str=${date_str//@month@/"$month"}
+  date_str=${date_str//@monthn@/"$monthn"}
+  date_str=${date_str//@year@/"$year"}
+  date_str=${date_str//@hour@/"$hour"}
+  date_str=${date_str//@minute@/"$minute"}
+
+  printf '%s' "$date_str"
+}
+
diff --git a/libexec/archive-vhost b/libexec/archive-vhost
--- a/libexec/archive-vhost
+++ b/libexec/archive-vhost
@@ -2,11 +2,6 @@
 
 # Options:
 # -P -- save shadow entry
-# -u -- place the archive in ~w_VHOST/gen/archive
-
-
-exec 3>&1
-exec 1>&2
 
 error()
 {
@@ -14,30 +9,32 @@ error()
   exit 1
 }
 
-archive_vhost_web_options=""
-check_archive_pathname_options=""
-opt_u=0
+usage() {
+  local prog=$(basename "$0")
 
-while getopts "Pu" OPTOPT
-do
-  case "$OPTOPT" in
-    P) archive_vhost_web_options="${archive_vhost_web_options+ }-P";;
-    u) opt_u=1;;
-    *) exit 1;
-  esac
-done
-shift `expr $OPTIND - 1`
+  echo "Usage: $prog [options] <vhost> [archive_name]
 
-dir=`dirname "$0"`
-vhost="$1"
-archive_dir="$2"
-tar_output_file=""
-user_db="b_$vhost"
-user_web="w_$vhost"
-action=archive
-[ o`basename $0` = o"remove-vhost" ] && action=remove
-KEEP_TMPDIR=0
-[ $action = remove ] && KEEP_TMPDIR=1
+  Options:
+    -P        save shadow entry
+    -d        debug mode: prints more verbose debug msgs, and doesn't remove
+              the temporary directory on exit
+
+  This command creates an archive of the current state of a vhost, saving
+  Apache files and MySQL databases into a tar ball.
+"
+  exit 1
+}
+
+cleanup()
+{
+  unlock_path "$vhost_archive_dir"
+
+  if [ -z "$debug" -a -n "$tmp_archive_dir" -a -d "$tmp_archive_dir" ]; then
+    rm_rf_safer "$tmp_archive_dir"
+  elif [ -n "$debug" ]; then
+    echo "Kept temporary directory at $tmp_archive_dir" 1>&2
+  fi
+}
 
 run()
 {
@@ -45,76 +42,194 @@ run()
   "$@"
 }
 
-usage()
-{
-  echo "Usage: $0 VHOST ARCHIVE_LABEL" >&2
-  exit 1
-}
+# main
 
-$dir/check-vhost-name archive "$vhost" || usage
-home="`eval \"echo ~$user_web\"`" || error
-[ -d "$home" ] || error "Home dir $home does not exist"
+[ $# -eq 0 -o -z "$1" ] && usage
 
-tar_output_file="$archive_dir"
+exec 3>&1
+exec 1>&2
 
-if [ $opt_u = 1 ]
-then
-  check_archive_pathname_options="${check_archive_pathname_options+ }-u$vhost"
-  [ o"`dirname \"$archive_dir\"`" = o"." ] || error "basename without path must be specified with the -u option"
-  [ o"`basename \"$archive_dir\"`" = o"$archive_dir" ] || error "basename without path must be specified with the -u option"
-  case "$archive_dir" in
-  *.tgz);;
-  *) error "$archive_dir: only .tgz is allowed with the -u option"
+archive_vhost_web_options=""
+check_archive_pathname_options=""
+debug=""
+
+while getopts "Pud" OPTOPT
+do
+  case "$OPTOPT" in
+    P) archive_vhost_web_options="${archive_vhost_web_options+ }-P";;
+    u) : ;; # removed, kept here meanwhile all references are not removed
+    d) debug=1 ;;
+    *) exit 1;
   esac
-  archive_dir="$home/public_html/gen/archive/$archive_dir"
+done
+[ $OPTIND -gt 1 ] && shift `expr $OPTIND - 1`
+
+[ $# -eq 0 -o -z "$1" ] && usage
+
+self_bin=$(readlink -e "$0")
+dir=`dirname "$self_bin"`
+sys_dir=$(readlink -e "$dir/..")
+
+lib_file="$sys_dir/lib/functions"
+if ! source "$lib_file"; then
+  echo "Error: unable to load lib file '$lib_file'" 1>&2
+  exit 1
 fi
 
-if [ o"$archive_dir" != o"-" ]; then  $dir/check-archive-pathname $check_archive_pathname_options archive "$archive_dir" || error; fi
+vhost="$1"
+archive_to="$2"
 
+user_db="b_$vhost"
+user_web="w_$vhost"
 
-TMPDIR=""
+$dir/check-vhost-name archive "$vhost" || usage
+home="`eval echo -n \~$user_web`"
+[ -d "$home" ] || error "Home dir $home does not exist"
 
-cleanup()
-{
-  if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]
-  then
-    if [ $KEEP_TMPDIR = 0 ]
-    then
-      echo "Removing temporary archive $TMPDIR" >&2
-      rm -rf "$TMPDIR"
-    fi
+assign_deref_os_prop_or_exit sys_data_dir "$sys_dir" data_dir
+sys_data_dir=$(readlink -e "$sys_data_dir")
+if [ $? -ne 0 ]; then
+  if   [ ! -e "$sys_data_dir" ]; then
+    error "missing system data directory $sys_data_dir"
+  elif [ ! -d "$sys_data_dir" ]; then
+    error "path '$sys_data_dir' is not a directory."
+  else
+    error "unknown error on path $sys_data_dir"
   fi
-}
+fi
 
-TMPDIR=`$dir/archive-mktemp archive-vhost` || exit 1
-trap 'cleanup' HUP INT QUIT ILL TRAP ABRT BUS FPE KILL SEGV PIPE STOP ALRM TERM EXIT
-archive_dir="$TMPDIR"
+assign_deref_os_prop_or_exit archive_template_str "$sys_dir" \
+  vhost_archive_template_str
 
+sys_archive_dir="$sys_data_dir/vhost_archives"
 
-echo Processing web...
-run mkdir -p "$archive_dir" || exit 1
-run $0-web $archive_vhost_web_options "$vhost" "$archive_dir/web" || exit 1
+# create sys_archive_dir if it doesn't exist
+if [ $? -ne 0 -o -z "$sys_archive_dir" ]; then
+  mkdir -m 711 "$sys_archive_dir"
+  if [ $? -ne 0 ]; then
+    error "unable to create archive directory '$sys_archive_dir'"
+  fi
+fi
+vhost_archive_dir="$sys_archive_dir/$vhost"
+
+if [ -n "$archive_to" ]; then
+  if [ "${archive_to:0:1}" == "/" ]; then
+    tmp_full_path="$archive_to"
+  else
+    tmp_full_path="$vhost_archive_dir/$archive_to"
+  fi
+
+  tmp_to_file=$(readlink -m "$tmp_full_path")
+  vhost_archive_dir_len=${#vhost_archive_dir}
+
+  # compare the full path name of $tmp_to_file with $sys_archive_dir
+  if [ ${#tmp_to_file} -le $vhost_archive_dir_len -o \
+    "${tmp_to_file:0:$vhost_archive_dir_len}" != "$vhost_archive_dir" ]; then
+    error "the file needs to created inside $vhost_archive_dir. Please don't\
+ use a path with the filename".
+  fi
+
+  archive_filename=$(basename "$archive_to")
+else
+  # archive name was not passed on cmdline, use the full template
+  archive_filename="$archive_template_str"
+fi
+
+# do some last transformations to the archive_filename
+archive_filename=${archive_filename//@archive_template_str@/"$archive_template_str"}
+archive_filename=${archive_filename//@vhost@/"$vhost"}
+archive_filename=$(date_placeholders "$archive_filename")
+[ $? -ne 0 ] && exit 1
+
+target_file="$vhost_archive_dir/$archive_filename"
+if ! [[ "$target_file" =~ \.[Tt][Gg][Zz]$ ]]; then
+  target_file+=".tgz"
+fi
+
+if [ -e "$target_file" -o -L "$target_file" ]; then
+  error "file '$target_file' already exists."
+fi
+
+# create vhost_archive_dir if it doesn't exist
+if [ ! -d "$vhost_archive_dir" ]; then
+  mkdir -m 2750 "$vhost_archive_dir"
+  if [ $? -ne 0 ]; then
+    error "unable to create directory '$vhost_archive_dir'"
+  fi
+  echo "Created directory '$vhost_archive_dir'..."
+fi
+
+# lock $vhost_archive_dir not to have other concurring backups
+# at the same time
+if ! lock_path "$vhost_archive_dir" >/dev/null; then
+  error "unable to lock directory $vhost_archive_dir"\
+\ "probably there's an ongoing backup running."
+fi
+trap 'cleanup' HUP INT QUIT ILL TRAP ABRT BUS FPE KILL SEGV \
+  PIPE STOP ALRM TERM EXIT
+
+# in case group ownership is different, chgrp vhost_archive_dir to $user_web
+group_name=$(stat -c %G "$vhost_archive_dir")
+if [ "$group_name" != "$user_web" ]; then
+  chgrp "$user_web" "$vhost_archive_dir"
+  if [ $? -ne 0 ]; then
+    error "unable to chgrp archive dir $vhost_archive_dir to $user_web"
+  fi
+  echo "Chgrp'd directory '$vhost_archive_dir' to $user_web..."
+fi
+
+tmp_archive_dir=`mktemp -d "$vhost_archive_dir/archive_vhost.tmp.XXXXXX"`
+if [ $? -ne 0 ]; then
+  error "unable to create temporary directory for archiving."
+fi
+
+tmp_target_file=$(mktemp "$tmp_archive_dir/$archive_filename.XXXXXX")
+if [ $? -ne 0 ]; then
+  error "unable to create temporary file"
+fi
+
+echo "Archiving web files..."
+${debug:+run} "$0-web" $archive_vhost_web_options "$vhost" "$tmp_archive_dir/web"
+if [ $? -ne 0 ]; then
+  error "unable to archive web files (temp dir $tmp_archive_dir/web)"
+fi
+
 if ! `id -u "$user_db" 2>/dev/null >/dev/null`
 then
   echo "Skipping db (no such user $user_db)"
 else
-  echo Processing db...
-  run $0-db "$vhost" "$archive_dir/db"
-fi
-
-echo "Making the archive readable to $user_web"
-run chmod -R g+rX  "$archive_dir"
-#run chgrp -R "$user_web" "$archive_dir"
-run chgrp -R "weadmin" "$archive_dir"
-
-
-if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]
-then
-  exec >&3
-  tar -C "$TMPDIR" -zcpf - . | "$dir/archive-vhost-store" $check_archive_pathname_options "$tar_output_file" || error
-  if [ $KEEP_TMPDIR = 0 ]
-  then
-    echo "Removing temporary archive $TMPDIR" >&2
-    rm -rf "$TMPDIR"
+  echo "Archiving MySQL databases..."
+  ${debug:+run} "$0-db" "$vhost" "$tmp_archive_dir/db"
+  if [ $? -ne 0 ]; then
+    error "unable to archive db files (temp dir $tmp_archive_dir/db)"
   fi
 fi
+
+exec >&3
+
+echo "Starting final tar ball archiving..."
+base_tmp_target_file=$(basename "$tmp_target_file")
+${debug:+run} tar -C "$tmp_archive_dir" --exclude="$base_tmp_target_file" \
+  -zScpf "$tmp_target_file" .
+if [ $? -ne 0 ]; then
+  error "unable to create archive file $tmp_target_file"
+fi
+
+# now move the tmp file to the target location
+# don't overwrite in case the target file exists
+if ! ${debug:+run} mv -n "$tmp_target_file" "$target_file"; then
+  error "unable to move '$tmp_target_file' to '$target_file'"
+fi
+
+if ! ${debug:+run} chgrp "$user_web" "$target_file"; then
+  echo "Warning: unable to chgrp archive file to group $user_web" 1>&2
+  sleep 2
+fi
+
+if ! ${debug:+run} chmod 0640 "$target_file"; then
+  echo "Warning: unable to chmod 640 archive file $target_file" 1>&2
+  sleep 2
+fi
+
+echo
+echo "Successfully saved archive file to '$target_file'"
diff --git a/libexec/archive-vhost-web b/libexec/archive-vhost-web
--- a/libexec/archive-vhost-web
+++ b/libexec/archive-vhost-web
@@ -24,13 +24,16 @@ run_su()
 
 self_bin=`readlink -e "$0"`
 dir=`dirname "$self_bin"`
+sys_dir=$(readlink -e "$dir/..")
+
 vhost="$1"
 archive_dir="$2"
 user="w_$vhost"
 home="`eval \"echo ~$user\"`"
 date=`date  +'%Y%m%d'`
 archive_file="$archive_dir/$user.tgz"
-conf=`readlink -e "$dir/../config/os/pathnames/etc/apache_vhosts/$user.conf"`
+conf=`readlink -m "$sys_dir/config/os/pathnames/etc/apache_vhosts/$user.conf"` # -m because it might have been removed
+conf_removed="$conf.removed"
 archive_shadow="$archive_dir/$user.shadow"
 archive_conf="$archive_dir/apache_$vhost.conf"
 logs_dir=`readlink -e "$dir/../config/os/pathnames/var/log/apache_vhosts/$user"`
@@ -102,9 +105,15 @@ if ! run tar --exclude ./public_html/gen/archive --exclude ./logs \
   exit 1
 fi
 
+if [ ! -f "$conf" -a -f "$conf_removed" ]; then
+  virtwww_file="$conf_removed"
+else
+  virtwww_file="$conf"
+fi
+
 echo "Copying apache config to $archive_conf"
-if ! cp "$conf" "$archive_conf"; then
-  echo "Error: unable to copy apache file '$conf' to '$archive_conf'" 1>&2
+if ! cp "$virtwww_file" "$archive_conf"; then
+  echo "Error: unable to copy apache file '$virtwww_file' to '$archive_conf'" 1>&2
   exit 1
 fi
 
diff --git a/libexec/config-vhost-apache b/libexec/config-vhost-apache
--- a/libexec/config-vhost-apache
+++ b/libexec/config-vhost-apache
@@ -4,7 +4,10 @@ error() { echo "ERROR${@+: }$@" >&2; exit 1; }
 usage() {
   local prog=`basename "$0"`
   echo "
-  Usage: $prog <vhost>
+  Usage: $prog [options] <vhost>
+
+  Options:
+    -D        disable the specified vhost
 
   This script generates apache mod_macro configuration files.
 "
@@ -284,11 +287,34 @@ in_array() {
   return 1
 }
 
+cleanup() {
+
+  [ -n "$tmp_new_vhost_file" ] && rm -f -- "$tmp_new_vhost_file"
+  [ -n "$vhost_bkp_file" ] && rm -f -- "$vhost_bkp_file"
+
+  unlock_path "$virtwww_dir"
+}
+
 # main
 
 [ $# -eq 0 -o -z "$1" ] && usage
 
 dir=`dirname "$0"`
+
+getopt_flags='D'
+while getopts $getopt_flags OPTN; do
+  case $OPTN in
+    D)
+      disable_vhost=1
+      ;;
+    *)
+      exit 1
+      ;;
+  esac
+done
+[ $OPTIND -gt 1 ] && shift $(( $OPTIND - 1 ))
+
+[ $# -eq 0 -o -z "$1" ] && usage # yes, again
 
 vhost="$1"
 user="w_$vhost"
@@ -315,10 +341,47 @@ assign_deref_os_fs_path_ex_or_exit apachectl "$we_base_dir" pathnames/sbin/apach
 assign_deref_os_fs_path_ex_or_exit virtwww_dir "$we_base_dir" pathnames/etc/apache_vhosts
 assign_deref_os_prop_or_exit websites_basedir "$we_base_dir" apache_virtwww_homedir
 
+if [ -f "$apachectl" -a -x "$apachectl" ]; then
+  hash -p "$apachectl" apachectl
+else
+  error "problem with $apachectl, doing nothing."
+fi
+
+if ! lock_path "$virtwww_dir" >/dev/null; then
+  error "Apache configuration is locked. There should have"\
+ "another process running."
+fi
+trap 'exit 1' HUP INT QUIT ILL TRAP ABRT BUS FPE KILL SEGV \
+              PIPE STOP ALRM TERM
+trap 'cleanup' EXIT
+
+if ! apachectl configtest &>/dev/null; then
+  error "Apache configuration is broken. Please check it."
+fi
+
 virtwww_file="$virtwww_dir/$user.conf"
 virtwww_file_old="$virtwww_file.old"
 config_dir="$we_base_dir/config/vhosts/$vhost"
 apache_svc_config_dir="$we_base_dir/config/packages/apache_vhost"
+
+if [ -n "$disable_vhost" ]; then
+  if [ -f "$virtwww_file" ]; then
+    mv -f "$virtwww_file" "$virtwww_file.removed"
+    if [ $? -eq 0 ]; then
+      apachectl graceful
+      if [ $? -eq 0 ]; then
+        echo "Successfully disabled vhost $vhost"
+        exit 0
+      else
+        error "apache configuration is broken. Failed to disable."
+      fi
+    else
+      error "unable to move out $virtwww_file"
+    fi
+  else
+    error "Error: didn't file virtwww file $virtwww_file. Aborted."
+  fi
+fi
 
 if get_metadata_value "$config_dir" "$DEVPANEL_VHOST_LOCK_FLAG" &>/dev/null; then
   error "vhost $vhost is locked. Can't work on a locked vhost."
@@ -337,14 +400,11 @@ tmp_new_vhost_file=`mktemp "$virtwww_file.XXXXXXXXXXXXXXX"`
 if [ $? -ne 0 ]; then
   error "unable to create temporary file"
 fi
-trap 'ex=$?; rm -f "$tmp_new_vhost_file"; exit $ex;' EXIT INT TERM QUIT
 
 vhost_bkp_file=`mktemp "$virtwww_file.bkp.XXXXXXXXXXXXXXX"`
 if [ $? -ne 0 ]; then
   error "unable to create a temporary backup file"
 fi
-trap 'exit 1' INT TERM QUIT
-trap 'rm -f "$tmp_new_vhost_file"; rm -f "$vhost_bkp_file";' EXIT
 
 if [ -f "$virtwww_file" ] && ! cat "$virtwww_file" > "$vhost_bkp_file"; then
   error "unable to write a copy of '$virtwww_file' into '$vhost_bkp_file'"
diff --git a/libexec/remove-vhost b/libexec/remove-vhost
--- a/libexec/remove-vhost
+++ b/libexec/remove-vhost
@@ -2,7 +2,6 @@
 
 # Options:
 # -P -- save shadow entry
-# -u -- place the archive in ~w_VHOST/gen/archive
 
 
 exec 3>&1
@@ -14,30 +13,15 @@ error()
   exit 1
 }
 
-archive_vhost_web_options=""
-check_archive_pathname_options=""
-opt_u=0
+usage() {
+  local prog=$(basename "$0")
 
-while getopts "Pu" OPTOPT
-do
-  case "$OPTOPT" in
-    P) archive_vhost_web_options="${archive_vhost_web_options+ }-P";;
-    u) opt_u=1;;
-    *) exit 1;
-  esac
-done
-shift `expr $OPTIND - 1`
+  echo "Usage: $prog <vhost> [archive_name]
 
-dir=`dirname "$0"`
-vhost="$1"
-archive_dir="$2"
-tar_output_file=""
-user_db="b_$vhost"
-user_web="w_$vhost"
-action=archive
-[ o`basename $0` = o"remove-vhost" ] && action=remove
-KEEP_TMPDIR=0
-[ $action = remove ] && KEEP_TMPDIR=1
+  This script removes the specified vhost from the system.
+"
+  exit 1
+}
 
 run()
 {
@@ -45,76 +29,101 @@ run()
   "$@"
 }
 
-usage()
-{
-  echo "Usage: $0 VHOST ARCHIVE_LABEL" >&2
-  exit 1
-}
+revert_disable_vhost() {
+  echo "Re-enabling vhost..."
 
-$dir/check-vhost-name archive "$vhost" || usage
-home="`eval \"echo ~$user_web\"`" || error
-[ -d "$home" ] || error "Home dir $home does not exist"
-
-tar_output_file="$archive_dir"
-
-if [ $opt_u = 1 ]
-then
-  check_archive_pathname_options="${check_archive_pathname_options+ }-u$vhost"
-  [ o"`dirname \"$archive_dir\"`" = o"." ] || error "basename without path must be specified with the -u option"
-  [ o"`basename \"$archive_dir\"`" = o"$archive_dir" ] || error "basename without path must be specified with the -u option"
-  case "$archive_dir" in
-  *.tgz);;
-  *) error "$archive_dir: only .tgz is allowed with the -u option"
-  esac
-  archive_dir="$home/public_html/gen/archive/$archive_dir"
-fi
-
-if [ o"$archive_dir" != o"-" ]; then  $dir/check-archive-pathname $check_archive_pathname_options archive "$archive_dir" || error; fi
-
-
-TMPDIR=""
-
-cleanup()
-{
-  if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]
-  then
-    if [ $KEEP_TMPDIR = 0 ]
-    then
-      echo "Removing temporary archive $TMPDIR" >&2
-      rm -rf "$TMPDIR"
-    fi
+  "$dir/config-vhost-apache" "$vhost"
+  if [ $? -eq 0 ]; then
+    echo "Successfully re-enabled vhost $vhost"
   fi
 }
 
-TMPDIR=`$dir/archive-mktemp archive-vhost` || exit 1
-trap 'cleanup' HUP INT QUIT ILL TRAP ABRT BUS FPE KILL SEGV PIPE STOP ALRM TERM EXIT
-archive_dir="$TMPDIR"
+# main
+archive_vhost_web_options=""
+check_archive_pathname_options=""
 
+while getopts "Pu" OPTOPT
+do
+  case "$OPTOPT" in
+    P) archive_vhost_web_options="${archive_vhost_web_options+ }-P";;
+    u) : ;; # option removed, left here until we update all references to it
+    *) exit 1;
+  esac
+done
+[ $OPTIND -gt 1 ] && shift `expr $OPTIND - 1`
 
-echo Processing web...
-run mkdir -p "$archive_dir" || exit 1
-run $0-web $archive_vhost_web_options "$vhost" "$archive_dir/web" || exit 1
+self_bin=$(readlink -e "$0")
+dir=`dirname "$self_bin"`
+sys_dir=$(readlink -e "$dir/..")
+
+vhost="$1"
+archive_to="$2"
+[ -z "$archive_to" ] && archive_to="removed--@archive_template_str@"
+
+user_db="b_$vhost"
+user_web="w_$vhost"
+
+"$dir/check-vhost-name" archive "$vhost" || exit 1
+
+lib_file="$sys_dir/lib/functions"
+if ! source "$lib_file"; then
+  echo "Error: unable to source lib file $lib_file" 1>&2
+  exit 1
+fi
+
+vhost_config_dir="$sys_dir/config/vhosts/$vhost"
+apache_base_log_dir=$(deref_os_fs_path "$sys_dir" pathnames/var/log/apache_vhosts)
+[ -n "$apache_base_log_dir" ] && apache_log_dir="$apache_base_log_dir/$user_web"
+
+"$dir/config-vhost-apache" -D "$vhost" || exit 1
+trap 'revert_disable_vhost' EXIT
+
+"$dir/archive-vhost" "$vhost" "$archive_to"
+[ $? -ne 0 ] && exit 1
+trap - EXIT # at this point revert_* doesn't make sense anymore
+
+# Removing database related stuff
 if ! `id -u "$user_db" 2>/dev/null >/dev/null`
 then
   echo "Skipping db (no such user $user_db)"
 else
-  echo Processing db...
-  run $0-db "$vhost" "$archive_dir/db"
-fi
+  echo Removing database related things...
 
-echo "Making the archive readable to $user_web"
-run chmod -R g+rX  "$archive_dir"
-#run chgrp -R "$user_web" "$archive_dir"
-run chgrp -R "weadmin" "$archive_dir"
+  dbmgr_dir="$sys_dir/config/os/pathnames/opt/dbmgr"
+  file1="$dbmgr_dir/config/db-daemons.conf"
+  file2="$dbmgr_dir/config/db-shadow.conf"
 
+  echo "Commenting out the entries in db-daemons.conf and db-shadow.conf:"
+  run sed -i.old "s/^$user_db:/#&/" "$file1"
+  #grep "$user" $file1 | sed 's/^/  /'
+  run sed -i.old "s/^$user_db:/#&/" "$file2"
 
-if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]
-then
-  exec >&3
-  tar -C "$TMPDIR" -zcpf - . | "$dir/archive-vhost-store" $check_archive_pathname_options "$tar_output_file" || error
-  if [ $KEEP_TMPDIR = 0 ]
-  then
-    echo "Removing temporary archive $TMPDIR" >&2
-    rm -rf "$TMPDIR"
+  "$dir/remove-user" "$user_db"
+
+  if [ $? -ne 0 ]; then
+    error "unable to remove database"
   fi
 fi
+
+# Removing web related stuff
+echo "Removing web things..."
+
+if [ -n "$apache_log_dir" -a -d "$apache_log_dir" ]; then
+  echo "Removing apache log files"
+  run rm_rf_safer "$apache_log_dir"
+fi
+
+echo "Removing webenabled config dir"
+run rm_rf_safer "$vhost_config_dir"
+
+echo "Removing cron for $user_web"
+run crontab -u "$user_web" -r
+
+echo "Removing the user $user_web"
+run "$dir/remove-user" "$user_web" || exit 1
+
+echo "Removing the group $user_web"
+run groupdel "$user_web" || true
+
+echo
+echo "Successfully removed vhost $vhost"
