archive-vhost: fixed stale lock problem

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -906,6 +906,28 @@ assign_deref_os_fs_path_ex_or_exit() {
   fi
 }
 
+get_lock_filename() {
+  local orig_name="$1"
+
+  if [ -z "$1" ]; then
+    echo "$FUNCNAME(): error, missing file name" 1>&2
+    return 1
+  fi
+
+  local real_path dir_name basename lock_file
+  real_path=$(readlink -m "$orig_name")
+  if [ $? -ne 0 -o -z "$real_path" ]; then
+    return 1
+  fi
+
+  dir_name=${real_path%/*}
+  basename=${real_path##*/}
+
+  lock_file="$dir_name/.$basename.lock"
+
+  echo "$lock_file"
+}
+
 lock_path() {
   local path="$1"
   local sleep_n="${2:-0.1}"
@@ -913,11 +935,11 @@ lock_path() {
 
   local lock_file=""
 
-  lock_file="`dirname "$path"`/.`basename "$path"`.lock"
+  lock_file=$(get_lock_filename "$path") || return 1
 
   local -i retries=1
   while [ $retries -le $max_retries ]; do
-    ln -s "pid:$PPID" "$lock_file" 2>/dev/null
+    ln -s "pid:$BASHPID" "$lock_file" 2>/dev/null
     if [ $? -eq 0 ]; then
       printf '%s' "$lock_file"
       return 0
@@ -936,7 +958,7 @@ unlock_path() {
   
   local lock_file=""
 
-  lock_file="`dirname "$path"`/.`basename "$path"`.lock"
+  lock_file=$(get_lock_filename "$path")
 
   if [ ! -L "$lock_file" -a ! -e "$lock_file" ]; then
     wedp_warn "didn't find lock file '$lock_file'"
diff --git a/libexec/archive-vhost b/libexec/archive-vhost
--- a/libexec/archive-vhost
+++ b/libexec/archive-vhost
@@ -36,7 +36,6 @@ usage() {
 cleanup()
 {
   unlock_path "$archive_lock"
-  rm -f -- "$archive_lock"
 
   if [ -z "$debug" -a -n "$tmp_archive_dir" -a -d "$tmp_archive_dir" ]; then
     rm_rf_safer "$tmp_archive_dir"
@@ -49,6 +48,18 @@ run()
 {
   echo "  Running $@"
   "$@"
+}
+
+process_still_exists() {
+  local pid="$1"
+
+  local pid_dir="/proc/$pid"
+
+  if [ -d "$pid_dir" ]; then
+    return 0
+  else
+    return 1
+  fi
 }
 
 # main
@@ -110,11 +121,38 @@ home="`eval echo -n \~$user_web`"
 
 # lock $vhost_archive_dir not to have other concurring backups
 # at the same time
-archive_lock="$sys_dir/config/vhosts/$vhost/.archive"
-touch "$archive_lock"
+archive_lock="$sys_dir/config/vhosts/$vhost"
 if ! lock_path "$archive_lock" >/dev/null; then
-  error "unable to lock directory $vhost_archive_dir"\
-\ "probably there's an ongoing backup running."
+  lock_f=$(get_lock_filename "$archive_lock")
+  if [ -L "$lock_f" ]; then
+    # lock file exists, check if it's from the same program type
+    #
+    # this is needed because on some VPSs when the script crashes because of
+    # lack of memory the lock file gets stale because the exit code is not
+    # run
+    prev_pid=$(deref_contents "$lock_f")
+    prev_pid=${prev_pid//[^0-9]/}
+    if [ -z "$prev_pid" ]; then
+      error "there's a lock file, but it was not possible to get pid from it"
+    fi
+
+    if process_still_exists "$prev_pid"; then
+      errmsg="unable to lock directory $vhost_archive_dir"
+      errmsg+=" there's another backup running already."
+      error "$errmsg"
+    else
+      # that pid not running anymore, just remove the lock
+      echo "Warning: removing stale pid file..."
+      unlock_path "$archive_lock"
+
+      # try locking again, but this time as the last attempt
+      if ! lock_path "$archive_lock" >/dev/null; then
+        exit 1
+      fi
+    fi
+  else
+    exit 1
+  fi
 fi
 
 trap 'exit 1 ' HUP INT QUIT ILL TRAP ABRT BUS FPE KILL SEGV \
