added full support to Let's Encrypt on vhosts

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -1148,7 +1148,84 @@ escape_quotes() {
   printf '%s' "$new"
 }
 
-get_virtwww_base_domain() {
+get_vhost_base_domain() {
+  # returns the real base domain of a vhost
+  local vhost="$1"
+
+  local domain_int base_domain key
+
+  key="apache_vhost:0:_:base_domain"
+
+  domain_int=$(get_vhost_key_value "$key" "$vhost") || return $?
+
+  base_domain=$(get_real_hostname "$domain_int") || return $?
+
+  echo "$base_domain"
+}
+
+get_vhost_default_hostname() {
+  # returns the default hostname of the vhost
+  # (i.e the one used on ServerName and in the app's config
+
+  local vhost="$1"
+  
+  local key="apache_vhost:0:_:ServerName"
+  local hostname
+
+  hostname=$(get_vhost_key_value "$key" "$vhost") || return $?
+  if [ $? -eq 0 ]; then
+    echo "$hostname"
+  else
+    echo "$FUNCNAME(): unable to get default hostname from vhost $vhost" 1>&2
+    return 1
+  fi
+}
+
+set_vhost_default_hostname() {
+  local vhost="$1"
+  local hostname="$2"
+
+  local metadata_str key
+  key="apache_vhost:0:_:ServerName"
+  metadata_str="set $key $hostname"
+
+  echo "$metadata_str" | "$DEVPANEL_HOME/libexec/apache-metadata-handler" \
+                           -q "$vhost"
+
+  if [ $? -eq 0 ]; then
+    return 0
+  else
+    echo "$FUNCNAME(): unable to set default domain for vhost $vhost" 1>&2
+    return 1
+  fi
+}
+
+set_vhost_base_domain() {
+  local vhost="$1"
+  local domain="$2"
+
+  local int_name metadata_str
+
+  if [ -z "$domain" ]; then
+    int_name=$(format_hostname_internal "$vhost") || return $?
+  else
+    int_name=$(format_hostname_internal "$domain") || return $?
+  fi
+
+  metadata_str="set apache_vhost:0:_:base_domain $int_name"
+
+  echo "$metadata_str" | "$DEVPANEL_HOME/libexec/apache-metadata-handler" \
+                           -q "$vhost"
+
+  if [ $? -eq 0 ]; then
+    return 0
+  else
+    echo "$FUNCNAME(): unable to set base domain for vhost $vhost" 1>&2
+    return 1
+  fi
+}
+
+get_server_base_domain() {
   local system_dir="${1:-$DEVPANEL_HOME}"
   local domain
 
@@ -1167,7 +1244,7 @@ format_hostname_internal() {
   local base_domain="$3"
 
   if [ -z "$base_domain" ]; then
-    base_domain=$(get_virtwww_base_domain) || return $?
+    base_domain=$(get_server_base_domain) || return $?
   fi
 
   local test_host_stripped="" final_hostname="" has_dot=""
@@ -1213,6 +1290,24 @@ format_hostname_internal() {
   echo -n "$final_hostname"
 }
 
+get_real_hostname() {
+  local hostname="$1"
+
+  local host_fmt="" server_base_domain=""
+
+  if [ "${hostname: -1}" == "." ]; then
+    # $len_minus_one is a workaround for older bash versions that don't know
+    # negative lengths (e.g. CentOS 6.5 and previous)
+    local len_minus_one=$(( ${#hostname} - 1 ))
+    host_fmt="${hostname:0:$len_minus_one}" # remove the last dot
+  else
+    server_base_domain=$(get_server_base_domain) || return $?   
+    host_fmt="$hostname.$server_base_domain"
+  fi
+
+  echo -n "$host_fmt"
+}
+
 get_list_of_vhosts() {
   local vhost_config_dir="$DEVPANEL_HOME/config/vhosts"
   local vhost vhost_dir
@@ -1238,12 +1333,15 @@ get_list_of_vhosts() {
 
 get_vhost_with_hostname() {
   local hostname="$1"
-  local tst_vhost tst_main tst_conf_dir tst_alias_link tst_main_link
+
+  local tst_vhost tst_main tst_conf_dir 
+  local tst_alias_link tst_value tst_base_link tst_link
   local hostname_fmt
 
   hostname_fmt=$(format_hostname_internal "$hostname")
 
-  local main_base="apache_vhost:0:_:ServerName"
+  local base_addr="apache_vhost:0:_:base_domain"
+  local default_base="apache_vhost:0:_:ServerName"
   local alias_base="apache_vhost:0:_:ServerAlias"
 
   for tst_vhost in $(get_list_of_vhosts); do
@@ -1255,16 +1353,52 @@ get_vhost_with_hostname() {
       return 0
     fi
 
-    tst_main_link="$tst_conf_dir/$main_base"
-    if tst_main=$(deref_contents "$tst_main_link"); then
-      if [ "$tst_main" == "$hostname" ]; then
-        echo "$tst_vhost"
-        return 0
+    tst_base_link="$tst_conf_dir/$base_addr"
+    tst_main_link="$tst_conf_dir/$default_base"
+
+    for tst_link in "$tst_base_link" "$tst_main_link"; do
+      if tst_value=$(deref_contents "$tst_link" 2>/dev/null); then
+        if [ "$tst_value" == "$hostname" ]; then
+          echo "$tst_vhost"
+          return 0
+        fi
       fi
-    fi
+    done
   done
 
   return 1 # not found in any vhost
+}
+
+get_hostnames_from_vhost() {
+  local vhost="$1"
+
+  local vhost_conf_dir="$DEVPANEL_HOME/config/vhosts/$vhost"
+
+  local base_domain base_domain_real tmp_link tmp_name tmp_fmt_name
+  local -a hosts_ar=()
+
+  base_domain=$(get_vhost_base_domain "$vhost") || return $?
+
+  hosts_ar+=( "$base_domain" )
+
+  for tmp_link in "$vhost_conf_dir/apache_vhost:0:_:ServerAlias:"*; do
+    if [ ! -L "$tmp_link" ]; then
+      continue
+    fi
+
+    # apache_vhost:0:_:ServerAlias:domain.com.
+    tmp_name=${tmp_link##*:}
+    tmp_fmt_name=$(get_real_hostname "$tmp_name") || return $?
+
+    if [ "$tmp_fmt_name" == "$base_domain" ]; then
+      continue
+    fi
+
+    hosts_ar+=( $tmp_fmt_name )
+  done
+
+  local IFS=$'\n'
+  echo "${hosts_ar[*]}"
 }
 
 translate_archive_placeholders() {
diff --git a/libexec/apply-ssl-config b/libexec/apply-ssl-config
--- a/libexec/apply-ssl-config
+++ b/libexec/apply-ssl-config
@@ -125,21 +125,41 @@ if [ "$cert_modulus" != "$key_modulus" ]; then
 "doesn't match key modulus ($key_modulus)"
 fi
 
+# need to get the full path of the files to use in the links below
+cert_file_full_path=$(readlink -e "$cert_file")
+if [ $? -ne 0 ]; then
+  error "unable to determine full path of file '$cert_file'"
+fi
+
+key_file_full_path=$(readlink -e "$key_file")
+if [ $? -ne 0 ]; then
+  error "unable to determine full path of file '$key_file'"
+fi
+
+if [ -n "$ca_bundle_file" ]; then
+  ca_bundle_file_full_path=$(readlink -e "$ca_bundle_file")
+  if [ $? -ne 0 ]; then
+    error "unable to determine full path of file '$ca_bundle_file'"
+  fi
+fi
+
 vhost_prefix="apache_vhost:3"
 vhost_internal_name="default_ssl"
 
 cert_link="$ssl_cert_dir/$vhost.$vhost_internal_name.crt"
 key_link="$ssl_key_dir/$vhost.$vhost_internal_name.key"
 
-ln -sf "$cert_file" "$cert_link"
-ln -sf "$key_file" "$key_link"
+ln -sf "$cert_file_full_path" "$cert_link"
+ln -sf "$key_file_full_path" "$key_link"
 
 ca_bundle_link="$ssl_cert_dir/CA-bundle.$vhost.$vhost_internal_name.crt"
 if [ -n "$ca_bundle_file" ]; then
-  ln -sf "$ca_bundle_file" "$ca_bundle_link"
-elif [ -L "$ca_bundle_link" ]; then
-  # CA bundle not provided, delete the link to CA file
-  rm -f "$ca_bundle_link"
+  ln -sf "$ca_bundle_file_full_path" "$ca_bundle_link"
+else
+  if [ -L "$ca_bundle_link" ]; then
+    # CA bundle not provided, delete the link to CA file
+    rm -f "$ca_bundle_link"
+  fi
 fi
 
 metadata_op=""
diff --git a/libexec/config-vhost-names b/libexec/config-vhost-names
--- a/libexec/config-vhost-names
+++ b/libexec/config-vhost-names
@@ -47,6 +47,11 @@ generate_serveralias() {
   local alias_link="$base:param:1:ServerAlias"
   local alias_hostname="" aliases_str="" hostname_fmt=""
 
+  if [ "$vhost_base_domain" != "$server_hostname" ]; then
+    # add the base hostname to the list of aliases
+    aliases_str+="$vhost_base_domain"
+  fi
+
   for alias_host in "$base":_:ServerAlias:*; do
     if [ "$alias_host" == "$base:_:ServerAlias:*" ]; then
       if [ -L "$alias_link" ]; then
@@ -89,20 +94,6 @@ generate_serveralias() {
 # main
 [ $# -eq 0 -o -z "$1" ] && usage
 
-if [ "${0:0:1}" != "/" ]; then
-  error "please call this script with the full path"
-fi
-
-self_bin=`readlink -e "$0"`
-dir=`dirname "$self_bin"`
-
-we_dir=`readlink -e "$dir/.."`
-
-lib_file="$we_dir/lib/functions"
-if ! source "$lib_file"; then
-  error "unable to source lib file '$lib_file'"
-fi
-
 prefix_with_www=1
 force_subdomain=0
 getopt_flags='nsi:'
@@ -127,6 +118,27 @@ do
 done
 [ $OPTIND -gt 1 ] && shift `expr $OPTIND - 1`
 
+[ -z "$1" ] && usage
+
+self_bin=`readlink -e "$0"`
+if [ $? -ne 0 ]; then
+  echo "Error: unable to get self path" 1>&2
+  exit 1
+fi
+
+dir=`dirname "$self_bin"`
+
+we_dir=`readlink -e "$dir/.."`
+
+lib_file="$we_dir/lib/functions"
+vars_file="$we_dir/lib/variables"
+
+for inc_file in "$lib_file" "$vars_file"; do
+  if ! source "$inc_file"; then
+    error "unable to source file '$inc_file'"
+  fi
+done
+
 vhost="$1"
 if ! "$dir/check-vhost-name" name-only "$vhost"; then
   error "vhost argument is in an invalid format"
@@ -140,19 +152,10 @@ fi
 sys_vhost_config_dir="$we_dir/config/vhosts"
 config_dir="$sys_vhost_config_dir/$vhost"
 
-server_hostname=`deref_os_prop "$we_dir" apache_virtwww_domain`
+server_hostname=`get_server_base_domain`
 if [ $? -ne 0 ]; then
   error "unable to get base domain name for apache virtual hosts"
 fi
-
-lib_file="$we_dir/lib/functions"
-vars_file="$we_dir/lib/variables"
-
-for inc_file in "$lib_file" "$vars_file"; do
-  if ! source "$inc_file"; then
-    error "unable to source file '$inc_file'"
-  fi
-done
 
 if get_metadata_value "$config_dir" "$DEVPANEL_VHOST_LOCK_FLAG" &>/dev/null; then
   error "vhost $vhost is locked. Can't work on a locked vhost."
@@ -166,15 +169,12 @@ mode=""
 
 vhost_config_prefix_str="apache_vhost:0"
 vhost_base="$config_dir/$vhost_config_prefix_str"
-base_host_link="$vhost_base:_:ServerName"
 
-if [ -L "$base_host_link" ]; then
-  default_name=`readlink "$base_host_link"`
+# administrative base domain
+vhost_base_domain=$(get_vhost_base_domain "$vhost") || exit $?
 
-  if [ -z "$default_name" ]; then
-    error "unable to get default hostname from vhost $vhost"
-  fi
-fi
+# default name that is on ServerName and in the app configs
+default_name=$(get_vhost_default_hostname "$vhost" 2>/dev/null) 
 
 unset changed
 alias_base="$vhost_base:param:1:ServerAlias"
@@ -210,10 +210,10 @@ for i; do
           fi
         fi
 
-        # saving the previous name into the aliases
-        [ -L "$base_host_link" ] && previous_name=`readlink "$base_host_link"`
+        previous_name="$default_name"
 
         if [ -n "$previous_name" ]; then
+          # saving the previous name into the aliases
           previous_name_cut=${previous_name%.$server_hostname}
           if [ "$previous_name" == "$default_name_apache" ]; then
             echo "Warning: the default name hasn't changed..." 1>&2
@@ -241,9 +241,7 @@ for i; do
         fi
 
         # overwriting the existing value
-        if ! ln -sf "$default_name_apache" "$base_host_link"; then
-          error "unable to set the default name"
-        fi
+        set_vhost_default_hostname "$vhost" "$default_name_apache" || exit $?
 
         if [ -n "$prefix_with_www" ]; then
           www_alias_link="$alias_priv:www.$new_default_name"
@@ -251,7 +249,6 @@ for i; do
             error "unable to set www alias to default name"
           fi
         fi
-
 
         # if this same name is already a domain alias, then remove it
         if [ -L "$alias_file" ]; then
@@ -273,7 +270,7 @@ for i; do
         this_hostname_fmt=`format_hostname_internal "$this_hostname" $force_subdomain`
         this_name_apache=`format_to_apache "$server_hostname" "$this_hostname_fmt" $force_subdomain`
 
-        if [ "$this_hostname_fmt" == "$default_name_fmt" ]; then
+        if [ "$this_name_apache" == "$default_name" ]; then
           echo "Warning: this hostname is equal to the default hostname.  Skipping..." 1>&2
           break;
         fi
@@ -309,10 +306,17 @@ for i; do
         this_hostname="$i"
 
         this_hostname_fmt=`format_hostname_internal "$this_hostname" $force_subdomain`
+        this_real_hostname=$(get_real_hostname "$this_hostname_fmt")
 
-        [ "$default_name" = "$this_hostname" ] && \
+        if [ "$this_real_hostname" == "$vhost_base_domain" ]; then
+          err_msg="host '$this_real_hostname' is the administrative hostname"
+          err_msg+=" for this vhost. Can't remove it."
+          error "$err_msg"
+        fi
+ 
+        [ "$default_name" = "$this_real_hostname" ] && \
           error "Cannot remove the default name $this_hostname; change the default name first"
-        
+       
         name_file="$alias_priv:$this_hostname_fmt"
         if [ ! -L "$name_file" ]; then
           printf "Warning: name %s doesn't exist for vhost %s and IP %s\n" \
