vhostctl.sh: removed hardcoded URLs from Webenabled for seed apps
previously it assumed that all apps were created from the original URL from
Webenabled. Removed the hardcoded URL and now use the 'install app' command
(that reads the URL internally from the configuration).

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -1873,7 +1873,9 @@ get_hostnames_from_vhost() {
   default_domain=$(get_vhost_default_hostname "$vhost") || return $?
 
   hosts_ar+=( "$base_domain" )
-  hosts_ar+=( "$default_domain" )
+  if [ "$base_domain" != "$default_domain" ]; then
+    hosts_ar+=( "$default_domain" )
+  fi
 
   for tmp_link in "$vhost_conf_dir/apache_vhost:0:_:ServerAlias:"*; do
     if [ ! -L "$tmp_link" ]; then
@@ -3249,4 +3251,79 @@ get_php_version_from_vhost() {
 
 get_default_php_version() {
   deref_os_prop "$DEVPANEL_HOME" php_default_version
+}
+
+is_nginx_on_port80() {
+  local apache_port pids_on_port80 tst_pid pid_exe
+
+  apache_port=$(get_apache_http_port ) || return $?
+
+  if [ "$apache_port" != 80 ]; then
+    if pids_on_port80=$(fuser 80/tcp 2>/dev/null ); then
+      while [ -n "$pids_on_port80" -a "${pids_on_port80:0:1}" == " " ]; do
+        # remove the leading space from the output
+        pids_on_port80="${pids_on_port80# }"
+      done
+
+      # test the first pid to see if it's nginx
+      tst_pid=${pids_on_port80%% *}
+
+      pid_exe=$(readlink -e /proc/$tst_pid/exe ) || return $?
+      if [[ "$pid_exe" == *nginx ]]; then
+        return 0
+      fi
+    fi
+  fi
+
+  return 1
+}
+
+write_nginx_local_vhost() {
+  local vhost="$1"
+
+  if ! vhost_exists "$vhost"; then
+    echo "$FUNCNAME(): vhost doesn't exist" 1>&2
+    return 1
+  fi
+
+  local nginx_vhost_dir nginx_vhost_lnk_dir
+  local vhost_base_domain vhost_file vhost_lnk vhost_hostnames vhost_txt
+  local apache_http_port server_base_domain
+
+  server_base_domain=$(get_server_base_domain )       || return $?
+  vhost_base_domain=$(get_vhost_base_domain "$vhost") || return $?
+  apache_http_port=$(get_apache_http_port )           || return $?
+
+  nginx_vhost_dir="/etc/nginx/sites-available"
+  nginx_vhost_lnk_dir="/etc/nginx/sites-enabled"
+
+  vhost_file="$nginx_vhost_dir/$vhost_base_domain.conf"
+  vhost_lnk="$nginx_vhost_lnk_dir/$vhost_base_domain.conf"
+
+  local vhost_tmpl_txt='
+server {
+  listen       80;
+  server_name  @vhost_hostnames@ @vhost@-gen.@server_base_domain@;
+  location / {
+    proxy_set_header Host $host;
+    proxy_pass http://127.0.0.1:@apache_http_port@;
+  }
+}
+'
+
+  vhost_hostnames=$(get_hostnames_from_vhost "$vhost") || return $?
+  vhost_hostnames=${vhost_hostnames//$'\n'/ }
+  vhost_txt="$vhost_tmpl_txt"
+  vhost_txt="${vhost_txt//@vhost@/$vhost}"
+  vhost_txt="${vhost_txt//@server_base_domain@/$server_base_domain}"
+  vhost_txt="${vhost_txt//@vhost_hostnames@/$vhost_hostnames}"
+  vhost_txt="${vhost_txt//@apache_http_port@/$apache_http_port}"
+
+  if echo "$vhost_txt" >"$vhost_file"; then
+    rm -f "$vhost_lnk"
+    ln -s "$vhost_file" "$vhost_lnk"
+  else
+    echo "$FUNCNAME(): unable to write vhost file '$vhost_file'" 1>&2
+    return 1
+  fi
 }
diff --git a/paas-provisioner/docker/functions b/paas-provisioner/docker/functions
--- a/paas-provisioner/docker/functions
+++ b/paas-provisioner/docker/functions
@@ -361,35 +361,17 @@ move_apache_ports() {
 
 detect_running_apache_and_patch_configs()
 {
-  local -a local_vhosts_ar=()
-  local -i n_vhosts=0
-  local base_domain=""
+  local apache_port
 
-  base_domain=$(get_server_base_domain)
-
-  local apache_port=$(get_apache_http_port)
+  apache_port=$(get_apache_http_port)
+  
   if [ "$apache_port" == 80 ]; then
     move_apache_ports
+    create_nginx_config
   fi
 
-  local_vhosts_ar=( $(get_list_of_local_vhosts) )
-  n_vhosts=${#local_vhosts_ar[@]}
-
-  if [ $n_vhosts -gt 0 ]; then
-    for vhost in "${local_vhosts_ar[@]}"; do
-      declare -a serverliases_ar=()
-      serveraliases_ar=( $(get_hostnames_from_vhost "$vhost") )
-      serveraliases_ar+=( "${vhost}-gen.${base_domain}" )
-
-      servername=${serveraliases_ar[0]}
-      serveraliases="${serveraliases_ar[*]}"
-
-      create_nginx_config
-    done
-
-    # update nginx configs with apache's hosts
-    restart_or_reload_nginx
-  fi
+  # update nginx configs with apache's hosts
+  restart_or_reload_nginx
 }
 
 update_scripts()
@@ -465,34 +447,6 @@ operation_handle()
       elif [ "$app_hosting" == "local" ]; then
         su - w_${vhost} -c "${sys_dir}/${handler_options}"
       fi
-    ;;
-
-    libexec/restore-vhost*http://www.webenabled.com/seedapps/*)
-      ${sys_dir}/${handler_options}
-      if [ -z "${app}" ]; then
-        case "$handler_options" in
-          libexec/restore-vhost*http://www.webenabled.com/seedapps/wordpress*.tgz)
-            app="wordpress"
-          ;;
-          libexec/restore-vhost*http://www.webenabled.com/seedapps/drupal-v7*.tgz)
-            app="drupal"
-          ;;
-          libexec/restore-vhost*http://www.webenabled.com/seedapps/drupal-v8*.tgz)
-            app="drupal8"
-          ;;
-          libexec/restore-vhost*http://www.webenabled.com/seedapps/mag*.tgz)
-            app="magento"
-          ;;
-          libexec/restore-vhost*http://www.webenabled.com/seedapps/grav*.tgz)
-            app="grav"
-          ;;
-          *)
-            echo "App not supported."
-            exit 1
-          ;;
-        esac
-      fi
-      create_local_config
     ;;
 
     libexec/restore-vhost*)
@@ -622,34 +576,18 @@ operation_create()
     echo "exit 0" >> /etc/rc.local
   elif [ "$host_type" == "local" ]; then
     vhost=`echo "${domain}" | awk -F'[.]' '{print $1}'`
-    domain_name=`echo "${domain}" | awk -F"${vhost}." '{print $2}'`
-    ${sudo} ${sys_dir}/libexec/config-vhost-names-default ${domain_name}
-
-    # get seedapps
-    case "$app" in
-      wordpress)
-        app_arch="wordpress-v4.1.tgz"
-      ;;
-      drupal)
-        app_arch="drupal-v7.50.tgz"
-      ;;
-      drupal8)
-        app_arch="drupal-v8.1.8.tgz"
-      ;;
-      magento)
-        app_arch="mag1800.tgz"
-      ;;
-      *)
-        echo "App not supported."
-        exit 1
-      ;;
-    esac
-    # check for downloaded app
-    if [ ! -f ${sys_dir}/${app}/${app_arch} ]; then
-      ${sudo} mkdir -p ${sys_dir}/${app} && cd ${sys_dir}/${app} && wget https://www.webenabled.com/seedapps/${app_arch} && tar zxvf ${app_arch}
+    if [ -z "$app" ]; then
+      echo "Error: missing app parameter. Please specify it with -A" 1>&2
+      return 1
     fi
 
-    ${sudo} ${sys_dir}/libexec/restore-vhost -F ${vhost} ${sys_dir}/${app}
+    ${sudo} devpanel install app --app "${app}" --publisher devpanel --vhost "${vhost}"
+    local st=$?
+    if [ $st -ne 0 ]; then
+      echo "Error: failed to install app '$app' on vhost '$vhost'" 1>&2
+      return $st
+    fi
+
     detect_running_apache_and_patch_configs
   else
     show_help
