CLI: added support to longer vhost names (not enabled by default)

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -301,17 +301,53 @@ is_valid_domain_string() {
   fi
 }
 
+generate_username_string_from_vhost() {
+  local vhost="$1"
+
+  if [ -z "$vhost" ]; then
+    echo "$FUNCNAME(): missing vhost" 1>&2
+    return 1
+  fi
+
+  if ! is_valid_vhost_string "$vhost"; then
+    echo "$FUNCNAME(): invalid format of vhost name" 1>&2
+    return 1
+  fi
+
+  local vhost_str vhost_str_1
+  vhost_str="$vhost"
+  vhost_str_1="${vhost_str:1}"
+
+  if [ ${#vhost_str} -gt 1 ]; then
+    # remove vogals after the 2nd position from $vhost string
+    vhost_str="${vhost_str:0:1}${vhost_str_1//[aeiou-]/}"
+  fi
+
+  if [ -z "$vhost_str" ]; then
+    # if it got empty from removing the vogals, then just return the first 6
+    # positions of $vhost
+    vhost_str="w_${vhost:0:6}"
+  else
+    vhost_str="w_${vhost_str:0:6}"
+  fi
+
+  echo "$vhost_str"
+}
+
 generate_linux_username_for_vhost() {
   local vhost="$1"
 
   unset _dp_value
 
-  local user randomstr
-  randomstr=$(gen_random_str_az_lower 6) || return 1
+  local user_str random_str
 
-  user="w_$randomstr"
+  user_str=$(generate_username_string_from_vhost "$vhost")
+  if linuxuser_exists "$user_str"; then
+    random_str=$(gen_random_str_az_lower 6) || return 1
+    user_str="w_$randomstr"
+  fi
 
-  _dp_value="$user"
+  _dp_value="$user_str"
   
   [ -n "$_dp_print" ] && printf '%s' "$_dp_value"
 
@@ -1181,6 +1217,53 @@ get_apache_metadata_value() {
   get_metadata_value "$vhost_conf_dir" "$key"
 }
 
+is_valid_vhost_string() {
+  local string="$1"
+
+  if [ -z "$string" ]; then
+    echo "$FUNCNAME(): received an empty vhost string" 1>&2
+    return 1
+  fi
+
+  local vhost_regex='^[a-z0-9]+[a-z0-9-]+$'
+
+  if [[ "$string" =~ $vhost_regex ]]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+vhost_exists() {
+  local test_str="$1"
+
+  if [ -z "$test_str" ]; then
+    echo "$FUNCNAME(): received an empty vhost string" 1>&2
+    return 1
+  fi
+
+  if ! is_valid_vhost_string "$test_str"; then
+    echo "$FUNCNAME(): invalid format of vhost name" 1>&2
+    return 1
+  fi
+
+  local config_dir="$DEVPANEL_HOME/config/vhosts/$test_str"
+  if [ -d "$config_dir" ]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+linuxuser_exists() {
+  local user="$1"
+
+  if getent -- passwd "$user" &>/dev/null; then
+    return 0
+  else
+    return 1
+  fi
+}
 
 is_distro_updates_enabled() {
   deref_os_prop "$DEVPANEL_HOME" automatic_distro_updates &>/dev/null
@@ -1729,6 +1812,10 @@ get_vhost_key_value() {
   local key_link="$DEVPANEL_HOME/config/vhosts/$vhost/$key"
 
   deref_contents "$key_link"
+}
+
+is_longer_vhost_names_enabled() {
+  deref_os_prop "$DEVPANEL_HOME" enable_long_vhost_names &>/dev/null
 }
 
 get_php_version_for_series() {
diff --git a/libexec/archive-vhost-db b/libexec/archive-vhost-db
--- a/libexec/archive-vhost-db
+++ b/libexec/archive-vhost-db
@@ -96,9 +96,14 @@ if ! source "$lib_file"; then
   exit 1
 fi
 
+get_linux_username_from_vhost "$vhost" && \
+user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+user="b_${user_web#w_}"
 archive_list="$archive_dir/databases"
 archive_my_cnf="$archive_dir/b_.my.cnf"
-user="b_$vhost"
 home="`eval \"echo ~$user\"`"
 date=`date  +'%Y%m%d'`
 vhost_config_dir="$sys_dir/config/vhosts/$vhost"
diff --git a/libexec/check-vhost-name b/libexec/check-vhost-name
--- a/libexec/check-vhost-name
+++ b/libexec/check-vhost-name
@@ -25,6 +25,8 @@ locked()
 
 # main
 
+declare -i max_vhost_length=6
+
 mode="$1"
 [ $# = 2 ] && case "$mode" in archive|restore|lock|unlock|config|name-only) true;; *) false;; esac || 
   error "Usage: $0 [archive|restore|lock|unlock|config|name-only] basename"
@@ -41,6 +43,13 @@ for inc_file in "$lib_file" "$vars_file"; do
   fi
 done
 
+unset enable_long_vhost_names
+enable_long_vhost_names=$(deref_os_prop "$devpanel_dir" \
+                          enable_long_vhost_names 2>/dev/null)
+if [ $? -eq 0 -a "$enable_long_vhost_names" == yes ]; then
+  max_vhost_length=30
+fi
+
 vhost="$2"
 get_linux_username_from_vhost "$vhost" && w_user="$_dp_value"
 if [ $? -ne 0 ]; then
@@ -48,7 +57,7 @@ if [ $? -ne 0 ]; then
 fi
 b_user="b_$vhost"
 
-(echo "$vhost"|egrep -q '^[-_a-z0-9]{1,6}$')||error "invalid vhost name '$vhost'"
+(echo "$vhost"|egrep -q "^[-_a-z0-9]{1,$max_vhost_length}\$")||error "invalid vhost name '$vhost'"
 
 assign_deref_os_fs_path_ex_or_exit apache_config_dir "$devpanel_dir" \
   "pathnames/etc/apache_vhosts"
diff --git a/libexec/config-vhost-apache b/libexec/config-vhost-apache
--- a/libexec/config-vhost-apache
+++ b/libexec/config-vhost-apache
@@ -322,6 +322,11 @@ if [ $? -ne 0 ]; then
   error "unable to get the linux username from vhost $vhost"
 fi
 
+doc_root=$(get_docroot_from_vhost "$vhost")
+if [ $? -ne 0 -o -z "$doc_root" ]; then
+  error "unable to get document root from vhost"
+fi
+
 user_home=$(eval echo -n \~"$user")
 if [ $? -ne 0 -o -z "$user_home" ]; then
   error "unable to get home directory of user '$user'"
@@ -925,6 +930,8 @@ for this_vhost_prefix in "$vhost_prefix_f:"[0-9] "$vhost_prefix_f:"[0-9][0-9]; d
   sed_line+="s/@@__VHOST__@@/`escape_sed "$vhost"`/g;"
   sed_line+="s/@@__VHOST_INTERNAL_NAME__@@/`escape_sed "$vhost_name"`/g;"
   sed_line+="s/@@__VHOST_NUMBER__@@/$vhn/g;"
+  sed_line+="s/@@__VHOST_USER__@@/`escape_sed "$user"`/g;"
+  sed_line+="s/@@__VHOST_DOC_ROOT__@@/`escape_sed "$doc_root"`/g;"
   sed_line+="s/@@__VHOST_USER_HOME__@@/`escape_sed "$user_home"`/g;"
   sed_line+="s/@@__TEMPLATE_FILE__@@/`escape_sed "$template_file"`/g;"
   sed_line+="s/@@__TEMPLATE_FILE_BASENAME__@@/`escape_sed "$vhost_template"`/g;"
diff --git a/libexec/create-virtwww b/libexec/create-virtwww
--- a/libexec/create-virtwww
+++ b/libexec/create-virtwww
@@ -2,6 +2,8 @@
 # Options:
 #   -n - do not activate apache vhost, use the 'Vhost-simple-dummy' macro
 
+[ "$1" == '--help' ] && usage
+
 dummy=""
 
 unset custom_template
@@ -68,9 +70,6 @@ function usage() {
     cat << EOF
 Usage: $progname [[account_name_base] [domain.tld[,alias[,...]]]]
 
-the length of account_name_base must not exceed 6 chars, since it'll prepended
-by "w_" prefix.
-
 EOF
     exit 1
 }
@@ -82,41 +81,31 @@ function check_domain_name() {
     for name in $DOMAIN_NAMES ; do
         result=$(echo "$name" | tr -d '[:alnum:].-')
         if [ -n "$result" ]; then
-            echo "check_domain_name: '$name' contains invalid characters '$result'"
-            return 1
+          echo "$FUNCNAME(): '$name' contains invalid characters '$result'"
+          return 1
         fi
     done
     return 0
 }
 
-function check_account_name() {
-    local ACCOUNT_NAME
-    if [ $# -ne 1 ]; then
-        echo 'check_account_name: wrong number of arguments'
-        return 1
-    fi
-    ACCOUNT_NAME="$1"
-    if [ ${#ACCOUNT_NAME} -gt 6 ]; then
-        echo 'check_account_name: account name too long (more than 6 chars)'
-        return 1
-    fi
-    return 0
-}
-
-[ $# -gt 2 -o "$1" == '--help' ] && usage
-ACCOUNT_NAME="$1"
+unset ACCOUNT_NAME
+vhost="$1"
 DOMAIN_NAMES="$2"
 
+"$we_base/libexec/check-vhost-name" restore "$vhost" || exit $?
+
+if [ -n "$DOMAIN_NAMES" ] && ! check_domain_name "$DOMAIN_NAMES"; then
+  exit 1
+fi
+
+generate_linux_username_for_vhost "$vhost" && ACCOUNT_NAME="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to generate linux username for vhost"
+fi
+
 DB_ACCOUNT_NAME="b_$ACCOUNT_NAME"
-vhost="$ACCOUNT_NAME"
-ACCOUNT_NAME="w_$ACCOUNT_NAME" # linux user
 VHOST_HOME="$WEBSITES_HOME/$ACCOUNT_NAME"
 VHOST_DOC_ROOT="$VHOST_HOME/public_html/$vhost"
-
-#generate_linux_username_for_vhost "$vhost" && ACCOUNT_NAME="$_dp_value"
-#if [ $? -ne 0 ]; then
-#  error "unable to generate linux username for vhost"
-#fi
 
 # stack stuff
 config_base_dir="$we_base/config/vhosts"
diff --git a/libexec/restore-vhost b/libexec/restore-vhost
--- a/libexec/restore-vhost
+++ b/libexec/restore-vhost
@@ -153,27 +153,13 @@ export DEVPANEL_HOME="$we_base_dir"
 
 metadata_bin="$DEVPANEL_HOME/libexec/apache-metadata-handler"
 config_dir="$we_base_dir/config/vhosts/$vhost"
-home="`eval \"echo ~$user_web\"`" || error "unable to get \$HOME of user $user_web"
-user_db="b_$vhost"
 vhost_config_dir=.webenabled/private
-shift
-shift
-
-if [ $create_vhost -eq 1 ]; then
-  $dir/check-vhost-name restore "$vhost" || usage
-elif [ $create_vhost -eq 0 ] && ! user_info=$(getent passwd "$user_web" 2>/dev/null); then
-  error "user '$user_web' must exist"
-fi
 
 aux_lib_file="$we_base_dir/lib/functions"
 if ! source "$aux_lib_file"; then
   error "unable to load auxiliary functions from $aux_lib_file"
 fi
 
-get_linux_username_from_vhost "$vhost" && user_web="$_dp_value"
-if [ $? -ne 0 ]; then
-  error "unable to get the linux username from vhost $vhost"
-fi
 
 assign_deref_os_prop_or_exit sys_datadir "$we_base_dir" data_dir
 
@@ -181,6 +167,10 @@ if [ -n "$subsystem" ]; then
   if ! is_known_seedapp_subsystem "$subsystem"; then
     error "unknown subsystem name specified"
   fi
+fi
+
+if [ $create_vhost -eq 1 ]; then
+  $dir/check-vhost-name restore "$vhost" || usage
 fi
 
 password="";
@@ -306,6 +296,14 @@ fi
 
 echo Processing web...
 run $0-web $web_options "$vhost" "$archive_dir/web" "$@" || exit 1
+
+get_linux_username_from_vhost "$vhost" && user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
+home="`eval \"echo ~$user_web\"`" || error "unable to get \$HOME of user $user_web"
+user_db="b_${user_web#w_}"
 
 if ! [ -d "$archive_dir/db" ]
 then
diff --git a/libexec/restore-vhost-web b/libexec/restore-vhost-web
--- a/libexec/restore-vhost-web
+++ b/libexec/restore-vhost-web
@@ -82,18 +82,40 @@ if ! source "$lib_file" ; then
   exit 1
 fi
 
+assign_deref_os_fs_path_ex_or_exit apache_config_dir "$we_base_dir" pathnames/etc/apache_vhosts
+assign_deref_os_fs_path_ex_or_exit chcgi "$we_base_dir" pathnames/sbin/chcgi
+assign_deref_os_fs_path_ex_or_exit apache_logs_dir  "$we_base_dir" pathnames/var/log/apache_vhosts
+
+assign_deref_os_prop_or_exit apache_group "$we_base_dir" names/apache.group
+assign_deref_os_prop_or_exit home_prefix  "$we_base_dir" apache_virtwww_homedir
+
+if [ $create_vhost -eq 1 ]; then
+  if vhost_exists "$vhost"; then
+    error "vhost '$vhost' already exists"
+  fi
+
+  base_domain=$(get_server_base_domain) || exit $?
+
+  echo -e "n\nn\ny"| run $dir/create-virtwww $options "$vhost" \
+    "$vhost.$base_domain"
+  if [ $? -ne 0 ]; then
+    error "unable to create vhost"
+  fi
+elif [ $create_vhost -eq 0 ]; then
+  if ! vhost_exists "$vhost"; then
+    error "vhost '$vhost' doesn't exist"
+  fi
+
+  if locked; then
+    error "Cannot restore apache config in locked state"
+  fi
+fi
+
 get_linux_username_from_vhost "$vhost" && \
 user="$_dp_value"
 if [ $? -ne 0 ]; then
   error "unable to get the linux username from vhost $vhost"
 fi
-
-if [ $create_vhost -eq 1 ] && getent passwd "$user" &>/dev/null; then
-  error "vhost '$vhost' already exists"
-elif [ $create_vhost -eq 0 ] && ! user_info=$(getent passwd "$user" 2>/dev/null); then
-  error "vhost '$vhost' doesn't exist"
-fi
-
 
 if [ $create_vhost -eq 0 -a $search_in_users_home -eq 1 \
   -a ! -e "$archive_label" -a "${archive_label:0:1}" != "/" \
@@ -131,13 +153,6 @@ old_user="w_$old_vhost"
 date=`date  +'%Y%m%d'`
 archive_file="$archive_dir/$old_user.tgz"
 
-assign_deref_os_fs_path_ex_or_exit apache_config_dir "$we_base_dir" pathnames/etc/apache_vhosts
-assign_deref_os_fs_path_ex_or_exit chcgi "$we_base_dir" pathnames/sbin/chcgi
-assign_deref_os_fs_path_ex_or_exit apache_logs_dir  "$we_base_dir" pathnames/var/log/apache_vhosts
-
-assign_deref_os_prop_or_exit apache_group "$we_base_dir" names/apache.group
-assign_deref_os_prop_or_exit home_prefix  "$we_base_dir" apache_virtwww_homedir
-
 conf="$apache_config_dir/$user.conf"
 archive_conf="$archive_dir/apache_$old_vhost.conf"
 logs_dir="$apache_logs_dir/$user"
@@ -153,19 +168,6 @@ elif [ ! -f "$archive_file" ]; then
   error "archive file is not a regular file"
 elif [ $create_vhost -eq 1 -a ! -e "$archive_conf" ]; then
   error "missing apache config file '$archive_conf'"
-fi
-
-if [ $create_vhost -eq 1 ] && \
-  ! default_domain=`deref_os_prop "$we_base_dir" apache_virtwww_domain`; then
-  error "Unable to get apache domain for virtualhosts"
-elif [ $create_vhost -eq 1 ] && \
-  ! echo -e "n\nn\ny"| run $dir/create-virtwww $options "$vhost" "$vhost.$default_domain"; then
-  error "unable to create vhost"
-elif [ $create_vhost -eq 0 ] && locked; then
-  echo "Restoring the locked state of apache cofig"
-  if ! run $dir/lock-vhost-apache "$vhost"; then
-    error "Cannot restore apache config in locked state"
-  fi
 fi
 
 home="`eval \"echo ~$user\"`"
