lib/functions: added pkg management functions

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -288,3 +288,158 @@ is_sshkey_in_keyfile() {
 
   return 1
 }
+
+devpanel_download_pkg() {
+  local package="$1"
+  local version="$2"
+  local base_url="$3"
+  local tmp_dir="${4:-/tmp}"
+
+  local pkg_url="$base_url/$pkg_n_version.tar.gz"
+
+  local tmp_pkg_dir="$tmp_dir/pkgs"
+  if [ ! -d "$tmp_pkg_dir" ] && ! mkdir -m 700 "$tmp_pkg_dir"; then
+    echo "$FUNCNAME(): unable to create temp dir '$tmp_pkg_dir'" 1>&2
+    return 1
+  fi
+
+  if ! download_file "$pkg_url" "$tmp_file"; then
+    echo "$FUNCNAME(): unable to download package '$package'" 1>&2
+    return 1
+  fi
+}
+
+devpanel_install_pkg() {
+  local package="$1"
+  local version="$2"
+  local file="$3"
+  local system_dir="$4"
+  local target_path="$5"
+  local tmp_dir="${6:-/tmp}"
+
+  local pkg_n_version="$package-$version"
+  local tmp_file=`mktemp "$tmp_dir/$pkg_n_version.tar.gz"`
+
+  local tmp_pkg_dir="$tmp_dir/pkgs/$pkg_n_version"
+  if [ ! -d "$tmp_pkg_dir" ] && ! mkdir -m 700 "$tmp_pkg_dir"; then
+    echo "$FUNCNAME(): unable to create temp dir '$tmp_pkg_dir'" 1>&2
+    return 1
+  fi
+
+  tar -zxf "$file" -C "$tmp_pkg_dir" setup
+  if [ $? -ne 0 ]; then
+    echo "$FUNCNAME(): unable to extract package file" 1>&2
+    return 1
+  fi
+
+  local pre_install_script="$tmp_pkg_dir/setup/pre-install"
+  local post_install_script="$tmp_pkg_dir/setup/post-install"
+  if [ -f "$pre_install_script" -a -x "$pre_install_script" ]; then
+    "$pre_install_script" "$package" "$version" "$system_dir" "$target_path"
+  fi
+
+  local target_dir="$system_dir/$target_path/$package/$version"
+  if ! mkdir -p "$target_dir"; then
+    echo "$FUNCNAME(): unable to create target dir '$target_dir' for package '$package'" 1>&2
+    return 1
+  fi
+
+  tar -zxf "$file" -C "$target_dir" --strip-components 1 pkg-files/
+  if [ $? -ne 0 ]; then
+    echo "$FUNCNAME(): unable to extract package files" 1>&2
+    return 1
+  fi
+
+  if [ -f "$post_install_script" -a -x "$post_install_script" ]; then
+    "$post_install_script" "$package" "$version" "$system_dir" "$target_path"
+  fi
+
+  devpanel_update_pkg_link_version "$package" "$version" "$system_dir/$target_path"
+  if [ $? -ne 0 ]; then
+    return 1
+  fi
+
+  return 0
+}
+
+devpanel_update_pkg() {
+  local package="$1"
+  local version="$2"
+  local file="$3"
+  local system_dir="$4"
+  local target_path="$5"
+  local tmp_dir="${6:-/tmp}"
+
+  local pkg_n_version="$package-$version"
+  local tmp_file=`mktemp "$tmp_dir/$pkg_n_version.tar.gz"`
+
+  local tmp_pkg_dir="$tmp_dir/pkgs/$pkg_n_version"
+  if [ ! -d "$tmp_pkg_dir" ] && ! mkdir -m 700 "$tmp_pkg_dir"; then
+    echo "$FUNCNAME(): unable to create temp dir '$tmp_pkg_dir'" 1>&2
+    return 1
+  fi
+
+  tar -zxf "$file" -C "$tmp_pkg_dir" setup
+  if [ $? -ne 0 ]; then
+    echo "$FUNCNAME(): unable to extract package file" 1>&2
+    return 1
+  fi
+
+  local pre_update_script="$tmp_pkg_dir/setup/pre-update"
+  local post_update_script="$tmp_pkg_dir/setup/post-update"
+  if [ -f "$pre_update_script" -a -x "$pre_update_script" ]; then
+    "$pre_update_script" "$package" "$version" "$system_dir" "$target_path"
+  fi
+
+  local target_dir="$system_dir/$target_path/$package/$version"
+  if ! mkdir -p "$target_dir"; then
+    echo "$FUNCNAME(): unable to create target dir '$target_dir' for package '$package'" 1>&2
+    return 1
+  fi
+
+  tar -zxf "$file" -C "$target_dir" --strip-components 1 pkg-files/
+  if [ $? -ne 0 ]; then
+    echo "$FUNCNAME(): unable to extract package files" 1>&2
+    return 1
+  fi
+
+  if [ -f "$post_update_script" -a -x "$post_update_script" ]; then
+    "$post_update_script" "$package" "$version" "$system_dir" "$target_path"
+  fi
+
+  devpanel_update_pkg_link_version "$package" "$version" "$system_dir/$target_path"
+  if [ $? -ne 0 ]; then
+    return 1
+  fi
+
+  return 0
+}
+
+devpanel_update_pkg_link_version() {
+  local package="$1"
+  local version="$2"
+  local pkg_dir="$3"
+
+  target_link="$pkg_dir/current"
+  local status
+
+  if [ ! -e "$pkg_dir/$version" ]; then
+    echo "$FUNCNAME(): dir '$pkg_dir/$version' doesn't seem to exist" 1>&2
+    return 1
+  fi
+
+  if [ -e "$target_link" -a ! -L "$target_link" ]; then
+    echo "$FUNCNAME(): path '$target_link' exists but is not a symbolic link" 1>&2
+    return 1
+  elif [ -e "$target_link" -a -L "$target_link" ]; then
+    rm -f "$target_link"
+  fi
+
+  ln -s "$version" "$target_link"
+  status=$?
+  if [ $status -ne 0 ]; then
+    echo "$FUNCNAME(): unable to update target link '$target_link'" 1>&2
+  fi
+
+  return $status
+}
