major change in system and vhost config storage
Changed system and vhost configuration to be based on ini files. All
distribution specific variables are defined on a single file. Also moved
configuration files to /etc/devpanel/ directory.

Implemented a migration system to make it easier to do post file update
configuration changes.

diff --git a/bin/.path/drush b/bin/.path/drush
--- a/bin/.path/drush
+++ b/bin/.path/drush
@@ -19,7 +19,18 @@ self_dir=${self_bin%/*}
 devpanel_dir=${self_dir%/*/*}
 
 lib_file="$devpanel_dir/lib/functions"
-source "$lib_file" 2>/dev/null
+if ! source "$lib_file"; then
+  echo "Error: unable to load file '$lib_file'" 1>&2
+  exit 1
+fi
+load_devpanel_config || exit $?
+
+if vhost=$(get_vhost_from_linuxuser ); then
+  load_vhost_config "$vhost"
+  public_dir="$v__vhost__linux_user_home"
+else
+  error "unable to get vhost from current user"
+fi
 
 # preferred locations for drush:
 #   if any of the paths below is found it's used
@@ -28,8 +39,6 @@ home_2_drush="$HOME/.drush/drush/drush"
 
 # fallback version
 devpanel_drush="$devpanel_dir/bin/packages/drush-7/drush"
-
-public_dir=$(get_docroot_from_user)
 
 # first check for drush on the user directory
 # if not found, and there isn't another drush in PATH, fallback to
@@ -40,8 +49,8 @@ elif [ -f "$home_2_drush" -a -x "$home_2_drush" ]; then
   drush_bin="$home_2_drush"
 else
   # check if there's a specific version of drush defined for this vhost
-  drush_version=$(get_vhost_key_value "app:0:_:drush_version" 2>/dev/null)
-  if [ $? -eq 0 ]; then
+  if [ -n "$v__app__drush_version" ]; then
+    drush_version="$v__app__drush_version"
     tmp_drush_bin="$devpanel_dir/bin/packages/drush-$drush_version/drush"
     if [ -f "$tmp_drush_bin" -a -x "$tmp_drush_bin" ]; then
       drush_bin="$tmp_drush_bin"
diff --git a/bin/list-backups b/bin/list-backups
--- a/bin/list-backups
+++ b/bin/list-backups
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 usage() {
-  echo "Usage: `basename "$0"` [ options ] [ directory ]
+  echo "Usage: "${0##*/}" [ options ] [ directory ]
 
   Options:
     -m <max_depth>        specify the maximum number of directories allowed to
@@ -49,16 +49,23 @@ if ! . "$lib_f"; then
   echo "Error: unable to import $lib_f" 1>&2
   exit 1
 fi
+load_devpanel_config || exit $?
+
+if [ $EUID -eq 0 -a -z "$1" ]; then
+  usage
+fi
 
 if [ -n "$1" ]; then
   backups_dir="$1"
-elif [ -z "$1" -a ${#USER} -gt 2 -a "${USER:0:2}" == "w_" ]; then
-  data_dir=$(get_devpanel_datadir ) || exit 1
-
+else
   vhost=$(get_vhost_from_linuxuser)
-  backups_dir="$data_dir/vhost_archives/$vhost"
-elif [ -z "$1" ]; then
-  error "unable to auto detect directory. Please specify it manually (see usage, use argument -h)."
+  if [ $? -ne 0 ]; then
+    error "unable to get vhost from linux user"
+  fi
+
+  load_vhost_config "$vhost" || exit $?
+
+  backups_dir="$v__vhost__archives_dir"
 fi
 
 if [ ! -d "$backups_dir" ]; then
diff --git a/bin/mysql-utils b/bin/mysql-utils
--- a/bin/mysql-utils
+++ b/bin/mysql-utils
@@ -294,7 +294,7 @@ cleanup_import_split_db() {
 }
 
 guess_database_name() {
-  db_name=$(get_apache_metadata_value "$sys_dir" 'app:0:_:db_name')
+  db_name=$v__app__database_name
   if [ $? -eq 0 -a -n "$db_name" ]; then
     echo "$db_name"
     return 0
@@ -328,6 +328,13 @@ lib_file="$sys_dir/lib/functions"
 if ! source "$lib_file"; then
   echo "Error: unable to source lib file $lib_file" 1>&2
   exit 1
+fi
+load_devpanel_config || exit $?
+
+if vhost=$(get_vhost_from_linuxuser ); then
+  load_vhost_config "$vhost" || exit $?
+else
+  error "unable to get vhost for current user"
 fi
 
 case "$operation" in
diff --git a/bin/template-tool b/bin/template-tool
--- a/bin/template-tool
+++ b/bin/template-tool
@@ -18,22 +18,11 @@ usage() {
   exit 1
 }
 
-load_defaults() {
-  local base_dir="$1"
-
-  local apache_virtwww_domain=`get_server_base_domain`
-  local apache_virtwww_homedir=`get_vhosts_homedir`
-
-  echo "s/@@__APACHE_VIRTWWW_DOMAIN__@@/`escape_sed "$apache_virtwww_domain"`/g;"
-  echo "s/@@__APACHE_VIRTWWW_HOMEDIR__@@/`escape_sed "$apache_virtwww_homedir"`/g;"
-}
-
 # main
 
 [ $# -lt 2 -o -z "$1" -o -z "$2" ] && usage
 
 getopt_flags='o:vn'
-load_defaults=1
 
 unset output_file verbose
 while getopts $getopt_flags OPTN; do
@@ -44,9 +33,6 @@ while getopts $getopt_flags OPTN; do
     v)
       verbose=1
       ;;
-    n)
-      unset load_defaults
-      ;;
     *)
       usage
       ;;
@@ -54,13 +40,18 @@ while getopts $getopt_flags OPTN; do
 done
 [ $OPTIND -gt 1 ] && shift $(( $OPTIND - 1 ))
 
-dir=`dirname "${BASH_SOURCE[0]}"`
-we_base=`readlink -e "$dir/.."`
+self_bin=$(readlink -e "${BASH_SOURCE[0]}")
+if [ $? -ne 0 ]; then
+  error "unable to get self path"
+fi
+self_dir=${self_bin%/*}
+sys_dir=${self_dir%/*}
 
-lib_file="$we_base/lib/functions"
+lib_file="$sys_dir/lib/functions"
 if ! source "$lib_file"; then
   error "unable to source lib file $lib_file"
 fi
+load_devpanel_config || exit $?
 
 umask 077
 tmp_sed_file=`mktemp`
@@ -86,31 +77,16 @@ fi
 
 trap 'rm -f "$tmp_sed_file" "$tmp_output_file"' HUP INT QUIT EXIT TERM
 
-shift
-
-while [ -n "$1" ]; do
-  name="$1"
-  value=`deref_os_prop "$we_base" "$name"`
-  if [ $? -ne 0 ]; then
-    error "unable to de-reference key $name"
-  fi
-
-  name_escaped=`escape_sed "$name"`
-  value_escaped=`escape_sed "$value"`
-
-  echo "s/@@__${name_escaped^^}__@@/$value_escaped/g;" >> "$tmp_sed_file"
-  if [ $? -ne 0 ]; then
-    error "unable to add line to temp file $tmp_sed_file"
-  fi
-  shift
-done
-
-if [ -n "$load_defaults" ]; then
-  load_defaults "$we_base" >> "$tmp_sed_file"
-  if [ $? -ne 0 ]; then
-    error "unable to load defaults into $tmp_sed_file"
-  fi
+if ! exec 3>$tmp_sed_file; then
+  error "unable to open '$tmp_sed_file'"
 fi
+
+for var in ${!conf__*} ${!lamp__*}; do
+  value_esc=$(escape_sed "${!var}")
+  if ! echo "s/@@__${var^^}__@@/$value_esc/g;" 1>&3; then
+    error "failed writing to $tmp_sed_file"
+  fi
+done
 
 sed -i -f "$tmp_sed_file" "$tmp_output_file"
 if [ $? -ne 0 ]; then
diff --git a/lib/cli/bin/restore-backup b/lib/cli/bin/restore-backup
--- a/lib/cli/bin/restore-backup
+++ b/lib/cli/bin/restore-backup
@@ -90,20 +90,22 @@ devpanel_cmd__restore_backup() {
     return $?
   fi
 
-  if ! vhost_exists_and_is_enabled "$vhost"; then
-    return $?
+  load_vhost_config "$vhost" || return $?
+
+  if ! is_vhost_enabled "$vhost"; then
+    error "this vhost is not enabled. Can't operate on a disabled vhost" -
+    return 1
   fi
 
-  get_linux_username_from_vhost "$vhost" && \
-  web_user="$_dp_value" || return $?
+  web_user="$v__vhost__linux_user"
 
-  vhost_home_dir=$(eval echo -n ~$web_user )
+  vhost_home_dir="$v__vhost__linux_user_home"
   if [ ! -d "$vhost_home_dir" ]; then
     error "unable to find home dir of vhost" -
     return $?
   fi
 
-  doc_root=$(get_docroot_from_vhost "$vhost" ) || return $?
+  doc_root="$v__vhost__document_root"
 
   temp_dir=$(mktemp -d)
   if [ $? -ne 0 ]; then
@@ -117,7 +119,7 @@ devpanel_cmd__restore_backup() {
   if [ $EUID -eq 0 ]; then
     # temporarily disable the vhost on apache for the app not to be modified
     # during the restore
-    "$sys_dir/libexec/config-vhost-apache" -D $vhost || return $?
+    "$sys_dir/libexec/rewrite-vhost-config" -D $vhost || return $?
   fi
   devpanel_trap_exit_cmds_ar+=( "devpanel_cmd__restore_backup_on_exit $vhost" )
 
@@ -181,7 +183,16 @@ devpanel_cmd__restore_backup() {
   fi
 
   # TODO(enhance): regenerate prod specific files (e.g. ~/logs ~/.my.cnf )
-  mysql_write_my_cnf "$vhost" "$web_user" "$vhost_home_dir"
+  if [ $EUID -eq 0 ]; then
+    run_as_user "$web_user" \
+      "rm -f $vhost_home_dir/{.my.cnf,logs} ; \
+       ln -s $v__vhost__logs_dir $vhost_home_dir/logs ; \
+       ln -s $v__mysql__client_file $vhost_home_dir/.my.cnf"
+  else
+    rm -f $vhost_home_dir/{.my.cnf,logs}
+    ln -s $v__vhost__logs_dir $vhost_home_dir/logs
+    ln -s $v__mysql__client_file $vhost_home_dir/.my.cnf
+  fi
 
   local extract_bin="$sys_dir/bin/extract-vhost-files-from-dir"
   local -a extract_cmd_ar=()
diff --git a/lib/cli/bin/test-http b/lib/cli/bin/test-http
--- a/lib/cli/bin/test-http
+++ b/lib/cli/bin/test-http
@@ -93,10 +93,9 @@ devpanel_cmd__test_http() {
     return $?
   fi
 
-  if ! vhost_exists "$vhost"; then
-    error "vhost doesn't exist." -
-    return $?
-  elif ! is_vhost_enabled "$vhost"; then
+  load_vhost_config "$vhost" || return $?
+
+  if ! is_vhost_enabled "$vhost"; then
     # it's ok to test a vhost that is not enabled, but let's just warn just
     # in case
     echo "Warning: vhost is not enabled" 1>&2
@@ -133,12 +132,21 @@ devpanel_cmd__test_http() {
   local st
   local recvd_http_code size 
   local time_nlookup time_connect time_header time_1st_byte time_total
+  local tmp_file
 
-  output=$(curl -sS -o /dev/null -w "$output_str" "${curl_args_ar[@]}" "$url")
+  if tmp_file=$(mktemp); then
+    temp_files_ar+=( "$tmp_file" )
+  else
+    error "unable to create temporary file" -
+    return $?
+  fi
+
+  curl -sSN -o /dev/null -w "$output_str" "${curl_args_ar[@]}" "$url" \
+    >$tmp_file
   st=$?
 
   IFS=' ' read recvd_http_code size time_nlookup time_connect time_header \
-                time_1st_byte time_total <<< "$output"
+                time_1st_byte time_total < $tmp_file
 
   if [ $st -eq 0 ]; then
     local status_txt
diff --git a/lib/cli/sbin/add-domain b/lib/cli/sbin/add-domain
--- a/lib/cli/sbin/add-domain
+++ b/lib/cli/sbin/add-domain
@@ -23,7 +23,8 @@ devpanel_cmd__add_domain() {
 
   local name vhost
   local server_domain curr_default_domain new_default_domain
-  local -a cmd_args_ar=() vhost_args_ar=() domains_ar=()
+  local reload=yes
+  local -a domains_ar=()
 
   while [ -n "$1" ]; do
     name="$1"
@@ -43,11 +44,12 @@ devpanel_cmd__add_domain() {
       --default)
         [ -z "$2" ] && error_missing_value "$name"
         new_default_domain="$2"
+        domains_ar+=( "$2" )
         shift 2
         ;;
 
       --no-reload)
-        cmd_args_ar+=( -N )
+        unset reload
         shift
         ;;
 
@@ -74,46 +76,88 @@ devpanel_cmd__add_domain() {
     return $?
   fi
 
-  server_domain=$(get_server_base_domain) || return $?
+  load_vhost_config "$vhost" || return $?
 
-  curr_default_domain=$( get_vhost_default_hostname "$vhost" ) || return $?
+  server_domain="$lamp__apache_vhosts__virtwww_domain"
 
-  if [ -z "$new_default_domain" ]; then
-    if [[ "$curr_default_domain" == *."$server_domain" ]] && \
-       [[ "${domains_ar[0]}"     != *."$server_domain" ]]; then
+  curr_default_domain="$v__vhost__server_name"
 
-      new_default_domain="${domains_ar[0]}"
-      unset domains_ar[0]
-    fi
-  fi
+  local -a args_ar=()
 
-  if [ -n "$new_default_domain" ]; then
-    if [[ ! "$new_default_domain" == *.* ]]; then
-      # if the domain string doesn't include a dot, then include a dot in
-      # the end to identify it as a fully qualified name
-      new_default_domain+="."
-    fi
-
-    vhost_args_ar+=( '*' "$new_default_domain" )
-  fi
-
+  local -i n_chg=0
   if [ -n "${domains_ar[*]}" ]; then
-    local _domain
+    local _domain other_vhost
     for _domain in "${domains_ar[@]}"; do
       [ -z "$_domain" ] && continue
-      [ "$_domain" == "$new_default_domain" ] && continue
 
-      if [[ ! "$_domain" == *.* ]]; then
-        # if the domain string doesn't include a dot, then include a dot in
-        # the end to identify it as a fully qualified name
-        _domain+="."
+      if other_vhost=$(get_vhost_with_hostname "$_domain" ); then
+        if [ "$other_vhost" == "$vhost" ]; then
+          echo "Warning: domain '$_domain' is already added. Skipping..." 1>&2
+          continue
+        else
+          error "domain '$_domain' is already on vhost '$other_vhost'" -
+          return $?
+        fi
       fi
-      vhost_args_ar+=( '+' "$_domain" )
+
+      if is_word_in_string "$_domain" "$v__vhost__domains"; then
+        echo "Warning: domain $_domain is already on vhost $vhost..." 1>&2
+        continue
+      else
+        v__vhost__domains+=" $_domain"
+        n_chg+=1
+        echo "Adding domain $_domain..."
+      fi
     done
   fi
 
-  cmd_args_ar+=( -n )
+  if [ -n "$new_default_domain" ]; then
+    if [ "$new_default_domain" != "$curr_default_domain" ]; then
+      args_ar+=( "vhost.server_name = $new_default_domain" )
+    fi
+  fi
 
-  "$sys_dir/libexec/config-vhost-names" "${cmd_args_ar[@]}" "$vhost" \
-    "${vhost_args_ar[@]}"
+  if [ ${#args_ar[@]} -eq 0 -a $n_chg -eq 0 ]; then
+    echo "Ok. No change needed."
+    return 0
+  fi
+
+  if [ $n_chg -gt 0 ]; then
+    args_ar+=( "vhost.domains = $v__vhost__domains" )
+
+    # when the default domain (ServerName) is not specified,
+    # try to guess a good value for it
+    if [ -z "$new_default_domain" -a \
+      "$v__vhost__server_name" == "$v__vhost__base_domain" ]; then
+      for _domain in $v__vhost__domains; do
+        if [[ "$_domain" != *\** ]] && \
+           [ "$_domain" != "$v__vhost__base_domain"   ] && \
+           [[ "$_domain" != *.$v__vhost__base_domain ]]; then
+          args_ar+=( "vhost.server_name = $_domain" )
+          [ -t 0 ] && echo "Setting $_domain as the ServerName..."
+          break
+        fi
+      done
+    fi
+  fi
+
+  if ! save_opts_in_vhost_config "$vhost" "${args_ar[@]}"; then
+    error "unable to update vhost configuration. No domain added." -
+    return $?
+  fi
+
+  if [ -n "$reload" ]; then
+    if ! rewrite_vhost_apache_config "$vhost"; then
+      echo "Warning: domains added to the configuration, but failed" \
+           "to reload Apache" 1>&2
+    fi
+  fi
+
+  echo
+  echo -n "Successfully added"
+  if [ $n_chg -eq 1 ]; then
+    echo " domain."
+  else
+    echo " $n_chg domains."
+  fi
 }
diff --git a/lib/cli/sbin/add-vhost-include b/lib/cli/sbin/add-vhost-include
--- a/lib/cli/sbin/add-vhost-include
+++ b/lib/cli/sbin/add-vhost-include
@@ -24,7 +24,6 @@ devpanel_cmd__add_vhost_include() {
 
   local name vhost file
   local tmp_file
-  local -a cmd_args_ar=()
   local reload=1 overwrite had_a_include
 
   while [ -n "$1" ]; do
@@ -49,7 +48,6 @@ devpanel_cmd__add_vhost_include() {
 
       --no-reload)
         unset reload
-        cmd_args_ar+=( -N )
         shift
         ;;
 
@@ -70,16 +68,12 @@ devpanel_cmd__add_vhost_include() {
 
   [ -z "$vhost" -o -z "$file" ] && usage
 
-  if ! vhost_exists "$vhost"; then
-    error "vhost '$vhost' doesn't exist." -
-    return $?
-  fi
+  load_vhost_config "$vhost" || return $?
 
-  if has_user_includes "$vhost"; then
-    had_a_include=1
-  fi
-  if  [ -n "$had_a_include" -a -z "$overwrite" ]; then
-    error "this vhost already has a include file. Please use --ovewrite to replace it."
+  if [ -n "$reload" ]; then
+    reload_opt=--
+  else
+    reload_opt=--no-reload
   fi
 
   if [ "$file" != - -a ! -f "$file" ]; then
@@ -88,7 +82,28 @@ devpanel_cmd__add_vhost_include() {
     error "include file is empty"
   fi
 
-  local config_dir="$sys_dir/config/vhosts/$vhost"
+  local config_dir="/etc/devpanel/lamp/vhosts/$vhost/apache"
+  local include_file="$config_dir/user_includes.inc"
+  local bkp_file="$include_file.bkp"
+
+  if [ -n "$v__vhost__user_includes" -a \
+          "$v__vhost__user_includes" == "yes" ]; then
+
+    had_a_include=1
+
+    if [ -z "$overwrite" ]; then
+      error "this vhost already has a include file. Please use --ovewrite to replace it." -
+      return $?
+    fi
+
+    if [ -f "$include_file" ] && ! cp -f "$include_file" "$bkp_file"; then
+      error "unable to make a copy of '$include_file'" -
+      return $?
+    elif [ -f "$bkp_file" ]; then
+      temp_files_ar+=( "$bkp_file" )
+    fi
+  fi
+
   tmp_file=$(mktemp "$config_dir/tmp_include.XXXXXX")
   if [ $? -eq 0 ]; then
     temp_files_ar+=( "$tmp_file" )
@@ -101,59 +116,53 @@ devpanel_cmd__add_vhost_include() {
   else
     cat "$file" >"$tmp_file"
   fi
-
   if [ $? -ne 0 ]; then
     error "unable to write to temporary file"
   fi
 
-  local int_file="${tmp_file%.*}.inc"
-  local final_file="$config_dir/user_includes.inc"
-
-  if ! mv -f "$tmp_file" "$int_file"; then
-    error "unable to move '$tmp_file' to $int_file"
+  local -a set_ar=( "vhost.user_includes = yes" )
+  if [ -z "$had_a_include" ]; then
+    if ! save_opts_in_vhost_config "$vhost" "${set_ar[@]}"; then
+      error "unable to save vhost configuration." -
+      return $?
+    fi
   fi
-  temp_files_ar+=( "$int_file" )
 
-  if set_user_include_metadata "$vhost" tmp_include; then
-    if apache_configtest; then
-      if [ -n "$had_a_include" ]; then
-        mv -f "$final_file" "$final_file.previous"
-      fi
+  if ! mv -f "$tmp_file" "$include_file"; then
+    error "unable to move '$tmp_file' to '$include_file'" -
+    return $?
+  fi
 
-      if mv -f "$int_file" "$final_file"; then
-        unset_user_include_metadata "$vhost" tmp_include
-        [ -z "$had_a_include" ] && set_user_include_metadata "$vhost" user_includes
-
-        if [ -n "$reload" ]; then
-          if ! devpanel_run rewrite vhost config --vhost "$vhost"; then
-            if [ -n "$had_a_include" ]; then
-              mv -f "$final_file.previous" "$final_file"
-            else
-              rm -f "$final_file"
-              unset_user_include_metadata "$vhost" user_includes
-            fi
-            return 1
-          fi
-        fi
-
-        if [ -n "$reload" ]; then
-          if reload_or_start_apache; then
-            echo "Successfully included file."
-          else
-            echo "Warning: included file, but apache reload failed." 1>&2
-          fi
-        fi
-
-        return 0
-      else
-        unset_user_include_metadata "$vhost" user_includes
-        error "unable to move $int_file to $final_file"
-      fi
-    else
-      unset_user_include_metadata "$vhost" tmp_include
-      error "this include created a malformed vhost config."
+  if devpanel_run rewrite vhost config --vhost "$vhost" $reload_opt; then
+    echo
+    echo -n "Successfully added include file."
+    if [ -n "$reload" ]; then
+      echo
+    else 
+      echo " Though Apache was not reloaded, as requested."
     fi
   else
-    error "unable to write vhost metadata."
+    if [ -n "$had_a_include" -a -f "$bkp_file" ]; then
+      mv -f "$bkp_file" "$include_file"
+    else
+      save_opts_in_vhost_config "$vhost" "- vhost.user_includes"
+      rm -f "$include_file"
+    fi
+
+    echo
+    if [ -n "$reload" ]; then
+      if devpanel_run rewrite vhost config --vhost "$vhost" $reload_opt; then
+        error "failed to add include file. It created an invalid Apache config." -
+        return $?
+      else
+        error "reverted vhost config, but Apache still has problems." -
+        return $?
+      fi
+    fi
+
+    error "failed to generate a valid Apache config file" -
+    return $?
   fi
+
+  return 0
 }
diff --git a/lib/cli/sbin/cat-vhost-config b/lib/cli/sbin/cat-vhost-config
--- a/lib/cli/sbin/cat-vhost-config
+++ b/lib/cli/sbin/cat-vhost-config
@@ -38,11 +38,12 @@ devpanel_cmd__cat_vhost_config() {
   
   "$sys_dir/libexec/check-vhost-name" archive "$vhost" || exit $?
 
-  get_linux_username_from_vhost "$vhost" && \
-  linux_user="$_dp_value"
+  load_vhost_config "$vhost" || return $?
 
-  local virtwww_dir="$sys_dir/compat/apache_include/virtwww"
-  local vhost_file="$virtwww_dir/$linux_user.conf"
-
-  cat "$vhost_file"
+  if [ -f "$v__vhost__file" ]; then
+    cat "$v__vhost__file"
+  else
+    error "missing file $v__vhost__file" -
+    return $?
+  fi
 }
diff --git a/lib/cli/sbin/create-vhost b/lib/cli/sbin/create-vhost
--- a/lib/cli/sbin/create-vhost
+++ b/lib/cli/sbin/create-vhost
@@ -21,6 +21,9 @@ set_usage_msg \
     --php-version <version>   the PHP version to use on this vhost (e.g.
                               5.6, 7.1)
 
+    --no-summary              don't print the summary information after
+                              creating the vhost
+
   Creates a new vhost from the specified source.
 "
 
@@ -30,6 +33,7 @@ devpanel_cmd__create_vhost() {
 
   local name vhost from source_type title desc
   local branch app_password read_pw_stdin php_version
+  local print_summary=yes
   local -a cmd_args=()
 
   # by default let's assume the source is a file
@@ -79,6 +83,12 @@ devpanel_cmd__create_vhost() {
         read_pw_stdin=1
         shift
         ;;
+
+      --no-summary)
+        unset print_summary
+        shift
+        ;;
+
       --[A-Za-z0-9_-]*)
         error "unknown argument $name"
         ;;
@@ -147,6 +157,10 @@ devpanel_cmd__create_vhost() {
   fi
 
   if [ $st -eq 0 ]; then
+    if ! load_vhost_config "$vhost"; then
+      echo "Warning: unable to load config for the newly created vhost" 1>&2
+    fi
+
     if [ -n "$app_password" ]; then
       echo "$app_password" | devpanel_run reset app password --vhost "$vhost"
       if [ $? -ne 0 ]; then
@@ -158,7 +172,8 @@ devpanel_cmd__create_vhost() {
       devpanel_run set vhost description --vhost "$vhost" --quiet --desc "$desc"
     fi
 
-    print_vhost_summary "$vhost"
+    [ -n "$print_summary" ] && print_vhost_summary "$vhost"
+
     echo "Successfully created vhost $vhost"
   fi
 
diff --git a/lib/cli/sbin/disable-htpasswd b/lib/cli/sbin/disable-htpasswd
--- a/lib/cli/sbin/disable-htpasswd
+++ b/lib/cli/sbin/disable-htpasswd
@@ -23,20 +23,37 @@ devpanel_cmd__disable_htpasswd() {
         vhost="$2"
         shift 2
         ;;
+
+      --)
+        shift
+        break
+        ;;
+
       --help)
         usage
         ;;
-      --[A-Za-z0-9_-]*)
-        error "unknown option $name"
-        ;;
+
       *)
-        cmd_args+=( "$name" )
-        shift
+        error "unknown option $name"
         ;;
     esac
   done
 
   [ -z "$vhost" ] && error_missing_param vhost
 
-  "$sys_dir/libexec/htaccess-unlock-vhost" "${cmd_args[@]}" $vhost
+  load_vhost_config "$vhost" || return $?
+
+  if ! is_vhost_enabled "$vhost"; then
+    error "can't disable htpasswd on a vhost that is disabled" -
+    return $?
+  fi
+
+  if ! is_htpasswd_enabled_on_vhost "$vhost" ; then
+    echo "Warning: htpasswd is already disabled for vhost '$vhost'" 1>&2
+    return 0
+  fi
+
+  save_opts_in_vhost_config "$vhost" "vhost.htpasswd = no" || return $?
+
+  rewrite_vhost_apache_config "$vhost"
 }
diff --git a/lib/cli/sbin/disable-vhost b/lib/cli/sbin/disable-vhost
--- a/lib/cli/sbin/disable-vhost
+++ b/lib/cli/sbin/disable-vhost
@@ -12,7 +12,7 @@ set_usage_msg \
 devpanel_cmd__disable_vhost() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
-  local name vhost file
+  local name vhost user
   local -a cmd_args=()
 
   while [ -n "$1" ]; do
@@ -23,20 +23,56 @@ devpanel_cmd__disable_vhost() {
         vhost="$2"
         shift 2
         ;;
+
       --help)
         usage
         ;;
-      --[A-Za-z0-9_-]*)
-        error "unknown option $name"
-        ;;
-      *)
-        cmd_args+=( "$name" )
+
+      --)
         shift
+        break
+        ;;
+
+      *)
+        error "unknown option $name"
         ;;
     esac
   done
 
   [ -z "$vhost" ] && error_missing_param vhost
 
-  "$sys_dir/libexec/lock-vhost" "${cmd_args[@]}" $vhost
+  load_vhost_config "$vhost" || return $?
+
+  vhost_exists_and_is_enabled "$vhost" || return $?
+
+  user="$v__vhost__linux_user"
+
+  if "$sys_dir/libexec/ignore-quota" "$user" 8 \
+       usermod -L "$user"; then
+    echo "Locking user's password"
+  else
+    error "failed to lock user password" -
+    return $?
+  fi
+
+  if "$sys_dir/libexec/ignore-quota" "$user" 8 \
+       su -l -c "$sys_dir/bin/lock-vhost-ssh" "$user"; then
+    echo "Locked .ssh/authorized_keys"
+  else
+    error "failed to lock ssh password" -
+    return $?
+  fi
+
+  if "$sys_dir/libexec/ignore-quota" "$user" 8 \
+       su -l -c "$sys_dir/bin/lock-vhost-crontab" "$user"; then
+
+    echo "Locked crontab"
+  else
+    error "failed locking crontab" -
+    return $?
+  fi
+
+  rewrite_vhost_apache_config "$vhost" || return $?
+
+  save_opts_in_vhost_config "$vhost" "vhost.enabled = no" || return $?
 }
diff --git a/lib/cli/sbin/enable-htpasswd b/lib/cli/sbin/enable-htpasswd
--- a/lib/cli/sbin/enable-htpasswd
+++ b/lib/cli/sbin/enable-htpasswd
@@ -12,7 +12,7 @@ set_usage_msg \
 devpanel_cmd__enable_htpasswd() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
-  local name vhost file
+  local name vhost
   local -a cmd_args=()
 
   while [ -n "$1" ]; do
@@ -23,20 +23,37 @@ devpanel_cmd__enable_htpasswd() {
         vhost="$2"
         shift 2
         ;;
+
       --help)
         usage
         ;;
-      --[A-Za-z0-9_-]*)
-        error "unknown option $name"
-        ;;
-      *)
-        cmd_args+=( "$name" )
+
+      --)
         shift
+        break
+        ;;
+
+      *)
+        error "unknown option $name"
         ;;
     esac
   done
 
   [ -z "$vhost" ] && error_missing_param vhost
 
-  "$sys_dir/libexec/htaccess-lock-vhost" "${cmd_args[@]}" $vhost
+  load_vhost_config "$vhost" || return $?
+
+  if ! is_vhost_enabled "$vhost"; then
+    error "can't set htpasswd on a vhost that is disabled" -
+    return $?
+  fi
+
+  if is_htpasswd_enabled_on_vhost "$vhost" ; then
+    echo "Warning: htpasswd is already enabled for vhost '$vhost'" 1>&2
+    return 0
+  fi
+
+  save_opts_in_vhost_config "$vhost" "vhost.htpasswd = yes" || return $?
+
+  rewrite_vhost_apache_config "$vhost"
 }
diff --git a/lib/cli/sbin/enable-vhost b/lib/cli/sbin/enable-vhost
--- a/lib/cli/sbin/enable-vhost
+++ b/lib/cli/sbin/enable-vhost
@@ -12,7 +12,7 @@ set_usage_msg \
 devpanel_cmd__enable_vhost() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
-  local name vhost file
+  local name vhost
   local -a cmd_args=()
 
   while [ -n "$1" ]; do
@@ -23,20 +23,55 @@ devpanel_cmd__enable_vhost() {
         vhost="$2"
         shift 2
         ;;
+
       --help)
         usage
         ;;
-      --[A-Za-z0-9_-]*)
-        error "unknown option $name"
-        ;;
-      *)
-        cmd_args+=( "$name" )
+
+      --)
         shift
+        break
+        ;;
+
+      *)
+        error "unknown option $name"
         ;;
     esac
   done
 
   [ -z "$vhost" ] && error_missing_param vhost
 
-  "$sys_dir/libexec/unlock-vhost" "${cmd_args[@]}" $vhost
+  load_vhost_config "$vhost" || return $?
+
+  if is_vhost_enabled "$vhost"; then
+    echo "Warning: vhost is already enabled. Doing nothing..." 1>&2
+    return 0
+  fi
+
+  user="$v__vhost__linux_user"
+
+  if "$sys_dir/libexec/ignore-quota" "$user" 8 \
+      usermod -U "$user"; then
+    echo "Unlocked user's password"
+  else
+    error "failed to lock user's password" -
+    return $?
+  fi
+
+  if run_as_user "$user" "$sys_dir/bin/unlock-vhost-ssh"; then
+    echo "Unlocked .ssh/authorized_keys"
+  else
+    echo "Warning: failed to unlock ssh authorized_keys file" 1>&2
+  fi
+
+  if "$sys_dir/libexec/ignore-quota" "$user" 8 \
+     su -l -c "$sys_dir/bin/unlock-vhost-crontab" "$user"; then
+    echo "Unlocked user's crontab"
+  else
+    echo "Warning: failed to unlock crontab" 1>&2
+  fi
+
+  save_opts_in_vhost_config "$vhost" "vhost.enabled = yes" || return $?
+
+  rewrite_vhost_apache_config "$vhost"
 }
diff --git a/lib/cli/sbin/install-app b/lib/cli/sbin/install-app
--- a/lib/cli/sbin/install-app
+++ b/lib/cli/sbin/install-app
@@ -138,7 +138,7 @@ devpanel_cmd__install_app(){
 
   echo "$app_password" | devpanel_run create vhost --vhost "$vhost" --from "$app_url" \
     ${php_version:+--php-version $php_version} ${desc:+--desc "$desc"} \
-    --password-stdin
+    --password-stdin --no-summary
   if [ $? -ne 0 ]; then
     error "unable to install app" -
     return $?
@@ -151,6 +151,12 @@ devpanel_cmd__install_app(){
       return $?
     fi
   fi
+
+  if ! load_vhost_config "$vhost"; then
+    echo "Warning: unable to load config for the newly created vhost" 1>&2
+  fi
+
+  print_vhost_summary "$vhost"
 
   local vhost_url
   vhost_url=$(get_main_url_of_vhost "$vhost")
diff --git a/lib/cli/sbin/remove-domain b/lib/cli/sbin/remove-domain
--- a/lib/cli/sbin/remove-domain
+++ b/lib/cli/sbin/remove-domain
@@ -19,7 +19,8 @@ devpanel_cmd__remove_domain() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
   local name vhost default_domain base_domain
-  local -a cmd_args_ar=() vhost_args_ar=() domains_ar=()
+  local reload=yes
+  local -a domains_ar=()
 
   while [ -n "$1" ]; do
     name="$1"
@@ -37,7 +38,7 @@ devpanel_cmd__remove_domain() {
         ;;
 
       --no-reload)
-        cmd_args_ar+=( -N )
+        unset reload
         shift
         ;;
 
@@ -58,13 +59,18 @@ devpanel_cmd__remove_domain() {
 
   [ -z "${domains_ar[*]}" -o -z "$vhost" ] && usage
 
+  load_vhost_config "$vhost" || return $?
+
   if ! vhost_exists_and_is_enabled "$vhost"; then
     return 1
   fi
 
-  default_domain=$(get_vhost_default_hostname "$vhost" ) || return $?
-  base_domain=$(get_vhost_base_domain "$vhost" ) || return $?
+  default_domain="$v__vhost__server_name"
+  base_domain="$v__vhost__base_domain"
 
+  local -a opts_ar=()
+
+  local -i n_chg=0
   local _domain
   for _domain in "${domains_ar[@]}"; do
     [ -z "$_domain" ] && continue
@@ -76,23 +82,64 @@ devpanel_cmd__remove_domain() {
       return $?
     fi
 
+    if ! is_word_in_string "$_domain" "$v__vhost__domains"; then
+      echo "Warning: domain '$_domain' is not on vhost '$vhost'" 1>&2
+      continue
+    fi
+
     if [ "$_domain" == "$default_domain" ]; then
       # if the domain is the default domain, then set the base domain as the new
       # default hostname for that domain
-      vhost_args_ar=( '*' "$base_domain" "${vhost_args_ar[@]}" )
+      opts_ar+=( "vhost.server_name = $base_domain" )
     fi
 
-    if [[ ! "$_domain" == *.* ]]; then
-      # if the domain string doesn't include a dot, then include a dot in
-      # the end to identify it as a fully qualified name
-      _domain+="."
+    if [[ "$v__vhost__domains" == $_domain\ * ]]; then
+      v__vhost__domains=${v__vhost__domains#$_domain *}
+      n_chg+=1
+    elif [[ "$v__vhost__domains" == *\ $_domain\ * ]]; then
+      v__vhost__domains=${v__vhost__domains// $_domain /\ }
+      n_chg+=1
+    elif [[ "$v__vhost__domains" == *\ $_domain ]]; then
+      v__vhost__domains=${v__vhost__domains% $_domain}
+      n_chg+=1
+    else
+      echo "Warning: skipping domain '$_domain' not found on vhost $vhost" 1>&2
+      continue
     fi
 
-    vhost_args_ar+=( '-' "$_domain" )
+    echo "Removing domain $_domain..."
   done
 
-  cmd_args_ar+=( -n )
+  if [ -z "$v__vhost__domains" ]; then
+    error "Aborted. List of domains would be empty. A vhost needs at least 1 domain."
+  fi
 
-  "$sys_dir/libexec/config-vhost-names" "${cmd_args_ar[@]}" "$vhost" \
-    "${vhost_args_ar[@]}"
+  if [ ${#opts_ar[@]} -eq 0 -a $n_chg -eq 0 ]; then
+    echo "Ok. No change needed."
+    return 0
+  fi
+
+  if [ $n_chg -gt 0 ]; then
+    opts_ar+=( "vhost.domains = $v__vhost__domains" )
+  fi
+
+  if ! save_opts_in_vhost_config "$vhost" "${opts_ar[@]}"; then
+    error "unable to update vhost configuration. No domain removed." -
+    return $?
+  fi
+
+  if [ -n "$reload" ]; then
+    if ! rewrite_vhost_apache_config "$vhost"; then
+      echo "Warning: successfully removed domains, but failed to" \
+           "reload Apache" 1>&2
+    fi
+  fi
+
+  echo
+  echo -n "Successfully removed"
+  if [ $n_chg -eq 1 ]; then
+    echo " domain."
+  else
+    echo " $n_chg domains."
+  fi
 }
diff --git a/lib/cli/sbin/remove-vhost-include b/lib/cli/sbin/remove-vhost-include
--- a/lib/cli/sbin/remove-vhost-include
+++ b/lib/cli/sbin/remove-vhost-include
@@ -17,7 +17,7 @@ devpanel_cmd__remove_vhost_include() {
 
   local name vhost include_file
   local -a cmd_args_ar=()
-  local reload=1
+  local reload=1 reload_opt=--
 
   while [ -n "$1" ]; do
     name="$1"
@@ -30,7 +30,7 @@ devpanel_cmd__remove_vhost_include() {
 
       --no-reload)
         unset reload
-        cmd_args_ar+=( -N )
+        reload_opt=--no-reload
         shift
         ;;
 
@@ -51,31 +51,27 @@ devpanel_cmd__remove_vhost_include() {
 
   [ -z "$vhost" ] && usage
 
-  if ! vhost_exists "$vhost"; then
-    error "vhost '$vhost' doesn't exist." -
-    return $?
-  fi
+  load_vhost_config "$vhost" || return $?
 
-  if ! has_user_includes "$vhost"; then
+  if [ -z "$v__vhost__user_includes" -o \
+          "$v__vhost__user_includes" != yes ]; then
     echo "Warning: vhost doesn't contain custom user includes" 1>&2
     return 0
   fi
 
-  include_file=$(get_vhost_include_filename "$vhost" ) || return $?
-
-  if unset_user_include_metadata "$vhost" user_includes; then
-    rm -f "$include_file"
-    devpanel_run rewrite vhost config --vhost "$vhost" --no-restart
-    if [ -n "$reload" ]; then
-      if ! reload_or_start_apache; then
-        echo "Warnings: removed vhost includes, but Apache reload failed" 1>&2
-        return 0
-      fi
+  if save_opts_in_vhost_config "$vhost" "- vhost.user_includes"; then
+    rm -f "$v__vhost__user_include_file"
+    if devpanel_run rewrite vhost config --vhost "$vhost" $reload_opt; then
+      echo
+      echo "Successfully removed user includes for vhost '$vhost'."
+    else
+      echo
+      echo "Warning: removed include file, but failed to reload Apache" 1>&2
     fi
-
-    echo "Successfully removed custom Apache includes from vhost $vhost."
-    return 0
   else
-    error "unable to disable vhost includes"
+    error "unable to update config file." -
+    return $?
   fi
+
+  return 0
 }
diff --git a/lib/cli/sbin/set-base-hostname b/lib/cli/sbin/set-base-hostname
--- a/lib/cli/sbin/set-base-hostname
+++ b/lib/cli/sbin/set-base-hostname
@@ -12,29 +12,164 @@ set_usage_msg \
 devpanel_cmd__set_base_hostname() {
   [ $# -eq 0 -o -z "$1" ] && usage
 
-  local arg name
+  local arg name new_domain old_domain old_domain_esc
 
   while [ -n "$1" ]; do
     arg="$1"
     case "$arg" in
       --name)
         [ -z "$2" ] && error_missing_value name
-        name="$2"
+        new_domain="$2"
         shift 2
         ;;
+
       --help)
         usage
         ;;
-      --[A-Za-z0-9_-]*)
-        error "unknown option $arg"
+
+      --)
+        shift
+        break
         ;;
+
       *)
-        usage
+        error "unknown option '$arg'" -
+        return $?
         ;;
     esac
   done
 
-  [ -z "$name" ] && error_missing_param name
+  [ -z "$new_domain" ] && error_missing_param name
 
-  "$sys_dir/libexec/config-vhost-names-default" "$name"
+  if ! is_valid_domain_string "$new_domain"; then
+    error "invalid string to use as base domain name"
+  fi
+
+  if [ -n "$lamp__apache_vhosts__virtwww_domain" ]; then
+    old_domain="$lamp__apache_vhosts__virtwww_domain"
+    old_domain_esc=${old_domain//./\\.}
+  fi
+
+  if [ -n "$old_domain" -a "$old_domain" == "$new_domain" ]; then
+    echo "Warning: new domain is equal to current domain. No change needed." 1>&2
+    return 0
+  fi
+
+  if ! set_lamp_virtwww_domain "$new_domain"; then
+    error "unable to set base domain for virtual hosts" -
+    return $?
+  fi
+
+	# add the hostname to the apache main file, in case it's not configured
+	# to avoid the warning when restarting Apache
+	if egrep -qs '^[[:space:]]*ServerName' \
+        "$lamp__apache_paths__main_config_file"; then
+
+    sed -i -e "s/^ServerName .\+/ServerName $new_domain/g;" \
+      "$lamp__apache_paths__main_config_file"
+
+  else
+		sed -i -e "1 i\
+ServerName $new_domain
+;" "$lamp__apache_paths__main_config_file"
+	fi
+
+  "$sys_dir/bin/add-to-known-hosts" -a "127.0.0.1,$new_domain" localhost
+
+  if [ -n "$old_domain" ]; then
+    sed -i "s/\b$old_domain_esc\b//g;" /etc/hosts
+    sed -i "/\b$old_domain_esc\b/d; /,$old_domain_esc/d;" \
+      /etc/ssh/ssh_known_hosts
+
+    "$sys_dir/bin/update-dot-ssh-config" /etc/ssh/ssh_config \
+      remove_section "$old_domain *.$old_domain"
+  fi
+
+	"$sys_dir/bin/update-dot-ssh-config" /etc/ssh/ssh_config \
+		add_section "$new_domain *.$new_domain" "Hostname=127.0.0.1"
+
+	"$sys_dir/bin/template-tool" \
+		-o "$sys_dir/compat/apache_include/global-includes/admin-ctl.conf" \
+		   "$sys_dir/compat/apache_include/admin-ctl.conf.template"
+
+
+  local -a ex_local_vhosts_ar=( $(get_list_of_local_vhosts) )
+  local prev_base_domain new_base_domain prev_def_vh_domain
+  local -a vhost_opts_ar=() new_domains_ar=()
+
+
+  for vh in "${ex_local_vhosts_ar[@]}"; do
+    vhost_opts_ar=()
+    new_domains_ar=()
+
+    load_vhost_config "$vh" || continue
+
+    prev_base_domain=$v__vhost__base_domain
+    prev_def_vh_domain=$v__vhost__server_name
+
+    new_base_domain="$vh.$new_domain"
+    vhost_opts_ar+=( "vhost.base_domain = $new_base_domain" )
+    new_domains_ar+=( "$new_base_domain" )
+
+    if [[ "$prev_def_vh_domain" == *.$old_domain ]]; then
+      tmp_vh_domain=${prev_def_vh_domain%.$old_domain}
+      new_vh_domain="$tmp_vh_domain.$new_domain"
+
+      vhost_opts_ar+=( "vhost.server_name = $vh.$new_domain" )
+
+      if [ "$new_vh_domain" != "$new_base_domain" ]; then
+        new_domains_ar+=( "$new_vh_domain" )
+      fi
+    fi
+
+    for vh_domain in $v__vhost__domains; do
+      if [[ "$vh_domain" == *.$old_domain ]]; then
+        tmp_vh_domain=${vh_domain%.$old_domain}
+        new_vh_domain="$tmp_vh_domain.$new_domain"
+
+        if [ "$new_vh_domain" == "$new_base_domain" ]; then
+          continue
+        else
+          new_domains_ar+=( "$new_vh_domain" )
+        fi
+      elif [ "$vh_domain" == "$prev_base_domain" ]; then
+        continue
+      else
+        if ! is_word_in_string "$vh_domain" "${new_domains_ar[*]}"; then
+          new_domains_ar+=( "$vh_domain" )
+        fi
+      fi
+    done
+
+    vhost_opts_ar+=( "vhost.domains = ${new_domains_ar[*]}" )
+
+    if save_opts_in_vhost_config "$vh" "${vhost_opts_ar[@]}"; then
+      # run in a sub-shell not to overwrite vhost variables
+      ( devpanel_run rewrite vhost config --vhost "$vh" --no-restart )
+    fi
+  done
+
+  post_update_dir="$sys_dir/compat/apache_include/post-update-hostname"
+  # after changing hostname, run scripts from apps that are dependant on
+  # hostname
+  for post_run_script in "$post_update_dir/"*; do
+    [ ! -e "$post_run_script" ] && continue
+
+    if [ -f "$post_run_script" -a -x "$post_run_script" ]; then
+      "$post_run_script" "$new_domain" "$old_domain"
+      script_status=$?
+      if [ $script_status -ne 0 ]; then
+        echo "Warning: post update script $post_run_script returned $script_status" 1>&2
+        [ -t 0 ] && sleep 1
+      fi
+    fi
+  done
+
+
+  if [ ${#ex_local_vhosts_ar[@]} -gt 0 ]; then
+    reload_or_start_apache
+  fi
+
+  echo
+  echo "Successfully updated vhost base domain."
 }
diff --git a/lib/cli/sbin/set-php-version b/lib/cli/sbin/set-php-version
--- a/lib/cli/sbin/set-php-version
+++ b/lib/cli/sbin/set-php-version
@@ -54,27 +54,42 @@ devpanel_cmd__set_php_version() {
     return 1
   fi
 
+  load_vhost_config "$vhost" || return $?
+
   local vhost_user vhost_home
-  if get_linux_username_from_vhost "$vhost"; then
-    vhost_user="$_dp_value"
-  else
-    error "unable to get linux username for vhost" -
+  local php_bin php_cgi_bin phar_bin
+  local php_bin_var php_cgi_bin_var phar_bin_var
+
+  vhost_user="$v__vhost__linux_user"
+  vhost_home="$v__vhost__linux_user_home"
+
+  php_bin_var="lamp__php_paths__php_${version//./_}"
+  php_bin="${!php_bin_var}"
+  if [ -z "$php_bin" -o ! -f "$php_bin" -o ! -x "$php_bin" ]; then
+    error "unable to find PHP binary for version $version" -
     return 1
   fi
 
-  local php_bin php_cgi_bin phar_bin
+  php_cgi_bin_var="lamp__php_paths__php_cgi_${version//./_}"
+  php_cgi_bin="${!php_cgi_bin_var}"
+  if [ -z "$php_cgi_bin" -o ! -f "$php_cgi_bin" -o ! -x "$php_cgi_bin" ]; then
+    error "unable to find PHP-CGI binary for version $version" -
+    return 1
+  fi
+
+  phar_bin_var="lamp__php_paths__phar_${version//./_}"
+  phar_bin="${!phar_bin_var}"
 
   if [ "$version" == default ]; then
-    local php_curr_ver
-    php_curr_ver=$(get_php_version_from_vhost "$vhost" 2>/dev/null )
-    if [ $? -ne 0 ]; then
+    if [ -n "$v__php__version" -a \
+            "$v__php_version" == "$lamp__php__default_version" ]; then
       echo "Ok, no action. This vhost is already using the default."
       return 0
     fi
 
     run_as_user "$vhost_user" "rm -f ~/bin/php ~/bin/php-cgi ~/bin/phar"
     if [ $? -eq 0 ]; then
-      rm_php_version_metadata_for_vhost "$vhost"
+      save_opts_in_vhost_config "$vhost" "- php.version"
       if [ $? -ne 0 ]; then
         echo "Warning: unable to remove PHP metadata" 1>&2
       fi
@@ -87,22 +102,6 @@ devpanel_cmd__set_php_version() {
     fi
   fi
 
-  php_bin=$(deref_os_prop "$sys_dir" pathnames/bin/php-$version 2>/dev/null)
-  if [ $? -ne 0 ]; then
-    error "unable to find PHP binary for version $version" -
-    return 1
-  fi
-
-  php_cgi_bin=$(deref_os_prop "$sys_dir" pathnames/bin/php-cgi-$version \
-                  2>/dev/null )
-  if [ $? -ne 0 ]; then
-    error "unable to find PHP-CGI binary for version $version" -
-    return 1
-  fi
-
-  phar_bin=$(deref_os_prop "$sys_dir" pathnames/bin/phar-$version \
-              2>/dev/null )
-
   run_as_user "$vhost_user" "
                ln -sf $php_cgi_bin ~/bin/php-cgi; ex=\$? ;          \
                ln -sf $php_bin ~/bin/php ;                          \
@@ -110,7 +109,7 @@ devpanel_cmd__set_php_version() {
               exit \$ex"
   if [ $? -eq 0 ]; then
     # set metadata for vhost
-    if set_php_version_metadata_for_vhost "$vhost" "$version"; then
+    if save_opts_in_vhost_config "$vhost" "php.version = $version"; then
       echo "Successfully set vhost PHP version to $version."
     else
       echo "Warning: PHP version set, but failed to update vhost metadata." 1>&2
diff --git a/lib/cli/sbin/set-platform-version b/lib/cli/sbin/set-platform-version
--- a/lib/cli/sbin/set-platform-version
+++ b/lib/cli/sbin/set-platform-version
@@ -22,8 +22,13 @@ devpanel_cmd__set_platform_version() {
     case "$name" in
       --version)
         [ -z "$2" ] && error_missing_value "$name"
-        # validation is done on the function
-        version="$2"
+        if [[ "$2" =~ ^[1-9]$ ]]; then
+          version="$2"
+        else
+          echo "$FUNCNAME(): invalid version string specified (must be [1-9])" 1>&2
+          return 1
+        fi
+
         shift 2
         ;;
 
@@ -44,14 +49,11 @@ devpanel_cmd__set_platform_version() {
 
   [ -z "$version" ] && error_missing_param version
 
-  set_platform_version "$version"
-  local st=$?
-
-  if [ $st -eq 0 ]; then
+  if save_opts_in_devpanel_config "platform.version = $version"; then
     echo "Successfully set the platform version to $version."
   else
     echo "Failed to set platform version." 1>&2
-    return $st
+    return 1
   fi
 
 }
diff --git a/lib/cli/sbin/update b/lib/cli/sbin/update
--- a/lib/cli/sbin/update
+++ b/lib/cli/sbin/update
@@ -7,8 +7,43 @@ set_usage_msg \
 "
 
 devpanel_cmd__update() {
-  # first update the system scripts
-  "$sys_dir/libexec/update-scripts" || return $?
+  local arg update_scripts=yes
+
+  while [ -n "$1" ]; do
+    arg="$1"
+    case "$arg" in
+      --skip-scripts-update)
+        unset update_scripts
+        shift
+        ;;
+
+      *)
+        error "unknown option '$arg'" -
+        shift
+        return 1
+        ;;
+    esac
+  done
+
+  # first load state data, so that we have a minimal information on system
+  # state to update the scripts and also run the migration scripts
+  if ! load_state_data ; then
+    error "missing state data. Unable to do any update." -
+    return 1
+  fi
+        
+  if [ -n "$update_scripts" ]; then
+    # first update the system scripts
+    "$sys_dir/libexec/update-scripts" || return $?
+
+    # after updating the scripts, re-run the command to run with any new
+    # update on the update script itself
+    "$__self_bin" update --skip-scripts-update
+
+    return $?
+  fi
+
+  devpanel_run run migrations --yes || return $?
 
   # then update the system packages
   "$sys_dir/libexec/package-mgr" update-all -y
diff --git a/libexec/apply-ssl-config b/libexec/apply-ssl-config
--- a/libexec/apply-ssl-config
+++ b/libexec/apply-ssl-config
@@ -92,15 +92,19 @@ lib_file="$we_base_dir/lib/functions"
 if ! source "$lib_file"; then
   error "unable to source lib file $lib_file"
 fi
+load_devpanel_config || exit $?
 
 if ! "$curr_dir/check-vhost-name" archive "$vhost"; then
   error "Invalid vhost name"
 fi
 
+if ! load_vhost_config "$vhost"; then
+  error "unable to load vhost configuration."
+fi
+
 ssl_cert_dir=$(get_ssl_cert_dir ) || return $?
 ssl_key_dir=$(get_ssl_key_dir   ) || return $?
 
-ssl_template_basename=$( get_ssl_template_basename ) || return $?
 
 umask 077
 
@@ -151,16 +155,13 @@ if [ -n "$ca_bundle_file" ]; then
   fi
 fi
 
-vhost_prefix="apache_vhost:3"
-vhost_internal_name="default_ssl"
-
-cert_link="$ssl_cert_dir/$vhost.$vhost_internal_name.crt"
-key_link="$ssl_key_dir/$vhost.$vhost_internal_name.key"
+cert_link="$ssl_cert_dir/cert.crt"
+key_link="$ssl_key_dir/private-key.key"
 
 ln -sf "$cert_file_full_path" "$cert_link"
 ln -sf "$key_file_full_path" "$key_link"
 
-ca_bundle_link="$ssl_cert_dir/CA-bundle.$vhost.$vhost_internal_name.crt"
+ca_bundle_link="$ssl_cert_dir/ca-bundle.crt"
 if [ -n "$ca_bundle_file" ]; then
   ln -sf "$ca_bundle_file_full_path" "$ca_bundle_link"
 else
@@ -170,30 +171,13 @@ else
   fi
 fi
 
-metadata_op=""
-metadata_op+="set $vhost_prefix $vhost_internal_name"$'\n'
-metadata_op+="set apache_vhost:_:name:$vhost_internal_name 3"$'\n'
-metadata_op+="set $vhost_prefix:_:replicate devpanel_main"$'\n'
-metadata_op+="set $vhost_prefix:_:template $ssl_template_basename"$'\n'
-
-if [ -n "$ip_addr" ]; then
-  metadata_op+="set $vhost_prefix:_:IP $ip_addr"$'\n'
-fi
-
-if [ -n "$ca_bundle_file" ]; then
-  metadata_op+="set $vhost_prefix:param:2:SSLCACertificateFile $ca_bundle_link"$'\n'
-fi
-
-echo "$metadata_op" | "$curr_dir/apache-metadata-handler" "$vhost"
-if [ $? -ne 0 ]; then
-  error "failed to set vhost metadata links"
-fi
+save_opts_in_vhost_config "$vhost" "ssl.enabled = yes"
 
 if is_https_redirect_enabled_by_default ; then
   set_https_redirect_metadata "$vhost"
 fi
 
-if ! "$curr_dir/config-vhost-apache" "$vhost"; then
+if ! rewrite_vhost_apache_config "$vhost"; then
   echo
   error "failed to apply SSL configuration for vhost $vhost"
 fi
diff --git a/libexec/create-virtwww b/libexec/create-virtwww
--- a/libexec/create-virtwww
+++ b/libexec/create-virtwww
@@ -2,11 +2,14 @@
 # Options:
 #   -n - do not activate apache vhost, use the 'Vhost-simple-dummy' macro
 
-[ "$1" == '--help' ] && usage
+function usage() {
+  echo "Usage: ${0##*/} <vhost> [domain.tld,alias[,...]]"
+	exit 1
+}
 
-dummy=""
 
-unset custom_template
+[ -z "$1" -o "$1" == '--help' ] && usage
+
 while getopts "n" OPTOPT
 do
   case "$OPTOPT" in
@@ -14,282 +17,158 @@ do
     *) exit 1;;
   esac
 done
-shift `expr $OPTIND - 1`
+[ $OPTIND -gt 1 ] && shift `expr $OPTIND - 1`
 
-progname=$(basename "$0")
-dir=$(dirname "$0")
+[ -z "$1" ] && usage
 
-we_base=`readlink -e "$dir/.."`
-dir_bin="$we_base/bin"
+self_bin=`readlink -e "$0"`
+if [ $? -ne 0 ]; then
+  echo "Error: unable to get self path" 1>&2
+  exit 1
+fi
 
-apache_metadata_bin="$we_base/libexec/apache-metadata-handler"
+self_dir="${self_bin%/*}"
+sys_dir="${self_dir%/*}"
 
-pathnames="$dir/../config/os/pathnames"
-#macro_file="$dir/../config/names/apache-macro"
-
-lib_file="$we_base/lib/functions"
+lib_file="$sys_dir/lib/functions"
 if ! source "$lib_file"; then
   echo "Error: unable to source lib file '$lib_file'" 1>&2
   exit 1
 fi
 
-chcgi=$(get_path_of_chcgi ) || exit 1
-edquota=$(get_path_of_edquota ) || exit 1
+load_devpanel_config || exit $?
 
-VIRTWWW_CFGDIR=$(get_apache_virtwww_config_dir ) || exit $?
-VIRTWWW_LOGDIR=$(get_apache_virtwww_log_dir ) || exit $?
-
-apache_group=$(get_apache_exec_group_name ) || exit 1
-WEBSITES_HOME=$(get_vhosts_homedir ) || exit 1
-
-server_base_domain=$(get_server_base_domain) || exit $?
-
-template_file="$we_base/config/packages/apache_vhost/_:template"
-if [ -f "$template_file" ]; then
-  assign_deref_contents_or_exit apache_vhost_template "$template_file"
-else
-  apache_vhost_template=$(get_apache_vhost_template ) || exit $?
-fi
-
-linuxuser_vhost_dir=$(get_linuxuser_vhost_dir)
-
-passgen="$dir_bin/genpass"
-
-ADDON_GROUPS=
-ADDON_GROUPS_FILE="$dir/../config/os/names/groups"
-
-if [ -s "$ADDON_GROUPS_FILE" ]
-then
-  ADDON_GROUPS=`paste -sd, <"$ADDON_GROUPS_FILE"`
-fi
-MYSQL_LOCAL=yes
-
-
-function usage() {
-    cat << EOF
-Usage: $progname [[account_name_base] [domain.tld[,alias[,...]]]]
-
-EOF
-    exit 1
-}
-
-function check_domain_name() {
-    local DOMAIN_NAMES IFS
-    DOMAIN_NAMES="$*"
-    IFS=', '
-    for name in $DOMAIN_NAMES ; do
-        result=$(echo "$name" | tr -d '[:alnum:].-')
-        if [ -n "$result" ]; then
-          echo "$FUNCNAME(): '$name' contains invalid characters '$result'"
-          return 1
-        fi
-    done
-    return 0
-}
-
-unset ACCOUNT_NAME
+unset domains_list_raw domains_list domains_txt
 vhost="$1"
-DOMAIN_NAMES="$2"
+[ -n "$2" ] && domains_list_raw="$2"
 
-"$we_base/libexec/check-vhost-name" restore "$vhost" || exit $?
+"$sys_dir/libexec/check-vhost-name" restore "$vhost" || exit $?
 
-if [ -n "$DOMAIN_NAMES" ] && ! check_domain_name "$DOMAIN_NAMES"; then
-  exit 1
+base_domain="$vhost.$lamp__apache_vhosts__virtwww_domain"
+domains_txt="$base_domain"
+
+if [ -n "$domains_list_raw" ]; then
+  domains_list=${domains_list_raw//,/ }
+  for domain in $domains_list; do
+    if ! is_valid_domain_string "$domain"; then
+      error "invalid domain string '$domain'"
+    elif curr_vhost_with_domain=$(get_vhost_with_hostname "$domain"); then
+      error "domain '$domain' is already on vhost '$curr_vhost_with_domain'"
+    fi
+
+    if [ -n "$domains_txt" ]; then
+      if ! in_array "$domain" $domains_txt; then
+        domains_txt+=" $domain"
+      fi
+    else
+      domains_txt="$domain"
+    fi
+  done
 fi
 
-generate_linux_username_for_vhost "$vhost" && ACCOUNT_NAME="$_dp_value"
+generate_linux_username_for_vhost "$vhost" && web_user="$_dp_value"
 if [ $? -ne 0 ]; then
   error "unable to generate linux username for vhost"
 fi
 
-DB_ACCOUNT_NAME="b_$ACCOUNT_NAME"
-VHOST_HOME="$WEBSITES_HOME/$ACCOUNT_NAME"
-VHOST_DOC_ROOT="$VHOST_HOME/public_html/$vhost"
-
-# stack stuff
-config_base_dir="$we_base/config/vhosts"
-config_dir="$config_base_dir/$vhost"
-vhost_cache_dir="$we_base/var/cache/vhost/$vhost"
-if [ ! -e "$config_base_dir" ] && \
-  ! mkdir -m 755 "$config_base_dir"; then
-  error "unable to create directory '$config_base_dir'"
-fi
-# /stack stuff
-
-echo "System account: $ACCOUNT_NAME"
-
-echo '---[ creating new virtual host ]---'
-
 # apache vhost
-  # create vhost group
-echo -n "+ checking for '$ACCOUNT_NAME' group ... "
-if grep -E "^$ACCOUNT_NAME:" /etc/group &>/dev/null; then
-    echo 'found'
-else
-    echo 'not found'
-    echo -n "+ creating '$ACCOUNT_NAME' group ... "
-    if ! groupadd "$ACCOUNT_NAME" ; then
-        echo
-        echo 'Aborting'
-        exit 2
-    fi
-    echo 'done'
+# create vhost group
+if ! getent group "$web_user"; then
+  if groupadd "$web_user"; then
+    echo "Created group: $web_user"
+  else
+    error "failed to create group '$web_user'"
+  fi
 fi
 
 # create linux user for vhost
-echo -n "+ checking for '$ACCOUNT_NAME' account ... "
-if [ x$(id -un "$ACCOUNT_NAME" 2>/dev/null) == "x$ACCOUNT_NAME" ]; then
-    echo 'found'
-    echo -n "+ checking primary group of '$ACCOUNT_NAME' account ... "
-    if [ x$(id -gn "$ACCOUNT_NAME" 2>/dev/null) != x"$apache_group" ]; then
-        echo 'failed'
-        echo
-        echo "Error: although '$ACCOUNT_NAME' account exists, it's primary group isn't '$apache_group'"
-        echo 'Aborting'
-        exit 2
-    fi
-    echo "ok, '$apache_group'"
-else
-    echo 'not found'
-    echo -n "+ creating '$ACCOUNT_NAME' account ... "
-    if ! useradd -g "$apache_group" -G "$ACCOUNT_NAME${ADDON_GROUPS:+,$ADDON_GROUPS}" \
-        -m -d "$VHOST_HOME" "$ACCOUNT_NAME"; then
-        echo
-        echo 'Aborting'
-        exit 2
-    fi
-    echo 'done'
+vhost_home="$lamp__apache_paths__virtwww_homedir/$web_user"
+doc_root="$vhost_home/public_html/$vhost"
+
+if ! getent passwd "$web_user"; then
+  if useradd -m -d "$vhost_home" -g "$lamp__apache__exec_group" \
+     -G "$web_user" "$web_user"; then
+    echo "Created user: $web_user"
+  else
+    error "failed to create web user '$web_user'"
+  fi
 fi
+
+ln -s "$vhost" "$lamp__paths__user_vhost_map/$web_user"
 # /linux user
 
-# stack stuff: chown stuff dir to just created user
+config_dir="$lamp__paths__vhosts_config_dir/$vhost"
 if ! mkdir -m 750 "$config_dir"; then
-  echo "Error: unable to create directory '$config_dir'" 1>&2
-  exit 1
+  error "unable to create directory '$config_dir'"
 fi
 
-if ! chown "root":"$ACCOUNT_NAME" "$config_dir"; then
-  echo "Error: unable to chown dir '$config_dir' to user '$ACCOUNT_NAME'" 1>&2
-  exit 1
+if ! mkdir -m 750 "$config_dir/apache" "$config_dir/ssl"; then
+  error "unable to create auxiliary dirs"
 fi
 
+touch "$config_dir/config.ini"
+chmod 640 "$config_dir/config.ini"
+chgrp -R "$web_user" "$config_dir"
+
+vhost_cache_dir="$sys_dir/var/cache/vhost/$vhost"
 mkdir -m 2750 $vhost_cache_dir
-chown root:$ACCOUNT_NAME $vhost_cache_dir
-
-set_vhost_base_domain      "$vhost" || exit $?
-
-# /stack stuff
-
-# apache vhost: create the basic directory structure
-echo -n '+ configuring home directory for virtual host ... '
-chgrp $apache_group "$VHOST_HOME" || exit 2
-su - -c "
-set -e
-chmod 0710 \"$VHOST_HOME\"
-mkdir -m 0711 ~/.webenabled ~/.webenabled/private
-# start of PHP hack (added by (GM) on 20050923)
-mkdir -p \"$VHOST_HOME/bin\"
-chmod 0700 \"$VHOST_HOME/bin\"
-# end of PHP hack
-mkdir -m 0755 -p \"$VHOST_HOME/public_html/$vhost\"
-mkdir -p \"$VHOST_HOME/public_html/gen\"
-mkdir -m 711 -p \"$VHOST_HOME/public_html/gen/archive\"
-chmod 0755 \"$VHOST_HOME/public_html/gen\"
-chmod 0711 \"$VHOST_HOME/public_html\"
-test -h \"$VHOST_HOME/logs\" && rm \"$VHOST_HOME/logs\"
-ln -s \"$VIRTWWW_LOGDIR/$ACCOUNT_NAME\" \"$VHOST_HOME/logs\"
-
-[ ! -d ~/.ssh ] && mkdir -m 700 ~/.ssh
-echo 'Host *
-  UserKnownHostsFile /dev/null
-  StrictHostKeyChecking no' >~/.ssh/config
-
-$we_base/bin/gen-vhost-ssh-priv-key -o
-
-mkdir -m 700 ~/.devpanel
-" -s /bin/bash "$ACCOUNT_NAME"
-if [ "$?" -eq 0 ]; then
-    echo 'done'
-else
-    echo 'failed'
-fi
-# // apache vhost
-
-# Fri May 20 2005 10:22 AM (fen@civicactions.com): added this section
-echo -n '+ setting up .php directory ... '
-su - -c "
-set -e
-test ! -d \"$VHOST_HOME/.php\" && mkdir \"$VHOST_HOME/.php\"
-chmod 0700 \"$VHOST_HOME/.php\"
-echo '# memory_limit = 24M;' >> \"$VHOST_HOME/.php/php.ini\"
-chmod 0600 \"$VHOST_HOME/.php/php.ini\"
-set +e
-" -s /bin/bash "$ACCOUNT_NAME"
-if [ "$?" -eq 0 ]; then
-    echo 'done'
-else
-    echo 'failed'
-fi
+chown root:$web_user $vhost_cache_dir
 
 # apache log dir setup
-echo -n '+ configuring httpd log directory for virtual host ... '
-set -e
-mkdir -p -m 0750 "$VIRTWWW_LOGDIR/$ACCOUNT_NAME"
-chown "root:$ACCOUNT_NAME" "$VIRTWWW_LOGDIR/$ACCOUNT_NAME"
-touch "$VIRTWWW_LOGDIR/$ACCOUNT_NAME/"{access,error}_log
-chmod 0644 "$VIRTWWW_LOGDIR/$ACCOUNT_NAME/"{access,error}_log
-touch "$VIRTWWW_LOGDIR/$ACCOUNT_NAME/$vhost-"{access,error}_log
-chmod 0644 "$VIRTWWW_LOGDIR/$ACCOUNT_NAME/$vhost-"{access,error}_log
-set +e
-echo 'done'
+vhost_log_dir="$lamp__apache_paths__vhost_logs_dir/$web_user"
+mkdir -p -m 0750 "$vhost_log_dir"
+touch "$vhost_log_dir/"{access,error}_log
+touch "$vhost_log_dir/$vhost-"{access,error}_log
+chmod 0640 "$vhost_log_dir/"{access,error}_log
+chmod 0640 "$vhost_log_dir/$vhost-"{access,error}_log
+chgrp -R "$web_user" "$vhost_log_dir"
 # // apache log dir setup
 
 # stack stuff
-echo '+ enabling personal CGIs:'
-"$chcgi" "$ACCOUNT_NAME" +0
+"$sys_dir/compat/suexec/chcgi" "$web_user" +0
+"$sys_dir/compat/suexec/chcgi" "$web_user" +2
+"$sys_dir/compat/suexec/chcgi" "$web_user" +7
 
-echo -n '+ setting default quotas (using w_ as a template) ... '
-if "$edquota" -p w_ "$ACCOUNT_NAME"; then
-    echo 'done'
+hash edquota &>/dev/null && edquota -p w_ "$web_user"
+# /stack stuff
+
+# apache vhost: create the basic directory structure
+chgrp -- $lamp__apache__group "$vhost_home"
+su - -c "
+chmod 0710 \"$vhost_home\"
+mkdir -m 0711 ~/.webenabled ~/.webenabled/private
+mkdir -p \"$vhost_home/bin\"
+chmod 0700 \"$vhost_home/bin\"
+mkdir -m 0755 -p \"$vhost_home/public_html/$vhost\"
+mkdir -p \"$vhost_home/public_html/gen\"
+mkdir -m 711 -p \"$vhost_home/public_html/gen/archive\"
+chmod 0755 \"$vhost_home/public_html/gen\"
+chmod 0711 \"$vhost_home/public_html\"
+rm -f \"$vhost_home/logs\"
+ln -s \"$vhost_log_dir\" \"$vhost_home/logs\"
+
+[ ! -d ~/.ssh ] && mkdir -m 700 ~/.ssh
+touch ~/.ssh/authorized_keys
+chmod 600 ~/.ssh/authorized_keys
+
+$sys_dir/bin/gen-vhost-ssh-priv-key -o
+
+mkdir -m 700 ~/.devpanel
+" -s /bin/bash "$web_user"
+# // apache vhost
+
+declare -a vhost_opts_ar=(
+  "vhost.base_domain = $base_domain"     \
+  "vhost.domains = $domains_txt"         \
+  "vhost.document_root = $doc_root"      \
+  "vhost.linux_user = $web_user"         \
+  "vhost.enabled = yes"                  \
+  "vhost.server_name = $base_domain"
+)
+
+save_opts_in_vhost_config "$vhost" "${vhost_opts_ar[@]}"
+if [ $? -eq 0 ]; then
+  echo "Successfully created vhost $vhost."
+else
+  error "failed to save config for '$vhost'"
 fi
-
-vhost_prefix_f="$config_dir/apache_vhost"
-metadata_str="
-set $vhost_prefix_f:_:linux_user $ACCOUNT_NAME
-set $vhost_prefix_f:_:document_root $VHOST_DOC_ROOT
-set $vhost_prefix_f:0 devpanel_main
-set $vhost_prefix_f:_:name:devpanel_main 0
-set $vhost_prefix_f:0:_:template_ref names/apache_vhost_template
-set $vhost_prefix_f:1 devpanel_tools
-set $vhost_prefix_f:_:name:devpanel_tools 1
-set $vhost_prefix_f:1:_:template_ref names/tools_vhost_template
-"
-
-echo "$metadata_str" | "$apache_metadata_bin" -q "$vhost" || exit $?
-
-ln -s "$vhost" "$linuxuser_vhost_dir/$ACCOUNT_NAME"
-
-echo '---[ end of creating new virtual host ]---'
-echo
-echo "Don't forget to set password for '$ACCOUNT_NAME' :)"
-echo "Bye"
-# //stack stuff
-
-# apache: add default domain to apache
-count=0
-for domain in $DOMAIN_NAMES; do
-  if [ $count -eq 0 ]; then
-    "$dir/config-vhost-names" "$vhost" '*' "$domain"
-    if [ $? -ne 0 ]; then
-      error "unable to set the ServerName for vhost $vhost"
-    fi
-  else
-    "$dir/config-vhost-names" "$vhost" '+' "$domain"
-    if [ $? -ne 0 ]; then
-      error "unable to add domain $domain to vhost $vhost"
-    fi
-  fi 
-  count=$(( $count + 1 ))
-done 
-
-exit 0
diff --git a/libexec/disable-ssl-config b/libexec/disable-ssl-config
--- a/libexec/disable-ssl-config
+++ b/libexec/disable-ssl-config
@@ -28,44 +28,27 @@ if ! source "$aux_lib"; then
   echo "Error: unable to import functions from $aux_lib" 1>&2
   exit 1
 fi
+load_devpanel_config || exit $?
 
 if ! "$sys_dir/libexec/check-vhost-name" name-only "$vhost"; then
   exit 1
 fi
 
-vhost_metadata_dir="$sys_dir/config/vhosts/$vhost"
-vhost_internal_name="default_ssl"
+load_vhost_config "$vhost" || exit $?
 
-vhost_number_key="apache_vhost:_:name:$vhost_internal_name"
-vhost_int_number=$(get_metadata_value "$vhost_metadata_dir" $vhost_number_key)
-if [ -z "$vhost_int_number" ]; then
-  echo "Warning: vhost doesn't have SSL configured." 1>&2
+if ! is_ssl_enabled_on_vhost "$vhost"; then
+  echo "Warning: SSL is not enabled on vhost $vhost" 1>&2
   exit 0
 fi
 
-if ! [[ "$vhost_int_number" =~ ^[0-9]+$ ]]; then
-  error "invalid value on vhost number: $vhost_int_number"
+if ! save_opts_in_vhost_config "$vhost" "ssl.enabled = no"; then
+  error "unable to update config file for vhost $vhost"
 fi
 
-key_prefix="apache_vhost:$vhost_int_number"
-
-metadata_op_str=""
-metadata_op_str+="rm $key_prefix"$'\n'
-metadata_op_str+="rm $vhost_number_key"$'\n'
-metadata_op_str+="rm $key_prefix:_:replicate"$'\n'
-metadata_op_str+="rm $key_prefix:_:template"$'\n'
-metadata_op_str+="rm $key_prefix:param:2:SSLCACertificateFile"$'\n'
-metadata_op_str+="rm $key_prefix:_:IP"$'\n'
-
-"$sys_dir/libexec/apache-metadata-handler" "$vhost" <<< "$metadata_op_str"
-if [ $? -eq 0 ]; then
-  "$sys_dir/libexec/config-vhost-apache" "$vhost"
-  if [ $? -eq 0 ]; then
-    echo "Successfully disabled SSL configuration for vhost $vhost"
-  else
-    echo "Warning: disabled SSL configuration, but failed to restart Apache" 1>&2
-  fi
+if devpanel rewrite vhost config --vhost "$vhost"; then
+  echo "Successfully disabled SSL configuration for vhost $vhost"
   exit 0
 else
-  error "unable to disable SSL configuration for vhost $vhost"
+  echo "Warning: disabled SSL configuration, but failed to reload Apache" 1>&2
+  exit 1
 fi
diff --git a/libexec/lets-encrypt-wrapper b/libexec/lets-encrypt-wrapper
--- a/libexec/lets-encrypt-wrapper
+++ b/libexec/lets-encrypt-wrapper
@@ -55,15 +55,17 @@ Usage: ${0##*/} $op [opts] <vhost>
 disable_lets_encrypt_for_vhost() {
   local vhost="$1"
 
-	echo "rm apache_vhost:_:config:lets_encrypt" | \
-    "$sys_dir/libexec/apache-metadata-handler" -q "$vhost"
+  save_opts_in_vhost_config "$vhost" \
+    "- ssl.enabled" \
+    "- ssl.type"
 }
 
 set_lets_encrypt_metadata_for_vhost() {
   local vhost="$1"
 
-  echo "set apache_vhost:_:config:lets_encrypt yes" | \
-    "$sys_dir/libexec/apache-metadata-handler" -q "$vhost"
+  save_opts_in_vhost_config "$vhost" \
+    "ssl.enabled = yes" \
+    "ssl.type = lets-encrypt"
 }
 
 cleanup() {
@@ -91,6 +93,7 @@ if ! . "$lib_f"; then
   echo "Error: unable to import $lib_f" 1>&2
   exit 1
 fi
+load_devpanel_config || exit $?
 
 acme_bin="$sys_dir/bin/packages/acme.sh/acme.sh"
 if [ ! -f "$acme_bin" -a -x "$acme_bin" ]; then
@@ -115,20 +118,20 @@ case "$op" in
       exit 1
     fi
 
+    if ! load_vhost_config "$vhost"; then
+      error "unable to load vhost configuration."
+    fi
+
     if is_ssl_enabled_on_vhost "$vhost"; then
       errmsg="SSL is already enabled on this vhost."
       errmsg+=" Please disable it first."
       error "$errmsg"
     fi
 
-		get_linux_username_from_vhost "$vhost" && linux_user="$_dp_value"
-		if [ $? -ne 0 ]; then
-			error "unable to get the linux username from vhost $vhost"
-		fi
+    linux_user="$v__vhost__linux_user"
+    server_base_domain="$lamp__apache_vhosts__virtwww_domain"
 
-    server_base_domain=$(get_server_base_domain) || exit 1
-
-    certs_dir="$sys_dir/config/vhosts/$vhost/lets-encrypt"
+    certs_dir="$v__vhost__ssl_dir/lets-encrypt"
     if [ -d "$certs_dir" ]; then
       chmod 700 "$certs_dir"
     else
@@ -139,19 +142,14 @@ case "$op" in
 
     acme_args+=( --home "$certs_dir" --renew-hook "$self_bin post-renew" )
 
-    public_dir=$(eval echo -n \~$linux_user/public_html/$vhost)
+    public_dir="$v__vhost__document_root"
     if [ ! -d "$public_dir" ]; then
       error "public directory not found: $public_dir"
     fi
 
-    tmp_domains=$(get_hostnames_from_vhost "$vhost")
-    if [ $? -ne 0 ]; then
-      error "unable to get domains from vhost $vhost"
-    fi
-
     declare -a domain_args=()
     unset first_domain
-    for tmp_domain in $tmp_domains; do
+    for tmp_domain in $v__vhost__domains; do
       if [[ "$tmp_domain" == *.$server_base_domain ]]; then
         continue
       else
@@ -223,7 +221,8 @@ case "$op" in
   cron)
     for vhost in $(get_list_of_vhosts); do
       if is_lets_encrypt_enabled_for_vhost "$vhost"; then
-        le_dir="$sys_dir/config/vhosts/$vhost/lets-encrypt"
+        load_vhost_config "$vhost" || continue
+        le_dir="$v__vhost__ssl_dir/lets-encrypt"
         if [ -d "$le_dir" ]; then
           acme.sh --home "$le_dir" --cron
         fi
@@ -259,12 +258,16 @@ case "$op" in
       exit 1
     fi
 
+    if ! load_vhost_config "$vhost"; then
+      error "unable to load vhost configuration."
+    fi
+
     if ! is_lets_encrypt_enabled_for_vhost "$vhost"; then
       echo "Warning: Let's Encrypt is not enabled for this vhost." 1>&2
       exit 0
     fi
 
-    le_dir="$sys_dir/config/vhosts/$vhost/lets-encrypt"
+    le_dir="$v__apache_conf__ssl_dir/lets-encrypt"
 
     acme.sh --home "$le_dir" --cron ${force:+--force} \
       ${domain:+ -d "$domain"}
@@ -272,11 +275,7 @@ case "$op" in
     ;;
 
   post-renew)
-    apache_service=$(get_apache_service_name ) || exit $?
-
-    services_bin="$sys_dir/libexec/system-services"
-
-    $services_bin $apache_service reload
+    reload_or_start_apache
     ;;
 
   disable)
diff --git a/libexec/remove-vhost b/libexec/remove-vhost
--- a/libexec/remove-vhost
+++ b/libexec/remove-vhost
@@ -32,7 +32,7 @@ run()
 revert_disable_vhost() {
   echo "Re-enabling vhost..."
 
-  "$dir/config-vhost-apache" "$vhost"
+  "$dir/rewrite-vhost-config" "$vhost"
   if [ $? -eq 0 ]; then
     echo "Successfully re-enabled vhost $vhost"
   fi
@@ -53,8 +53,12 @@ done
 [ $OPTIND -gt 1 ] && shift `expr $OPTIND - 1`
 
 self_bin=$(readlink -e "$0")
-dir=`dirname "$self_bin"`
-sys_dir=$(readlink -e "$dir/..")
+if [ $? -ne 0 ]; then
+  echo "Error: unable to get self path" 1>&2
+  exit 1
+fi
+dir=${self_bin%/*}
+sys_dir=${dir%/*}
 
 vhost="$1"
 "$dir/check-vhost-name" archive "$vhost" || exit 1
@@ -69,16 +73,13 @@ if ! source "$lib_file"; then
   echo "Error: unable to source lib file $lib_file" 1>&2
   exit 1
 fi
+load_devpanel_config || exit $?
 
-sys_data_dir=$(get_devpanel_datadir ) || exit 1
+load_vhost_config "$vhost" || exit $?
 
-apache_base_log_dir=$(get_apache_virtwww_log_dir ) || exit 1
+apache_base_log_dir="$lamp__apache_paths__vhost_logs_dir"
 
-get_linux_username_from_vhost "$vhost" && \
-user_web="$_dp_value"
-if [ $? -ne 0 ]; then
-  error "unable to get the linux username from vhost $vhost"
-fi
+user_web="$v__vhost__linux_user"
 user_db="b_${user_web#w_}"
 
 date_ts=`date  +'%b-%d-%Y-%Hh%Mmin'`
@@ -86,13 +87,13 @@ if [ $? -ne 0 -o -z "$date_ts" ]; then
   error "unable to get current date"
 fi
 
-vhost_config_dir="$sys_dir/config/vhosts/$vhost"
+vhost_config_dir="$v__vhost__config_dir"
 vhost_cache_dir="$sys_dir/var/cache/vhost/$vhost"
-archived_files_dir="$sys_data_dir/vhost_archives/$vhost"
+archived_files_dir="$v__vhost__archives_dir"
 apache_log_dir="$apache_base_log_dir/$user_web"
-removed_vhosts_dir="$sys_data_dir/removed_vhosts"
+removed_vhosts_dir="$conf__paths__data_dir/removed_vhosts"
 
-"$dir/config-vhost-apache" -D "$vhost" || exit 1
+"$dir/rewrite-vhost-config" -D "$vhost" || exit 1
 trap 'revert_disable_vhost' EXIT
 
 # if $archive_to not equal "-" then archive it before removing
@@ -159,8 +160,8 @@ if [ -d "$archived_files_dir" ]; then
   fi
 fi
 
-linuxuser_vhost_dir=$(get_linuxuser_vhost_dir)
-rm -f "$linuxuser_vhost_dir/$user_web"
+rm -f "$v__vhost__config_link"
+rm -f "$lamp__paths__user_vhost_map/$user_web"
 
 echo "Removing cron for $user_web"
 run crontab -u "$user_web" -r
diff --git a/libexec/store-ssl-files b/libexec/store-ssl-files
--- a/libexec/store-ssl-files
+++ b/libexec/store-ssl-files
@@ -217,9 +217,14 @@ lib_file="$we_base_dir/lib/functions"
 if ! source "$lib_file"; then
   error "unable to source lib file $lib_file"
 fi
+load_devpanel_config || exit $?
 
 if ! "$curr_dir/check-vhost-name" archive "$vhost"; then
   error "Invalid vhost name"
+fi
+
+if ! load_vhost_config "$vhost"; then
+  error "unable to load vhost configuration."
 fi
 
 ssl_cert_dir=$(get_ssl_cert_dir ) || return $?
