SSL: removed legacy functions that were generating warnings
removed legacy functions that are not needed anymore and were generating
unnecessary warnings.

diff --git a/libexec/apply-ssl-config b/libexec/apply-ssl-config
--- a/libexec/apply-ssl-config
+++ b/libexec/apply-ssl-config
@@ -171,10 +171,8 @@ else
   fi
 fi
 
-save_opts_in_vhost_config "$vhost" "ssl.enabled = yes"
-
-if is_https_redirect_enabled_by_default ; then
-  set_https_redirect_metadata "$vhost"
+if ! save_opts_in_vhost_config "$vhost" "ssl.enabled = yes"; then
+  error "failed to write SSL metadata on vost"
 fi
 
 if ! rewrite_vhost_apache_config "$vhost"; then
