apply-ssl-config: better status msgs

diff --git a/libexec/apply-ssl-config b/libexec/apply-ssl-config
--- a/libexec/apply-ssl-config
+++ b/libexec/apply-ssl-config
@@ -153,3 +153,11 @@ if [ $? -ne 0 ]; then
 fi
 
 "$curr_dir/config-vhost-apache" "$vhost"
+if [ $? -eq 0 ]; then
+  echo
+  echo "Successfully applied SSL configuration for vhost $vhost"
+  exit 0
+else
+  echo
+  error "failed to apply SSL configuration for vhost $vhost"
+fi
