big change to replace hardcoded entries of w_$vhost strings

diff --git a/libexec/archive-tokens b/libexec/archive-tokens
--- a/libexec/archive-tokens
+++ b/libexec/archive-tokens
@@ -116,8 +116,14 @@ if [ -z "$clone_type" ]; then
 fi
 
 vhost="$1"
-if ! getent passwd "w_$vhost" &>/dev/null; then
-  error "user 'w_$vhost' doesn't exist"
+get_linux_username_from_vhost "$vhost" && \
+vhost_user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
+if ! getent passwd "$vhost_user" &>/dev/null; then
+  error "user '$vhost_user' doesn't exist"
 fi
 
 if [ $delete_token -eq 1 -a -z "$token_str" ]; then
@@ -144,9 +150,9 @@ if [ "$clone_type" == "recv_active" -o \
     error "unable to create archive dir for vhost '$vhost'"
   elif [ -e "$vhost_archive_dir" -a ! -d "$vhost_archive_dir" ]; then
     error "directory '$vhost_archive_dir' exists but is not a directory"
-  elif ! chown "w_$vhost" "$vhost_archive_dir"; then
+  elif ! chown "$vhost_user" "$vhost_archive_dir"; then
     error "unable to change the permissions of directory"\
-"$vhost_archive_dir to user 'w_$vhost'"
+"$vhost_archive_dir to user '$vhost_user'"
   fi
 fi
 
@@ -203,9 +209,9 @@ echo "$secret_key" >"$token_file"
 if [ $? -ne 0 ]; then
   error "unable to create token file."
 fi
-if ! chgrp "w_$vhost" "$token_file"; then
+if ! chgrp "$vhost_user" "$token_file"; then
   rm -f "$token_file"
-  error "unable to chgrp token file '$token_file' to group 'w_$vhost'"
+  error "unable to chgrp token file '$token_file' to group '$vhost_user'"
 fi
 
 if [ $print_token_in_the_end -eq 1 ]; then
diff --git a/libexec/archive-vhost b/libexec/archive-vhost
--- a/libexec/archive-vhost
+++ b/libexec/archive-vhost
@@ -111,7 +111,11 @@ vhost="$1"
 archive_to="$2"
 
 user_db="b_$vhost"
-user_web="w_$vhost"
+get_linux_username_from_vhost "$vhost" && user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 
 $dir/check-vhost-name archive "$vhost" || usage
 home="`eval echo -n \~$user_web`"
diff --git a/libexec/archive-vhost-list b/libexec/archive-vhost-list
--- a/libexec/archive-vhost-list
+++ b/libexec/archive-vhost-list
@@ -2,7 +2,6 @@
 dir=`dirname $0`
 dir_bin="$dir/../bin"
 vhost="$1"
-user="w_$vhost"
 label="$2"
 error()
 {
@@ -16,6 +15,19 @@ case "$0" in
 esac
 # using mode archive: it's OK to operate on a locked vhost
 $dir/check-vhost-name archive "$vhost" || exit 1
+
+lib_f="$dir/../lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 home="`eval \"echo ~$user\"`" || error
 [ -d "$home" ] || error "Home dir $home does not exist"
 if [ -n "$label" ]; then $dir/check-archive-pathname -u"$vhost" restore "$home/public_html/gen/archive/$label" || exit 1; fi
diff --git a/libexec/archive-vhost-store b/libexec/archive-vhost-store
--- a/libexec/archive-vhost-store
+++ b/libexec/archive-vhost-store
@@ -15,7 +15,6 @@ do
   case "$OPTOPT" in
     u) opt_u=1
        vhost="$OPTARG"
-       user_web="w_$vhost"
        ;;
     *) exit 1;
   esac
@@ -79,6 +78,19 @@ write_tar_output()
 
 # using mode archive: it's OK to operate on a locked vhost
 [ -n "$tar_output_file" ] || error "no label"
+
+lib_f="$dir/../lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 if [ $opt_u = 1 ]
 then
   $dir/check-vhost-name archive "$vhost" || exit 1
diff --git a/libexec/archive-vhost-web b/libexec/archive-vhost-web
--- a/libexec/archive-vhost-web
+++ b/libexec/archive-vhost-web
@@ -35,8 +35,21 @@ dir=`dirname "$self_bin"`
 sys_dir=$(readlink -e "$dir/..")
 
 vhost="$1"
+$sys_dir/libexec/check-vhost-name archive "$vhost" || exit 1
+
+lib_f="$sys_dir/lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 archive_dir="$2"
-user="w_$vhost"
 home="`eval \"echo ~$user\"`"
 date=`date  +'%Y%m%d'`
 archive_file="$archive_dir/$user.tgz"
diff --git a/libexec/check-archive-pathname b/libexec/check-archive-pathname
--- a/libexec/check-archive-pathname
+++ b/libexec/check-archive-pathname
@@ -41,7 +41,12 @@ then
   prefix=/opt/webenabled/data
 else
   $mydir/check-vhost-name archive "$opt_u" || error
-  user="w_$opt_u"
+	get_linux_username_from_vhost "$opt_u" && \
+	user="$_dp_value"
+	if [ $? -ne 0 ]; then
+		error "unable to get the linux username from vhost $opt_u"
+	fi
+
   home="`eval \"echo ~$user\"`" || error
   [ -d "$home" ] || error "Home dir $home does not exist"
   prefix="$home/public_html/gen/archive"
diff --git a/libexec/check-vhost-name b/libexec/check-vhost-name
--- a/libexec/check-vhost-name
+++ b/libexec/check-vhost-name
@@ -42,7 +42,10 @@ for inc_file in "$lib_file" "$vars_file"; do
 done
 
 vhost="$2"
-w_user="w_$vhost"
+get_linux_username_from_vhost "$vhost" && w_user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 b_user="b_$vhost"
 
 (echo "$vhost"|egrep -q '^[-_a-z0-9]{1,6}$')||error "invalid vhost name '$vhost'"
diff --git a/libexec/chpass-vhost b/libexec/chpass-vhost
--- a/libexec/chpass-vhost
+++ b/libexec/chpass-vhost
@@ -36,8 +36,23 @@ done
 [ $# -lt 1 -o "$1" == "" ] && usage
 
 vhost="$1"
-user="w_$vhost"
 $dir/check-vhost-name config "$vhost" || exit 1
+
+self_dir="${self_bin%/*}"
+sys_dir="${self_dir%/*}"
+
+lib_f="$sys_dir/lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 
 if [ -n "$pass_from_stdin" ]; then
   # received -i. read pass from stdin
diff --git a/libexec/clone-tokens b/libexec/clone-tokens
--- a/libexec/clone-tokens
+++ b/libexec/clone-tokens
@@ -98,8 +98,14 @@ elif [ $delete_token -eq 1 ]; then
   fi
 fi
 
-if ! getent passwd "w_$vhost" ; then
-  wedp_warn "vhost 'w_$vhost' doesn't exist yet (this is just a warning)"
+get_linux_username_from_vhost "$vhost" && \
+vhost_user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
+if ! getent passwd "$vhost_user" ; then
+  wedp_warn "vhost '$vhost_user' doesn't exist yet (this is just a warning)"
 fi
 
 if [ -z "$token_str" ]; then
diff --git a/libexec/clone-vhost-local b/libexec/clone-vhost-local
--- a/libexec/clone-vhost-local
+++ b/libexec/clone-vhost-local
@@ -22,6 +22,7 @@ usage()
 [ $# -lt 2 ] && usage
 dir=`dirname "${BASH_SOURCE[0]}"`
 sys_dir=$(readlink -e "$dir/..")
+lib_file="$sys_dir/lib/functions"
 
 while getopts "PpinS:IF" OPTOPT
 do
@@ -48,7 +49,18 @@ shift
 $dir/check-vhost-name archive "$source" || usage
 $dir/check-vhost-name restore "$target" || usage
 
-source_home=$(eval echo -n \~"w_$source")
+if ! . source "$lib_file"; then
+  echo "Error: unable to load lib file '$lib_file'" 1>&2
+  exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+source_vuser="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $source"
+fi
+
+source_home=$(eval echo -n \~"$source_vuser")
 TMP_FILE="tmp_archive_$source-$(date +%b-%d-%Y--%H-%M).tgz"
 TMP_FILE_FP="$source_home/public_html/gen/archive/$TMP_FILE"
 
diff --git a/libexec/command-tar b/libexec/command-tar
--- a/libexec/command-tar
+++ b/libexec/command-tar
@@ -4,9 +4,29 @@ dir_bin="$dir/../bin"
 vhost="$1"
 tar_command="$2"
 param="$3"
-user="w_$vhost"
 
 # using mode archive: it's OK to operate on a locked vhost
 $dir/check-vhost-name archive "$vhost" || exit 1
+
+self_bin=`readlink -e "$0"`
+if [ $? -ne 0 ]; then
+  echo "Error: unable to get self path" 1>&2
+  exit 1
+fi
+
+self_dir="${self_bin%/*}"
+sys_dir="${self_dir%/*}"
+
+lib_f="$sys_dir/lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 su -l -c "tar $param $tar_command" $user
diff --git a/libexec/config-vhost-apache b/libexec/config-vhost-apache
--- a/libexec/config-vhost-apache
+++ b/libexec/config-vhost-apache
@@ -301,9 +301,13 @@ done
 [ $# -eq 0 -o -z "$1" ] && usage # yes, again
 
 vhost="$1"
-user="w_$vhost"
-
 "$dir/check-vhost-name" name-only "$vhost" || error
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 we_base_dir=`readlink -e "$dir/.."`
 
diff --git a/libexec/config-vhost-names b/libexec/config-vhost-names
--- a/libexec/config-vhost-names
+++ b/libexec/config-vhost-names
@@ -143,7 +143,11 @@ vhost="$1"
 if ! "$dir/check-vhost-name" name-only "$vhost"; then
   error "vhost argument is in an invalid format"
 fi
-user="w_$vhost"
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 if [ -z "$ip" ]; then
   ip='*'
diff --git a/libexec/config-vhost-quota b/libexec/config-vhost-quota
--- a/libexec/config-vhost-quota
+++ b/libexec/config-vhost-quota
@@ -5,15 +5,30 @@ option="$1"
 vhost="$2"
 user="$vhost"
 
+# main
+
+lib_f="$dir/../lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
 # using mode archive: it's OK to operate on a locked vhost
 $dir/check-vhost-name archive "$vhost" || exit 1
 
+get_linux_username_from_vhost "$vhost" && \
+vhost_user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+db_user="b_$vhost"
+
 if [ "$option" = "-g" ]; then
-  $dir_bin/quota-scripts/get-disk-quota.sh w_$user
-  $dir_bin/quota-scripts/get-disk-quota.sh b_$user
+  $dir_bin/quota-scripts/get-disk-quota.sh "$vhost_user"
+  $dir_bin/quota-scripts/get-disk-quota.sh "$db_user"
 elif [ "$option" = "-s" ]; then
   w_quota="$3"
   b_quota="$4"
-  $dir_bin/quota-scripts/set-disk-quota.sh w_$user $3
-  $dir_bin/quota-scripts/set-disk-quota.sh b_$user $4
+  $dir_bin/quota-scripts/set-disk-quota.sh "$vhost_user" $3
+  $dir_bin/quota-scripts/set-disk-quota.sh "$db_user" $4
 fi
diff --git a/libexec/create-virtwww b/libexec/create-virtwww
--- a/libexec/create-virtwww
+++ b/libexec/create-virtwww
@@ -155,7 +155,11 @@ fi
 
 DB_ACCOUNT_NAME="b_$ACCOUNT_NAME"
 vhost="$ACCOUNT_NAME"
-ACCOUNT_NAME="w_$ACCOUNT_NAME"
+
+generate_linux_username_for_vhost "$vhost" && ACCOUNT_NAME="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to generate linux username for vhost"
+fi
 
 config_base_dir="$we_base/config/vhosts"
 config_dir="$config_base_dir/$vhost"
diff --git a/libexec/crontab-vhost-edit b/libexec/crontab-vhost-edit
--- a/libexec/crontab-vhost-edit
+++ b/libexec/crontab-vhost-edit
@@ -23,9 +23,14 @@ EOF
 [ $# -lt 1 ] && usage
 
 vhost="$1"
-user="w_$vhost"
 # using mode archive: it's OK to operate on a locked vhost
 $dir/check-vhost-name archive "$vhost" || exit 1
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 temp_file=$(su -l -c 'export TMPDIR=${TMPDIR:-/tmp}; mktemp -p "$TMPDIR" cron_edit.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' "$user")
 status=$?
diff --git a/libexec/crontab-vhost-get b/libexec/crontab-vhost-get
--- a/libexec/crontab-vhost-get
+++ b/libexec/crontab-vhost-get
@@ -18,10 +18,22 @@ dir=`dirname $0`
 [ "$dir" == "." ] && dir="$PWD"
 dir_bin="$dir/../bin"
 
+lib_f="$dir/../lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
 vhost="$1"
-user="w_$vhost"
 # using mode archive: it's OK to operate on a locked vhost
 $dir/check-vhost-name archive "$vhost" || exit 1
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 
 temp_file=$(su -l -c 'export TMPDIR=${TMPDIR:-/tmp}; mktemp -p "$TMPDIR" cron_get.XXXXXXXXXXXXXXXXXXXXXXXX' "$user")
 trap 'rm -f -- "$temp_file"' EXIT
diff --git a/libexec/export-vhost b/libexec/export-vhost
--- a/libexec/export-vhost
+++ b/libexec/export-vhost
@@ -23,7 +23,6 @@ shift `expr $OPTIND - 1`
 dir=`dirname "$0"`
 dir_bin="$dir/../bin"
 vhost="$1"
-user_web="w_$vhost"
 vhost_config_dir=.webenabled/private
 run()
 {
@@ -42,6 +41,19 @@ run_su()
 }
 
 $dir/check-vhost-name archive "$vhost" || usage
+
+lib_f="$dir/../lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 home="`eval \"echo ~$user_web\"`" || error
 
 config="`cat`"
diff --git a/libexec/fix-vhost-logs-ownshp-n-perms b/libexec/fix-vhost-logs-ownshp-n-perms
--- a/libexec/fix-vhost-logs-ownshp-n-perms
+++ b/libexec/fix-vhost-logs-ownshp-n-perms
@@ -78,7 +78,13 @@ for vhost in ${vhost_ar[*]}; do
     continue
   fi
 
-  vhost_user="w_$vhost"
+  get_linux_username_from_vhost "$vhost" && \
+	vhost_user="$_dp_value"
+	if [ $? -ne 0 ]; then
+		echo "Warning: unable to get the linux username from vhost $vhost" 1>&2
+    continue
+	fi
+
   if ! getent passwd "$vhost_user" &>/dev/null; then
     echo "Warning: couldn't find user '$vhost_user'. Skipping..." 1>&2
     continue
diff --git a/libexec/gen-app-tool-token b/libexec/gen-app-tool-token
--- a/libexec/gen-app-tool-token
+++ b/libexec/gen-app-tool-token
@@ -45,18 +45,23 @@ if ! source "$lib_f"; then
 fi
 
 vhost="$1"
+# using mode archive: it's OK to operate on a locked vhost
+"$self_dir/check-vhost-name" archive "$vhost" || exit 1
+
 app="${2##*/}"
 
 [ -z "$1" -o -z "$2" ] && usage
 
-user="w_$vhost"
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 
 assign_deref_os_prop_or_exit url_tmpl "$sys_dir" tools_base_url_tmpl
 
 virtwww_base_domain=$(get_server_base_domain) || exit 1
-
-# using mode archive: it's OK to operate on a locked vhost
-"$self_dir/check-vhost-name" archive "$vhost" || exit 1
 
 token_bin="$self_dir/token-mgr"
 
diff --git a/libexec/gen-archive-download-token b/libexec/gen-archive-download-token
--- a/libexec/gen-archive-download-token
+++ b/libexec/gen-archive-download-token
@@ -46,15 +46,19 @@ fi
 [ -z "$1" -o -z "$2" ] && usage
 
 vhost="$1"
+# using mode archive: it's OK to operate on a locked vhost
+"$self_dir/check-vhost-name" archive "$vhost" || exit 1
+
 archive_file_in="$2"
 
-user="w_$vhost"
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 assign_deref_os_prop_or_exit url_tmpl "$sys_dir" archive_download_url_tmpl
 assign_deref_os_prop_or_exit data_dir "$sys_dir" data_dir
-
-# using mode archive: it's OK to operate on a locked vhost
-"$self_dir/check-vhost-name" archive "$vhost" || exit 1
 
 archives_dir=$(readlink -m "$data_dir/vhost_archives/$vhost")
 archive_file=$(readlink -m "$archives_dir/$archive_file_in")
diff --git a/libexec/htpasswd-lock-mng b/libexec/htpasswd-lock-mng
--- a/libexec/htpasswd-lock-mng
+++ b/libexec/htpasswd-lock-mng
@@ -107,11 +107,15 @@ dir_bin="$base_dir/bin"
 metadata_handler="$base_dir/libexec/apache-metadata-handler"
 
 vhost="$1"
-password="$2"
-user="w_$vhost"
-
 # using mode archive: it's OK to operate on a locked vhost
 "$dir/check-vhost-name" archive "$vhost" || exit 1
+
+password="$2"
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 lib_file="$base_dir/lib/functions"
 flag_file="$base_dir/lib/variables"
diff --git a/libexec/import-site-from-files b/libexec/import-site-from-files
--- a/libexec/import-site-from-files
+++ b/libexec/import-site-from-files
@@ -113,6 +113,12 @@ if ! "$self_dir/check-vhost-name" $vhost_check "$vhost"; then
   exit 1
 fi
 
+get_linux_username_from_vhost "$vhost" && \
+vhost_user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 if [ -z "$orig_archive_file" ]; then
   error "missing archive file. Please specify it with option -f"
 fi
@@ -219,7 +225,7 @@ elif [ "$db_dump_type" == zip ]; then
   fi
 fi
 
-web_archive_file="$pack_dir/web/w_$vhost.tgz"
+web_archive_file="$pack_dir/web/$vhost_user.tgz"
 tar -zSpcf "$web_archive_file" -C "$app_dir_dist" .
 if [ $? -ne 0 ]; then
   error "unable to pack web dir $app_dir_dist"
diff --git a/libexec/import-site-from-git b/libexec/import-site-from-git
--- a/libexec/import-site-from-git
+++ b/libexec/import-site-from-git
@@ -171,6 +171,12 @@ else
   vhost_check=restore
 fi
 
+get_linux_username_from_vhost "$vhost" && \
+vhost_user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 if [ -n "$install_profile" -a -n "$orig_db_dump_file" ]; then
   error "can't use option install_profile with a database dump."
 fi
@@ -287,7 +293,7 @@ if [ -z "$subsystem" ]; then
   fi
 fi
 
-web_archive_file="$pack_dir/web/w_$vhost.tgz"
+web_archive_file="$pack_dir/web/$vhost_user.tgz"
 tar -zSpcf "$web_archive_file" -C "$app_dir_dist" .
 if [ $? -ne 0 ]; then
   error "unable to pack web dir $app_dir_dist"
diff --git a/libexec/import-vhost b/libexec/import-vhost
--- a/libexec/import-vhost
+++ b/libexec/import-vhost
@@ -29,7 +29,14 @@ shift `expr $OPTIND - 1`
 dir=`dirname "$0"`
 dir_bin="$dir/../bin"
 vhost="$1"
-user_web="w_$vhost"
+$dir/check-vhost-name restore "$vhost" || error
+
+get_linux_username_from_vhost "$vhost" && \
+user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 vhost_config_dir=.webenabled/private
 run()
 {
@@ -47,7 +54,6 @@ run_su()
   su -l -c "$*" "$user_web"
 }
 
-$dir/check-vhost-name restore "$vhost" || error
 home="`eval \"echo ~$user_web\"`" || error
 
 config="`sed \"\\$a\
diff --git a/libexec/lets-encrypt-wrapper b/libexec/lets-encrypt-wrapper
--- a/libexec/lets-encrypt-wrapper
+++ b/libexec/lets-encrypt-wrapper
@@ -115,6 +115,11 @@ case "$op" in
       exit 1
     fi
 
+		get_linux_username_from_vhost "$vhost" && linux_user="$_dp_value"
+		if [ $? -ne 0 ]; then
+			error "unable to get the linux username from vhost $vhost"
+		fi
+
     server_base_domain=$(get_server_base_domain) || exit 1
 
     certs_dir="$sys_dir/config/vhosts/$vhost/lets-encrypt"
@@ -128,7 +133,7 @@ case "$op" in
 
     acme_args+=( --home "$certs_dir" --renew-hook "$self_bin post-renew" )
 
-    public_dir=$(eval echo -n \~w_$vhost/public_html/$vhost)
+    public_dir=$(eval echo -n \~$linux_user/public_html/$vhost)
     if [ ! -d "$public_dir" ]; then
       error "public directory not found: $public_dir"
     fi
@@ -165,7 +170,7 @@ case "$op" in
     # Encrypt. Will be brought back after the certificate generation
     unset moved_htaccess
     if [ -f "$htaccess_file" ]; then
-      su -l -s /bin/bash -c "mv -n $htaccess_file $htaccess_file_moved" "w_$vhost"
+      su -l -s /bin/bash -c "mv -n $htaccess_file $htaccess_file_moved" "$linux_user"
       if [ $? -eq 0 ]; then
         moved_htaccess=1
       fi
diff --git a/libexec/lock-vhost b/libexec/lock-vhost
--- a/libexec/lock-vhost
+++ b/libexec/lock-vhost
@@ -44,14 +44,19 @@ for inc_file in "$lib_file" "$vars_file"; do
 done
 
 vhost="$1"
-user="w_$vhost"
-vhost_config_dir="$devpanel_dir/config/vhosts/$vhost"
-
 if [ "$cmd_name" == "lock-vhost" ]; then
   $dir/check-vhost-name lock "$vhost" || error
 elif [ "$cmd_name" == "unlock-vhost" ]; then
   $dir/check-vhost-name unlock "$vhost" || error
 fi
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
+vhost_config_dir="$devpanel_dir/config/vhosts/$vhost"
 
 trap 'exit 1' INT TERM HUP
 if lock_path "$vhost_config_dir"; then
diff --git a/libexec/lock-vhost-apache b/libexec/lock-vhost-apache
--- a/libexec/lock-vhost-apache
+++ b/libexec/lock-vhost-apache
@@ -26,7 +26,17 @@ dir=`dirname "$self_bin"`
 devpanel_dir=`readlink -e "$dir/.."`
 
 vhost="$1"
-user="w_$vhost"
+if [ "$cmd_name" == "lock-vhost" ]; then
+  $dir/check-vhost-name lock "$vhost" || exit 1
+elif [ "$cmd_name" == "unlock-vhost" ]; then
+  $dir/check-vhost-name unlock "$vhost" || exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 lib_file="$devpanel_dir/lib/functions"
 vars_file="$devpanel_dir/lib/variables"
@@ -42,11 +52,6 @@ assign_deref_os_fs_path_ex_or_exit apache_config_dir "$devpanel_dir" \
 
 apache_config="$apache_config_dir/$user.conf"
 
-if [ "$cmd_name" == "lock-vhost" ]; then
-  $dir/check-vhost-name lock "$vhost" || exit 1
-elif [ "$cmd_name" == "unlock-vhost" ]; then
-  $dir/check-vhost-name unlock "$vhost" || exit 1
-fi
 
 assign_deref_os_fs_path_ex_or_exit apachectl "$devpanel_dir" \
   pathnames/sbin/apachectl
diff --git a/libexec/mysql-password-vhost b/libexec/mysql-password-vhost
--- a/libexec/mysql-password-vhost
+++ b/libexec/mysql-password-vhost
@@ -20,14 +20,19 @@ sys_dir=$(readlink -e "$dir/..")
 dir_bin="$sys_dir/bin"
 
 vhost="$1"
-password="$2"
-
-user="w_$vhost"
-db_user="b_$vhost"
-user_home=$(eval echo \~"$user")
-
 # using mode archive: it's OK to operate on a locked vhost
 "$dir/check-vhost-name" archive "$vhost" || exit 1
+
+password="$2"
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
+db_user="b_$vhost"
+user_home=$(eval echo \~"$user")
 
 lib_file="$sys_dir/lib/functions"
 if ! source "$lib_file"; then
diff --git a/libexec/phpmyadmin-token b/libexec/phpmyadmin-token
--- a/libexec/phpmyadmin-token
+++ b/libexec/phpmyadmin-token
@@ -11,11 +11,21 @@ usage() {
 self_bin=`readlink -e "$0"`
 dir=`dirname "$self_bin"`
 dir_bin="$dir/../bin"
-vhost="$1"
-user="w_$vhost"
 
-# using mode archive: it's OK to operate on a locked vhost
-"$dir/check-vhost-name" archive "$vhost" || exit 1
+vhost="$1"
+$sys_dir/libexec/check-vhost-name archive "$vhost" || exit 1
+
+lib_f="$dir/../lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 token_bin="$dir/token-mgr"
 
diff --git a/libexec/public-key-vhost b/libexec/public-key-vhost
--- a/libexec/public-key-vhost
+++ b/libexec/public-key-vhost
@@ -166,7 +166,11 @@ shift $(( $OPTIND - 1 ))
 
 if [ -z "$for_root" ]; then
   vhost="$1"
-  user="w_$vhost"
+	get_linux_username_from_vhost "$vhost" && user="$_dp_value"
+	if [ $? -ne 0 ]; then
+		error "unable to get the linux username from vhost $vhost"
+	fi
+
   # using mode archive: it's OK to operate on a locked vhost
   if ! $dir/check-vhost-name archive "$vhost"; then
     echo "Invalid vhost name." 1>&2
diff --git a/libexec/rawlogs-list b/libexec/rawlogs-list
--- a/libexec/rawlogs-list
+++ b/libexec/rawlogs-list
@@ -2,13 +2,24 @@
 dir=`dirname $0`
 dir_bin="$dir/../bin"
 vhost="$1"
-user="w_$vhost"
 lines="$2"
 
 # using mode archive: it's OK to operate on a locked vhost
 $dir/check-vhost-name archive "$vhost" || exit 1
 
 [ -z "$lines" ] && lines=10
+
+lib_f="$dir/../lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 echo ' 'ACCESS
 su -ls /bin/bash $user -c 'tail -n '$lines' ~/logs/'${vhost}'-access_log'
diff --git a/libexec/recurring-snapshot-utils b/libexec/recurring-snapshot-utils
--- a/libexec/recurring-snapshot-utils
+++ b/libexec/recurring-snapshot-utils
@@ -225,6 +225,13 @@ case $op in
       exit 1
     fi
      
+		get_linux_username_from_vhost "$vhost" && \
+		vhost_user="$_dp_value"
+		if [ $? -ne 0 ]; then
+			error "unable to get the linux username from vhost $vhost"
+		fi
+		vhost_group="$vhost_user"
+
     assign_deref_os_prop_or_exit archive_template_str "$sys_dir" \
       vhost_snapshot_${frequency}_template_str
 
@@ -246,7 +253,7 @@ case $op in
     cache_dir="$system_cache_dir/$vhost"
     if [ ! -e "$cache_dir" ]; then
       if mkdir -m 750 "$cache_dir"; then
-        if ! chown "root:w_$vhost" "$cache_dir"; then
+        if ! chown "root:$vhost_group" "$cache_dir"; then
           error "unable to chown $cache_dir"
         fi
       else
@@ -329,7 +336,6 @@ case $op in
     fi
 
     # no archive for the same frequency exists, go and archive it
-    vhost_user="w_$vhost"
     vhost_dir=$(eval echo \~$vhost_user)
     exclude_file="$vhost_dir/.devpanel/recurring-snapshots.exclude-$frequency"
     if [ ! -f "$exclude_file" ]; then
diff --git a/libexec/remove-vhost b/libexec/remove-vhost
--- a/libexec/remove-vhost
+++ b/libexec/remove-vhost
@@ -57,15 +57,19 @@ dir=`dirname "$self_bin"`
 sys_dir=$(readlink -e "$dir/..")
 
 vhost="$1"
+"$dir/check-vhost-name" archive "$vhost" || exit 1
+
 archive_to="$2"
 if [ -z "$archive_to" ]; then
   archive_to="@archive_template_str@"
 fi
 
 user_db="b_$vhost"
-user_web="w_$vhost"
-
-"$dir/check-vhost-name" archive "$vhost" || exit 1
+get_linux_username_from_vhost "$vhost" && \
+user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 lib_file="$sys_dir/lib/functions"
 if ! source "$lib_file"; then
diff --git a/libexec/restore-vhost b/libexec/restore-vhost
--- a/libexec/restore-vhost
+++ b/libexec/restore-vhost
@@ -153,7 +153,11 @@ export DEVPANEL_HOME="$we_base_dir"
 
 metadata_bin="$DEVPANEL_HOME/libexec/apache-metadata-handler"
 config_dir="$we_base_dir/config/vhosts/$vhost"
-user_web="w_$vhost"
+get_linux_username_from_vhost "$vhost" && user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 home="`eval \"echo ~$user_web\"`" || error "unable to get \$HOME of user $user_web"
 user_db="b_$vhost"
 vhost_config_dir=.webenabled/private
@@ -328,11 +332,11 @@ fi
 echo "$output"
 [ $status = 0 ] || exit $status
 
-mysql_host_port=$(get_param_from_db_output "w_$vhost" host "$output")
+mysql_host_port=$(get_param_from_db_output "$user_web" host "$output")
 mysql_host=${mysql_host_port%:*}
 mysql_port=${mysql_host_port#*:}
-mysql_user=$(get_param_from_db_output "w_$vhost" user "$output")
-mysql_password=$(get_param_from_db_output "w_$vhost" password "$output")
+mysql_user=$(get_param_from_db_output "$user_web" user "$output")
+mysql_password=$(get_param_from_db_output "$user_web" password "$output")
 
 # write the ~/.my.cnf file
 { printf 'client.host = %s\nclient.port = %s\nclient.user = %s\n' \
diff --git a/libexec/restore-vhost-db b/libexec/restore-vhost-db
--- a/libexec/restore-vhost-db
+++ b/libexec/restore-vhost-db
@@ -44,8 +44,13 @@ fi
 
 vhost="$1"
 user="b_$vhost"
-user_web="w_$vhost"
 archive_label="$2"
+
+get_linux_username_from_vhost "$vhost" && \
+user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 if [ $create_db_instance -eq 1 ] && getent passwd "$user" &>/dev/null; then
   error "user '$user' already exists"
diff --git a/libexec/restore-vhost-web b/libexec/restore-vhost-web
--- a/libexec/restore-vhost-web
+++ b/libexec/restore-vhost-web
@@ -73,7 +73,6 @@ done
 dir=`dirname "$0"`
 bin_dir="$dir/../bin"
 vhost="$1"
-user="w_$vhost"
 archive_label="$2"
 
 we_base_dir=`readlink -e "$dir/.."`
@@ -81,6 +80,12 @@ lib_file="$we_base_dir/lib/functions"
 if ! source "$lib_file" ; then
   echo "Error: unable to load auxiliary functions from '$lib_file'" 1>&2
   exit 1
+fi
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
 fi
 
 if [ $create_vhost -eq 1 ] && getent passwd "$user" &>/dev/null; then
diff --git a/libexec/run-vhost-shell b/libexec/run-vhost-shell
--- a/libexec/run-vhost-shell
+++ b/libexec/run-vhost-shell
@@ -10,12 +10,33 @@ usage() {
 
 [ $# -lt 2 -o -z "$1" -o -z "$2" ] && usage
 
-#
+# main
+self_bin=`readlink -e "$0"`
+if [ $? -ne 0 ]; then
+  echo "Error: unable to get self path" 1>&2
+  exit 1
+fi
+
+self_dir="${self_bin%/*}"
+sys_dir="${self_dir%/*}"
+
+lib_f="$sys_dir/lib/functions"
+if ! source "$lib_f"; then
+  echo "Error: unable to import $lib_f" 1>&2
+  exit 1
+fi
 
 vhost="$1"
+$sys_dir/libexec/check-vhost-name archive "$vhost" || exit 1
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
 command="$2"
 
-user="w_$vhost"
 if ! getent passwd "$user" &>/dev/null; then
   echo "Error: unknown user" 1>&2
   exit 1
diff --git a/libexec/token-mgr b/libexec/token-mgr
--- a/libexec/token-mgr
+++ b/libexec/token-mgr
@@ -150,7 +150,11 @@ fi
 if [ -n "$literal_user" ]; then
   token_owner="$vhost"
 else
-  token_owner="w_$vhost"
+	get_linux_username_from_vhost "$vhost" && \
+	token_owner="$_dp_value"
+	if [ $? -ne 0 ]; then
+		error "unable to get the linux username from vhost $vhost"
+	fi
 fi
 
 if [ -n "$token_contents" ]; then
