recurring backups: added optional exclude file
optional exclude file to skip defined files on daily, monthly and weekly
backups. This is convenient for websites with big media files, when it's not
desired to do daily snapshots of media, for example.

diff --git a/libexec/archive-vhost-web b/libexec/archive-vhost-web
--- a/libexec/archive-vhost-web
+++ b/libexec/archive-vhost-web
@@ -2,10 +2,18 @@
 
 opt_P=0
 
-while getopts "P" OPTOPT
+unset exclude_file
+while getopts "Pe:" OPTOPT
 do
   case "$OPTOPT" in
     P) opt_P=1;;
+    e)
+      exclude_file=$OPTARG
+      if [ ! -f "$exclude_file" ]; then
+        echo "Error: missing exclude file $exclude_file" 1>&2
+        exit 1
+      fi
+      ;;
     *) exit 1;
   esac
 done
@@ -100,7 +108,7 @@ abort_if_exists "$archive_conf"
 echo "Archiving $home to $archive_file"
 echo "$vhost" >$archive_id
 if ! run tar --exclude ./public_html/gen/archive --exclude ./logs \
- -C "$home" -zcf "$archive_file" .; then
+  ${exclude_file:+-X $exclude_file} -C "$home" -zcf "$archive_file" .; then
   echo "Error: unable to archive the site files" 1>&2
   exit 1
 fi
