added method to check all available logs on server for applications

diff --git a/libexec/check-logs b/libexec/check-logs
--- a/libexec/check-logs
+++ b/libexec/check-logs
@@ -10,12 +10,14 @@ echo "Example: ./check-logs -l error -u john"
 
 echo "Options: "
 echo "    -h     Show this help message"
+echo "    -a     Show list of all available logs of all users"
 echo "    -u     Select user"
-echo "    -l     Select log error/access"
+echo "    -l     Select current log error/access"
+echo "              Example: ./check-logs -l error -u john"
 echo "    -s     Show logs available "
 echo "           Example: ./check-logs -s john"
 echo "    -f     Force fire read"
-echo "           Example: ./check-logs -f /path/to/file"
+echo "              Example: ./check-logs -f /path/to/file"
 }
 
 #This method will read the logs from the desired user
@@ -24,15 +26,19 @@ readlog(){
 ERRLOGPATH=$virtwww_log_dir/w_$VHOST/$VHOST-error_log
 ACCLOGPATH=$virtwww_log_dir/w_$VHOST/$VHOST-access_log
 if [ "$READLOG" == "error" ]; then
-	cat "$ERRLOGPATH"
+        cat "$ERRLOGPATH"
 
 elif [ "$READLOG" == "access" ];then
-	cat "$ACCLOGPATH"
+        cat "$ACCLOGPATH"
 else 
-	echo "Error in the command, see the usage for more information"
+        echo "Error in the command, see the usage for more information"
 fi
 }
 
+#Method to list all logs of all users
+checkavaillogs(){
+find $virtwww_log_dir/w_*/*_log*
+}
 
 # This method will read a specific given log (just the name of the file)
 readspecific(){
@@ -40,15 +46,15 @@ readspecific(){
 FILETYPE=$(file $SPECLOG)
 
 if [ ! -f $SPECLOG ];then
-	echo "The file does not exist, see the usage for more information"
-	exit 1
+        echo "The file does not exist, see the usage for more information"
+        exit 1
 fi
 
 if [[ $FILETYPE =~ .*gzip.* ]];then
-	zcat $SPECLOG | tail -100
+        zcat $SPECLOG | tail -100
 
 elif [[ $FILETYPE =~ .*ASCII.* ]];then
-	cat $SPECLOG  | tail -100
+        cat $SPECLOG  | tail -100
 fi
 }
 
@@ -80,24 +86,29 @@ fi
 assign_deref_os_prop_or_exit virtwww_log_dir "$sys_dir" \
   pathnames/var/log/apache_vhosts
 
-while getopts ":l: :u: :s: :f:" opt ; do
+
+[ $# -eq 0 ] && usage
+while getopts ":l: :u: :s: :f: a" opt ; do
   case $opt in
 
     l)
         READLOG="$OPTARG"
+        ;;
+    a)
+        checkavaillogs
         ;;
     u)
         VHOST="$OPTARG"
         readlog
         ;;
     f)
-	SPECLOG="$OPTARG"
-	readspecific
-	;;
-    s)	
-	VHOST="$OPTARG"
-	showavaillogs
-	;;
+        SPECLOG="$OPTARG"
+        readspecific
+        ;;
+    s)
+        VHOST="$OPTARG"
+        showavaillogs
+        ;;
 
     *)
         usage
