libexec/check-vhost-name: changes for a better lock functionality
changed the lock functionality a bit because it got broken after the removal
of mod_macro. This change is a preparation for the follow-up lock changes.

diff --git a/libexec/check-vhost-name b/libexec/check-vhost-name
--- a/libexec/check-vhost-name
+++ b/libexec/check-vhost-name
@@ -1,10 +1,4 @@
 #!/bin/bash
-dir=`dirname "$0"`
-mode="$1"
-vhost="$2"
-w_user="w_$vhost"
-b_user="b_$vhost"
-apache_config="$dir/../config/os/pathnames/etc/apache_vhosts/$w_user.conf"
 
 error()
 {
@@ -26,17 +20,46 @@ home()
 
 locked()
 {
-  egrep -q '^Use[[:space:]]+Vhost-[^[:space:]]+-locked\>' "$apache_config"
+  get_metadata_value "$vhost_meta_dir" "$DEVPANEL_VHOST_LOCK_FLAG" &>/dev/null
 }
 
-[ $# = 2 ] && case "$mode" in archive|restore|lock|unlock|config) true;; *) false;; esac || 
-  error "Usage: $0 [archive|restore|lock|unlock|config] basename"
+# main
 
+mode="$1"
+[ $# = 2 ] && case "$mode" in archive|restore|lock|unlock|config|name-only) true;; *) false;; esac || 
+  error "Usage: $0 [archive|restore|lock|unlock|config|name-only] basename"
+
+self_bin=`readlink -e "$0"`
+dir=`dirname "$self_bin"`
+devpanel_dir=`readlink -e "$dir/.."`
+
+lib_file="$devpanel_dir/lib/functions"
+vars_file="$devpanel_dir/lib/variables"
+for inc_file in "$lib_file" "$vars_file"; do
+  if ! source "$inc_file"; then
+    error "unable to source file '$inc_file'"
+  fi
+done
+
+vhost="$2"
+w_user="w_$vhost"
+b_user="b_$vhost"
 
 (echo "$vhost"|egrep -q '^[-_a-z0-9]{1,6}$')||error "invalid vhost name '$vhost'"
 
-if [ $mode = restore ]
-then
+vhost_meta_dir="$devpanel_dir/config/vhosts/$vhost"
+if [ ! -d "$vhost_meta_dir" ]; then
+  error "missing vhost config dir '$vhost_meta_dir'"
+fi
+
+assign_deref_os_fs_path_ex_or_exit apache_config_dir "$devpanel_dir" \
+  "pathnames/etc/apache_vhosts"
+
+apache_config="$apache_config_dir/$w_user.conf"
+
+if [ "$mode" == "name-only" ]; then
+  exit 0
+elif [ $mode = restore ]; then
   exists "$w_user" && error "$w_user must not exist"
   exists "$b_user" && error "$b_user must not exist"
 else
@@ -45,7 +68,7 @@ else
   [ -d "$home" ] || error "home dir $home must exist"
   owner=`stat --format %U "$home"` || error
   [ o"$owner" = o"$w_user" ] || error "$home must be owned by $w_user"
-  [ -r "$apache_config" ] || error "$apache_config must exist"
+  [ $mode != unlock -a ! -r "$apache_config" ] && error "$apache_config must exist"
   [ $mode = lock -o $mode = config ] && locked && error "$vhost must not be locked"
   [ $mode = unlock ] && ! locked && error "$home must be locked"
   # it's ok to archive both locked and unlocked vhosts
