fixes to bug in previous big commit

diff --git a/libexec/config-vhost-apache b/libexec/config-vhost-apache
--- a/libexec/config-vhost-apache
+++ b/libexec/config-vhost-apache
@@ -303,12 +303,6 @@ done
 vhost="$1"
 "$dir/check-vhost-name" name-only "$vhost" || error
 
-get_linux_username_from_vhost "$vhost" && \
-user="$_dp_value"
-if [ $? -ne 0 ]; then
-  error "unable to get the linux username from vhost $vhost"
-fi
-
 we_base_dir=`readlink -e "$dir/.."`
 
 lib_file="$we_base_dir/lib/functions"
@@ -321,6 +315,12 @@ for inc_file in "$lib_file" "$vars_file"; do
     error "unable to source file '$inc_file'"
   fi
 done
+
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 user_home=$(eval echo -n \~"$user")
 if [ $? -ne 0 -o -z "$user_home" ]; then
diff --git a/libexec/create-virtwww b/libexec/create-virtwww
--- a/libexec/create-virtwww
+++ b/libexec/create-virtwww
@@ -20,6 +20,8 @@ dir=$(dirname "$0")
 we_base=`readlink -e "$dir/.."`
 dir_bin="$we_base/bin"
 
+apache_metadata_bin="$we_base/libexec/apache-metadata-handler"
+
 pathnames="$dir/../config/os/pathnames"
 #macro_file="$dir/../config/names/apache-macro"
 
@@ -155,11 +157,13 @@ fi
 
 DB_ACCOUNT_NAME="b_$ACCOUNT_NAME"
 vhost="$ACCOUNT_NAME"
+ACCOUNT_NAME="w_$ACCOUNT_NAME"
+VHOST_HOME="$WEBSITES_HOME/$ACCOUNT_NAME"
 
-generate_linux_username_for_vhost "$vhost" && ACCOUNT_NAME="$_dp_value"
-if [ $? -ne 0 ]; then
-  error "unable to generate linux username for vhost"
-fi
+#generate_linux_username_for_vhost "$vhost" && ACCOUNT_NAME="$_dp_value"
+#if [ $? -ne 0 ]; then
+#  error "unable to generate linux username for vhost"
+#fi
 
 config_base_dir="$we_base/config/vhosts"
 config_dir="$config_base_dir/$vhost"
@@ -267,7 +271,7 @@ else
     echo 'not found'
     echo -n "+ creating '$ACCOUNT_NAME' account ... "
     if ! useradd -g "$apache_group" -G "$ACCOUNT_NAME${ADDON_GROUPS:+,$ADDON_GROUPS}" \
-        -m -d "$WEBSITES_HOME/$ACCOUNT_NAME" "$ACCOUNT_NAME"; then
+        -m -d "$VHOST_HOME" "$ACCOUNT_NAME"; then
         echo
         echo 'Aborting'
         exit 2
@@ -315,7 +319,6 @@ fi # MYSQL_LOCAL
 mkdir -m 2750 $vhost_cache_dir
 chown root:$ACCOUNT_NAME $vhost_cache_dir
 
-VHOST_HOME="$WEBSITES_HOME/$ACCOUNT_NAME"
 echo -n '+ configuring home directory for virtual host ... '
 chgrp $apache_group "$VHOST_HOME" || exit 2
 su - -c "
@@ -448,30 +451,18 @@ fi
 echo 'done'
 
 vhost_prefix_f="$config_dir/apache_vhost"
+metadata_str="
+set $vhost_prefix_f:_:linux_user $ACCOUNT_NAME
+set $vhost_prefix_f:_:document_root $VHOST_HOME
+set $vhost_prefix_f:0 devpanel_main
+set $vhost_prefix_f:_:name:devpanel_main 0
+set $vhost_prefix_f:0:_:template_ref names/apache_vhost_template
+set $vhost_prefix_f:1 devpanel_tools
+set $vhost_prefix_f:_:name:devpanel_tools 1
+set $vhost_prefix_f:1:_:template_ref names/tools_vhost_template
+"
 
-if ln -s "devpanel_main" "$vhost_prefix_f:0"; then
-  if ! ln -s 0 "$vhost_prefix_f:_:name:devpanel_main"; then
-    error "unable to set the name for vhost 0 (devpanel_main)"
-  fi
-
-  if ! ln -s "names/apache_vhost_template" "$vhost_prefix_f:0:_:template_ref"; then
-    error "unable to create template ref $vhost_prefix_f:0:_:template_ref"
-  fi
-else
-  error "unable to create vhost entry $vhost_prefix_f:0"
-fi
-
-if ln -s "devpanel_tools" "$vhost_prefix_f:1"; then
-  if ! ln -s 1 "$vhost_prefix_f:_:name:devpanel_tools"; then
-    error "unable to set the name for vhost 1 (tools vhost)"
-  fi
-
-  if ! ln -s "names/tools_vhost_template" "$vhost_prefix_f:1:_:template_ref"; then
-    error "unable to create template ref $vhost_prefix_f:1:_:template_ref"
-  fi
-else
-  error "unable to create vhost entry $vhost_prefix_f:1"
-fi
+echo "$metadata_str" | "$apache_metadata_bin" -q "$vhost" || exit $?
 
 echo '---[ end of creating new virtual host ]---'
 echo
diff --git a/libexec/htpasswd-lock-mng b/libexec/htpasswd-lock-mng
--- a/libexec/htpasswd-lock-mng
+++ b/libexec/htpasswd-lock-mng
@@ -110,13 +110,6 @@ vhost="$1"
 # using mode archive: it's OK to operate on a locked vhost
 "$dir/check-vhost-name" archive "$vhost" || exit 1
 
-password="$2"
-get_linux_username_from_vhost "$vhost" && \
-user="$_dp_value"
-if [ $? -ne 0 ]; then
-  error "unable to get the linux username from vhost $vhost"
-fi
-
 lib_file="$base_dir/lib/functions"
 flag_file="$base_dir/lib/variables"
 for lib_f in "$flag_file" "$lib_file"; do
@@ -125,6 +118,13 @@ for lib_f in "$flag_file" "$lib_file"; do
     exit 1
   fi
 done
+
+password="$2"
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 unset webenabled_backwards
 if deref_os_prop "$base_dir" webenabled_backwards &>/dev/null; then
diff --git a/libexec/lock-vhost-apache b/libexec/lock-vhost-apache
--- a/libexec/lock-vhost-apache
+++ b/libexec/lock-vhost-apache
@@ -32,12 +32,6 @@ elif [ "$cmd_name" == "unlock-vhost" ]; then
   $dir/check-vhost-name unlock "$vhost" || exit 1
 fi
 
-get_linux_username_from_vhost "$vhost" && \
-user="$_dp_value"
-if [ $? -ne 0 ]; then
-  error "unable to get the linux username from vhost $vhost"
-fi
-
 lib_file="$devpanel_dir/lib/functions"
 vars_file="$devpanel_dir/lib/variables"
 for inc_file in "$lib_file" "$vars_file"; do
@@ -46,6 +40,11 @@ for inc_file in "$lib_file" "$vars_file"; do
   fi
 done
 
+get_linux_username_from_vhost "$vhost" && \
+user="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
 
 assign_deref_os_fs_path_ex_or_exit apache_config_dir "$devpanel_dir" \
   pathnames/etc/apache_vhosts
diff --git a/libexec/remove-vhost b/libexec/remove-vhost
--- a/libexec/remove-vhost
+++ b/libexec/remove-vhost
@@ -64,17 +64,17 @@ if [ -z "$archive_to" ]; then
   archive_to="@archive_template_str@"
 fi
 
+lib_file="$sys_dir/lib/functions"
+if ! source "$lib_file"; then
+  echo "Error: unable to source lib file $lib_file" 1>&2
+  exit 1
+fi
+
 user_db="b_$vhost"
 get_linux_username_from_vhost "$vhost" && \
 user_web="$_dp_value"
 if [ $? -ne 0 ]; then
   error "unable to get the linux username from vhost $vhost"
-fi
-
-lib_file="$sys_dir/lib/functions"
-if ! source "$lib_file"; then
-  echo "Error: unable to source lib file $lib_file" 1>&2
-  exit 1
 fi
 
 assign_deref_os_prop_or_exit sys_data_dir "$sys_dir" data_dir
diff --git a/libexec/restore-vhost b/libexec/restore-vhost
--- a/libexec/restore-vhost
+++ b/libexec/restore-vhost
@@ -153,11 +153,6 @@ export DEVPANEL_HOME="$we_base_dir"
 
 metadata_bin="$DEVPANEL_HOME/libexec/apache-metadata-handler"
 config_dir="$we_base_dir/config/vhosts/$vhost"
-get_linux_username_from_vhost "$vhost" && user_web="$_dp_value"
-if [ $? -ne 0 ]; then
-  error "unable to get the linux username from vhost $vhost"
-fi
-
 home="`eval \"echo ~$user_web\"`" || error "unable to get \$HOME of user $user_web"
 user_db="b_$vhost"
 vhost_config_dir=.webenabled/private
@@ -173,6 +168,11 @@ fi
 aux_lib_file="$we_base_dir/lib/functions"
 if ! source "$aux_lib_file"; then
   error "unable to load auxiliary functions from $aux_lib_file"
+fi
+
+get_linux_username_from_vhost "$vhost" && user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
 fi
 
 assign_deref_os_prop_or_exit sys_datadir "$we_base_dir" data_dir
