a few parameter renamings on www

diff --git a/libexec/config-vhost-apache b/libexec/config-vhost-apache
--- a/libexec/config-vhost-apache
+++ b/libexec/config-vhost-apache
@@ -304,13 +304,12 @@ fi
 
 assign_deref_os_fs_path_ex_or_exit apachectl "$we_base_dir" pathnames/sbin/apachectl
 assign_deref_os_fs_path_ex_or_exit virtwww_dir "$we_base_dir" pathnames/etc/apache_vhosts
-assign_deref_os_prop_or_exit websites_basedir "$we_base_dir" websites_basedir
+assign_deref_os_prop_or_exit websites_basedir "$we_base_dir" apache_virtwww_homedir
 
 virtwww_file="$virtwww_dir/$user.conf"
 virtwww_file_old="$virtwww_file.old"
 config_dir="$we_base_dir/config/vhosts/$vhost"
 apache_svc_config_dir="$we_base_dir/config/packages/apache_vhost"
-server_hostname_file="$we_base_dir/config/names/default"
 
 tmp_new_vhost_file=`mktemp "$virtwww_file.XXXXXXXXXXXXXXX"`
 if [ $? -ne 0 ]; then
@@ -329,8 +328,8 @@ if ! cat "$virtwww_file" > "$vhost_bkp_file"; then
   error "unable to write a copy of '$virtwww_file' into '$vhost_bkp_file'"
 fi
 
-if ! server_hostname=`deref_contents "$server_hostname_file"`; then
-  error "unable to get server hostname from link '$server_hostname_file'"
+if ! server_hostname=`deref_os_prop "$we_base_dir" apache_virtwww_domain`; then
+  error "unable to default domain name for apache virtual host"
 fi
 
 declare -i n_vhosts=0
@@ -347,7 +346,7 @@ for this_vhost_prefix in "$vhost_prefix_f:"[0-9] "$vhost_prefix_f:"[0-9][0-9]; d
     continue
   fi
 
-  vhn=${this_vhost_prefix_f##*:}
+  vhn=${this_vhost_prefix##*:}
   sed_line=""
   sed_include_str=""
   vhost_base_str=`basename "$this_vhost_prefix"`
@@ -815,6 +814,7 @@ for this_vhost_prefix in "$vhost_prefix_f:"[0-9] "$vhost_prefix_f:"[0-9][0-9]; d
   sed_line+="s/@@__WEBSITES_BASEDIR__@@/`escape_sed "$websites_basedir"`/g;"
   sed_line+="s/@@__SERVER_HOSTNAME__@@/`escape_sed "$server_hostname"`/g;"
   sed_line+="s/@@__VHOST__@@/`escape_sed "$vhost"`/g;"
+  sed_line+="s/@@__VHOST_NUMBER__@@/$vhn/g;"
   sed_line+="s/@@__TEMPLATE_FILE__@@/`escape_sed "$template_file"`/g;"
   sed_line+="s/@@__TEMPLATE_FILE_BASENAME__@@/`escape_sed "$vhost_template"`/g;"
 
@@ -857,6 +857,8 @@ if ! "$apachectl" configtest; then
   if ! "$apachectl" configtest; then
     error "Apache config is broken, call a system administrator NOW!"
   fi
+
+  error "nothing was updated because of errors on the new apache config"
 else
   cp -f "$vhost_bkp_file" "$virtwww_file_old"
   if [ $? -eq 0 ]; then
diff --git a/libexec/create-virtwww b/libexec/create-virtwww
--- a/libexec/create-virtwww
+++ b/libexec/create-virtwww
@@ -35,8 +35,8 @@ assign_deref_os_fs_path_ex_or_exit edquota   "$we_base" pathnames/sbin/edquota
 assign_deref_os_fs_path_ex_or_exit VIRTWWW_LOGDIR "$we_base" pathnames/var/log/apache_vhosts
 assign_deref_os_fs_path_ex_or_exit VIRTWWW_CFGDIR "$we_base" pathnames/etc/apache_vhosts
 
-assign_deref_os_prop_or_exit apache_group          "$we_base"  names/apache-exec.group
-assign_deref_os_prop_or_exit WEBSITES_HOME         "$we_base"  websites_basedir
+assign_deref_os_prop_or_exit apache_group    "$we_base"  names/apache-exec.group
+assign_deref_os_prop_or_exit WEBSITES_HOME   "$we_base" apache_virtwww_homedir
 
 template_file="$we_base/config/packages/apache_vhost/_:template"
 if [ -f "$template_file" ]; then
@@ -268,8 +268,13 @@ else
     echo 'done'
 fi
 
-if ! mkdir -m 751 "$config_dir"; then
+if ! mkdir -m 750 "$config_dir"; then
   echo "Error: unable to create directory '$config_dir'" 1>&2
+  exit 1
+fi
+
+if ! chown "root":"$ACCOUNT_NAME" "$config_dir"; then
+  echo "Error: unable to chown dir '$config_dir' to user '$ACCOUNT_NAME'" 1>&2
   exit 1
 fi
 
