fixed lock/unlock problem on vhosts

diff --git a/libexec/config-vhost-apache b/libexec/config-vhost-apache
--- a/libexec/config-vhost-apache
+++ b/libexec/config-vhost-apache
@@ -298,9 +298,13 @@ user="w_$vhost"
 we_base_dir=`readlink -e "$dir/.."`
 
 lib_file="$we_base_dir/lib/functions"
-if ! source "$lib_file"; then
-  error "unable to source lib file '$lib_file'"
-fi
+vars_file="$we_base_dir/lib/variables"
+
+for inc_file in "$lib_file" "$vars_file"; do
+  if ! source "$inc_file"; then
+    error "unable to source file '$inc_file'"
+  fi
+done
 
 assign_deref_os_fs_path_ex_or_exit apachectl "$we_base_dir" pathnames/sbin/apachectl
 assign_deref_os_fs_path_ex_or_exit virtwww_dir "$we_base_dir" pathnames/etc/apache_vhosts
@@ -310,6 +314,10 @@ virtwww_file="$virtwww_dir/$user.conf"
 virtwww_file_old="$virtwww_file.old"
 config_dir="$we_base_dir/config/vhosts/$vhost"
 apache_svc_config_dir="$we_base_dir/config/packages/apache_vhost"
+
+if get_metadata_value "$config_dir" "$DEVPANEL_VHOST_LOCK_FLAG" &>/dev/null; then
+  error "vhost $vhost is locked. Can't work on a locked vhost."
+fi
 
 tmp_new_vhost_file=`mktemp "$virtwww_file.XXXXXXXXXXXXXXX"`
 if [ $? -ne 0 ]; then
diff --git a/libexec/config-vhost-names b/libexec/config-vhost-names
--- a/libexec/config-vhost-names
+++ b/libexec/config-vhost-names
@@ -134,13 +134,10 @@ if [ "${0:0:1}" != "/" ]; then
   error "please call this script with the full path"
 fi
 
-dir=`dirname "$0"`
-dir=`readlink -e "$dir"`
-if [ ! -d "$dir" ]; then
-  error "couldn't determine current dir"
-fi
+self_bin=`readlink -e "$0"`
+dir=`dirname "$self_bin"`
 
-we_dir=`dirname "$dir"`
+we_dir=`readlink -e "$dir/.."`
 
 lib_file="$we_dir/lib/functions"
 if ! source "$lib_file"; then
@@ -167,10 +164,10 @@ do
       ;;
   esac
 done
-shift `expr $OPTIND - 1`
+[ $OPTIND -gt 1 ] && shift `expr $OPTIND - 1`
 
 vhost="$1"
-if ! "$dir/check-vhost-name" archive "$vhost"; then
+if ! "$dir/check-vhost-name" name-only "$vhost"; then
   error "vhost argument is in an invalid format"
 fi
 user="w_$vhost"
@@ -186,6 +183,23 @@ if [ $? -ne 0 ]; then
   error "unable to get base domain name for apache virtual hosts"
 fi
 
+lib_file="$we_dir/lib/functions"
+vars_file="$we_dir/lib/variables"
+
+for inc_file in "$lib_file" "$vars_file"; do
+  if ! source "$inc_file"; then
+    error "unable to source file '$inc_file'"
+  fi
+done
+
+if get_metadata_value "$config_dir" "$DEVPANEL_VHOST_LOCK_FLAG" &>/dev/null; then
+  error "vhost $vhost is locked. Can't work on a locked vhost."
+fi
+
+# second check-vhost-name validation, to validate homedir, etc
+if ! "$dir/check-vhost-name" archive "$vhost"; then
+  exit 1
+fi
 mode=""
 vhost_base="$config_dir/apache_vhost:0"
 base_host_link="$vhost_base:_:ServerName"
diff --git a/libexec/lock-vhost b/libexec/lock-vhost
--- a/libexec/lock-vhost
+++ b/libexec/lock-vhost
@@ -1,8 +1,5 @@
 #!/bin/bash
-dir=`dirname "$0"`
-dir_bin="$dir/../bin"
-vhost="$1"
-user="w_$vhost"
+
 run()
 {
   echo "  Running $@"
@@ -30,15 +27,65 @@ home()
   perl -le '@a=getpwnam $ARGV[0] or die "no such user $ARGV[0]\n"; print $a[7]'  "$user"
 }
 
-$dir/check-vhost-name lock "$vhost" || error
+# main
 
-home=`home "$user"` || error "cannot get $user's home dir"
+self_bin=`readlink -e "$0"`
+cmd_name=`basename "$0"`
+dir=`dirname "$self_bin"`
+dir_bin=`readlink -m "$dir/../bin"`
+devpanel_dir=`readlink -e "$dir/.."`
 
-echo "Disabling apache virtual host"
-$dir/lock-vhost-apache "$vhost" || error
-echo "Locking user's password"
-run "$dir/ignore-quota" "$user" 8 usermod -L "$user" || error
-echo "Locking .ssh/authorized_keys"
-run_su "$dir_bin/lock-vhost-ssh" || error
-echo "Locking crontab"
-run_su_ignore_quota "$dir_bin/lock-vhost-crontab" || error
+lib_file="$devpanel_dir/lib/functions"
+vars_file="$devpanel_dir/lib/variables"
+for inc_file in "$lib_file" "$vars_file"; do
+  if ! source "$inc_file"; then
+    error "unable to source file '$inc_file'"
+  fi
+done
+
+vhost="$1"
+user="w_$vhost"
+vhost_config_dir="$devpanel_dir/config/vhosts/$vhost"
+
+if [ "$cmd_name" == "lock-vhost" ]; then
+  $dir/check-vhost-name lock "$vhost" || error
+elif [ "$cmd_name" == "unlock-vhost" ]; then
+  $dir/check-vhost-name unlock "$vhost" || error
+fi
+
+trap 'exit 1' INT TERM HUP
+if lock_path "$vhost_config_dir"; then
+  trap 'unlock_path "$vhost_config_dir"' EXIT
+else
+  exit 1
+fi
+
+if [ "$cmd_name" == "lock-vhost" ]; then
+  # locking all services on the vhost
+  echo "Disabling apache virtual host"
+  "$dir/lock-vhost-apache" "$vhost" || error
+
+  echo "Locking user's password"
+  run "$dir/ignore-quota" "$user" 8 usermod -L "$user" || error
+
+  echo "Locking .ssh/authorized_keys"
+  run_su "$dir_bin/lock-vhost-ssh" || error
+
+  echo "Locking crontab"
+  run_su_ignore_quota "$dir_bin/lock-vhost-crontab" || error
+elif [ "$cmd_name" == "unlock-vhost" ]; then
+  # un-locking all services
+  echo "Enabling apache virtual host"
+  "$dir/unlock-vhost-apache" "$vhost" || error
+
+  echo "Unlocking user's password"
+  run "$dir/ignore-quota" "$user" 8 usermod -U "$user" || error
+
+  echo "Unlocking .ssh/authorized_keys"
+  run_su "$dir_bin/unlock-vhost-ssh" || error
+
+  echo "Unlocking crontab"
+  run_su_ignore_quota "$dir_bin/unlock-vhost-crontab" || error
+else
+  error "unknown command name (was this file renamed?)"
+fi
diff --git a/libexec/lock-vhost-apache b/libexec/lock-vhost-apache
--- a/libexec/lock-vhost-apache
+++ b/libexec/lock-vhost-apache
@@ -1,22 +1,9 @@
 #!/bin/bash
-dir=`dirname "$0"`
-vhost="$1"
-user="w_$vhost"
-apache_config_dir="$dir/../config/os/pathnames/etc/apache_vhosts"
-apache_config="$apache_config_dir/$user.conf"
-apache_config_locked="$apache_config.locked"
-$dir/check-vhost-name lock "$vhost" || exit 1
-apachectl="$dir/../config/os/pathnames/sbin/apachectl"
 
-backup()
-{ 
-  local filename="$1"
-  if [ -f "$filename" ]
-  then
-     TMP=`mktemp "$filename.renamed.XXXXXXXX"` || exit 1
-     cat "$filename" >$TMP || exit 1
-     rm "$filename" || exit 1
-  fi
+error()
+{
+  echo "ERROR${1+: }$@" >&2
+  exit 1
 }
 
 run()
@@ -25,50 +12,98 @@ run()
   "$@"
 }
 
-error()
-{
-  echo "ERROR${1+: }$@" >&2
+usage() {
+  echo "Usage: `basename "$0"` <vhost>"
   exit 1
 }
 
-[ -r "$apache_config" ] || error "cannot find $apache_config"
+# main
+[ $# -lt 1 ] && usage
 
-echo "Modifying $apache_config"
-output=`perl -e '
-     use strict;
-     my %macro = map { $_ => 1 } qw(Vhost-simple-dummy Vhost-simple Vhost-simple-SSL Vhost-simple-SSL-wildcard Vhost-simple-SSL-intermediate);
-     sub locked
-     {
-        my $macro = shift;
-        die "unknown macro $macro\n" unless defined $macro{$macro};
-        return "$macro-locked";
-     }
-  while(<>)
-  {
-    if (/^\s*$/ || /^\s*#/) { print; next; }
-    if (s/^(\s*Use\s+)(\S+)/"$1".(locked $2)/e) { print; next }
-    die "unexpected directive in $ARGV line $., please comment it own manually before locking: $_";
-  }
-' "$apache_config"` || error
+self_bin=`readlink -e "$0"`
+cmd_name=`basename "$0"`
+dir=`dirname "$self_bin"`
+devpanel_dir=`readlink -e "$dir/.."`
 
-echo "Saving old $apache_config as $apache_config_locked"
-backup "$apache_config_locked" || error
-cat "$apache_config" >"$apache_config_locked" || error
-echo "$output" >"$apache_config" || error
+vhost="$1"
+user="w_$vhost"
 
-echo Validating apache config syntax
-if ! run "$apachectl" configtest  
-then
-  echo Syntax validation failed, reverting the changes
-  if cat "$apache_config_locked" >"$apache_config" &&
-     rm "$apache_config_locked" &&
-     run "$apachectl" configtest
-   then
-        error Aborted
-   else
-	error "Apache config is broken, call a system administrator NOW!"
-   fi
+lib_file="$devpanel_dir/lib/functions"
+vars_file="$devpanel_dir/lib/variables"
+for inc_file in "$lib_file" "$vars_file"; do
+  if ! source "$inc_file"; then
+    error "unable to source file '$inc_file'"
+  fi
+done
+
+
+assign_deref_os_fs_path_ex_or_exit apache_config_dir "$devpanel_dir" \
+  pathnames/etc/apache_vhosts
+
+apache_config="$apache_config_dir/$user.conf"
+
+if [ "$cmd_name" == "lock-vhost" ]; then
+  $dir/check-vhost-name lock "$vhost" || exit 1
+elif [ "$cmd_name" == "unlock-vhost" ]; then
+  $dir/check-vhost-name unlock "$vhost" || exit 1
 fi
 
-echo Restarting apache
-run "$apachectl" graceful || error echo "Cannot restart apache, call a system administrator NOW!"
+assign_deref_os_fs_path_ex_or_exit apachectl "$devpanel_dir" \
+  pathnames/sbin/apachectl
+
+hash -p "$apachectl" apachectl
+
+vhost_metadata_dir=`readlink -e "$devpanel_dir/config/vhosts/$vhost"`
+if [ $? -ne 0 ]; then
+  error "couldn't find path '$devpanel_dir/config/vhosts/$vhost'"
+fi
+
+if ! run apachectl configtest;  then
+  error "Apache config seems already broken, won't try to change anything."
+fi
+
+if [ "$cmd_name" == "lock-vhost-apache" ]; then
+
+  [ -r "$apache_config" ] || \
+    error "cannot find apache config file '$apache_config'"
+
+  apache_locked_file="$apache_config.locked"
+  mv -f "$apache_config" "$apache_locked_file"
+  if [ $? -ne 0 ]; then
+    error "unable to move $apache_config to $apache_config.locked"
+  fi
+
+  echo "set $DEVPANEL_VHOST_LOCK_FLAG 1" | \
+    "$dir/apache-metadata-handler" -n "$vhost"
+  if [ $? -ne 0 ]; then
+    mv -f "$apache_locked_file" "$apache_config" # revert back the move
+    error "unable to update apache metadata"
+  fi
+
+  if apachectl configtest;  then
+    apachectl graceful && echo "Successfully locked apache vhost"
+  else
+    echo "Warning: apache vhost was locked, but Apache config is broken" 1>&2
+  fi
+
+  exit 0
+elif [ "$cmd_name" == "unlock-vhost-apache" ]; then
+  metadata_str="rm $DEVPANEL_VHOST_LOCK_FLAG"$'\n'
+  echo "$metadata_str" | "$dir/apache-metadata-handler" -n "$vhost"
+  if [ $? -ne 0 ]; then
+    error "unable to remove locked flag from vhost '$vhost'"
+  fi
+
+  "$dir/config-vhost-apache" "$vhost"
+  status=$?
+  if [ $status -eq 0 ]; then
+    echo "Successfully created apache config on vhost '$vhost'"
+    exit 0
+  else
+    error "failed to unlock apache on vhost '$vhost'"
+  fi
+else
+  error "unknown command (was this file renamed?)"
+fi
+
+
