more flexible Apache configuration

diff --git a/libexec/config-vhost-apache b/libexec/config-vhost-apache
--- a/libexec/config-vhost-apache
+++ b/libexec/config-vhost-apache
@@ -1,128 +1,324 @@
 #!/bin/bash
 error() { echo "ERROR${@+: }$@" >&2; exit 1; }
+
+usage() {
+  local prog=`basename "$0"`
+  echo "
+  Usage: $prog <vhost>
+
+  This script generates apache mod_macro configuration files.
+"
+
+  exit 1
+}
+
 run()
 {
   echo "  running $@"
   "$@"
 }
-backup()
-{ 
-  local filename="$1"
-  if [ -f "$filename" ]
-  then
-     TMP=`mktemp "$filename.renamed.XXXXXXXX"` || exit 1
-     cat "$filename" >$TMP || exit 1
-     rm "$filename" || exit 1
+
+format_hostname() {
+  local server_hostname="$1"
+  local local_hostname="$2"
+  local hostname_stripped="" new_hostname=""
+
+  # remove the server hostname from the end of name
+  hostname_stripped=${local_hostname%$server_hostname}
+  if [ "$hostname_stripped" == "$local_hostname" ]; then
+    # is not a simple alias to the host domain...add a dot
+    # to the end of the name
+    new_hostname+="${local_hostname}."
+  else
+    new_hostname="$hostname_stripped"
   fi
+
+  echo -n "$new_hostname"
 }
+
+# main
+
+[ $# -eq 0 -o -z "$1" ] && usage
+
 dir=`dirname "$0"`
-apachectl="$dir/../config/os/pathnames/sbin/apachectl"
+
 vhost="$1"
 user="w_$vhost"
-apache_config_dir="$dir/../config/os/pathnames/etc/apache_vhosts"
-apache_config_dir_removed="$dir/../config/os/pathnames/etc/apache_vhosts_removed"
-apache_config="$apache_config_dir/$user.conf"
-apache_config_old="$apache_config_dir_removed/$user.conf.old"
-shift
-$dir/check-vhost-name config "$vhost" || error
-config_dir="/opt/webenabled/config/vhosts/$vhost"
-default_apache_macro=Vhost-simple
-macro_file=/opt/webenabled/config/names/apache-macro
-if [ -s "$macro_file" ]
-then
-  default_apache_macro=`cat "$macro_file"`
-  if ! echo "$default_apache_macro"|grep '^Vhost-[-_A-Za-z0-9]*$'
-  then
-    echo "Invalid macro name in $macro_file"
-    exit 1
-  fi
+
+"$dir/check-vhost-name" config "$vhost" || error
+
+we_base_dir=`readlink -e "$dir/.."`
+
+lib_file="$we_base_dir/lib/functions"
+if ! source "$lib_file"; then
+  error "unable to source lib file '$lib_file'"
 fi
 
-echo "Configuring apache for the following names:"
-names_with_ip=`$dir/list-vhost-names -a "$vhost"` || error
-echo "$names_with_ip"
+assign_deref_os_fs_path_ex_or_exit apachectl "$we_base_dir" pathnames/sbin/apachectl
+assign_deref_os_fs_path_ex_or_exit virtwww_dir "$we_base_dir" pathnames/etc/apache_vhosts
 
-[ -r "$apache_config" ] || error "cannot find $apache_config"
+virtwww_file="$virtwww_dir/$user.conf"
+virtwww_file_old="$virtwww_file.old"
+config_dir="$we_base_dir/config/vhosts/$vhost"
+apache_svc_config_dir="$we_base_dir/config/packages/apache_vhost"
+server_hostname_file="$we_base_dir/config/names/default"
 
-change_ssl_settings=0
-fqdn=$vhost.`$dir/list-vhost-names-default` || true
+tmp_new_vhost_file=`mktemp "$virtwww_file.XXXXXXXXXXXXXXX"`
+if [ $? -ne 0 ]; then
+  error "unable to create temporary file"
+fi
+trap 'ex=$?; rm -f "$tmp_new_vhost_file"; exit $ex;' EXIT INT TERM QUIT
 
-output=`echo "$names_with_ip"|perl -e '
-  use strict;
-  my $vhost = shift;
-  my $fqdn = shift;
-  my $default_apache_macro = shift;
-  my $verbatim_flag;
-  my $verbatim = "";
-  my %domains_for_ip;
-  my %ssl_for_ip;
-  my %ssl_intermediate_for_ip;
-  my $template;
-  my ($template_directive, $template_username, $template_ip, $template_subdomain, $template_domain, $template_aliases, $template_home, $template_token);
-  while(<STDIN>)
-  {
-    chomp;
-    my $ip = "*";
-    my ($domain, @options) = split(/\s+/, $_);
-    $domain ne "" or die "invalid domain";
-    my %options = map { /^([^=]+)=(.*)/ ? ($1, $2) : ($_, "yes") } @options;
-    $ip = $options{ip} if defined $options{ip};
-    $domain = "$domain www.$domain" unless $domain =~ /^www\./;
-    if (defined $domains_for_ip{$ip}) { $domains_for_ip{$ip} .= " " } else { $domains_for_ip{$ip} = "" }
-    $domains_for_ip{$ip} .= $domain;
-    $ssl_for_ip{$ip} = 1 if $options{ssl};
-    $ssl_intermediate_for_ip{$ip} = 1 if $options{ssl_intermediate};
-  }
-  while(<>)
-  {
-    $verbatim_flag = 1 if (/^\s*#\s*webenabled_custom\b/);
-    $verbatim .= $_ if $verbatim_flag;
-    my @s = /^Use\s+(Vhost-simple|Vhost-simple-SSL|Vhost-simple-dummy|Vhost-simple-SSL-wildcard|Vhost-simple-SSL-wildcard-dummy|Vhost-simple-SSL-intermediate|Vhost-simple-SSL-intermediate-dummy)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+"([^"]*)"\s+"([^"]*)"\s+(\S+).*/si;
-    if (@s)
-    {
-      ($template_directive, $template_username, $template_ip, $template_subdomain, $template_domain, $template_aliases, $template_home, $template_token) = @s if @s;
-      $template = 1;
-    }
-  }
-  die "no template" unless $template;
-  for my $ip (sort keys %domains_for_ip)
-  {
+vhost_bkp_file=`mktemp "$virtwww_file.bkp.XXXXXXXXXXXXXXX"`
+if [ $? -ne 0 ]; then
+  error "unable to create a temporary backup file"
+fi
+trap 'ex=$?; rm -f "$tmp_new_vhost_file"; rm -f "$vhost_bkp_file"; exit $ex;' \
+ EXIT INT TERM QUIT
 
-    if ($ip ne "*")
-    {
-      print "NameVirtualHost $ip:80\n";
-      print "NameVirtualHost $ip:443\n" if $default_apache_macro =~ /SSL/ || $ssl_for_ip{$ip};
-    }
-    # Vhost-simple-wildcard cannot be used for any IP if Vhost-simple is used for at least one IP
-    my $apache_macro = (grep { $_ ne "*" } keys %ssl_for_ip) ? "Vhost-simple" : $default_apache_macro;
-    if ($ssl_for_ip{$ip})
-    {
-      $apache_macro = $ssl_intermediate_for_ip{$ip} ? "Vhost-simple-SSL-intermediate" : "Vhost-simple-SSL";
-    }
-    print "Use $apache_macro $template_username $ip $template_subdomain $template_domain \"$domains_for_ip{$ip}\" \"$template_home\" $template_token\n";
-  }
-  print $verbatim;
-' "$vhost" "$fqdn" "$default_apache_macro" "$apache_config"` || error
+if ! cat "$virtwww_file" > "$vhost_bkp_file"; then
+  error "unable to write a copy of '$virtwww_file' into '$vhost_bkp_file'"
+fi
 
-echo "Saving old $apache_config as $apache_config_old"
-backup "$apache_config_old" || error
-cat "$apache_config" >"$apache_config_old" || error
-echo "$output" >"$apache_config" || error
+if ! server_hostname=`deref_contents "$server_hostname_file"`; then
+  error "unable to get server hostname from link '$server_hostname_file'"
+fi
+
+for F in "$config_dir/apache_vhost:"[0-9]; do
+  if [ "$F" == "$config_dir/apache_vhost:[0-9]" ]; then
+    error "this vhost has the configuration broken"
+  fi
+
+  sed_line=""
+  sed_include_str=""
+  vhost_base_str=`basename "$F"`
+
+  # 'template' is a special variable
+  # as it's used below, and not set as a variable
+  if [ -L "$config_dir/$vhost_base_str:_:template" ]; then
+    template_link="$config_dir/$vhost_base_str:_:template"
+  else
+    template_link="$apache_svc_config_dir/_:template"
+  fi
+
+  vhost_template=`deref_contents "$template_link"`
+  if [ $? -ne 0 ]; then
+    error "unable to get vhost template name"
+  fi
+
+  # rename the variable below, use a dedicated variable for apache_svc
+  tmpl_basename=`basename "$vhost_template"`
+  local_template="$apache_svc_config_dir/templates/local/$tmpl_basename"
+  template_file="$apache_svc_config_dir/templates/$tmpl_basename"
+
+  if [ -f "$local_template" ]; then
+    template_file="$local_template"
+  elif [ ! -f "$template_file" ]; then
+    error "missing template file '$template_file'"
+  fi
+
+  if ! cat "$template_file" >>"$tmp_new_vhost_file"; then
+    error "unable to copy template contents to '$tmp_new_vhost_file'"
+  fi
+
+  # a few special non-verbatim parameters
+  #
+  for param in IP Port; do
+    # check for these parameters in the following order:
+    # 1) vhost     2) template   3) server
+    if [ -L "$config_dir/$vhost_base_str:_:$param" ]; then
+      param_link="$config_dir/$vhost_base_str:_:$param"
+    elif [ -L "$apache_svc_config_dir/template:$vhost_template:$param" ]; then
+      param_link="$apache_svc_config_dir/template:$vhost_template:$param"
+    elif [ -L "$apache_svc_config_dir/_:$param" ]; then
+      param_link="$apache_svc_config_dir/_:$param"
+    else
+      error "unable to determine apache parameter $param"
+    fi
+
+    param_value=`readlink "$param_link"`
+    param_name_escaped=`escape_sed "${param^^}"`
+    param_value_escaped=`escape_sed "$param_value"`
+
+    sed_line+="s/@@__PARAM_${param_name_escaped}__@@/$param_value_escaped/g;"
+  done
+
+  # a few special verbatim parameters
+  # these are about system defaults, to avoid having to create links on all
+  # vhosts
+  #
+  # This way when a larger system wide change happens, we just update it
+  # once and it applies to all vhosts
+  params_str=""
+  for param in ServerName DocumentRoot SuexecUserGroup CustomLog ErrorLog; do
+    # check for these parameters in the following order:
+    # 1) vhost     2) template   3) server
+    if [ -L "$config_dir/$vhost_base_str:_:$param" ]; then
+      param_link="$config_dir/$vhost_base_str:_:$param"
+    elif [ -L "$apache_svc_config_dir/template:$vhost_template:_:$param" ]; then
+      param_link="$apache_svc_config_dir/template:$vhost_template:_:$param"
+    elif [ -L "$apache_svc_config_dir/_:$param" ]; then
+      param_link="$apache_svc_config_dir/_:$param"
+    else
+      error "unable to determine apache parameter $param"
+    fi
+
+    param_value=`readlink "$param_link"`
+    param_name_escaped=`escape_sed "${param^^}"`
+    param_value_escaped=`escape_sed "$param_value"`
+
+    params_str+="  $param $param_value"$'\n'
+    sed_line+="s/@@__PARAM_${param_name_escaped}__@@/$param_value_escaped/g;"
+  done
+
+  # generic Apache parameters for the template, available system wide.
+  # Have the same intent of the previous one, to make it easy to distribute
+  # mass updates on system templates
+  for P in "$apache_svc_config_dir/template:$vhost_template:param:"[0-9]:*; do
+    [ "$P" == "$apache_svc_config_dir/template:$vhost_template:param:[0-9]:*" ] && break
+
+    param_basename=`basename "$P"`
+    param_name="${param_basename##*:}"
+    param_name_escaped=`escape_sed "$param_name"`
+    param_value=`readlink "$P"`
+    param_value_escaped=`escape_sed "$param_value"`
+
+    # store the params on the sed_line, so it can eventually be re-used in
+    # templates
+    sed_line+="s/@@__PARAM_${param_name_escaped}__@@/$param_value_escaped/g;"
+
+    params_str+="  $param_name $param_value"$'\n'
+  done
+
+
+  # other less important (or less widely-distributed parameters)
+  for P in "$config_dir/$vhost_base_str:param:"[0-9]:*; do
+    [ "$P" == "$config_dir/$vhost_base_str:param:[0-9]:*" ] && break
+    param_basename=`basename "$P"`
+    param_name="${param_basename##*:}"
+    param_name_escaped=`escape_sed "$param_name"`
+    param_value=`readlink "$P"`
+    param_value_escaped=`escape_sed "$param_value"`
+
+    # store the params on the sed_line, so it can eventually be re-used in
+    # templates
+    sed_line+="s/@@__PARAM_${param_name_escaped}__@@/$param_value_escaped/g;"
+
+    params_str+="  $param_name $param_value"$'\n'
+  done
+
+  if [ -n "$params_str" ]; then
+    params_str_escaped=`escape_sed "$params_str"`
+    sed_line+="s/^[[:space:]]*#[[:space:]]*@@__PARAMS__@@/$params_str_escaped/g;"
+  else
+    sed_line+="/^[[:space:]]*#[[:space:]]*@@__PARAMS__@@/d;"
+  fi
+
+  sys_inc_base="$apache_svc_config_dir/template:$vhost_template:include:"
+
+  for inc in "$sys_inc_base"*; do
+    [ "$inc" == "$sys_inc_base*" ] && break
+
+    include_file=`readlink "$inc"`
+    if [ $? -ne 0 -o -z "$include_file" ]; then
+      error "unable to de-reference file '$inc'"
+    fi
+
+    tmpl_file="$apache_svc_config_dir/templates/$include_file"
+    sys_include_str+=`cat "$tmpl_file"`
+  done
+
+  if [ -n "$sys_include_str" ]; then
+    sys_include_str_escaped=`escape_sed "$sys_include_str"`
+    sed_include_str+="s/^[[:space:]]*#[[:space:]]*@@__SYSTEM_INCLUDES__@@/$sys_include_str_escaped/g;"
+  else
+    sed_include_str+="/^[[:space:]]*#[[:space:]]*@@__SYSTEM_INCLUDES__@@/d;"
+  fi
+
+  usr_inc_base="$config_dir/$vhost_base_str:_:include:"
+  for inc in "$usr_inc_base"*; do
+    [ "$inc" == "$usr_inc_base*" ] && break
+
+    include_file=`deref_contents_or_die "$inc"`
+    if [ $? -ne 0 -o -z "$include_file" ]; then
+      error "unable to de-reference file '$inc'"
+    fi
+    tmpl_file="$apache_svc_config_dir/templates/$include_file"
+
+    usr_include_str+=`cat "$tmpl_file"`
+  done
+
+  if [ -n "$usr_include_str" ]; then
+    usr_include_str_escaped=`escape_sed "$usr_include_str"`
+    sed_include_str+="s/^[[:space:]]*#[[:space:]]*@@__USER_INCLUDES__@@/$usr_include_str_escaped/g;"
+  else
+    sed_include_str+="/^[[:space:]]*#[[:space:]]*@@__USER_INCLUDES__@@/d;"
+  fi
+
+  for V in "$config_dir/$vhost_base_str:var:"*; do
+    [ "$V" == "$config_dir/$vhost_base_str:var:*" ] && break
+    var_basename=`basename "$V"`
+    var_name=${var_basename##*:var:}
+    var_value=`readlink "$V"`
+
+    var_name_escaped=`escape_sed "${var_name^^}"`
+    var_value_escaped=`escape_sed "$var_value"`
+
+    sed_line+="s/@@__VAR_${var_name_escaped}__@@/$var_value_escape/g;"
+  done
+
+  # first include all external files
+  sed -i -e "$sed_include_str" "$tmp_new_vhost_file"
+  if [ $? -ne 0 ]; then
+    error "unable to update include lines on file '$tmp_new_vhost_file'"
+  fi
+
+  sed_line+="s/@@__SERVER_HOSTNAME__@@/`escape_sed "$server_hostname"`/g;"
+  sed_line+="s/@@__VHOST__@@/`escape_sed "$vhost"`/g;"
+  sed_line+="s/@@__TEMPLATE_FILE__@@/`escape_sed "$template_file"`/g;"
+  sed_line+="s/@@__TEMPLATE_FILE_BASENAME__@@/`escape_sed "$vhost_template"`/g;"
+
+  # then replace all parameters and variables
+  sed -i -e "$sed_line" "$tmp_new_vhost_file"
+  if [ $? -ne 0 ]; then
+    error "unable to replace variables"
+  fi
+done
 
 echo Validating apache config syntax
 
-if ! run "$apachectl" configtest  
-then
-  echo Syntax validation failed, reverting the changes
-  if cat "$apache_config_old" >"$apache_config" &&
-     rm "$apache_config_old" &&
-     run "$apachectl" configtest
-   then
-        error Aborted
-   else
-	error "Apache config is broken, call a system administrator NOW!"
-   fi
+if ! cat "$tmp_new_vhost_file" > "$virtwww_file"; then
+  error "unable to copy contents from '$tmp_new_vhost_file'"\
+" to '$virtwww_file'"
 fi
 
+if ! "$apachectl" configtest; then
+  echo Syntax validation failed, reverting the changes
+  if ! cat "$vhost_bkp_file" >"$virtwww_file"; then
+    error "unable to copy back the contents from $vhost_bkp_file"\
+" to '$virtwww_file'"
+  fi
+
+  echo
+  echo "-- BROKEN TEMPLATE FILE (?) --"
+  cat "$tmp_new_vhost_file"
+  echo "-- END OF TEMPLATE --"
+  echo
+
+  if ! "$apachectl" configtest; then
+    error "Apache config is broken, call a system administrator NOW!"
+  fi
+else
+  cp -f "$vhost_bkp_file" "$virtwww_file_old"
+  if [ $? -eq 0 ]; then
+    echo "Successfully saved previous vhost file on $virtwww_file_old"
+  else
+    echo "Warning: unable to save a copy of the old file (not critical)" 1>&2
+  fi
+fi
+
+echo "Successfully updated vhost $vhost on file $virtwww_file"
 echo Restarting apache
-run "$apachectl" graceful || error echo "Cannot restart apache, call a system administrator NOW!"
+
+run "$apachectl" graceful || \
+  error "Cannot restart apache, call a system administrator NOW!"
diff --git a/libexec/create-virtwww b/libexec/create-virtwww
--- a/libexec/create-virtwww
+++ b/libexec/create-virtwww
@@ -13,36 +13,43 @@ do
 done
 shift `expr $OPTIND - 1`
 
-progname="$(basename $0)"
-dir="$(dirname $0)"
+progname=$(basename "$0")
+dir=$(dirname "$0")
+
+we_base=`readlink "$dir/.."`
+dir_bin="$we_base/bin"
+
 pathnames="$dir/../config/os/pathnames"
-macro_file="$dir/../config/names/apache-macro"
-dir_bin="$dir/../bin"
-chcgi="$pathnames/sbin/chcgi"
-apachectl="$pathnames/sbin/apachectl"
-edquota="$pathnames/sbin/edquota"
+#macro_file="$dir/../config/names/apache-macro"
+
+lib_file="$we_base/lib/functions"
+if ! source "$lib_file"; then
+  error "unable to source lib file '$lib_file'"
+fi
+
+assign_deref_os_fs_path_ex_or_exit chcgi     "$we_base" pathnames/sbin/chcgi
+assign_deref_os_fs_path_ex_or_exit apachectl "$we_base" pathnames/sbin/apachectl
+assign_deref_os_fs_path_ex_or_exit edquota   "$we_base" pathnames/sbin/edquota
+assign_deref_os_fs_path_ex_or_exit VIRTWWW_LOGDIR "$we_base" pathnames/var/log/apache_vhosts
+assign_deref_os_fs_path_ex_or_exit VIRTWWW_CFGDIR "$we_base" pathnames/etc/apache_vhosts
+
 passgen="$dir_bin/genpass"
 WEBSITES_HOME=/home/clients/websites
-VIRTWWW_LOGDIR=`readlink "$dir/../config/os/pathnames/var/log/apache_vhosts"`
-VIRTWWW_CFGDIR="$pathnames/etc/apache_vhosts"
+
 ADDON_GROUPS=
 ADDON_GROUPS_FILE="$dir/../config/os/names/groups"
-apache_group=`head -1 $dir/../config/os/names/apache-exec.group`
+
+assign_deref_os_prop_or_exit apache_group          "$we_base" names/apache-exec.group
+assign_deref_os_prop_or_exit apache_vhost_template "$we_base" names/apache_vhost_template
+assign_deref_os_prop_or_exit tools_vhost_template  "$we_base" names/tools_vhost_template
+ 
+
 if [ -s "$ADDON_GROUPS_FILE" ]
 then
   ADDON_GROUPS=`paste -sd, <"$ADDON_GROUPS_FILE"`
 fi
 MYSQL_LOCAL=yes
-macro=Vhost-simple
-if [ -s "$macro_file" ]
-then
-  macro=`cat "$macro_file"`
-  if ! echo "$macro"|grep '^Vhost-[-_A-Za-z0-9]*$'
-  then
-    echo "Invalid macro name in $macro_file"
-    exit 1
-  fi
-fi
+
 
 function usage() {
     cat << EOF
@@ -321,37 +328,6 @@ else
     echo 'failed'
 fi
 
-# Thu Oct 14 2005 20:05 PM (galaxy@initsoft.com): added this section
-echo -n '+ setting up Webalizer directory ... '
-su - -c "
-set -e
-test ! -d \"$VHOST_HOME/public_html/gen/$PRIMARY_NAME-usage\" && mkdir \"$VHOST_HOME/public_html/gen/$PRIMARY_NAME-usage\"
-chmod 0711 \"$VHOST_HOME/public_html/gen/$PRIMARY_NAME-usage\"
-cat << EOF > \"$VHOST_HOME/public_html/gen/$PRIMARY_NAME-usage/.htaccess\"
-DirectoryIndex index.html
-
-AuthUserFile \"$VHOST_HOME/.htpasswd.stats\"
-AuthType Basic
-AuthName "Statistics"
-Require valid-user
-Satisfy all
-Deny from all
-Allow from all
-Order Deny,Allow
-EOF
-chmod 0644 \"$VHOST_HOME/public_html/gen/$PRIMARY_NAME-usage/.htaccess\"
-cat << EOF > \"$VHOST_HOME/.htpasswd.stats\"
-stats:\\\$apr1\\\$UtFyb/..\\\$CJolXmFkT3rgUuPVWU6Pf.
-EOF
-chmod 0644 \"$VHOST_HOME/.htpasswd.stats\"
-set +e
-" -s /bin/bash "$ACCOUNT_NAME"
-if [ "$?" -eq 0 ]; then
-    echo 'done'
-else
-    echo 'failed'
-fi
-
 echo -n '+ configuring httpd log directory for virtual host ... '
 set -e
 mkdir -p -m 0750 "$VIRTWWW_LOGDIR/$ACCOUNT_NAME"
@@ -362,20 +338,6 @@ touch "$VIRTWWW_LOGDIR/$ACCOUNT_NAME/$PRIMARY_NAME-"{access,error}_log
 chmod 0644 "$VIRTWWW_LOGDIR/$ACCOUNT_NAME/$PRIMARY_NAME-"{access,error}_log
 set +e
 echo 'done'
-
-# (GM): XXX: unsafe - race!
-echo -n '+ configuring WIT (Webalize-IT) ... '
-if [ -w /opt/wit/config/wit.conf ]
-then
-  echo "$ACCOUNT_NAME:$(echo -n $DOMAIN_NAMES | cut -f1 -d' ' | cut -f1 -d','):$VIRTWWW_LOGDIR/$ACCOUNT_NAME/$PRIMARY_NAME-access_log.1:$VHOST_HOME/public_html/gen/$PRIMARY_NAME-usage:" >> /opt/wit/config/wit.conf
-  if [ "$?" -eq 0 ]; then
-      echo 'done'
-  else
-      echo 'failed'
-  fi
-else
-  echo "skipped (wit.conf not found)"
-fi
 
 echo '+ enabling personal CGIs:'
 "$chcgi" "$ACCOUNT_NAME" +0
@@ -428,31 +390,6 @@ for domain in $DOMAIN_NAMES ; do
     count=$(($count+1))
 done
 
-echo -n '+ generating phpmyadmin token ... '
-PHPMYADMINTOKEN="$($passgen 2>/dev/null)"
-if [ $? -eq 0 ]; then
-        echo 'done'
-else
-        echo 'failed'
-fi
-
-if [ -n "$VHOST_MULTISITE" ]; then
-    cat << EOF >> "$TMPFILE"
-Use Vhost-multi$dummy $ACCOUNT_NAME * $PRIMARY_NAME $PRIMARY_DOMAIN "${ALIAS_LIST:-$PRIMARY_NAME.$PRIMARY_DOMAIN}" "$WEBSITES_HOME/$ACCOUNT_NAME" $PHPMYADMINTOKEN
-EOF
-else
-    cat << EOF >> "$TMPFILE"
-Use $macro$dummy $ACCOUNT_NAME * $PRIMARY_NAME $PRIMARY_DOMAIN "${ALIAS_LIST:-$PRIMARY_NAME.$PRIMARY_DOMAIN}" "$WEBSITES_HOME/$ACCOUNT_NAME" $PHPMYADMINTOKEN
-EOF
-fi
-
-config_dir="/opt/webenabled/config/vhosts/$PRIMARY_NAME"
-mkdir -p "$config_dir/apache-include"
-if [ -r /opt/webenabled/config/features/enabled/cloud9 ]
-then
-  touch "$config_dir/apache-include/cloud9"
-fi
-
 if ! ln "$TMPFILE" "$VIRTWWW_CFGDIR/$ACCOUNT_NAME.conf" 2>/dev/null ; then
 	echo 'failed'
 	echo "$0: could not add configuration for '$ACCOUNT_NAME'"
@@ -468,6 +405,12 @@ else
   fi
 fi
 echo 'done'
+
+vhost_prefixed_f="$config_dir/apache_vhost:0"
+tools_vhost_prefixed="$config_dir/apache_vhost:1"
+
+ln -s "$apache_vhost_template" "$vhost_prefixed_f:_:template"
+ln -s "$tools_vhost_template" "$vhost_prefixed_f:_:template"
 
 echo -n '+ checking Apache configuration integrity ... '
 RESULT="$("$apachectl" configtest 2>&1)"
diff --git a/libexec/restore-vhost b/libexec/restore-vhost
--- a/libexec/restore-vhost
+++ b/libexec/restore-vhost
@@ -237,6 +237,12 @@ do
   fi
   if grep -q "^$subsystem\$" "$archive_dir/db/databases"
   then
+    if ! run_su cd "$HOME" \; $dir_bin/restore-vhost-subsystem \
+      $subsystem_options -n -s "$subsystem"; then
+
+      error "unable to update app configuration files"
+    fi
+
     run_su $dir_bin/restore-vhost-subsystem $subsystem_options -I -s "$subsystem" || exit 1
   fi
 done
diff --git a/libexec/restore-vhost-web b/libexec/restore-vhost-web
--- a/libexec/restore-vhost-web
+++ b/libexec/restore-vhost-web
@@ -67,14 +67,16 @@ done
 
 [ $# -lt 2 ] && usage
 
-dir=`dirname $0`
+dir=`dirname "$0"`
 bin_dir="$dir/../bin"
 vhost="$1"
 user="w_$vhost"
 archive_label="$2"
 
-if ! source "$dir/../lib/functions" ; then
-  echo "Error: unable to load auxiliary functions" 1>&2
+we_base_dir=`readlink "$dir/.."`
+lib_file="$we_base_dir/lib/functions"
+if ! source "$lib_file" ; then
+  echo "Error: unable to load auxiliary functions from '$lib_file'" 1>&2
   exit 1
 fi
 
@@ -117,12 +119,14 @@ fi
 old_user="w_$old_vhost"
 date=`date  +'%Y%m%d'`
 archive_file="$archive_dir/$old_user.tgz"
-apache_config_dir="$dir/../config/os/pathnames/etc/apache_vhosts"
-apache_group=`cat "$dir/../config/os/names/apache.group"`
-chcgi="$dir/../config/os/pathnames/sbin/chcgi"
+apache_config_dir=`deref_os_prop_or_exit "$we_base_dir" pathnames/etc/apache_vhosts`
+apache_group=`deref_os_prop_or_exit "$we_base_dir" names/apache.group`
+chcgi=`deref_os_prop_or_exit "$we_base_dir" pathnames/sbin/chcgi`
+apache_logs_dir=`deref_os_prop_or_exit "$we_base_dir" pathnames/var/log/apache_vhosts`
+
 conf="$apache_config_dir/$user.conf"
 archive_conf="$archive_dir/apache_$old_vhost.conf"
-logs_dir="$dir/../config/os/pathnames/var/log/apache_vhosts/$user"
+logs_dir="$apache_logs_dir/$user"
 archive_logs="$archive_dir/logs_$old_vhost.tgz"
 archive_shadow="$archive_dir/$old_user.shadow"
 archive_crontab="$archive_dir/crontab"
@@ -137,7 +141,7 @@ elif [ $create_vhost -eq 1 -a ! -e "$archive_conf" ]; then
 fi
 
 if [ $create_vhost -eq 1 ] && \
-  ! default_domain=`head -1 "$dir/../config/names/default"`; then
+  ! default_domain=`deref_contents "$we_base_dir/config/names/default"`; then
   error "No default domain"
 elif [ $create_vhost -eq 1 ] && \
   ! echo -e "n\nn\ny"| run $dir/create-virtwww $options "$vhost" "$vhost.$default_domain"; then
