fixes + better error handling

diff --git a/libexec/create-virtwww b/libexec/create-virtwww
--- a/libexec/create-virtwww
+++ b/libexec/create-virtwww
@@ -34,16 +34,15 @@ assign_deref_os_fs_path_ex_or_exit edquota   "$we_base" pathnames/sbin/edquota
 assign_deref_os_fs_path_ex_or_exit VIRTWWW_LOGDIR "$we_base" pathnames/var/log/apache_vhosts
 assign_deref_os_fs_path_ex_or_exit VIRTWWW_CFGDIR "$we_base" pathnames/etc/apache_vhosts
 
-passgen="$dir_bin/genpass"
-WEBSITES_HOME=/home/clients/websites
-
-ADDON_GROUPS=
-ADDON_GROUPS_FILE="$dir/../config/os/names/groups"
-
 assign_deref_os_prop_or_exit apache_group          "$we_base" names/apache-exec.group
 assign_deref_os_prop_or_exit apache_vhost_template "$we_base" names/apache_vhost_template
 assign_deref_os_prop_or_exit tools_vhost_template  "$we_base" names/tools_vhost_template
+assign_deref_os_prop_or_exit WEBSITES_HOME         "$we_base" websites_basedir
  
+passgen="$dir_bin/genpass"
+
+ADDON_GROUPS=
+ADDON_GROUPS_FILE="$dir/../config/os/names/groups"
 
 if [ -s "$ADDON_GROUPS_FILE" ]
 then
@@ -149,7 +148,12 @@ DB_ACCOUNT_NAME="b_$ACCOUNT_NAME"
 vhost="$ACCOUNT_NAME"
 ACCOUNT_NAME="w_$ACCOUNT_NAME"
 
-config_dir="$we_base/config/vhosts/$vhost"
+config_base_dir="$we_base/config/vhosts/"
+config_dir="$config_base_dir/$vhost"
+if [ ! -e "$config_base_dir" ] && \
+  ! mkdir -m 755 "$config_base_dir"; then
+  error "unable to create directory '$config_base_dir'"
+fi
 
 echo
 VHOST_MULTISITE=
@@ -449,8 +453,14 @@ count=0
 for domain in $DOMAIN_NAMES; do
   if [ $count -eq 0 ]; then
     "$dir/config-vhost-names" "$vhost" '*' "$domain"
+    if [ $? -ne 0 ]; then
+      error "unable to set the ServerName for vhost $vhost"
+    fi
   else
     "$dir/config-vhost-names" "$vhost" '+' "$domain"
+    if [ $? -ne 0 ]; then
+      error "unable to add domain $domain to vhost $vhost"
+    fi
   fi 
   count=$(( $count + 1 ))
 done 
