major change to Apache config store
* simplified the parsing and configuration of Apache vhost configuration.
  Now it requires less preconfigured variables.

* it also checks for local/ directories of all templates, parameters and
  variables, so that it's possible to do local customizations on the
  servers.

diff --git a/libexec/create-virtwww b/libexec/create-virtwww
--- a/libexec/create-virtwww
+++ b/libexec/create-virtwww
@@ -35,9 +35,8 @@ assign_deref_os_fs_path_ex_or_exit edquota   "$we_base" pathnames/sbin/edquota
 assign_deref_os_fs_path_ex_or_exit VIRTWWW_LOGDIR "$we_base" pathnames/var/log/apache_vhosts
 assign_deref_os_fs_path_ex_or_exit VIRTWWW_CFGDIR "$we_base" pathnames/etc/apache_vhosts
 
-assign_deref_os_prop_or_exit apache_group          "$we_base" names/apache-exec.group
-assign_deref_os_prop_or_exit tools_vhost_template  "$we_base" names/tools_vhost_template
-assign_deref_os_prop_or_exit WEBSITES_HOME         "$we_base" websites_basedir
+assign_deref_os_prop_or_exit apache_group          "$we_base"  names/apache-exec.group
+assign_deref_os_prop_or_exit WEBSITES_HOME         "$we_base"  websites_basedir
 
 template_file="$we_base/config/packages/apache_vhost/_:template"
 if [ -f "$template_file" ]; then
@@ -156,7 +155,7 @@ DB_ACCOUNT_NAME="b_$ACCOUNT_NAME"
 vhost="$ACCOUNT_NAME"
 ACCOUNT_NAME="w_$ACCOUNT_NAME"
 
-config_base_dir="$we_base/config/vhosts/"
+config_base_dir="$we_base/config/vhosts"
 config_dir="$config_base_dir/$vhost"
 if [ ! -e "$config_base_dir" ] && \
   ! mkdir -m 755 "$config_base_dir"; then
@@ -426,22 +425,30 @@ else
 fi
 echo 'done'
 
-vhost_prefix_f="$config_dir/apache_vhost:"
+vhost_prefix_f="$config_dir/apache_vhost"
 
 if ln -s "devpanel_main" "$vhost_prefix_f:0"; then
   if ! ln -s 0 "$vhost_prefix_f:_:name:devpanel_main"; then
     error "unable to set the name for vhost 0 (devpanel_main)"
+  fi
+
+  if ! ln -s "names/apache_vhost_template" "$vhost_prefix_f:0:_:template_ref"; then
+    error "unable to create template ref $vhost_prefix_f:0:_:template_ref"
   fi
 else
   error "unable to create vhost entry $vhost_prefix_f:0"
 fi
 
 if ln -s "devpanel_tools" "$vhost_prefix_f:1"; then
-  if ! ln -s 1 "$vhost_prefix_f:_:devpanel_tools"; then
+  if ! ln -s 1 "$vhost_prefix_f:_:name:devpanel_tools"; then
     error "unable to set the name for vhost 1 (tools vhost)"
   fi
+
+  if ! ln -s "names/tools_vhost_template" "$vhost_prefix_f:1:_:template_ref"; then
+    error "unable to create template ref $vhost_prefix_f:1:_:template_ref"
+  fi
 else
-  error "unable to create vhost entry $tools_vhost_prefixed"
+  error "unable to create vhost entry $vhost_prefix_f:1"
 fi
 
 echo '---[ end of creating new virtual host ]---'
