support for systemd and recent mysql updates
support for CentOS 7 and Debian 8

fixes to Debian 7

support for mysqld 5.7

fixes to extplorer on CentOS 7

diff --git a/libexec/dbmgr-mysql-as-root b/libexec/dbmgr-mysql-as-root
--- a/libexec/dbmgr-mysql-as-root
+++ b/libexec/dbmgr-mysql-as-root
@@ -9,9 +9,18 @@ then
   echo "Usage: $0 username" >&2
   exit 1
 fi
-if ! password=`$dir/../config/os/pathnames/opt/dbmgr/current/bin/root-password --user="$user" 2>/dev/null`
-then
-  echo "ERROR: cannot get root password for $user" >&2
-  exit 1
+
+dbmgr_config_dir="$dir/../config/os/pathnames/opt/dbmgr/config/mysql/$user"
+
+root_client_cnf=$(readlink -m "$dbmgr_config_dir/root.client.cnf")
+
+if [ -f "$root_client_cnf" ]; then
+  su - -s /bin/bash -c "$command --defaults-file=$root_client_cnf $*" "$user"
+else
+  if ! password=`$dir/../config/os/pathnames/opt/dbmgr/current/bin/root-password --user="$user" 2>/dev/null`
+  then
+    echo "ERROR: cannot get root password for $user" >&2
+    exit 1
+  fi
+  su - -s /bin/bash -c "$command -S mysql/mysql.sock -u root -p\"$password\" $*" "$user"
 fi
-su - -s /bin/bash -c "$command -S mysql/mysql.sock -u root -p\"$password\" $*" "$user"
