htpasswd-lock-mng: fixed backwards compatibility with WE 1.0
also adjusted usage messages to be coherent with the link structure.

diff --git a/libexec/htpasswd-lock-mng b/libexec/htpasswd-lock-mng
--- a/libexec/htpasswd-lock-mng
+++ b/libexec/htpasswd-lock-mng
@@ -1,6 +1,29 @@
 #!/bin/bash
 
 usage() {
+  case $script_name in
+    htaccess-lock-vhost)
+      usage_htaccess_lock_vhost
+      ;;
+    htaccess-unlock-vhost)
+      usage_htaccess_unlock_vhost
+      ;;
+    htaccess-lock-status-vhost)
+      usage_htaccess_lock_status
+      ;;
+    "$real_script_name")
+      echo -n "Error: please don't use this script directly. "
+      echo    "Use one of the links pointing to it."
+      exit 1
+      ;;
+    *)
+      echo "Error: unknown script basename" 1>&2
+      exit 1
+      ;;
+  esac
+}
+
+usage_htaccess_lock_vhost() {
   local prog=$(basename "$0")
   echo "
 
@@ -18,7 +41,31 @@ Usage: $prog [ options ] <vhost>
   exit 1
 }
 
+usage_htaccess_unlock_vhost() {
+  local prog="$(basename "$0")"
+
+  echo "Usage: $prog <vhost>
+  
+Disables htpasswd lock of the specified vhost.
+"
+  exit 1
+}
+
+usage_htaccess_lock_status() {
+  local prog="$(basename "$0")"
+
+  echo "Usage: $prog <vhost>
+
+  Outputs 0 if the vhost is not locked, 1 if vhost is locked.
+"
+  exit 1
+}
+
 # main()
+
+script_path=$(readlink -e "$0")
+real_script_name=$(basename "$script_path")
+script_name=`basename "$0"`
 
 [ $# -lt 1 ] && usage
 
@@ -53,7 +100,6 @@ while getopts $getopt_flags OPT ; do
 done
 [ $OPTIND -gt 1 ] && shift $(( $OPTIND - 1 ))
 
-script_name=`basename "$0"`
 self_bin=`readlink -e "$0"`
 dir=`dirname "$self_bin"`
 base_dir=`readlink -e "$dir/.."`
@@ -76,6 +122,11 @@ for lib_f in "$flag_file" "$lib_file"; do
   fi
 done
 
+unset webenabled_backwards
+if deref_os_prop "$base_dir" webenabled_backwards &>/dev/null; then
+  webenabled_backwards=1
+fi
+
 if [ -n "$DEVPANEL_VHOST_HTPASSWD_LOCK_FLAG" ]; then
   flag_str="$DEVPANEL_VHOST_HTPASSWD_LOCK_FLAG"
 else
@@ -89,16 +140,9 @@ if [ -L "$flag_link" ]; then
 fi
 
 if [ "$script_name" == "htaccess-lock-vhost" ]; then
-  if [ -z "$is_locked" ]; then
-    "$metadata_handler" -q "$vhost" <<< "set $flag_str 1"$'\n'
-    if [ $? -ne 0 ]; then
-      error "unable to set lock flag on vhost '$vhost'"
-    fi
-  else
-    echo "Warning: vhost '$vhost' is already locked..." >&2
+  if [  -n "$webenabled_backwards" -a -z "$read_pw_stdin" -a -z "$password" ]; then
+    password=$(wedp_gen_random_str 10)
   fi
-
-  main_ex=0 # so far good, most things have succeeded enough up to now
 
   su -l -c '[ ! -f "~/.htpasswd" ] && touch ~/.htpasswd' "$user"
   if [ $? -ne 0 ]; then
@@ -107,17 +151,25 @@ if [ "$script_name" == "htaccess-lock-vhost" ]; then
     su -l -c 'chmod 640 ~/.htpasswd' "$user"
   fi
 
-  if [ -n "$read_pw_stdin" ]; then
+  if [ -n "$webenabled_backwards" -a -n "$password" ]; then
+    printf "~:guest:%s\n" "$password" | su -l -c "$dir_bin/htpasswd-bulk ~/.htpasswd" "$user"
+    main_ex=$?
+  elif [ -n "$read_pw_stdin" ]; then
+    tty &>/dev/null && echo "Reading user operations from STDIN..."
     su -l -c "$dir_bin/htpasswd-bulk ~/.htpasswd" "$user"
-    status=$?
-    main_ex=$status
-    if [ $status -eq 0 ]; then
+    main_ex=$?
+    if [ $main_ex -eq 0 ]; then
       echo "Successfully updated the passwords."
-    else
-      echo "Error: unable to update user/passwords. htpasswd-bulk returned $status" 1>&2
+    else 
+      echo "Error: unable to update user/passwords. htpasswd-bulk returned $main_ex" 1>&2
     fi
   fi
 elif [ "$script_name" == "htaccess-unlock-vhost" ]; then
+  if [ -z "$is_locked" ]; then
+    echo "Warning: already unlocked..." 1>&2
+    exit 0
+  fi
+
   "$metadata_handler" -q "$vhost" <<< "rm $flag_str"$'\n'
   if [ $? -ne 0 ]; then
     error "unable to remove lock flag"
@@ -140,6 +192,16 @@ if [ $main_ex -ne 0 ]; then
 else
   if   [ "$script_name" == "htaccess-lock-vhost" ]; then
     verb="enabled"
+
+    if [ -z "$is_locked" ]; then
+      "$metadata_handler" -q "$vhost" <<< "set $flag_str 1"$'\n'
+      if [ $? -ne 0 ]; then
+        error "unable to set lock flag on vhost '$vhost'"
+      fi
+    else
+      echo "Warning: vhost '$vhost' is already locked..." >&2
+    fi
+
   elif [ "$script_name" == "htaccess-unlock-vhost" ]; then
     verb="disabled"
   fi
@@ -151,6 +213,9 @@ else
     fi
 
     echo "Successfully $verb htpasswd protection on vhost '$vhost'."
+    [ -n "$webenabled_backwards" -a -n "$password" ] && \
+      printf '%s\n' "$password"
+
   else
     echo "Warning: configuration changed, but not immediately applied." 1>&2
   fi
