libexec/restore-vhost-web: alow to restore on an existing vhost

diff --git a/libexec/restore-vhost-web b/libexec/restore-vhost-web
--- a/libexec/restore-vhost-web
+++ b/libexec/restore-vhost-web
@@ -1,19 +1,5 @@
-#!/bin/sh
-# Options:
-# -P - replicate shadow
-# -n - do not activate apache vhost (used for hosting_link)
-
-opt_P=0 options=""
-
-while getopts "Pn" OPTOPT
-do
-  case "$OPTOPT" in
-    P) opt_P=1;;
-    n) options="$options${options+ }-n";;
-    *) exit 1;;
-  esac
-done
-shift `expr $OPTIND - 1`
+#!/bin/bash
+WEBENABLED_BASE_DIR=${WEBENABLED_BASE_DIR:-/opt/webenabled}
 
 run()
 {
@@ -26,19 +12,108 @@ run_su()
   su -l -c "$*" "$user"
 }
 
+usage() {
+  echo "
+Usage: $0 [ OPTIONS ] VHOST ARCHIVE_DIR
+
+  Options:
+  
+    -P          replicate shadow
+    -n          do not activate apache vhost (used for hosting_link)
+    -S          sync the files (don't create a vhost, just sync the files)
+    -H          search for the archive in the users HOME dir
+                public_html/gen/archive
+    -N          don't create a vhost user
+
+    VHOST is the target vhost to be created or sync'ed
+    ARCHIVE_DIR is the dir where the archive files reside in
+"
+  exit 1
+}
+
+locked()
+{
+  egrep -q '^Use[[:space:]]+Vhost-[^[:space:]]+-locked\>' "$archive_conf"
+}
+
+abort_if_not_exist()
+{
+  local file="$1"
+  if ! [ -r "$file" ]
+  then
+    echo "$file does not exist" >&2
+    exit 1
+  fi
+}
+
+
+# main
+
+opt_P=0 options="" sync=0 search_in_users_home=0
+create_vhost=1
+
+while getopts "NPnSH" OPTOPT
+do
+  case "$OPTOPT" in
+    P) opt_P=1;;
+    n) options="$options${options+ }-n";;
+    S) sync=1 ;;
+    H) search_in_users_home=1 ;;
+    N) create_vhost=0 ;;
+    *) exit 1;;
+  esac
+done
+[ $OPTIND -gt 0 ] && shift `expr $OPTIND - 1`
+
+[ $# -lt 2 ] && usage
+
 dir=`dirname $0`
 bin_dir="$dir/../bin"
 vhost="$1"
-archive_dir="$2"
-archive_id="$archive_dir/id"
 user="w_$vhost"
-shift
-shift
-if ! old_vhost=`cat "$archive_id"`
-then
+archive_label="$2"
+
+if ! source "$dir/../lib/functions" ; then
+  echo "Error: unable to load auxiliary functions" 1>&2
+  exit 1
+fi
+
+if [ $create_vhost -eq 1 ] && getent passwd "$user" &>/dev/null; then
+  error "vhost '$vhost' already exists"
+elif [ $create_vhost -eq 0 ] && ! user_info=$(getent passwd "$user" 2>/dev/null); then
+  error "vhost '$vhost' doesn't exist"
+fi
+
+
+if [ $create_vhost -eq 0 -a $search_in_users_home -eq 1 \
+  -a ! -e "$archive_label" -a "${archive_label:0:1}" != "/" \
+  -a "${archive_label:0:2}" != "./" \
+  -a "${archive_label:0:3}" != "../" ]; then
+
+  user_home_dir=$(echo "$user_info" | cut -d: -f 6)
+  test_archive="$user_home_dir/public_html/gen/archive/$archive_label"
+  [ -f "$test_archive" ] && archive_label="$test_archive"
+fi
+
+if [ ! -e "$archive_label" ] ; then
+  error "path '$archive_label' doesn't exist"
+elif [ -d "$archive_label" ]; then
+  archive_dir="$archive_label"
+elif [ -f "$archive_label" ]; then
+  tmp_extract=`run_su mktemp -d`
+  run_su tar -zxf "$archive_label" -C "$tmp_extract"
+  if [ $? -ne 0 ]; then
+    error "unable to extract file '$archive_label'"
+  fi
+  archive_dir="$tmp_extract/web"
+fi
+
+archive_id="$archive_dir/id"
+if ! old_vhost=`head -1 "$archive_id"` || [ -z "$old_vhost" ]; then
   echo "Cannot read $archive_id" >&2
   exit 1
 fi
+
 old_user="w_$old_vhost"
 date=`date  +'%Y%m%d'`
 archive_file="$archive_dir/$old_user.tgz"
@@ -51,120 +126,102 @@ logs_dir="$dir/../config/os/pathnames/var/log/apache_vhosts/$user"
 archive_logs="$archive_dir/logs_$old_vhost.tgz"
 archive_shadow="$archive_dir/$old_user.shadow"
 archive_crontab="$archive_dir/crontab"
-home_prefix=/home/clients/websites
+home_prefix=${WEBENABLED_HOME_PREFIX:-/home/clients/websites}
 
-locked()
-{
-  egrep -q '^Use[[:space:]]+Vhost-[^[:space:]]+-locked\>' "$archive_conf"
-}
-
-if  `id -u "$user" 2>/dev/null >/dev/null`
-then
-  echo "User $user must not exist" >&2
-  exit 1
+if [ ! -e "$archive_file" ]; then
+  error "missing archive file '$archive_file'"
+elif [ ! -f "$archive_file" ]; then
+  error "archive file is not a regular file"
+elif [ $create_vhost -eq 1 -a ! -e "$archive_conf" ]; then
+  error "missing apache config file '$archive_conf'"
 fi
-if ! default_domain=`cat /opt/webenabled/config/names/default` || [ -z "$default_domain" ] 
-then
+
+if [ $create_vhost -eq 1 ] && \
+  ! default_domain=`head -1 "$dir/../config/names/default"`; then
   error "No default domain"
+elif [ $create_vhost -eq 1 ] && \
+  ! echo -e "n\nn\ny"| run $dir/create-virtwww $options "$vhost" "$vhost.$default_domain"; then
+  error "unable to create vhost"
 fi
 
-echo -e "n\nn\ny"| run $dir/create-virtwww $options "$vhost" "$vhost.$default_domain" || exit 1
-config_dir=/opt/webenabled/config/vhosts/$vhost
-[ $# = 0 ] && set -- "$vhost.$default_domain"
-default_name="$1"
-run $dir/config-vhost-names "$vhost" '*' "$default_name" '+' "$@" || exit 1
-if locked 
-then
+config_dir="$WEBENABLED_BASE_DIR/config/vhosts/$vhost"
+
+if [ $create_vhost -eq 1 ]; then
+  default_name="$vhost.$default_domain"
+  if ! run "$dir/config-vhost-names" "$vhost" '*' "$default_name" '+' "$default_name"; then
+    error "unable to configure vhost hostname"
+  fi
+fi
+
+if [ $create_vhost -eq 0 ] && locked; then
   echo "Restoring the locked state of apache cofig"
-  if ! run $dir/lock-vhost-apache "$vhost" 
-  then
-  echo "Cannot restore apache config in locked state" >&2; exit 1
+  if ! run $dir/lock-vhost-apache "$vhost"; then
+    error "Cannot restore apache config in locked state"
   fi
 fi
 
 home="`eval \"echo ~$user\"`"
-
-if ! [ -d "$home" ]
-then
-  echo "Home dir $home does not exist" >&2
-  exit 1
-fi
-
-if ! echo "$home" | grep -q "^$home_prefix/"
-then
-  echo "Home dir $home is outside $home_prefix, why???" >&2
-  exit 1
-fi
-
-rm -rf "$home"
-
-if ! [ -d "$logs_dir" ]
-then
-  echo "Logdir $logs_dir does not exist" >&2
-  exit 1
-fi
-
-abort_if_not_exist()
-{
-  local file="$1"
-  if ! [ -r "$file" ]
-  then
-    echo "$file does not exist" >&2
-    exit 1
+if [ $create_vhost -eq 1 ]; then
+  echo "Restoring $home from $archive_file"
+  if [ ! -d "$home" ] && ! run mkdir "$home"; then
+    error "unable to create site dir"
   fi
-}
 
-abort_if_not_exist "$archive_file"
-abort_if_not_exist "$archive_logs"
-abort_if_not_exist "$archive_conf"
+  if ! run chown "$user":"$apache_group" "$home"; then
+    error "unable to chmod home dir '$home' to '$user:$apache_group'"
+  fi
 
+  run "$chcgi" "$user" +2
+  run "$chcgi" "$user" +7
+  run_su ln -snf $logs_dir logs
 
-echo "Restoring $home from $archive_file"
-run mkdir "$home" || exit 1
-run chown "$user":$apache_group "$home" || exit 1
-run_su tar -C "$home" -zxpf - <"$archive_file" || exit 1
-run "$chcgi" "$user" +2
-run "$chcgi" "$user" +7
-if [ o"$vhost" != o"$old_vhost" ]
-then
-  run_su mv public_html/$old_vhost public_html/$vhost || exit 1
-  # ignore errors
-  run_su mv public_html/$old_vhost-usage public_html/$vhost-usage
 fi
-run_su ln -snf $logs_dir logs || exit 1
 
-#FIXME: .htpasswd for phpmyadmin
-run_su 'echo >.htpasswd'
+if ! run_su tar -C "$home" \
+  $([ $sync -eq 1 ] && echo -n --exclude='settings.php') \
+  $([ $sync -eq 1 ] && echo -n --exclude='default.settings.php') -zxpf - <"$archive_file"; then
+  error "unable to extract files"
+fi
+
+if [ "$vhost" != "$old_vhost" ]; then
+  if [ ! -e "$home/public_html/$old_vhost" ]; then
+    error "missing previous vhost dir 'public_html/$old_vhost'"
+  elif [ -e "$home/public_html/$vhost" ]; then
+    run_su mv "$home/public_html/$vhost" "$home/public_html/$vhost".$(date +%s)
+  fi
+
+  if ! run_su mv "$home/public_html/$old_vhost" "$home/public_html/$vhost"; then
+    error "unable to move 'public_html/$old_vhost' to 'public_html/$vhost'"
+  fi
+
+  [ -d "$home/public_html/$old_vhost-usage" ] && \
+    run_su mv "$home/public_html/$old_vhost-usage" "$home/public_html/$vhost-usage"
+fi
 
 #FIXME: 
 #restoring crontab of a locked vhost doesn't work
 #It's better to get rid of automatic crontab modifications in all cases
-echo "Restoring crontab from $archive_crontab"
-crontab_contents="`cat \"$archive_crontab\"`" || exit 1
-echo "$crontab_contents"
-if [ -n "$crontab_contents" ]
-then
-  echo "$crontab_contents" | run_su crontab -|| exit 1
-  run_su "$bin_dir/update-vhost-crontab" || exit 1
-else
-  echo no crontab
+if [ -f "$archive_crontab" ]; then
+  echo "Restoring crontab from $archive_crontab"
+  run_su crontab - < "$archive_crontab"
+  crontab_status=$?
+  if [ $crontab_status -eq 0 ]; then
+    if ! run_su "$bin_dir/update-vhost-crontab"; then
+      echo "webenabled_warning: unable to adjust crontab dates" 1>&2
+    fi
+  else 
+    echo "webenabled_warning: unable to restore crontab contents" 1>&2
+  fi
+elif [ ! -e "$archive_crontab" ]; then
+  echo "Skipping crontab restore: crontab archive is missing" 1>&2
 fi
 
-if [ $opt_P = 1 ] 
-then
-  if [ -s "$archive_shadow" ]
-  then
-    echo "Restoring the password from $archive_shadow"
-    password=`cut -d: -f2 "$archive_shadow"` || exit 1
-    echo "$user:$password" | chpasswd -e || exit 1
-  else
-    echo "No shadow file"
+if [ $opt_P -eq 1 -a ! -e "$archive_shadow" ]; then
+  echo "webenabled_warning: missing shadow file '$archive_shadow'" 1>&2
+elif [ $opt_P -eq 1 -a -s "$archive_shadow" ]; then
+  echo "Restoring the password from $archive_shadow"
+  password=`cut -d: -f2 "$archive_shadow"`
+  if [ -n "$password" ] && ! echo "$user:$password" | chpasswd -e; then
+    echo "webenabled_warning: unable to restore the shell password" 1>&2
   fi
 fi
-
-#echo "Replacing apache config with $archive_conf"
-#run cp "$archive_conf" "$conf"
-
-#echo "Archiving $logs_dir to $archive_logs"
-#run mkdir -p "$archive_dir"
-#run tar -C "$logs_dir" -zcf "$archive_logs" .
