Fix Issue : https://help.webstandard.com/issues/7237 Can't CLONE app when choice different TARGET SERVER 	modified:   libexec/restore-vhost 	    Define variable 'home' before first call it

diff --git a/libexec/restore-vhost b/libexec/restore-vhost
--- a/libexec/restore-vhost
+++ b/libexec/restore-vhost
@@ -160,6 +160,14 @@ if ! source "$aux_lib_file"; then
   error "unable to load auxiliary functions from $aux_lib_file"
 fi
 
+# Move to here to fix issue https://help.webstandard.com/issues/7237
+get_linux_username_from_vhost "$vhost" && user_web="$_dp_value"
+if [ $? -ne 0 ]; then
+  error "unable to get the linux username from vhost $vhost"
+fi
+
+home="`eval \"echo ~$user_web\"`" || error "unable to get \$HOME of user $user_web"
+user_db="b_${user_web#w_}"
 
 assign_deref_os_prop_or_exit sys_datadir "$we_base_dir" data_dir
 
@@ -296,13 +304,6 @@ fi
 echo Processing web...
 run $0-web $web_options "$vhost" "$archive_dir/web" "$@" || exit 1
 
-get_linux_username_from_vhost "$vhost" && user_web="$_dp_value"
-if [ $? -ne 0 ]; then
-  error "unable to get the linux username from vhost $vhost"
-fi
-
-home="`eval \"echo ~$user_web\"`" || error "unable to get \$HOME of user $user_web"
-user_db="b_${user_web#w_}"
 
 if ! [ -d "$archive_dir/db" ]
 then
