libexec/token-mgr: added cmd line opts -i -l
options required by cgit (git browser). But will also be useful
for other cases.

-l  vhost is a literal user (don't prepend w_ to
    the vhost name)
-i  read the contents of the token file from stdin

diff --git a/libexec/token-mgr b/libexec/token-mgr
--- a/libexec/token-mgr
+++ b/libexec/token-mgr
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-umask 027
+umask 077
 
 token_length=50
 
@@ -14,9 +14,12 @@ Usage: $prog [ OPTIONS ] <vhost>
   Options:
     -n number         number of characters of the token
     -t type           Type of the token
-    -T token          use the specified token (instead of generating a
+    -T token_str      use the specified token (instead of generating a
                       random one)
     -r                remove the token specified in option -T
+    -l                vhost is a literal user (don't prepend w_ to
+                      the vhost name)
+    -i                read the contents of the token file from stdin
 "
   exit 1
 }
@@ -38,8 +41,8 @@ elif [ ! -d "$token_dir" ]; then
 fi
 
 delete_token=0
-unset token_str
-getopt_flags='rn:t:T:'
+unset token_str token_type token_str token_contents literal_user
+getopt_flags='rn:t:T:li'
 while getopts $getopt_flags OPTN; do
   case $OPTN in
     n)
@@ -67,6 +70,13 @@ while getopts $getopt_flags OPTN; do
       ;;
     r)
       delete_token=1
+      ;;
+    l)
+      literal_user=1
+      ;;
+    i)
+      echo "reading token contents from stdin" 1>&2
+      read token_contents
       ;;
     *)
       usage
@@ -98,10 +108,6 @@ elif [ $delete_token -eq 1 ]; then
   else
     error "unable to delete token file '$token_file'"
   fi
-fi
-
-if ! getent passwd "w_$vhost" >/dev/null; then
-  wedp_warn "vhost 'w_$vhost' doesn't exist yet (this is just a warning)"
 fi
 
 if [ -z "$token_str" ]; then
@@ -137,6 +143,23 @@ if [ $status -ne 0 ]; then
   error "unable to create token file. touch returned exit code: $status"
 fi
 
-chgrp virtwww "$token_file"
+if [ -n "$literal_user" ]; then
+  token_owner="$vhost"
+else
+  token_owner="w_$vhost"
+fi
 
-exit $status
+if [ -n "$token_contents" ]; then
+  echo "$token_contents" >"$token_file"
+  if [ $? -ne 0 ]; then
+    error "unable to save token_contents on token file '$token_file'"
+  fi
+fi
+
+if ! getent passwd "$token_owner" >/dev/null; then
+  wedp_warn "vhost '$token_owner' doesn't exist yet (this is just a warning)"
+elif ! chown "$token_owner" "$token_file"; then
+  error "unable to chown '$token_file' to '$token_owner'"
+fi
+
+exit 0
