install/pack-bootstrap: updated to new dir layout
made the changes to support the new directory layout

diff --git a/install/pack-bootstrap b/install/pack-bootstrap
--- a/install/pack-bootstrap
+++ b/install/pack-bootstrap
@@ -27,8 +27,10 @@ error() {
 # main
 
 declare -a bootstrap_files=( \
-  'lib/' \
+  'lib/functions' \
+  'lib/perl5/' \
   'sbin/taskd' \
+  'libexec/system-services' \
 )
 
 [ $# -lt 2 ] && usage
@@ -58,6 +60,11 @@ if [ ! -d "$source_dir" ]; then
   error "unable to find source directory '$source_dir'"
 fi
 
+if [ "${source_dir:0:1}" != "/" ]; then
+  source_dir="$PWD/$source_dir"
+fi
+source_dir="${source_dir%/.}"
+
 if [ -e "$target_file" ]; then
   error "target file '$target_file' already exists."
 fi
@@ -86,9 +93,24 @@ fi
 
 echo "Starting copy of files to temp dir '$internal_pack_dir'"
 
-mkdir "$internal_pack_dir/config"
+internal_root_dir="$internal_pack_dir/root"
+if ! mkdir "$internal_root_dir"; then
+  error "unable to create dir '$internal_root_dir'"
+fi
+
+mkdir "$internal_root_dir/config"
 if [ $? -ne 0 ]; then
-  error "unable to create directory '$internal_pack_dir/config'"
+  error "unable to create directory '$internal_root_dir/config'"
+fi
+
+mkdir "$internal_root_dir/etc"
+if [ $? -ne 0 ]; then
+  error "unable to create directory '$internal_root_dir/etc'"
+fi
+
+if ! cp "$source_dir/install/config/devpanel.conf.template" \
+  "$internal_root_dir/etc/devpanel.conf"; then
+  error "unable to copy file '$source_dir/install/config/devpanel.conf.template'"
 fi
 
 cp -a "$source_dir/install/bootstrap/install.sh" "$internal_pack_dir"
@@ -96,9 +118,22 @@ if [ $? -ne 0 ]; then
   error "unable to copy '$source_dir/bootstrap/install.sh' to '$internal_pack_dir'"
 fi
 
+cp -a "$source_dir/install/bootstrap/bootstrap"*.sh "$internal_pack_dir"
+if [ $? -ne 0 ]; then
+  error "unable to copy files install/bootstrap/bootstrap*.sh"
+fi
+
+cp -a "$source_dir/install/skel" "$internal_pack_dir"
+if [ $? -ne 0 ]; then
+  error "unable to copy dir '$source_dir/install/skel' to '$internal_pack_dir'"
+fi
+
 for file in "${bootstrap_files[@]}"; do
   file_path="$source_dir/$file"
-  target_dir="$internal_pack_dir"/`dirname "$file_path"`
+  internal_path=`dirname "$file_path"`
+  internal_path=${internal_path##$source_dir}
+
+  target_dir="$internal_root_dir/$internal_path"
   if [ -e "$target_dir" -a -d "$file_path" ]; then
     cp -a "$file_path" "$target_dir"
     status=$?
@@ -109,12 +144,18 @@ for file in "${bootstrap_files[@]}"; do
   elif [ -d "$target_dir" ]; then
     cp -a "$file_path" "$target_dir"
     status=$?
+  elif [ ! -d "$target_dir" ]; then
+    mkdir -p "$target_dir"
+    if [ $? -ne 0 ]; then
+      error "unable to create dir '$target_dir' while copying '$file_path'"
+    fi
+    cp -a "$file_path" "$target_dir"
   else
     error "unknown condition when packing file '$file_path'"
   fi
 
   if [ $status -ne 0 ]; then
-    error "unable to copy '$file_path' to dest dir '$internal_pack_dir'"
+    error "unable to copy '$file_path' to dest dir '$internal_root_dir'"
   fi
 done
 
