renamed commands to list and install seed apps
renamed: 'list apps'   to 'list seed apps'

renamed: 'install app' to 'install seed app'

diff --git a/paas-provisioner/docker/functions b/paas-provisioner/docker/functions
--- a/paas-provisioner/docker/functions
+++ b/paas-provisioner/docker/functions
@@ -577,10 +577,10 @@ operation_create()
       return 1
     fi
 
-    ${sudo} devpanel install app --app "${app}" --publisher devpanel --vhost "${vhost}"
+    ${sudo} devpanel install seed app --app "${app}" --publisher devpanel --vhost "${vhost}"
     local st=$?
     if [ $st -ne 0 ]; then
-      echo "Error: failed to install app '$app' on vhost '$vhost'" 1>&2
+      echo "Error: failed to install seed app '$app' on vhost '$vhost'" 1>&2
       return $st
     fi
 
